### ISSUE TITLE
HyperIterables ignore loop phasers

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#1200]
```
my @a = (^10).list; @a = @a.hyper(:batch(5)).map({ LAST say "last"; „∅“ });
# rakudo-moar d10d69774: ( no output )

# expexted output at the end of a batch:
# last

# FIRST and NEXT are ignored too
# It may be sensible to fail on LAST in a HyperIterable and provide a
# LAST-BATCH phaser to avoid confusion when non-parallel code is
# changed.
```

**Comment by lizmat** [comment]
FWIW, I’m making *all* phasers throw a NYI for the 2017.10 release.  So we can figure out semantics until the next release.

**Comment by AlexDaniel** [comment]
↑ https://github.com/rakudo/rakudo/commit/a042fd927c672cc2bf6d186e2d40f3ae69d88b86

**Comment by jnthn** [comment]
They're simply NYI (which is the case for many things with hyper/race). `FIRST` should fire on the first element, and `LAST` on the last element, just as with a non-`hyper` loop. Batches shouldn't come in to it. The batch with the first element carries a flag indicating that, and it's the same for the batch with the last element. I don't think that we should need to make any guarantee that `FIRST` will run before iterations in another worker, nor that `LAST` will run after, since a loop with such order dependencies couldn't be parallelized anyway.

I suspect most situations where a `LAST-IN-BATCH` could be useful would generally be better done with a race `reduce`, which will be one of the next race-related things I implement (if nobody beats me to it).

**Comment by chee** [comment]
could this issue be considered closed now that it throws a `X::NYI`?

**Comment by lizmat** [comment]
Yes, thanks for the nudge!
