### ISSUE TITLE
MoarVM panic: Could not spawn thread: errorcode -11

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1223]
This reliably fails on camelia bot: (-11... segfault?)
```
m: await ^60 .map: { start sleep ⅓ }
rakudo-moar ae1f0fdaf: OUTPUT: «MoarVM panic: Could not spawn thread: errorcode -11␤»
```

This doesn't happen with the same bot using 2017.07 release, suggesting it might be a regression:

```
star: await ^60 .map: { start sleep ⅓ }
star-m 2017.07: ( no output )
```

Also it doesn't happen with `committable` bot on HEAD either:

```
c: HEAD await ^600 .map: { start sleep ⅓ }
Zoffix, ¦HEAD(ae1f0fd): «»
```

~~So maybe the error is due to some `ulimit` or something?~~ Doesn't seem to be it; replicated the entire ulimit setup from camelia's box on my local box and can't repro the issue locally.

**Comment by jnthn** [comment]
It's probably a memory limit or a handles limit. The new scheduler tries to get away with as few threads as it can; because of that, it can have a far higher maximum count (the previous scheduler had a very low maximum because it would almost always hit it anyway, even without much reason to do so). In this program, the scheduler correctly detects that the sleeping threads are not making progress, sees there is work in the queue, and starts up more threads to try and break a potential deadlock. Threads need resources, the resources don't exist, so it fails.

**Comment by jnthn** [comment]
Also, a panic is a situation where the VM recognizes it's in trouble, and brings itself to a (non-SEGV) end. So no, not SEGV.

**Comment by zoffixznet** [comment]
This [works fine if set to old limit of 16 threads](https://irclog.perlgeek.de/perl6-dev/2017-11-02#i_15393022) so it's just camelia's env.
