### ISSUE TITLE
Broken default value assignment on shaped array attributes

### ISSUE THREAD

**Issue by kalkin** [rakudo/rakudo#1226]
## The Problem
```perl6
class F { 
    has @.color[4] = <1 2 3 4>;
}; 
my $f = F.new();
say $f.color
```
## Expected Behavior
`$f.color == <1 2 3 4>`
## Actual Behavior
`$f.color == [(Any) (Any) (Any) (Any)]`

## Environment
Seems to happen in 2017.09 and HEAD version used by the **m** bot in *#perl6*

**Comment by W4anD0eR96** [comment]
```
➜  perl6 -e 'class F { has @.color = <1 2 3 4>; }; my $f = F.new(); say $f.color'
[1 2 3 4]
➜  perl6 -v
This is Rakudo version 2017.10-64-g697e4ecff built on MoarVM version 2017.10-29-g116c7a13
implementing Perl 6.c.
➜  perl6 -e 'class F { has @.color = <1 2 3 4>; }; my $f = F.new(); dd $f.color' 
Array @!color = [IntStr.new(1, "1"), IntStr.new(2, "2"), IntStr.new(3, "3"), IntStr.new(4, "4")]
```

**Comment by kalkin** [comment]
Sorry I meant `  has @.color[4] = <1 2 3 4>;` Will edit the issue

**Comment by lizmat** [comment]
This *should* work, but doesn’t, and I don’t see a quick solution.

The problem is caused by the finickiness of attribute initialization.  You can consider Rakudo Perl 6 Opaque as a hash at a low level, where every attribute has a key and a value.

For all other cases of attribute initialization, having a key for an attribute in that low level hash, means it has been initialized.  This is checked with nqp::attrinited.

In the case of:

class A { has @.a[4] = 1,2,3,4 }

but also:

class A { has %.a is SetHash = 1,2,3,4 }

extra code is run to make sure that the container is of the correct type (buildplan code 9). 

However, running this code makes the attribute exist in the low level hash.  Which in turn means that nqp::attrinited for that attribute returns True, causing the initialization *not* to run.

This is alas not an easily solvable problem, as any solution will either cause severe object creation performance degradation for *all* objects, *or* have potential issues with “invisible” initialization from other attributes or subclasses.


So my suggestion is to make the combination of buildplan code 9 and default (code 4,5,6,7) to throw an NYI (not yet implemented) exception.  This should at least reduce frustration.


BTW, a workaround for this problem is:

class A {
    has @.a[4];
    method TWEAK(*%args) {
        @!a = 1,2,3,4 unless %args<a>:exists
    }
}

**Comment by lizmat** [comment]
Commit 0973b307ad implemented the X::Comp::NYI error.  The output is now:

$ 6 'class F { has @.color[4] = <1 2 3 4> }'
===SORRY!=== Error while compiling -e
Defaults on compound attribute types not yet implemented. Sorry.
Workaround: Create/Adapt TWEAK method in class F, e.g:
    method TWEAK() { @!color = (initial values) unless %_<color>:exists

This should at least prevent frustration in the future.
