### ISSUE TITLE
"trans" method does not remove complement characters in some cases

### ISSUE THREAD

**Issue by koorchik** [rakudo/rakudo#1227]
## The Problem
"trans" method does not work as expected.
```
"string".trans("tz" => "", :complement, :delete) # works
"string".trans("xz" => "", :complement, :delete) # does not work
```

## Expected Behavior
Should remove all complement characters
## Actual Behavior
Removes complement characters only if at least one of original was in a string. 
## Steps to Reproduce
```
"string".trans("xz" => "", :complement, :delete) # does not work
```

## Environment
* Operating system: Windows 10
* Compiler version (`perl6 -v`): 
This is Rakudo version 2017.07 built on MoarVM version 2017.07
implementing Perl 6.c.

**Comment by zoffixznet** [comment]
Did some rudimentary debugging:

* The `LSM` class in src/core/Str that handles more advanced transes seems to forget to even take the `:delete` arg (and possibly has other cases where delete doesn't work)
* The OP issue only happens when the part to match does NOT appear at all in the string
* Similar issue also exists with `:c` alone, where it doesn't do anything if the match does not appear in the string:

```
<Zoffix__> m: say 'abc'.trans: 'b' => '♥', :c
<camelia> rakudo-moar 8b24bf5cd: OUTPUT: «♥b♥␤»
<Zoffix__> m: say 'abc'.trans: 'z' => '♥', :c
<camelia> rakudo-moar 8b24bf5cd: OUTPUT: «abc␤»
```

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/428a5c2d94
