### ISSUE TITLE
Proposal: easier syntax for multiple param aliases

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1293]
See https://github.com/perl6/doc/issues/1696.

Wouldn't it be better if instead of:
```perl6
sub ordinated( :st(:nd(:rd(:th($num))))=-1 ) {
```
it was possible to write:
```perl6
sub ordinated( :st:nd:rd:th($num)=-1 ) {
```

The current version is hard to read and hard to write, and the proposed variant is a syntax error anyway.

Grammar code in question:
https://github.com/rakudo/rakudo/blob/4fca9474362f3362603ea79dd35fa0c7d3a1ef8d/src/Perl6/Grammar.nqp#L3097-L3107

**Comment by zoffixznet** [comment]
👎 from me: YAGNI. I don't see this as something that has much benefit to being slightly easier to write and we yet might need the suggested syntax for some other feature.

**Comment by treyharris** [comment]
@zoffixznet I just grepped all the .p6 I've ever written and it seems that when _I_ define an alias, I'm more likely than not to define more than one. So either styles differ or I'm generally doing it wrong. 😛

Your comment on the syntax, though, is a point well-taken. Seems like a @TimToady waterbed-squashing problem?

**Comment by zoffixznet** [comment]
>  So either styles differ or I'm generally doing it wrong. 😛

IMO adding many ways to do the exact same thing is a sure way to make your documentation huge, burdening your users with a lot of information they don't have to learn. I know some like to throw around TIMTOWTDI as a justification for just that, but I think many overdo it and often don't consider long-term consequences.

People ask all the time what's the difference between `.foo()` and `.foo:`. They'll be asking the same for `:foo(:bar($ber))` and `:foo:bar($ber)` and the answer will be that *we thought of a cleaner syntax later on but had to keep old syntax too since people were using it already, so now we support and you have to learn both.*

I know I naysay on these proposals a lot, but it just feels like people are ignoring the fact that we're into our third year of claiming to be a stable language. They still attempt to re-design cornerstone features and syntax and, to avoid spectest breakage, they pile their re-designs onto existing design and then throw in a TIMTOWTDI as a justification for their Frankenstein.

What will be the state of the language in 10 years? It will have warts, but I rather the warts be the fact that you have to type extra parentheses in places rather than learn 5 different syntaxes and worry they don't clash.

**Comment by jnthn** [comment]
> I know I naysay on these proposals a lot

But thanks for doing so, so I don't feel like it's just me. :-)

> but it just feels like people are ignoring the fact that we're into our third year of claiming to be a stable language

I think stability is more about being careful not to break user's existing code, though, which isn't what's being proposed here - it was suggested as additive. That said, every addition we make means there's:

* More to document
* More to teach
* More code in the compiler to maintain
* More spectests
* Potentially, something new to consider for optmization

So it had better pull its weight. I'm not personally convinced the change proposed here does that. I say "personally" because it just doesn't show up much at all in Perl 6 code I've written, but as @treyharris notes, styles differ. So the question for me is if there's much demand for this, such that it justifies all of the above.

Also, an implementation aside: named parameter aliases are a bit of a pain for compilation/optimization. We do special-case a single alias (that is, 2 names); 2 aliases (3 names) or more and you are thrown back to the slow-path binder and pay a huge overhead for them. For the case of just 2, [the specializer doesn't yet handle them](https://github.com/MoarVM/MoarVM/blob/master/src/spesh/args.c#L318), meaning it's not as bad as the slow-path binder, but using aliases still prevents a bunch of optimizations. So we'd be introducing a shorter syntax that is only applicable in cases that are going to tank performance.

**Comment by vendethiel** [comment]
Is aliased params a feature used often enough that we need syntax for such cases?

**Comment by W4anD0eR96** [comment]
Less is more. By the way, we have `let` and `temp` which are so similar. What's more, I don't see even they are so common that should be listed as spec(in fact we don't have one..). However, it happened and we have to keep backward compatibility.

**Comment by AlexDaniel** [comment]
This ticket is more suitable for the problem-solving repo but I'm no longer interested in the original proposal, so I think we can just close this.
