### ISSUE TITLE
Chainable ops silently fail to be chained when negated

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1304]
Don't know if there's some logic behind this behaviour that I'm missing, but it looks like the ops that can normally be chained with different ops don't chain right when negating them (i.e. the Bool return of one seems to be used as input for the second op in the chain).

IMO it's LTA that it silently gives wrong result. Perhaps there's a way to make it work or make it complain?

```
$ perl6 -e 'say 1 < 3 > 2 '
True
$ perl6 -e 'say 1 !< 3 !> 2 '
True
$ perl6 -v
This is Rakudo version 2017.11-8-g7939014 built on MoarVM version 2017.11
implementing Perl 6.c.
```

**Comment by zoffixznet** [comment]
If this issue is rejected, please rip out the fudged tests in https://github.com/perl6/roast/commit/5cbef9d6825e9e3fbcbc278190a59d5f004417ae

**Comment by zoffixznet** [comment]
> Maybe we should close RT#121987 in favor of this ticket.

👍  I like GitHub's tracker more.

**Comment by AlexDaniel** [comment]
So, more tests here: https://github.com/perl6/roast/blob/5cbef9d6825e9e3fbcbc278190a59d5f004417ae/S03-operators/relational.t#L151-L155 (from RT#121987).

**Comment by jstuder-gh** [comment]
I don't know if this is the right solution for this problem, but I have one possible fix that addresses it and reapplies chaining when using the negation metaoperator.

NQP Commit:
<https://github.com/jstuder-gh/nqp/commit/84eef7cbf71d3194afb509ae4c31d6865211a155>

Rakudo Commit:
<https://github.com/jstuder-gh/rakudo/commit/07909381852d825cc6ccc5b195c735e8e12fad68>

NQP is modified because this modifies the 'chain' op (MoarVM only for now) so that it can use the first child node as the callee (as the negation metaop produces a subtree to determine the operator's behavior; seen below).

    - QAST::Op(call &METAOP_NEGATE)  :is_pure<?>
      - QAST::Var(lexical &infix:«<») <wanted>

Of course something similar would need to be done for the JVM and JS backends (I have not looked into what this would entail). I suppose this could complicate upkeep of the different backends and I don't know how this would affect optimization efforts.

If you think that this is a good solution, I can clean up these commits a bit (reword, add more context) and submit as PRs in their respective repos.

**Comment by zoffixznet** [comment]
Don't know much about this part of the codebase, but I'm not seeing where negation is being done. In the NQP commit, the code has logic to fish out the original chained op, but does it negate the result afterwards?

Also, looks like [the optimizer gets to METAOP_NEGATE](https://github.com/rakudo/rakudo/blob/b4df753dfcd4260ab9a0d40d1eb9dfdb5a5043d9/src/Perl6/Optimizer.nqp#L1716-L1722) and the nameless call first and rewrites it to a `prefix:<!>` call, with the nameless call removed. 

Does your version give right results for stuff like `say 1 !< 3 !> 2`? I think the optimizer's business is done *before* the `chain` op handling in NQP, so if it removes nameless stuff , perhaps the logic you added never gets triggered.

BTW, you can see what QAST gets generated with `--target` command line arg; it shows QAST before (`--target=ast`) and after static optimizer (`--target=optimize`)

```bash
$ perl6 --target=optimize -e 'say 1 !< 3 !> 2'

[...]

- QAST::Op(callstatic &say) <sunk> :statement_id<?> say 1 !< 3 !> 2
                    - QAST::Op(call &prefix:<!>) 
                      - QAST::Op(call &infix:«>») 
                        - QAST::Op(call &prefix:<!>) 
                          - QAST::Op(call &infix:«<») 
                            - QAST::Want <wanted> 1
                              - QAST::WVal(Int) 
                              - Ii
                              - QAST::IVal(1) 
                            - QAST::Want <wanted> 3
                              - QAST::WVal(Int) 
                              - Ii
                              - QAST::IVal(3) 
                        - QAST::Want <wanted> 2
                          - QAST::WVal(Int) 
                          - Ii
                          - QAST::IVal(2) 
```

And you can get the same output by using `.dump` method on QAST nodes. `note($qast.dump)`

**Comment by jstuder-gh** [comment]
Sorry, I didn't provide enough context on the modifications I was making.

The changes in Rakudo make it so that if the 'pasttype' on the base operator is 'chain' (as they are for '<' and '>' in the grammar) and the metaop is '!', then the nameless 'call' that would normally wrap the expression nodes is set to 'chain'.

But I needed to modify the 'chain' op too (in NQP). Before the name of the op served as the operator sub and the children the operands. This modification makes it so that, if there is no name provided to the chain, child 0 serves as the operator and children 1 and 2 the operands.

The result of the expression on this branch correctly results in False.

    $ perl6 -e 'say 1 !< 3 !> 2'
    > False


The target 'ast' and 'optimize' trees are included below:

    perl6 --target=ast -e 'say 1 !< 3 !> 2'
    
    - QAST::Op(call &say) <sunk> :statement_id<?> say 1 !< 3 !> 2
      - QAST::Op(chain) <wanted> !>
        - QAST::Op(call &METAOP_NEGATE)  :is_pure<?>
          - QAST::Var(lexical &infix:«>») <wanted>
        - QAST::Op(chain) <wanted> !<
          - QAST::Op(call &METAOP_NEGATE)  :is_pure<?>
            - QAST::Var(lexical &infix:«<») <wanted>
          - QAST::Want <wanted> 1
            - QAST::WVal(Int) 
            - Ii
            - QAST::IVal(1) 
          - QAST::Want <wanted> 3
            - QAST::WVal(Int) 
            - Ii
            - QAST::IVal(3) 
        - QAST::Want <wanted> 2
          - QAST::WVal(Int) 
          - Ii
          - QAST::IVal(2) 

    
    perl6 --target=optimize -e 'say 1 !< 3 !> 2
    
    - QAST::Op(callstatic &say) <sunk> :statement_id<?> say 1 !< 3 !> 2
      - QAST::Op(chain) <wanted> !>
        - QAST::Op(callstatic &METAOP_NEGATE)  :is_pure<?>
          - QAST::Var(lexical &infix:«>») <wanted>
        - QAST::Op(chain) <wanted> !<
          - QAST::Op(callstatic &METAOP_NEGATE)  :is_pure<?>
            - QAST::Var(lexical &infix:«<») <wanted>
          - QAST::Want <wanted> 1
            - QAST::WVal(Int) 
            - Ii
            - QAST::IVal(1)
          - QAST::Want <wanted> 3
            - QAST::WVal(Int)
            - Ii
            - QAST::IVal(3)
        - QAST::Want <wanted> 2
          - QAST::WVal(Int)
          - Ii
          - QAST::IVal(2)

As you can see, they are pretty similar besides a few 'callstatic' ops being substituted for 'call'. So this implementation is functional and gets the proper result, but may be missing out on some of the benefits of optimization.

**Comment by zoffixznet** [comment]
Ah, now I see. Changing it to `chain` indeed makes it miss [the call optimization that expects a `call` op](https://github.com/rakudo/rakudo/blob/b4df753dfcd4260ab9a0d40d1eb9dfdb5a5043d9/src/Perl6/Optimizer.nqp#L1336-L1345).

Right results are more important than fast results, so IMO I think it's OK to PR these changes (ensure they pass all tests in `make spectest` in rakudo) and add a `# TODO` comment that these need to be made static-optimized.

If it helps, QAST nodes can be annotated and the annotations can later be used in other places to do things:
```
<Zoffix___> m: use QAST:from<NQP>; my $qast := QAST::Op.new(:op<call>, :name<&die>); $qast.annotate('cat', 'meow'); say $qast.ann: 'cat'
<camelia> rakudo-moar b4df753df: OUTPUT: «meow␤»

<Zoffix___> m: use QAST:from<NQP>; my $qast := QAST::Op.new(:op<call>, :name<&die>); $qast.annotate('cat', 'meow'); say $qast.has_ann: 'cat'
<camelia> rakudo-moar b4df753df: OUTPUT: «1␤»
```

**Comment by jstuder-gh** [comment]
Do you want me to take a stab at the 'chain' mapping for the other backends before submitting a PR, or should I just submit what I have currently (and those can come later)?

**Comment by zoffixznet** [comment]
You can submit what you currently have.

**Comment by zoffixznet** [comment]
PRs merged; tests unfudged in https://github.com/perl6/roast/commit/bfe44db948
