### ISSUE TITLE
.raku should produce curly quotes

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1311]
Code:
```raku
say "foo".raku
```
Current output:
```
"foo"
```
Suggested output:
```
“foo”
```

Why:
> \<TimToady\> maybe for 6.d that should produce curly quotes, to make it easier to paste into windows shells
> \<TimToady\> since double-quotes are “taken” there…
> \<TimToady\> and we do have the info as to which quote is the opener and which is the closure
> \<TimToady\> so why throw away information?

**Comment by zoffixznet** [comment]
Worth mentioning the other two tickets we have:

* [RT#132452: Unicode: Windows shells print garbage instead of "｢｣"](https://rt.perl.org/Ticket/Display.html?id=132452#ticket-history)
* [RT#132441: [SEVERE] Windows REPL cannot handle «, » characters](https://rt.perl.org/Ticket/Display.html?id=132441#ticket-history)

**Comment by zoffixznet** [comment]
Moving this Issue from 6.d to 6.e

**Comment by lizmat** [comment]
Although this feels like a very simple change, an attempt at implementing this revealed quite severe test breakage.  Implementing this for 6.e only would only make an upgrade path of any existing codebase troublesome, especially with regards to testing.

So closing this now with a WONT IMPLEMENT
