### ISSUE TITLE
combinations sub no longer cheats

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1330]
Code:
```perl6
say +combinations 50, 7
```
Result (2017.11,af9812fa73^):
```
99884400
```

Result (af9812fa73,2017.12):
```
*timeout*
```

Bisectable: (2017-12-08) https://github.com/rakudo/rakudo/commit/af9812fa732927238715730d6c1e025bd89e74eb

**Comment by zoffixznet** [comment]
Fixed in https://github.com/rakudo/rakudo/commit/5eed2b002010bcc64a20084b87ef8c9b9ee07016 tests these methods exist in rakudo are in https://github.com/rakudo/rakudo/commit/5eed2b002010bcc64a20084b87ef8c9b9ee07016 the spec also contains [additional, detailed tests](https://github.com/perl6/roast/blob/9a1d5e7ed9bec0463c6341383b725955a4e6af15/MISC/bug-coverage.t#L21) for these that run when the iterator implements optimization methods.

**Comment by AlexDaniel** [comment]
Can we have a high-level test that makes sure these don't take forever to run?

**Comment by zoffixznet** [comment]
> a high-level test

What does that mean?

**Comment by AlexDaniel** [comment]
I missed it, sorry. It's here: https://github.com/rakudo/rakudo/commit/5eed2b002010bcc64a20084b87ef8c9b9ee07016#diff-e452fa5550c76e16ca4cd7fc4f86fc0cR5. I meant something that doesn't care about iterators and just tests that combinations gives the result relatively fast. That test does it.

**Comment by zoffixznet** [comment]
Yeah, I should've mentioned the tests test perf along with existence of methods.
