### ISSUE TITLE
Short script 'misusing' an iterator crashes Rakudo

### ISSUE THREAD

**Issue by dogbert17** [rakudo/rakudo#1340]
## The Problem

The following snippet causes Rakudo to SEGV:

    my SetHash $a = ('0/2', '2/2').SetHash; 
    my @result = (); 
    find-strongest($a); 
    sub find-strongest(SetHash $a) { 
      my $keys = $a.keys; 
      for $keys.List -> $item { 
        my @split-item = $item.comb; 
        $a{$item}:delete; 
        find-strongest($a); 
      }
    }
## Expected Behavior

Some kind of nice error message :-)

## Actual Behavior

SEGV

## Steps to Reproduce

See code snippet above

## Environment

Camelia on irc, see https://irclog.perlgeek.de/perl6-dev/2017-12-24#i_15619001 for more information.

**Comment by zoffixznet** [comment]
Golfed to:

```
<Zoffix_> m: use nqp; my $h := nqp::hash("a", 42); my $i := nqp::iterator($h); nqp::deletekey($h, "a"); nqp::iterval(nqp::shift($i)).say
<camelia> rakudo-moar bf6451dac: OUTPUT: «(signal SEGV)»
```

The SEGV looks to be inside `3rdparty/uthash.h`. I poked at it a bit, but didn't manage to fix.

After SEGV is fixed, we'd get `could not find candidate in postfix:<{ }>` because `.pull-one` from `.keys` would return a `null`. *That* IMO falls under DIHWIDT as the user is trying to iterate over the `.keys` `Seq` while reducing the number of available keys. 

To workaround the DIHWIDT, simply reify the `.keys` `Seq` right away, but shoving keys into an `Array`:

```perl6
my SetHash $a = ('0/2', '2/2').SetHash;
my @result = ();
find-strongest($a);
sub find-strongest(SetHash $a) {
  my @keys = $a.keys;
  for @keys -> $item {
    my @split-item = $item.comb;
    $a{$item}:delete;
    find-strongest($a);
  }
}
```

**Comment by dogbert17** [comment]
Seems to have been fixed by commit https://github.com/rakudo/rakudo/commit/8fd029a3025307f8ccac11adeed77d170408b5a8

**Comment by ab5tract** [comment]
No longer an issue:

```
> set-base; r 'use nqp; my $h := nqp::hash("a", 42); my $i := nqp::iterator($h); nqp::deletekey($h, "a"); nqp::shift($i)'

> set-rakuast; > r 'use nqp; my $h := nqp::hash("a", 42); my $i := nqp::iterator($h); nqp::deletekey($h, "a"); nqp::shift($i)'

> ./rakudo-m -v
Welcome to Rakudo™ v2024.04-92-g24057e69c.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-6-g84121f0de.
```
