### ISSUE TITLE
state variable resets for each loop of a loop expression

### ISSUE THREAD

**Issue by Summertime** [rakudo/rakudo#1341]
## The Problem
```pl6
say do loop { state $x = 0;  last if ++$x > 2;  $x; }
```
## Expected Behavior

outputs `(1 2)`

## Actual Behavior

outputs an infinite list `(1 1 1 1 1 1 ...)`

*aside:* it appears to work with jvm:
```pl6
j: say do loop { state $x = 0; last if ++$x > 2; $x }
<camelia> rakudo-jvm a92950fb4: OUTPUT: «(1 2)␤»
```

## Steps to Reproduce

```
PS C:\[...]> perl6 -e 'say do loop { state $x = 0;  last if ++$x > 2;  $x; }'
(1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ...)
```

## Environment
* Operating system: Windows 10 64bit
* Compiler version (`perl6 -v`):
```
This is Rakudo Star version 2017.10 built on MoarVM version 2017.10
implementing Perl 6.c.
```

**Comment by jstuder-gh** [comment]
This code produces the QAST subtree below:

        - QAST::Block(:cuid(3) :blocktype(declaration_static))  :statement_id<1> :in_stmt_mod<?> :code_object<?> :outer<?>
          - QAST::Stmts  { state $x = 0; last if ++$x > 2; $x }
          - QAST::Stmts 
            - QAST::Block(:cuid(1) :blocktype(immediate)) <wanted> :statement_id<2> :in_stmt_mod<?> :code_object<?> :outer<?> { state $x = 0; last if ++$x > 2; $x }
              - QAST::Stmts  
                - QAST::Var(lexical $x :decl(statevar)) 
                - QAST::Var(lexical $_ :decl(var)) 

The block cuid(3) gets cloned repeatedly by a looping construct and as a result a fresh new container is being created for the nested cuid(1) for each statevar instance. The value in each new container is reinitialized to 0, resulting in the result seen in the ticket when incremented.

I thought maybe I could make make_thunk_ref use cuid(1) when creating the target ref instead of having it create a new block cuid(3) to wrap cuid(1), but this failed the spec tests whenever UNDO phasers were involved.


What if we "elevated" the statevar up to the parent block cuid(3)? Since cuid(3) is created explicitly to wrap cuid(1) and provide a target for cloning, it shouldn't create any symbol conflicts or leak the statevar to surrounding scopes.

I hacked together a version that handles this specific case and it produces the QAST below (trimmed to the relevant bits), receives the desired result, and passes the spectest:

    - QAST::Block(:cuid(3) :blocktype(declaration_static))  :statement_id<1> :in_stmt_mod<?> :code_object<?> :outer<?>
      - QAST::Stmts  { state $x = 0; last if ++$x > 2; $x }
        - QAST::Var(lexical $x :decl(statevar)) 
      - QAST::Stmts 
        - QAST::Block(:cuid(1) :blocktype(immediate)) <wanted> :statement_id<2> :in_stmt_mod<?> :code_object<?> :outer<?> { state $x = 0; last if ++$x > 2; $x }
          - QAST::Stmts  
            - QAST::Var(lexical $_ :decl(var)) 

What if we were to annotate the enclosed block (ie cuid(1) ) to indicate the presence of the statevar and then within the wanted sub (where the final looping construct and enclosing thunk_ref are produced) check for the annotation and "elevate" the statevar if found? Does that seem like a valid solution to you?

It does create an odd special case, but it also works and seems relatively safe to me.
