### ISSUE TITLE
::?ROLE is not nqp::eqaddr the role's type, breaking `===`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1352]
This was found in an old [roast commit](https://github.com/rakudo/rakudo/commit/fe2be65806d907efbbaa). The value of `::?ROLE` does not `nqp::eqaddr` the role's type. 

Question is, should it? And if yes, should it also `===`? Right now `===` uses `nqp::eqaddr` and that causes it to fail:

```
<Zoffix__> m: use nqp; role Bar { method z { dd nqp::eqaddr(::?ROLE, Bar) } }; Bar.z
<camelia> rakudo-moar e2c7bcaec: OUTPUT: «0␤»

<Zoffix__> m: use nqp; role Bar { method z { dd ::?ROLE === Bar } }; Bar.z
<camelia> rakudo-moar e2c7bcaec: OUTPUT: «Bool::False␤»
```

**Comment by lizmat** [comment]
> On 30 Dec 2017, at 19:54, Zoffix Znet <notifications@github.com> wrote:
> 
> This was found in an old roast commit. The value of ::?ROLE does not nqp::eqaddr the role's type.
> 
> Question is, should it? And if yes, should it also ===? Right now === uses nqp::eqaddr and that causes it to fail:
> 
> <Zoffix__> m: use nqp; role Bar { method z { dd nqp::eqaddr(::?ROLE, Bar) } }; Bar.z
> <camelia> rakudo-moar e2c7bcaec: OUTPUT: «0␤»
> 
> <Zoffix__> m: use nqp; role Bar { method z { dd ::?ROLE === Bar } }; Bar.z
> <camelia> rakudo-moar e2c7bcaec: OUTPUT: «Bool::False␤»

FWIW, I think this is because Bar gets autopunned?  And the autopunned class is different from the un-autopunned role?

**Comment by zoffixznet** [comment]
> And the autopunned class is different from the un-autopunned role?

I would've thought the autopunned class would be in `::?CLASS` and the `::?ROLE` would remain the unpunned thing

**Comment by lizmat** [comment]
> On 30 Dec 2017, at 20:05, Zoffix Znet <notifications@github.com> wrote:
> 
> And the autopunned class is different from the un-autopunned role?
> 
> I would've thought the autopunned class would be in ::?CLASS and the ::?ROLE would remain the unpunned thing

Yes, but what is “Bar” in this context?  By the time you call .z on it, it has been autopunned.

**Comment by zoffixznet** [comment]
> Yes, but what is “Bar” in this context?  By the time you call .z on it, it has been autopunned.

Isn't "autopunning" is just a class being made behind-the-scenes automatically and the role being mixed into it? 

```
<Zoffix__> m: use nqp; role Bar { method z { dd [::?CLASS, ::?CLASS.HOW.^name, ::?ROLE, ::?ROLE.HOW.^name] } }; Bar.z
<camelia> rakudo-moar e2c7bcaec: OUTPUT: «[Bar, "Perl6::Metamodel::ClassHOW", Bar, "Perl6::Metamodel::ParametricRoleHOW"]␤»
```

That actually gave me the lead to figure out the problem. See how the `HOW` for `::?ROLE` above is just `ParametricRoleHOW`. For `Bar` it's `ParametricRoleGroupHOW`. Bar is a group of roles and `::?ROLE` is just one of the candidates. So for `nqp::eqaddr` to match, you have to match with a candidate:

```
<Zoffix__> m: use nqp; role Bar { method z { use nqp; dd nqp::eqaddr(::?ROLE, Bar.^candidates.head) } }; Bar.z
<camelia> rakudo-moar e2c7bcaec: OUTPUT: «1␤»
```

This is the same as with routines, where `&foo` is not a specific `&?ROUTINE` but just the routine that dispatches to the right thing:

```
<Zoffix__> m: multi foo { use nqp; dd nqp::eqaddr(&?ROUTINE, &foo) }; foo
<camelia> rakudo-moar e2c7bcaec: OUTPUT: «0␤»
<Zoffix__> m: multi foo { use nqp; dd nqp::eqaddr(&?ROUTINE, &foo.candidates.head) }; foo
<camelia> rakudo-moar e2c7bcaec: OUTPUT: «1␤»
```

So. Everything works as expected and there's no bug.

**Comment by jnthn** [comment]
> The value of ::?ROLE does not nqp::eqaddr the role's type.
> 
> Question is, should it?

No, and a quick peek at metaspace reveals why:

```
$ perl6 -e 'role Bar { method z { say ::?ROLE.HOW.^name; say Bar.HOW.^name; } }; Bar.z'
Perl6::Metamodel::ParametricRoleHOW
Perl6::Metamodel::ParametricRoleGroupHOW
```

Roles can be overloaded by signature, the best role being picked at composition time. The thing that is installed is thus a group, which you can think of as a bit like a `proto` sub, whereas `::?ROLE` is a particular variant, which you can think of a bit like a `multi` candidate. (This isn't far from the truth at all, since the multi-dispatcher is what's used to pick the role to use.)

Auto-punning was mentioned also, this isn't what's happening in this case, but of course the punned class won't be `===` to `::?ROLE` nor the short name that group is installed under. Further, there's also another form of a role that represent a role with all but its initial parameter (the initial parameter being the class it is finally composed in to), plus a transient concretization too that you never see unless actually meddling with meta-objects. All in all, there are 4 different types of meta-objects involved in representing roles, and a 5th if you count the pun (which is `ClassHOW`).
