### ISSUE TITLE
Semantic change with List.WHICH

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1425]
[This](https://github.com/perl6/roast/commit/5670acf676d65167e892515a42b71c81984f39f2) roast commit touches one of the 6.c-errata tests, so the question is whether it should be reverted or if we should change the test. To me it looks like one of those cases when we should keep our promise (of not breaking 6.c-errata tests) instead of trying to improve stuff, so this change will be reverted for the 2018.01 rakudo release.

So, are there any good reasons to rerevert within v6.c? Or if not, should we stage it for v6.d?

Ping @lizmat.

**Comment by lizmat** [comment]
Pinging @Larry

**Comment by vendethiel** [comment]
I think you mean @TimToady ?

**Comment by vendethiel** [comment]
I think you might mean @TimToady ?

**Comment by AlexDaniel** [comment]
FWIW before I drop to bed: here is another .WHICH-related change that has to be done in 6.c-errata: https://github.com/perl6/roast/commit/904ae98f034e705e6e090748de115a2468a6bc97

**Comment by zoffixznet** [comment]
> So, are there any good reasons to rerevert within v6.c? Or if not, should we stage it for v6.d?

IMO if it stays in v6.c it's as a direct violation of the 6.c spec as it can get:

1) The test explicitly tests the affect feature
2) The test's description explicitly says it's testing that `"List is not a value type"`
3) [A user was affected](https://irclog.perlgeek.de/perl6/2017-12-29#i_15631531) by the change and commented about this being changed in 6.c

We're already skating on thin ice with our promise of language stability due to all the changes that were made since December 2015 that made it in simply because they were not covered by spec or the spec tests were argued to be incorrect. If we accept a direct violation of the spec, we can no longer lay claim to language stability.

I rather we take this opportunity to forge a piece of proof that our language is stable and defer this change until 6.d.

--------

TimToady did [make a short comment here](https://irclog.perlgeek.de/perl6-dev/2017-12-30#i_15633354):

```
<TimToady> possible we should distinguish a Tuple type in 6.d
```

**Comment by jnthn** [comment]
I don't think `List` should behave like a value type depending upon its content - and I mean not ever, let, alone in 6.c. TimToady's comment that we could do it as a separate `Tuple` type would be a better way to go.

**Comment by lizmat** [comment]
Ok, that settles it.  Commit has been reverted, as have been the tests, right?  If so, this issue can be closed and we'll start to think about implementing a Tuple type for 6.d.  Which probably will also mean we should have a look at Arrays and Lists as well (do we really need them to be subclasses of each other??)

**Comment by AlexDaniel** [comment]
@lizmat correct

Maybe this ticket should be repurposed for discussion about Tuple?

**Comment by AlexDaniel** [comment]
Wait, does it mean that 729caa8f should also be reverted?

**Comment by lizmat** [comment]
Yes, that also should be reverted.

**Comment by AlexDaniel** [comment]
Actually, https://github.com/rakudo/rakudo/commit/729caa8f17f4cb94c90e0da547a5c3978a14ff16 was reverted together with https://github.com/perl6/roast/commit/5670acf676d65167e892515a42b71c81984f39f2 in this commit: https://github.com/perl6/roast/commit/906c688aba2ab99c5eb77fb7e0b581f96500bb33
So it's good.

**Comment by ab5tract** [comment]
There are more recent movements to deal with the underlying issue: #5510. Closing this as the initial quandary about 6.c-ness was resolved long ago.
