### ISSUE TITLE
`let`/`temp` fail to restore holes in arrays

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1433]
```
<Zoffix__> m: (my @a is default(Nil))[3] = 42; say @a[1]:exists; say @a; { let @a; Nil }; say @a[1]:exists; say @a
<camelia> rakudo-moar 0a1641e94: OUTPUT: «False␤[Nil Nil Nil 42]␤True␤[(Any) (Any) (Any) 42]␤»

<Zoffix__> m: (my @a is default(Nil))[3] = 42; say @a[1]:exists; say @a; { temp @a; Nil }; say @a[1]:exists; say @a
<camelia> rakudo-moar 0a1641e94: OUTPUT: «False␤[Nil Nil Nil 42]␤True␤[(Any) (Any) (Any) 42]␤»
```

**Comment by raiph** [comment]
I just tried this and the holes are now restored to the default. But that's not the same as restoring the variable, and its holes; note the difference in `@a[1]:exists`:
```
(my @a is default(Nil))[3] = 42; say @a[1]:exists; say @a; { let @a; Nil }; say @a[1]:exists; say @a;
# OUTPUT: «False␤[Nil Nil Nil 42]␤True␤[Nil Nil Nil 42 ]␤»

(my @a is default(Nil))[3] = 42; say @a[1]:exists; say @a; { temp @a; Nil }; say @a[1]:exists; say @a;
# OUTPUT: «False␤[Nil Nil Nil 42]␤True␤[Nil Nil Nil 42 ]␤»
```

**Comment by vrurg** [comment]
While generally speaking I'd rather agree that it makes sense for a hole to be restored, I'm not sure it worth the cost to implement this functionality. Because technically `let` is a routine and `@a[$i]` results in an auto-vivified container which then gets passed into `let` as an argument, there is no way for the operator to know that it operates on an array element.

The task could be done by the phaser code, the compiler installs to actually implement the restoration process. But that code is agnostic about what it operates upon. In order to function correctly (including itemized arrays like in `$a[$i]` case) it would have to introspect the object. This  would involve cases like `I-return-array()[$i]`, `$obj.a[$i]`, etc.

Ok, the postcircumfix tips the compiler about possible line of actions to be taken. But what about `$obj.a.AT-POS($i)`? Or any kind of alternate method implementing similar functionality on a `Positional`?

There is a workaround though which I'm not yet fully certain about as it just have came into my mind. It should be possible to mark an auto-vivified `Scalar` as a "hole representative". It could be a container descriptor flag, which would be reset as soon as the scalar gets assigned. Having a way to distinguish a "hole representative" from other scalars could provide a way to implement a solution.

**Comment by raiph** [comment]
See also https://github.com/rakudo/rakudo/issues?q=is%3Aissue+is%3Aopen+hole+in%3Atitle

**Comment by vrurg** [comment]
Closing via #4602
