### ISSUE TITLE
Type constraints on constants not implemented

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1503]
I spotted code in core that `.=` is supposed to work on `constant` declarations, however, you can't specify the type constraint, making `.=` rather pointless:

```
<Zoffix__> m: constant Int $foo .= new: 42;
<camelia> rakudo-moar 562edfc50: OUTPUT: «===SORRY!=== Error while compiling <tmp>␤Missing initializer on constant declaration␤at <tmp>:1␤------> constant Int⏏ $foo .= new: 42;␤»
```

**Comment by jnthn** [comment]
>  constant Int $foo .= new: 42;

That's the wrong syntax for a typed constant, though. We can't put the type after the word `constant`, because it'd be ambiguous (given one can write `constant PI = 3.14`). The type would instead go after a scope declarator, e.g. `my Int constant ANSWER = 42`. This is currently parsed, but also ignored.

**Comment by zoffixznet** [comment]
Thanks. That explanation also explains why some of the `.=` cases mentioned on #1504 weren't working.

**Comment by zoffixznet** [comment]
> Type constraints on constants not implemented

[They are now](https://github.com/rakudo/rakudo/commit/a1f544ad42d56aa969f1ea23c62fd3a768027535). With tests in https://github.com/perl6/roast/blob/master/S04-declarations/constant-6.d.t

```
m: my Int constant $foo .= new: 42; dd $foo                                                                                                          rakudo-moar 2177ee234: OUTPUT: «42␤»
```
