### ISSUE TITLE
Type coercion turns optional named argument into required one substantially

### ISSUE THREAD

**Issue by titsuki** [rakudo/rakudo#1517]
## The Problem
Type coercion (e.g., `Num(Rat)`) turns optional named argument into required one substantially.
Even if explicitly specify `?` to a named argument, it requires to specify the named argument:
```
$ perl6 -e 'sub func(Num(Rat) :$v?) { say $v if $v.defined; }; func();'
Cannot look up attributes in a Rat type object
  in sub func at -e line 1
  in block <unit> at -e line 1
```

## Expected Behavior
Even if the named argument isn't given, it doesn't cause an error because the named argument is optional.

## Actual Behavior
It cause an error.

## Steps to Reproduce

```
$ perl6 -e 'sub func(Num(Rat) :$v?) { say $v if $v.defined; }; func();'
Cannot look up attributes in a Rat type object
  in sub func at -e line 1
  in block <unit> at -e line 1
```

## Environment
* Operating system: Debian stretch
* Compiler version (`perl6 -v`): 
```
$ perl6 --version
This is Rakudo version 2017.12-211-g029226fe9 built on MoarVM version 2017.12.1-30-ged7c1234f
implementing Perl 6.c.
```

**Comment by zoffixznet** [comment]
To note, optionality has little to do with this problem. All arguments have values; see last paragraph [in this section](https://docs.perl6.org/type/Signature#Constraining_Defined_and_Undefined_Values)

-------

The problem is the default-default value of a coercer attribute gets the source value (`Rat`) instead of the target one (`Num`). We actually already fixed a type of this problem on master, in [a recent commit](https://github.com/rakudo/rakudo/commit/ae697080d2d522552e7fb8d168a1bfd2da127bae). Not yet sure why it's not picking up this case...

However, the problem in OP's case is the `Num` *is not* a `Rat`. So even if the fix in the commit picked it up, it'd typecheck-fail, like this:

```
<Zoffix__> m: -> Num(Rat) $x? { dd $x }(Num)
<camelia> rakudo-moar 00af9ce27: OUTPUT: «Type check failed in binding
    to parameter '$x'; expected Rat but got Num (Num)␤  in block <unit> at <tmp> line 1␤␤»
```

So looks like there's no winnable scenario for coercers that convert from two types that aren't subclasses, since if we modify the default type check from Rat to Num, it'd sort differently in multi-dispatch, wouldn't it?

@jnthn , do you have any suggestions?
