### ISSUE TITLE
.subst/.subst-mutate should always return a List when :g is specified

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1523]
When `.match` is used with `:g`, and no matches occur, the return value and `$/` are an empty list:

```
$ perl6 -e 'dd "foo".match(/z/, :g); dd $/'
()
List $/ = $( )
```

The same is not the case for `.subst`/`.subst-mutate`, which return the same value as for singular (non-`:g`) matches:

```
$ perl6 -e '"foo".subst: /z/, "x", :g; dd $/'
Nil $/ = Nil

$ perl6 -e 'dd ($ = "foo").subst-mutate: /z/, "x", :g; dd $/'
Nil
Nil $/ = Nil
```

Which creates problems if the user is storing those matches somewhere:
```
$ perl6 -e 'my @matches := ($ = "foo").subst-mutate: /z/, "x", :g;'
Type check failed in binding; expected Positional but got Nil (Nil)
  in block <unit> at -e line 1
```
Or even silently storing wrong values:

```
$ perl6 -e 'my @matches = ($ = "foo").subst-mutate: /z/, "x", :g; dd @matches'
Array @matches = [Any]
```
---

```
$ perl6 -v
This is Rakudo version 2018.01 built on MoarVM version 2018.01
implementing Perl 6.c.
```

**Comment by lizmat** [comment]
subst-mutate should be fine now (77794a28aab724a73d07) (tests needed).

wrt to subst, I assume you mean that $/ should always be a list when :g is specified.  I’m afraid the semantics of that are not really developed yet, e.g. doing a subst using a Str rather than a Regex, doesn’t set $/ at all:

$ 6 '$/ := "bar"; "foo".subst("o","x"); say $/‘
bar

FWIW, this interaction between $/ and .subst has always been a little too esoteric and action at a distance to me.  Not to mention the overhead involved.  So I wouldn’t mind this going away in 6.d

**Comment by zoffixznet** [comment]
> I assume you mean that $/ should always be a list when :g is specified.

That's what I meant, yeah.

> So I wouldn’t mind this going away in 6.d

I now recall that's [already proposed for method forms](https://github.com/perl6/6.d-prep/blob/master/TODO/FEATURES.md#make-method-matcher-forms-not-set-). And `s///` and `S///` always use regexes (the only catch is currently they use method forms under the hood)

**Comment by zoffixznet** [comment]
Mentioned the `.subst` (or rather `S///` thing) on 6.d-prep for [`Make method matcher forms not set $/` TODO](https://github.com/perl6/6.d-prep/blob/master/TODO/FEATURES.md#make-method-matcher-forms-not-set-). 

Tests in https://github.com/perl6/roast/commit/8c358cfc87adde779e7965f871cf27a4aca1ddb3
