### ISSUE TITLE
Add reminder of memory requirements to website and/or build doco

### ISSUE THREAD

**Issue by drforr** [rakudo/rakudo#1548]
A brief reminder that ~1.25Gb of RAM is recommended to build rakudo would be appreciated, either as part of the instructions on https://perl6.org/downloads/ or a reminder during the build step. Of course this figure is only an approximation, but for those of us that still build by hand, the occasional reminder of "Hey, we need >1Gb of RAM to build, are you *sure* you've allocated enough in your VM?" or "Huh, this is taking a *really* long time to build... oh, yeah, they *said* I needed >1Gb to build, no wonder." would certainly help.

Something as simple as:

"You will need recent versions of perl, git, make and gcc. Also a basic familiarity with UNIX.<br\>
(We recommend at least 1.25Gb of RAM for the initial build.)"

would do the trick.

**Comment by zoffixznet** [comment]
> part of the instructions on https://perl6.org/downloads/ 

👎 That page is cluttered as it is

> a reminder during the build step

👍 Print it right along with the "The following step can take a long time, please be patient" statement. I image building on JVM backend might have different RAM requirement, so could be handy to measure it to know what it is.

**Comment by drforr** [comment]
+1 for "The following step..." - I don't find the HTML too cluttered, but I understand not wanting to go overboard.

I'd be happy with the latter. I know that it can only be an approximation, especially if someone is building a JavaScript or JVM target, but the reminder would be a nice touch. History: I ran a MoarVM build in a 1Gb VirtualBox installation and things ground to a virtual halt; it took me a bit to remember "Oh, yeah, I just used the default RAM for that, no wonder." Had the reminder been available, even on the console, I'd probably have thought "Oh, wait, it's running in 1Gb... _kill, shutdown, bump RAM, restart_"

**Comment by stmuk** [comment]
On 20 February 2018 at 12:03, Zoffix Znet <notifications@github.com> wrote:

> part of the instructions on https://perl6.org/downloads/
>
> 👎 That page is cluttered as it is
>

Totally agreed!


> a reminder during the build step
>
> 👍 Print it right along with the "The following step can take a long
> time, please be patient" statement. I image building on JVM backend might
> have different RAM requirement, so could be handy to measure it to know
> what it is.
>

This is a better idea.

I'd just suggest adding "2Gb of RAM recommended" at this point (similar to
the message rakudup prints) even if its not exactly the figure (and its
technically VM rather than RAM anyway).

I've found adding a temporary swap file (rather than partition) is often
handy as a quick fix in low RAM situations (Raspberry PI, cheap VM)
whatever but the trouble with documenting everything like this is that the
docs get too long and people don't read them anyway! There comes a point
where a certain level of technical knowledge is needed anyway.

-- 
Steve Mynott <steve.mynott@gmail.com>
cv25519/ECF8B611205B447E091246AF959E3D6197190DD5
