### ISSUE TITLE
Segfault in one liner that used to work in 2018.01

### ISSUE THREAD

**Issue by JRaspass** [rakudo/rakudo#1550]
I bumped Perl 6 on code-golf.io and one solution that used to pass under 2018.01 now segfaults under 2018.02. I've tried to golf the already golfed solution down and have the following one liner that reliably segfaults on my laptop:

```
$ perl6 -e 'my%m=0,1;my&f={%m{$_}//=$_+f($_-1)};.say for map 1/*.&f,^250'
```

**Comment by zoffixznet** [comment]
Bisecting this puts blame on the [whatever currier re-design](https://gist.github.com/815fe3d8db848d7cb9d00ae9d43fdc2d).

Setting `MVM_SPESH_INLINE_DISABLE` avoids the issue, but I think the problem is in the new currier. The AST has a gutted block that'd normally you'd see from multi-arg Whatevers, which I don't see here.

```
MVM_SPESH_INLINE_DISABLE=1 ./perl6 -e 'my %m = 0, 1; my &f = { %m{$_} //= $_ + f($_-1) }; .say for map 1/*.&f, ^250'
```

Gonna take a closer look in ~3h

**Comment by AlexDaniel** [comment]
@JRaspass thanks for reporting. That was pretty quick.

**Comment by zoffixznet** [comment]
Bug's [fixed](https://github.com/rakudo/rakudo/commit/5270471c38) with tests in https://github.com/perl6/roast/commit/4f6cd0c388

We [talked](https://irclog.perlgeek.de/perl6-dev/2018-02-22#i_15846592) on IRC and given the scope of this bug's impact, I think we'd need to cut a point release.

-----

The bug was in QAST gen. While the incorrect QAST tickled a part of MoarVM that segfaults, considering it took us less than 5 minutes to find the place (and cause) of that SEGV, I'm *not* going to add a NULL check in that place, because it's inside a common operation and it's partially already guarded by the assumption that if code survives long enough, it wouldn't be errors that cause that pointer to be NULL.

*(excerpt from https://irclog.perlgeek.de/perl6-dev/2018-02-21#i_15843401 )*
```
<jnthn> It's assuming that if the interpreted code survives long enough to be JITted, 
             then it didn't have bounds errors on the outer chain
<jnthn> There's even a comment saying so, iirc :)
<jnthn> Zoffix: And yeah, NULL guarding is probably the right thing
<jnthn> Though it's kind of annoying to have to do it on such a common thing (lexical lookup)
```

In case check for that NULL is required for some reasons I'm unaware of, it would go somewhere around here, the SEGV is due to the `f` pointer being NULL: https://github.com/MoarVM/MoarVM/blob/642a2afa8bf0d4f69e2d7235842d1231941cb9f1/src/core/interp.c#L5737
