### ISSUE TITLE
Should we allow "is pure" on proto's in the setting

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#1574]
Currently, many `proto sub`s in the setting carry a "is pure" trait.

I think this is actually incorrect, as there is no guarantee that all candidates will always return a "is pure" result, since additional candidates can be added after the setting has been compiled.

So I think that at least in the setting, the "is pure" trait should live on the candidates, but *not* on the `proto`.

Suggestions / Comments?

**Comment by zoffixznet** [comment]
:+1:  as this is LTA:

```
m: multi infix:<+> (Num:D, Int:D) {say 42}; say 42e0 + 42; INIT say "ended compile"
rakudo-moar 32b08035b: OUTPUT: «42␤ended compile␤True␤»
```

---------

Currently, putting it on the candidates will disable all constant folding, as in the optimizer we [don't try to find a specific candidate before checking pureness](https://github.com/rakudo/rakudo/blob/32b08035b42d9e94cec6cd624a99a33adab6e69e/src/Perl6/Optimizer.nqp#L1458-L1464) (another location [for chained ops](https://github.com/rakudo/rakudo/blob/32b08035b42d9e94cec6cd624a99a33adab6e69e/src/Perl6/Optimizer.nqp#L1387-L1392)).

```perl6
proto foo(|) {}; multi foo (Int) is pure {}; multi foo(Any) {};
&foo.can("is-pure").say; # OUTPUT: «()»
```

So that'd need to be modified first (I think `.cando` method on routines can be used?).

------

Partly-related: comments from TimToady on assumptions about what users adding custom ops would expect (regarding other optimizations): https://irclog.perlgeek.de/perl6-dev/2018-02-07#i_15786958

Perhaps, we should ask a bigger-picture question: should users defining custom candidates be expected to opt-in or opt-out of optimizations and how would they do that? And then apply that principle consistently across the language.

**Comment by jnthn** [comment]
> I think this is actually incorrect, as there is no guarantee that all candidates will always return a "is pure" result, since additional candidates can be added after the setting has been compiled.

Creating a non-pure definition of an operator a typical language user would quite reasonably expect to be pure would be unusual and antisocial. In fact, the very reason Perl 6 allows the definition of new operators is so there is no need to override existing ones with unrelated behaviors. An `infix:<+>` that does side-effects meets the standard to "too different" and so should be declared as a different operator.

The `is pure` being on the `proto` has the benefit that those who declare overloads of operators that behave appropriately will automatically get constant folding of there operators for free. Surely, the burden should be placed on those creating surprising behavior to find a way to opt out of the optmization, not on those doing things that are entirely reasonable to opt in.

Overriding an operator means you have to play along with the precedence and associativity set down by its `proto`; I see no reason for `is pure` to be an exception to this rule.

**Comment by lizmat** [comment]
Message understood.  Thank you!
