### ISSUE TITLE
Arbitrary drift of methods to `Mu` and `Any`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1575]
I'm noticing we're gradually moving many methods to `Any` and `Mu` types, and by extension, making them part of the interface of all Perl 6 objects.

Looking at diff between 2015.12 Rakudo and HEAD (v2018.02.1.63.g.7835652.d.5), we've added 3 new methods to `Mu`—`.emit`, `.iterator`, and a `.splice` proto (no candidates??). When it comes to `Any` we added a whopping 11 new methods and I can't say I understand why they belong in it:

```
.Map
.Seq
.batch
.collate
.match
.maxpairs
.minpairs
.serial
.skip
.substr
.toggle
```

Why can `.toggle`, `.pick`, and `.roll` be called on `Any`, but not `.map`, `.reduce`, or `.produce`? Why can `.batch`, `.combinations`, and `.permutations` be called on `Any`, but not `.rotor`, `.rotate`, or `.grep`? Why can `.skip`, `.substr`, and `.match` be called on Any, but not `.hyper`, `.subst`, or `.uc`?

If we're following the any-class-can-be-1-el-list semantics, does that mean **all** methods offered by `List` and `Seq` types must be part of `Any`? (`Mu`?)

Does it really make sense for every Perl 6 class to have `.match` or `.substr` as part of their interface? Considering they're not `Cool` and don't have other stringy methods, like `.chars` or `.uniprop`. Stringifying them warns, suggesting it's an out-of-ordinary behaviour for an arbitrary Perl 6 class to be stringified. `&substr` can take an `Any`, which presumably was used to justify adding it to `Any` as a method, but if anything, it's `&substr` that should change to constrain on `Cool`.

`.serial` and `.collate` aren't even documented, so without reading the source code I can't even say what they do, yet these are part of the interface of 99% of Perl 6 objects.

----

What exactly is the criteria used to add methods to classes that are used as ancestors by all Perl 6 types?

**Comment by lizmat** [comment]
Good question.  I'm not too sure either.

**Comment by llelf** [comment]
+1.

Case in point: having `rule serial` in a grammar and getting cryptic errors (true story :-/).

**Comment by jnthn** [comment]
The overall design principle is:

* `Mu` should be kept pretty minimal. It should contain built-in methods that should not auto-thread over `Junction`s, such as `Bool`, `ACCEPTS`, the various method forms of control operators, and the uppercase methods like `WHERE` that we currently choose to implement as methods rather than as a special compiler form. It's simply wrong that `split` and `splice` are in there.
* `Any` should contain methods that operate on lists, under the principle that an any value can be treated as a one-element list. It's for sure that `match` and `substr` violate this principle. I believe `collate` is a form of `sort` but applying Unicode collation rules, so that one would be OK.
* `Cool` should contain coerce-and-delegate methods that allow types inheriting from it to happily act like a string or a number. Thus `match` and `split` would belong in here, not in `Any`.

**Comment by lizmat** [comment]
I started working on normalizing this (88d61bd945 for `splice`).

However, if a look at `split`, I see all classes but `Str` have `only method`.  So, do I just move the `proto` from `Mu` to `Cool` (which would look strange, as the version in `Cool` is an `only method`) or convert all `only method`s to `multi method`s as well?

**Comment by zoffixznet** [comment]
> I see all classes but Str have only method

I think then it can just go to `Str`?

**Comment by lizmat** [comment]
Sure it can, but I'm more looking for a "best practice" answer, than a fix for this particular problem.  Sorry I wasn't clear enough about that.

**Comment by zoffixznet** [comment]
This Issue was [touched today on the chat](http://colabti.org/irclogger/irclogger_log/perl6?date=2018-06-13#l753)…

There's kind'f a snag:

> Any should contain methods that operate on lists,
> […] It's for sure that match and substr violate this principle

But… `List`s *are* `Cool`. You can call `substr` on a list, but not on an "any value treated as one-element list".
