### ISSUE TITLE
Nodality of .produce / .reduce

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#1633]
## The Problem

$ 6 'dd [[2, 3], [4, [5, 6]]]».produce(&[+])'
((2, 5).Seq, (4, 6).Seq)

This is the expected outcome if `.produce` is considered to be nodal, at least in my understanding.
The >> descends 1 level, sees `[2,3]` and produces `(2,2+3)`, sees `[4, [5,6]` and produces `(4,4+[5,6])`

## Expected Behavior

`S03-metaops/hyper.t` tests 134-135 expect a non-nodal answer, namely

    [[(2,).Seq, (3,).Seq], [(4,).Seq, [(5,).Seq, (6,).Seq]]]

## Actual Behavior

I think the behaviour since 08eb465f9fcd0fc686f13 is actually the correct behaviour, and the tests are currently wrong.

## Environment
* Operating system: 
* Compiler version (`perl6 -v`):

**Comment by zoffixznet** [comment]
> and the tests are currently wrong.

Also, `.flat` is tested in the same file for being nodal, but the test's `$expected` is incorrect and shows the current non-nodal behaviour.

Also, `.head`/`.tail` IMO should be nodal, because `.AT-POS` is.

**Comment by zoffixznet** [comment]
It's mildly annoying the current master has those tests failing as that requires all the developers try to separate those failures from failures caused by the changes they made.

This also breaks automated tools like Z-Script version bumper that relies on clean stresstest to perform the automated bumps.

Either the fixed tests should be pushed with the commit that changes the behaviour or the changed behaviour should be made in a separate branch and PRed with request to review the test changes.
