### ISSUE TITLE
users should have access to a usable “pid” attribute (process id)

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#1638]

**Comment by Kaiepi** [comment]
Doesn't this exist?
```
> $*PID
45402
```

**Comment by zoffixznet** [comment]
Given on what the OP's been working on recently, I believe they meant `pid` for the process being run by `Proc`/`Proc::Async` objects.

**Comment by AlexDaniel** [comment]
@zoffixznet is correct, and the OP is probably not very wordy because this is a relatively known issue.

We already have these tickets:
* [RT#126380](https://rt.perl.org/Ticket/Display.html?id=126380) (``Proc``)
* [RT#126381](https://rt.perl.org/Ticket/Display.html?id=126381) (``Proc::Async``)

I'm closing both of them now because `Proc` is nowadays built upon `Proc::Async`, so once `Proc::Async` gets a `.pid` it should be trivial to add it to `Proc`.

**Comment by jnthn** [comment]
Available in `Proc::Async` thanks to Rakudo commit https://github.com/rakudo/rakudo/commit/1321917d1b and tested in https://github.com/perl6/roast/commit/cbb0422090.

I'm not sure how useful it would actually be on `Proc`, though I'm dubious about any use of synchronous `Proc` stuff beyond a simple `run` or `shell`. I'll let somebody who actually uses synchronous process stuff beyond that figure out how it might sensibly look there, if we want to provide it.

**Comment by lizmat** [comment]
@tbrowder: did you mean `Proc`, `Proc::Async` or both?

**Comment by tbrowder** [comment]
The problems I’ve needed the pid with used Proc::Async, so that’s my first choice for now.

**Comment by lizmat** [comment]
Support for `Proc.pid` added with 05816139ea

**Comment by Kaiepi** [comment]
Added tests for `Proc.pid` in perl6/roast@d9a4a65b1c

**Comment by zoffixznet** [comment]
> Added tests for Proc.pid in perl6/roast@d9a4a65

with additional fixes in https://github.com/perl6/roast/commit/eeb1086cf91090c7286bceb877f7e5a163403a75#diff-7088a842985d0ab3a21036456545189f
