### ISSUE TITLE
first() does not accept multiple positionals in signature

### ISSUE THREAD

**Issue by 0racle** [rakudo/rakudo#1657]
## The Problem

`List.kv.first(-> $k, $v { ... })`  fails with `Too few positionals passed`

## Expected Behavior

In most scenarios, `first` should accept whatever `grep` accepts, ie, result should be akin to this

```perl-6
say (3, 1, 2).kv.grep(-> $k, $v { $v == $k })[0];
# OUTPUT: (1 1)
```

## Actual behavior

```perl-6
say (3, 1, 2).kv.first(-> $k, $v { $v == $k });
# STDERR: Too few positionals passed; expected 2 arguments but got 1
```

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2018.03-92-g1c4eebe built on MoarVM version 2018.03-31-gfdb5e4d

However, it appears this was never spec'd, as bisectable stated that "On both starting points (old=2015.12 new=5db9ebc) the exit code is 1 and the output is identical as well"

**Comment by zoffixznet** [comment]
👎 on this.

`.first` returns the first item that smartmatches against the given matcher. There's no reason to overcompilate and overengineer `.first` to be just a `.grep` with implicit `.head` tucked to it. What's the point of having it then?

In fact, I'd argue the opposite way. `.grep` automatically `.rotor`ing the given list just because the matcher's `.count` is not 1 is unintuitive and surprising. If I wanted to `.rotor`, I'd do it myself. If there were any behaviour for `.count > 1` Callables at all, I would've expected the Callable to simply receive the extra elements to let me decide whether the first one should make it into the final list and not to `.rotor` anything.

In other words, I understand OP as proposing `say (3, 1, 2).kv.first(-> $k, $v { $v == $k });` to print `(1, 1)`, but that's not "the first item" in the list. It's extra pre-processing performed on the list, which is then matched against. The returned item is nowhere to be found in the list. Instead of moving 2-at-a-time and returning a List, I would've expected it to move 1-at-a-time, giving two consecutive items to the Callable and return the first item when Callable returns true (i.e. `$k` would always be returned, and `$v` would always be the next item after `$k`).

This works, is short, and doesn't require any extra knowledge on behalf of the reader to know how `.count > 1` Callables on `.first` behave.
```
<Zoffix__> m: say (3, 1, 2).kv.rotor(2).first: { [==] $_ }
<camelia> rakudo-moar e3aef509b: OUTPUT: «(1 1)␤»
```

**Comment by 0racle** [comment]
Thanks for the input, @zoffixznet. I agree that I was not really interested in "the first item", so in that sense I guess I was not using `first` idiomatically here. I wasn't sure whether this was bug-worthy, which is why I asked on IRC. 

  > I'd argue the opposite way. .grep automatically .rotoring the given list just because the matcher's .count is not 1 is unintuitive and surprising.

It's not doing anything automatically, `.kv` returns a flat list, and then grep pulls 2 elems at a time, just like a loop
 
```> <A B C>.kv
(0 A 1 B 2 C)
```

  > If I wanted to .rotor, I'd do it myself. 

I certainly figured I could work around the limitation the same way you did (albeit with `batch` instead of `rotor`). My use case was slightly different than my example, and I eventually went with `@a.keys.first(-> $k { @a[$k] eqv @b[$k] }).defined`. There are other ways, as well

The point is, I'm familiar enough with Perl 6 to know how to work around that limitation as soon as it happened, as are you... Will others? We like to tout Perl 6 as being highly composeable, so the question then becomes: Does this break composeability enough to warrant a change?

If the answer is a resounding "no", then please close the issue.

**Comment by lizmat** [comment]
Perhaps this is a lazy enough workaround in that it will stop as soon as the first item is found as well:

    List.kv.grep(-> $k, $v { ... }).head

I agree that adding this the .first feature list may be a bit much.  Note that if you don’t need the index value inside the block, you can use the :kv named parameter on .first:

    $ 6 'say <a b c>.first( "c", :kv )'
    (2 c)

or if you only want to know the index:

    $ 6 'say <a b c>.first( "c", :k )'
    2

**Comment by zoffixznet** [comment]
> The point is, I'm familiar enough with Perl 6 to know how to work around that limitation as soon as it happened, as are you... Are others?

FWIW, I didn't know grep had any features for `.count > 1` Callables until today. I never would've expected it to have that and it's also not even documented.

I see exactly one test in roast defining this surprising behaviour and ironically the author of the test felt it necessary to provide a commented out `.map` example to explain what's even going on. As stated earlier, the current behaviour isn't how I would've thought N-at-a-time grep would've worked. Both grep and first are like a filter in my eyes; they aren't meant to mutate my data.

So, TBH, I'm not buying the idea of someone who can surmise the correct undocumented behaviour of .grep with `.count > 1` Callables, yet is so helpless with the language to not think of an alternative.

> We like to tout Perl 6 as being highly composeable

People love to use these vague catch phrases to justify overengineering things, but I think the endgame with such an approach is a bloated language with a thousands of methods that all do the same thing: a God Function that takes a billion arguments and is able to produce a cornucopia of specialized outputs. 

`.grep` with `.count > 1` Callables should never have existed and neither should .`first`. The alternatives are very short and accessible.

**Comment by zoffixznet** [comment]
Actually, I see even that one test isn't expecting the actual structure produced by today's grep and is passing for the wrong reason ( filed as https://github.com/rakudo/rakudo/issues/1661 ). So among three people, we now have three different expectations for how this feature was meant to work at all.

**Comment by lizmat** [comment]
Please note that .first was from before the GLR *and* before we had .head.  So I think there is some historical baggage here.

**Comment by 0racle** [comment]
I'm ok for closing this... I raised this issue because I wasn't sure if this was intended behavior. It's probably the first time I (or possibly anyone) attempted to use `first` in this manner, so I don't think anyone is sorely missing this feature.

Adding the fact that there are plenty of alternate forms that can produce this functionality, there's little reason to make a change here.

**Comment by lizmat** [comment]
Agreeing with 0racle, so closing
