### ISSUE TITLE
Inconsistent handling of Cool -> Str migration

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#1724]
Some methods have an `only` in `Cool`, convert to `Str` and pass it on to a `proto` and `multi` in Str.  Some of these actually restrict to `Cool:D`.  Some of these call `Stringy` instead of `Str` to stringify.

Other methods have a `multi` in `Cool`, convert to `Str` and pass it on to the candidate in `Str`.

This results in these different behaviours:

    $ 6 'dd Cool.chomp'
    Invocant of method 'chomp' must be an object instance of type 'Cool', not a type object of type 'Cool'.  Did you forget a '.new'?

    $ 6 'dd Cool.uc'
    Use of uninitialized value of type Cool in string context.
    Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
      in block <unit> at -e line 1
    ""

    $ 6 'dd Cool.chop'
    Cannot resolve caller chop(Cool: ); none of these signatures match:
        (Cool:D $: *%_)
        (Cool:D $: $n, *%_)
      in block <unit> at -e line 1

It feels to me that this last behaviour is the most useful.  But I could be persuaded otherwise.  In any case I feel that the behaviour of these methods should be consistent.

**Comment by zoffixznet** [comment]
FWIW, in the past we had bugs that:
- had different behaviour between Cool and Str/Numeric methods because the candidates were not the same
- had hangs with wrong args because dispatch was bouncing between Cool and Str/Numeric candidates

So IMO it makes sense for most Cool candidates to just capture args in `only` methods, coerce to right type, and forward all the args. But I guess that has a performance penalty, especially now, where using captures prevent dispatch caching.

---- 

For "Use of uninitialized value in string context" stuff. I've long been been a proponent of ditching that behaviour for strings and numerics, but last time I tried to remove it there were tons of failing tests. I wouldn't be surprised if removing it from stuff like `Cool.uc` would either fail the spectests or create inconsistencies (e.g. Cool.uc throws, while Str.uc warngs, because it's specced to do so or something).

**Comment by ab5tract** [comment]
All three examples now result in the same behavior:

```
> r 'dd Cool.uc'
Cannot resolve caller uc(Cool:U: ); none of these signatures matches:
    (Cool:D: *%_)

> r 'dd Cool.uc'
Cannot resolve caller uc(Cool:U: ); none of these signatures matches:
    (Cool:D: *%_)

> r 'dd Cool.chomp'
Cannot resolve caller chomp(Cool:U: ); none of these signatures matches:
    (Cool:D: *%_)
    (Cool:D: Cool:D $needle, *%_)
    
> ./rakudo-m -v
Welcome to Rakudo™ v2024.04-106-gcf87ccf95.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-7-gfe2080ac3.
```
