### ISSUE TITLE
Make storing too large stuff in integers throw instead of overflow

### ISSUE THREAD

**Issue by pmurias** [rakudo/rakudo#1725]
Current storing values that are too big but big enough to fit in a int64 overflow rather than throw an exception.
A sensible behavior would be throw when we get too large of a value and overflow when an operation (like ++) generates a too big of a value.

my int8 $foo = 1000; # doesn't throw

Storing super big values still throws:

my int8 $foo = 1000000000000000000000000000000000; # throws an exception

Unfortunately there are tests in roast for this behavior:
https://github.com/perl6/roast/blob/master/S02-types/native.t#L326

**Comment by lizmat** [comment]
It was decided that overflow on natives would not throw.

Basically what happens is that all integers are first coerced to native size (32-bit on 32-bit builds, and 64-bit on 64-bit builds) and then masked to the size of the native int.

The `my int8 $foo = 1000000000000000000000000000000000;` case fails because it cannot fit into the 32/64-bit (as the message states).  The reason for this is that if you're working with big ints, trying to stuff that into a native is probably most definitely wrong.

If you really want bounds checking, you could use a subset:
```raku
subset int8 of Int where -128 <= $_ <= 127;
my int8 $a = 127;
$a++;
# Type check failed in assignment to $a; expected int8 but got Int (128)
```

**Comment by lizmat** [comment]
This issue was inspiration for the [Native::Overflow](https://raku.land/zef:lizmat/Native::Overflow) distribution.  Although this isn't yet 100% functional, it is working well enough to be able to close this issue and discussion
