### ISSUE TITLE
Significant newline when parsing Pair constructor infix

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1759]
`␤` marks the newline; Looks like its presence causes the unquoted Pair key to be parsed as a sub call instead:

```
<Zoffix__> m: dd [foo ␤=> 42]
<camelia> rakudo-moar a138dcf50: OUTPUT: «===SORRY!=== Error while compiling <tmp>␤Preceding context expects a term, but found infix => instead.␤at <tmp>:2␤------> =>⏏ 42]␤»
<Zoffix__> m: dd ['foo' ␤=> 42]
<camelia> rakudo-moar a138dcf50: OUTPUT: «[:foo(42)]␤»
<Zoffix__> m: dd [foo => 42]
<camelia> rakudo-moar a138dcf50: OUTPUT: «[:foo(42)]␤»
```

**Comment by jnthn** [comment]
The `fatarrow` token parsing this is intentionally constrained to parse horizontal whitespace ([implementation here](https://github.com/rakudo/rakudo/blob/master/src/Perl6/Grammar.nqp#L1953). We can't do `<.ws>` there because that's an LTM terminator, and parsing it as a fatarrow pair constructor relies on `foo =>` being a longer token than `foo`.

I'm not sure whether the intention of the ticket was "want a better error" or "want more liberal whitespace parsing". I'm certainly good with a better error. I'm not keen on liberalizing to `\s*` there instead; one can already put the newline after the `=>` which I'd argue is visually better anyway, and it'd be odd to create a place where a newline is acceptable but a comment is not (and, due to the LTM needs, we won't be able to address that one, I don't think).

**Comment by zoffixznet** [comment]
Thanks.

> "want more liberal whitespace parsing"

Yeah, wanted that. I think the error is good enough as it is.
