### ISSUE TITLE
Hash ~~ Hash violates "smartmatch never throws" paradigm

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1772]
Looks like it does `eqv` under the hood and `eqv` cannot handle `Mu`s:

```
m: my %h = a => Mu; say $%h ~~ $%h
rakudo-moar 79ed89ba4: OUTPUT: «Type check failed in binding to parameter '<anon>'; expected Any but got Mu (Mu)␤  in block <unit> at <tmp> line 1␤␤»
```

Possibly the fix would involve just wrapping the potentially-explosive code into a `try` and returning `False` in case of an exception.

**Comment by jsimonet** [comment]
The routine used is `multi sub infix:<eqv>(Map:D \a, Map:D \b)` and it's using `eqv` internally to compare `Map`'s values but as you said `eqv` cannot handle `Mu`'s.
`my %h = a=>Mu; say %h ~~ %h` is working correctly because the test refers to the same memory block, and `eqv` checks the memory address first.

It's means this code explodes too : 
`my %h = a=>Mu; my %h2 = a=>Mu; say %h ~~ %h2;`
If a `try` block is added, this code will returns `False`, but `say Mu ~~ Mu` already returns `True`, so having these different behaviours seems weird.

I tried to write some code in the `Map`'s `eqv` method to check if parameters types are `Mu`'s, but of course, every object in Perl6 inherits from `Mu` so it was not successful… 

Is there a way to check for exact type of an object, like `===` in other languages?

**Comment by zoffixznet** [comment]
> If a try block is added, this code will returns False, but say Mu ~~ Mu already returns True, so having these different behaviours seems weird.

IMO that's not weird at all, considering the `~~` operator is just sugar for calling `.ACCEPTS` method and the semantics are defined by object on the RHS of the operator. Right now for hashes it's defined to just do an `eqv`, which is simple to understand. Specifying some specialized exceptional behaviour to make it instead do a typecheck a rare-ish type object would be unwanted IMO.

Also, there's a reason `eqv` doesn't take a `Mu` and that's because of it needs to auto-thread Junctions. Which currently works as expected when they're used as values in hashes:

```perl6
my Mu %h1 = foo => <a b c>.any; my Mu %h2 = foo => 'c'; say %h1 ~~ %h2; 
# OUTPUT: «True␤»
my Mu %h1 = foo => <a b c>.any; my Mu %h2 = foo => 'd'; say %h1 ~~ %h2; 
# OUTPUT: «False␤»
```

**Comment by jsimonet** [comment]
Ok, I understand.

Would it be better to catch the exception as soon as possible ? For example, by adding a `CATCH` block inside the `Map::eqv(Map, Map)` method?
This way, others possible exceptions would continue to be thrown?

**Comment by zoffixznet** [comment]
`eqv` doesn't have the "never explode" semantics. Just the `.ACCEPTS` method (it's used in `when` and `where` and exploding while trying to dispatch just because you gave a unmatching type is not very friendly).

Also, you don't need a `CATCH` block. Just a `(try a eqv b) // False`

**Comment by jsimonet** [comment]
Ok. Sorry to ask so many questions, I'm trying to understand well everything :)

So `%h eqv %h2` will continue to explode whereas `%h ~~ %h2` will not?

**Comment by zoffixznet** [comment]
> So %h eqv %h2 will continue to explode whereas %h ~~ %h2 will not?

Correct.

**Comment by lizmat** [comment]
I'm not sure what needs to be documented.  Can this be closed?
