### ISSUE TITLE
"do for" doesn't evaluate the last statement in a block on-the-fly each time it passes when the last statement consists of only a variable.

### ISSUE THREAD

**Issue by titsuki** [rakudo/rakudo#1789]
## The Problem

See the following results:
```
$ perl6 -e 'my $a = 0; say do for ^5 { $a++; $a }'
(5 5 5 5 5)
$ perl6 -e 'my $a = 0; say do for ^5 { $a++; $a + 0 }'
(1 2 3 4 5)
```
I think the 1st example should return the same result as the 2nd example returns because the value of the variable `$a` at the end of the N-th iteration is N (e.g., At the end of the 1st iteration, the value of `$a` is `1`). 

## Expected Behavior
"do for" evaluates the last statement in a block on-the-fly each time it passes.

## Actual Behavior
"do for" returns the List of the final state of the variable (i.e., 5) in the last statement.

## Steps to Reproduce

I already mentioned in the above section.

## Environment
* Operating system: Debian Stretch
* Compiler version (`perl6 -v`): 
```
$ perl6 --version
This is Rakudo version 2018.03-129-g7572983a4 built on MoarVM version 2018.03-35-gafdcad424
implementing Perl 6.c.
```

**Comment by jnthn** [comment]
This isn't to do with evaluation; it's that a `Block` does not dereference a `Scalar` that is returned from it, which is by design. The same mutable `Scalar` is returned each time, giving the results observed. You can explicitly deference it:

    my $a = 0; say do for ^5 { $a++; $a<> }

Which will read the value from the `Scalar` at each time.
