### ISSUE TITLE
Dealing with anguage traps; Trap doc; compiler failures; warnings; deprecations; and lang evolution

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#1790]
This is intended to be a I think we need a generic issue related to traps that either stays open forever or turns into a separate document.

First, here's [issues that mention 'trap'](https://github.com/rakudo/rakudo/issues?utf8=%E2%9C%93&q=is%3Aissue+trap).

Hunter McMillen's last two SO questions are arguably about traps:

    return .... and ...

never means what the writer meant afaict. It's mentioned in [Traps](https://docs.perl6.org/language/traps) but can we do better? I can't see us changing the language for this but, aiui, could reasonably be detected and become a compile time error or at least a warning. But it would bloat and slow the compiler.

Using a single Positional argument, whose elements are not all Arrays, as the single subscript argument of an object hash declared as `%hash{Array}`, could, aiui, reasonably be detected and warn appropriately at run-time.

I might be wrong about one or both these particular examples, or they might not be worth detecting (yet or ever) but my general point is that there are traps and there are likely ways they could be detected at compile or run time and turned into warnings or fatal errors. I looked thru the issues and didn't find one like this (apologies if one's there and I missed it). I'm sure this will come up over the years so I'm pre-emptively filing this as a generic issue for discussion of

**Comment by raiph** [comment]
Sorry about the noise. Had decided to turn this into a gist that I might reveal another day/year and then fat-fingered.

**Comment by AlexDaniel** [comment]
Oh, this is close to my heart! I think right now we should simply document all traps that we notice. Most trap issues are actually filed [in the doc repo](https://github.com/perl6/doc/issues?utf8=%E2%9C%93&q=trap+is%3Aissue+is%3Aopen+), not here. If you stumble upon something new on stackoverflow or elsewhere, please do that.

My plan was to start (eventually) a dedicated effort to reduce the number of [traps that we documented](https://docs.perl6.org/language/traps) by tweaking the compiler/language so that either the trap is completely gone, or there's an awesome compile-time error. Most likely we won't be able to do that for every existing trap, but I believe that the situation can be improved dramatically. In some sense this is already happening, for example see [this commit](https://github.com/perl6/doc/commit/f14b8a223ea9c174f66d6a0870181e5684878b23) ([bonus discussion](https://irclog.perlgeek.de/perl6/2018-04-22#i_16076853)).

Personally I'd much rather push for v6.d right now and think about detrapping after v6.d is out. But you don't have to agree with this, so feel free to file a detrap ticket right now for every trap that is documented (preferably with some good thoughts on how rakudo can be improved without sacrificing anything). I've added a label for that.

**Comment by smls** [comment]
> I can't see us changing the language for this but, aiui, could reasonably be detected and become a compile time error or at least a warning. But it would bloat and slow the compiler.

Compilers for various other languages (Java, C#, C++...) do detect such cases of unreachable code, and warn about it at compile time.

In Perl 6, things are complicated by the fact that `return` is a subroutine (or method), not a keyword.  
But if it's nonetheless possible to do the static analysis in simple cases like this, it would indeed be nice to produce such warnings.

> reduce the number of traps that we documented by tweaking the compiler/language so that either the trap is completely gone, or there's an awesome compile-time error

:+1: 

Also, on the doc side of things, I feel like the [/language/traps](https://docs.perl6.org/language/traps) page should probably be eliminated in favor of documenting any remaining traps related to feature X right on the respective doc page for feature X, where people learning about feature X will actually read it.

**Comment by AlexDaniel** [comment]
> I feel like the /language/traps page should probably be eliminated in favor of documenting any remaining traps related to feature X right on the respective doc page for feature X

Feel free to document them there also. The traps page is extremely useful and should not be eliminated.
