### ISSUE TITLE
DateTime Stringification sensitive to null milliseconds

### ISSUE THREAD

**Issue by robertlemmen** [rakudo/rakudo#1904]
this *could* be intentional, and of course can be avoided with a formatter. but I find it rather surprising behavior:

> DateTime.new('2018-06-05T07:24:01.001')
2018-06-05T07:24:01.001000Z
> DateTime.new('2018-06-05T07:24:01.000')
2018-06-05T07:24:01Z

**Comment by W4anD0eR96** [comment]
https://github.com/rakudo/rakudo/blob/148d7c56af911d59dde69daa4863e23b3ac4d7a2/src/core/DateTime.pm6#L10-L25

look at line13-15, the fraction is removed intentionally

**Comment by robertlemmen** [comment]
thought that it is intentional, but is that the desired behavior? it is rather surprising to see the output switch format, and note that with e.g. random or sampled/measured data this only happens very infrequently...

**Comment by W4anD0eR96** [comment]
One elegant solution is add a `$millsecond` field, otherwise we need more `if-else` condition to judge what `$second` is. However, it causes a internal implement change and I don't know if it break something. In fact, we do support millsecond part, but why that's no `$millsecond`...

**Comment by lizmat** [comment]
According to the documentation (both internally and externally), `DateTime.Str` should return an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string.  Which, as far as I can see, does not have any support for milliseconds.  The wikipedia page also states:

> For reduced accuracy,[16] any number of values may be dropped from any of the date and time representations, but in the order from the least to the most significant.

So that makes it feel ok to me to lose the millisecond data if it is exactly 0.

OTOH, there **is** no support mentioned for milliseconds in ISO 8601.  So maybe we should get rid of the millisecond support altogether?

**Comment by lizmat** [comment]
FWIW, removing the millisecond from the stringification, breaks 3 spectests that test specifically for that (S32-temporal/DateTime.t).  And sadly, these tests where added just before the 5.c release.

So in light of this, I suggest we close this ticket.
