### ISSUE TITLE
assuming a sub that has a **@param slurpy gives a compile error

### ISSUE THREAD

**Issue by kjkuan** [rakudo/rakudo#1918]
```
[20:48] <kjk> p6: sub x(**@a, :$b) { 123 }; &x.assuming(:!b)
[20:48] <+camelia> rakudo-moar f2b503785: OUTPUT: «===SORRY!=== Error while compiling /home/camelia/EVAL_2␤Redeclaration of symbol '@a'␤at /home/camelia/EVAL_2:1␤------> $res = (my proto __PRIMED_ANON (*@a, *@a⏏, Any :b($b) --> Mu) { {*} });␤    expecting any of:␤        shape…»
```
I should be able to `&x.assuming(:!b)` with the sub above, but it gives a compile error instead.

## Environment
* Operating system: MacOS 10.13.4
* Compiler version: `This is Rakudo version 2018.05 built on MoarVM version 2018.05
implementing Perl 6.c.`

**Comment by jstuder-gh** [comment]
This is happening for ```+@``` params as well

    sub x(+@a, :$b) { say "{@a.perl} and $b" }; &x.assuming(:!b);

If you add slurpy_lol and slurpy_onearg to Parameter's internal NOT_POSITIONAL constant then they will work (commit doing so [here](https://github.com/jstuder-gh/rakudo/commit/93a8ec66553b78405052b71fa793f062e073b109)).

    sub x(**@a, :$b) { say "{@a.perl} and $b" }

    my &xx = &x.assuming(:!b);
    &xx(1, 2, (3, 4));

    # OUTPUT: «[1, 2, (3, 4)] and False␤»

Since these were testing positively for both ```positional``` and ```slurpy``` they were being added a new param list twice ([here](https://github.com/rakudo/rakudo/blob/master/src/core/Code.pm6#L196) and [here](https://github.com/rakudo/rakudo/blob/master/src/core/Code.pm6#L216)) resulting in redeclaration when EVALed.

I don't know a lot about the design of the ```Parameter``` types. Is there a reason these should be considered ```positional``` and ```slurpy``` or is it perhaps an oversight that they were not added to NOT_POSITIONAL? The spectest passes with these changes so presumably these properties are safe to modify? Assuming it is safe to do I will submit the above commit as a PR.

**Comment by jstuder-gh** [comment]
I believe this can be closed now. Both the [fix](https://github.com/rakudo/rakudo/commit/93a8ec66553b78405052b71fa793f062e073b109) and the [roast test](https://github.com/perl6/roast/commit/9dc848d559d04af36d31d912e11148a7147ff10a) have been merged into master in their respective repos.
