### ISSUE TITLE
Regression related to MONKEY-TYPING and spesh-plugins merge

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1923]
[Test::Fuzz](https://github.com/FCO/Test-Fuzz) is currently failing with this output:
```
ok 1 - Test::Fuzz::Generator module can be use-d ok
    ok 1 - 
    ok 2 - An object of type 'Parameter+{Test::Fuzz::Generator}' can do the method 'generate'
No such method 'generate-samples' for invocant of type 'IntStr'. Did you mean 'generate-samples'?
  in block  at /home/alex/git/Test-Fuzz/lib/Test/Fuzz/Generator.pm6 (Test::Fuzz::Generator) line 33
  in method generate at /home/alex/git/Test-Fuzz/lib/Test/Fuzz/Generator.pm6 (Test::Fuzz::Generator) line 32
  in block  at t/01-generator.t line 24
  in block <unit> at t/01-generator.t line 14
```

The change is bisectable to these commits:
* f6f43d58e35ef0ba3ea92a47c7164429873977b2
* 51ff83c7ca90af8fbe40acaad728c6fa79f65b76
* c6a61f563b478337a6fb6290d0d612d663d60471
* c5d14062abb2231a18688f3de854b6dbd3a3df1f

I attempted to golf it but noticed other weird cases:

Code:
```perl6
use MONKEY-TYPING; augment class Int { method foo(::?CLASS:U:) { 999 } }; say IntStr.foo
```

Output:
```
¦2018.05,HEAD(2fa08d5): «No such method 'foo' for invocant of type 'IntStr'. Did you mean 'foo'?␤  in block <unit> at /tmp/jUt1kqM_rB line 1␤␤ «exit code = 1»»
```

---------

Code:
```perl6
use MONKEY-TYPING; augment class Int { method foo(::?CLASS:U:) { 999 } }; say IntStr.?foo
```
Output:
```
¦2018.05: «Nil␤» ¦HEAD(2fa08d5): «999␤»
```

---------

Code:
```perl6
use MONKEY-TYPING; augment class Int { method foo(::?CLASS:U:) { 999 } }; say <42>.?foo
```
Output:
```
¦«2018.05»:
Nil

¦«HEAD(2fa08d5)»:
Invocant of method 'foo' must be a type object of type 'Int', not an object instance of type 'IntStr'.  Did you forget a 'multi'?
  in method foo at /tmp/VyWjqD6FFR line 1
  in block <unit> at /tmp/VyWjqD6FFR line 1

«exit code = 1»
```

---------

That's all info I have right now.

**Comment by jnthn** [comment]
Starting out with the golf attempts:

> use MONKEY-TYPING; augment class Int { method foo(::?CLASS:U:) { 999 } }; say IntStr.foo
> ¦2018.05,HEAD(2fa08d5): «No such method 'foo' for invocant of type 'IntStr'. Did you mean 'foo'?␤ 

This issue - methods augmented into a parent type aren't propagated to a subtype - is a longstanding problem (going back many years). I'm planning to replace the current method cache approach with the spesh plugin mechanism in the future; this will have various advantages, one of them being that it will largely address this issue.

> use MONKEY-TYPING; augment class Int { method foo(::?CLASS:U:) { 999 } }; say IntStr.?foo
> ¦2018.05: «Nil␤» ¦HEAD(2fa08d5): «999␤»

Here, the behavior change is because the use of the spesh plugin mechanism for `.?` means that the bug mentioned above is now resolved for this form of method dispatch.

> use MONKEY-TYPING; augment class Int { method foo(::?CLASS:U:) { 999 } }; say <42>.?foo
> ¦«2018.05»:
> Nil
> 
> ¦«HEAD(2fa08d5)»:
> Invocant of method 'foo' must be a type object of type 'Int', not an object instance of type 'IntStr'.  Did you forget a 'multi'?

Same as above. Previously, we failed to find the `foo` method augmented into the parent class. Now we do find it, and can call it, and the signature fails to bind.

> Test::Fuzz is currently failing

It seems that it fails here:

```
	my %generator
		<== map({.^name => lazy .generate-samples})
		<== grep({try {lazy .?generate-samples}})
		<== @types
	;
```

Because `.?generate-samples` now is fixed and so can find `generate-samples` correctly. However, since the basic form of method dispatch isn't yet fixed, the `.generate-samples` call now fails.

So, it's one of those unfortunate cases where something that considered in isolation is an improvement both in terms of performance *and* fixing a bug, but ends up causes breakage.

We could choose to exclude https://github.com/rakudo/rakudo/commit/c6a61f563b478337a6fb6290d0d612d663d60471 from the release, and/or send a PR to change the `.?` to be `.`; there's a `try` there anyway. Perhaps preferable to that would be for me to see if I can make `.?` be bug-compatible with how it was in previous releases, which would let us keep the optimization and not break this module. It's a slight pity to re-introduce a bug on purpose that I was happy to have fixed, but less of a pity than losing the performance part of the improvement.

It'd be nice if I could say "and soon I'll have normal dispatch re-worked", but I'd not especially planned to prioritize that. We use the current pre-published method cache approach as a bootstrap mechanism, so it has potential to have quite a lot of fallout in the internals. Furthermore, it will also implicate NQP and the other backends, probably in non-trivial ways. Sure, I'd like the bug fix and (hopefully) a memory use improvement, but it's a heck of a lot of work (I suspect at least a week's full time effort), and doesn't much help performance (perhaps startup a little bit due to less to deserialize, but nothing at runtime).

**Comment by AlexDaniel** [comment]
@jnthn I think reverting is an ok and safe solution that we can apply right now. That said, I don't know what would be the right time to re-introduce the change. “As soon as we have normal dispatch reworked” is probably LTA… but that we can decide later. I'll make a PR to that module (later today) to make sure it keeps working if we decide to rerevert later after the release.

**Comment by jnthn** [comment]
> I think reverting is an ok and safe solution that we can apply right now.

Let's do that for this release; it's totally safe, and is much better than we putting in a "make this bug-compatible" fix right before the release happens.

> That said, I don't know what would be the right time to re-introduce the change. 

I'd prefer it's just excluded from the release (which equates to it being put back in straight after the release). I know how to put in the bug-compat tweak already, having had a little time to think about it since posting here yesterday, and it will allows us to retain the performance gain until the point the normal dispatch is also fixed. However, I'd rather not ship that fix which we don't have much time to test, so I'll apply it post-release.

**Comment by AlexDaniel** [comment]
OK, this should be fine now. I reverted the commit on master, and re-reverted it on post-release branch.

I've also submitted a PR to the module even though that was not really needed because there's a chance we'll have a bug-compatible fix (so just in case things turn out to be different than we expect).

**Comment by jnthn** [comment]
Applied the bug-compatibility fix, and made sure it helps Test::Fuzz. I suggest we add a spectest that uses the pattern Test::Fuzz does, to cover this.

**Comment by AlexDaniel** [comment]
Seems to be that this ticket is simply missing some tests.

**Comment by lizmat** [comment]
closing as basically untestable
