### ISSUE TITLE
Wanted configuration option to exclude home dir from repos

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1936]
Today, [a user was asking](http://colabti.org/irclogger/irclogger_log/perl6?date=2018-06-17#l865) how to get rid of `$HOME/.perl6` in the list of module search paths.

Looking [at the code](https://github.com/rakudo/rakudo/blob/61878c3e074e1250634455de7f9dc61ff78e6144/src/core/CompUnit/RepositoryRegistry.pm6#L165-L201) looks like those are currently automatically added, including the one that uses user's home dir.

I don't know what the difference between all these repos is, but it's probably LTA that a system-wide install of perl6 includes user-specific search locations for modules and perhaps there should be a configuration option to exclude it from the list?

**Comment by niner** [comment]
Why would it be LTA to have the possibility as a user to install modules in a simple way? The linked IRC discussion does not mention any reason and neither does this issue.

**Comment by zoffixznet** [comment]
I have a feeling the IRC user thought *all* users would have ` "inst#/home/lembark/.perl6"` search path rather than each user getting their home dir, which is why they were trying to get rid of it.

As for why: I don't know much about what all of these different repos are to answer that properly. I see I have some stuff in my own  `~/.perl6`, which means: (a) I installed some software without administrator's permissions and (b) my perl6 installation differs from other users' installation and when I tell the administrator about the problems I'm having with this perl6 script I'm supposed to be using they have to take into account that I might have some unauthorized modules installed in my own `~/.perl6` that they have to grab in order to replicate the problem.

> Why would it be LTA to have the possibility as a user to install modules in a simple way?

It might be nice, but it's not just a possibility, it's always available and there's no way to for system administrators to exclude that possibility.

**Comment by lizmat** [comment]
Steven Lembark is a long time Perl 5 user and sys-admin who was in my class on how to port Perl 5 modules to Perl 6.

In his experiences, having things installed in a user’s home directory, is an accident waiting to happen.  If some webservices running on a machine depend on a users home directory, what happens if that user leaves the company.  So he wants to ensure that *all* users on a machine, have the same environment wrt installed modules.

In the case of Perl 5, he would just make sure that the default @INC of the Perl installation would not include any home dir.  He would like to do the same for Perl 6.

With my sysadmin head on, I think he has a point  :-)

**Comment by niner** [comment]
I just wonder how many things would have to go wrong for a webservice to depend on some user's home directory. That would mean that the webservice is running with some human user's account. In that case some installed modules will probably the smallest of the problems this entails.

It would also mean that the mere presence of some modules on a system causes software to fail. This would mean that there's something really wrong with the software, i.e. it doesn't specify its dependencies nearly well enough. We give users lots of sophisticated tools to fix compatibility issues. They really ought to use them.

So in conclusion, this proposal seems to try to work around problems at the very end of the chain, far away from the real issues. Also use of ~/.perl6 is completely optional. Just don't install modules there and no modules will be loaded from there. But if you do install modules into ~/.perl6 chances are you do that precisely so they get used.

Even if none of this convinces you and you still want to go forward, there's no need to change rakudo for achieving the desired behavior. Thanks to jnthn++'s genius, the repository chain makes it quite simple to implement this in a loadable module. There's for example already CompUnit::Repository::Mask for pretending certain modules are not installed. Ignoring a whole repository in the chain is even simpler. If you implement that as a repository itself, it can be automatically prepended to any script's repository chain by loading it via PERL6LIB environment variable (`export PERL6LIB='CompUnit::Repository::HideHome#'`)
Or simply unset your $HOME environment variable (`unset HOME`) before running a script.

**Comment by ugexe** [comment]
One could say you could achieve the same thing by holding your developers accountable for their code and auditing dependencies to only use those that explicitly declare version/auth/api when importing as best practice. There is merit to being able to control the initial repositories used or even their exact ordering ( I've proposed this before myself ), but I feel a Perl 5 user / sysadmin is coming from a place where they are primarily trying to control version selection ( which is already solved with explicit declarations ). I can name a couple slightly exotic reasons why this is useful, but I think most issues are resolved by changing your mindset of how modules are loaded.

> If some webservices running on a machine depend on a users home directory, what happens if that user leaves the company.

DIHWIDT -- sure you *could* write code in such a way, but I wouldn't expect it to pass a peer review.

**Comment by AlexDaniel** [comment]
I think nowadays any service can be adjusted to one's needs (e.g. with systemd features), so even if the service doesn't run on a separate user (why?) and `$HOME` is set, then it should be possible to make the path (`$HOME/.perl6`) inaccessible (e.g. by using `InaccessiblePaths` in systemd). The question I have is whether rakudo is actually going to work this way, because I recall having some problems with writability and precomp dirs. Perhaps it will work perfectly right away, but it would be great if somebody tested it… :)

**Comment by lembark** [comment]
Simplest reason for avoiding ~/.perl is that I don't want production code to accidentally depend on people's home dir's (e.g., prefer not to have production, Q/A, or demo code break because a user has the wrong version of a module installed in their home dir).
If people want to install something into their sandbox they can use PERL6LIB or -I to pull in development lib's. 
I'm not saying it should be removed for everyone, but I should have a way to take it out if necessary here for production issues.

**Comment by lembark** [comment]
Aside: Holding people "accountable" only goes so far if minor mistakes leave code broken. I'd rather have a simple fix that avoids having to beat people up.

**Comment by lembark** [comment]
Why not add /var/tmp/perl6, /etc/.perl6 to the path also? Just not have people install there... 
The point is making it simpler to avoid issues: if people are working on code they should be using their sandbox, not their home dir. I'd also avoid storing anything in in a .* directory; if someone needs ~/perl6 then they can do it, but I'd rather not having something invisible as a dependency.

I'd also prefer to avoid having to back up all of the modules that everyone might install in their home dir's; one reason we use sandboxes is that they don't pollute home dir's with cruft that has to be managed simply because it is there.

I can update zef to avoid installing into ~/.perl6, I just don't see why I cannot have Perl6 avoid using ~/.perl6 also without patching the source.

**Comment by niner** [comment]
@lembark can you tell us why the solutions I posted above are not enough?
