### ISSUE TITLE
Document Rakudo-specific classes to support Perl 6 documentation

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#1941]
## The Problem

Whenever a Rakudo-specific issue arises in [perl6/doc](https://docs.perl6.org), we are of two minds. On one hand, it's rakudo specific, so it's subject to change. On the other hand, we do need to document those Rakudo features so that people can use them. Also, we need to understand them to document some parts of Perl 6, which are public-facing and where, for lack of documentation, we have to go directly to the source to understand what a function actually does. 

In any case we might have to go to the source, but having some Rakudo-specific, searchable documentation, showing class hierarchy, or a brief description of the functionality, would really save us a lot of work. And probably help Rakudo implementors too.

## Expected Behavior

It would be nice if some class specific documentation was created in this area. For instance, [it would be useful to know the behavior of the CompUnit classes](https://github.com/rakudo/rakudo/blob/98e575de00db42101d4879e43fe740a34791c418/src/core/CompUnit/Repository/Spec.pm6), which are [very slightly documented](https://docs.perl6.org/language/modules-core#index-entry-CompUnit_%28Rakudo_classes%29) (with "documented" mainly meaning source is linked from a page). I am not sure whether this should actually go to this repo or to the docs repo (and if that's eventually the decision, feel free to open an issue there), but I'm positive we need this kind of thing...

**Comment by coke** [comment]
As long as it's clear that a thing is compiler specific, I'm OK with it being in the docs.

**Comment by zoffixznet** [comment]
FWIW, I don't think CompUnit types are meant to be rakudo specific. They just never made it into the spec because IIRC they were all built just a month or two before first lang release.

**Comment by JJ** [comment]
This is not CompUnit specific. It's a more general concern. The problem is that when some feature is requested in the doc issues, you have to look up in a couple of places to really find out if it's Rakudo specific or not. And if they are, generally they get low priority over other things. Just a stub of documentation, maybe attached to the class itself, could really help, at least to know the specificity of the thing and maybe learn a little bit about the behavior instead of having to wade through the source to know what's going on. 
WRT to CompUnit itself, there's a lot of functionality that is just not being used due to lack of knowledge and thus documentation... Maybe we can return this issue back to perl6/doc (and close it) saying "Improve *that* documentation", but actually it's not the only case, just the most outstanding.

**Comment by zoffixznet** [comment]
> if it's Rakudo specific or not. And if they are, generally they get low priority over other things.

How many rakudo-specific things are there? Other than `dd`, some env vars, and `Telemetry` stuff I can hardly think of any, yet your description suggests there's a whole ton.

**Comment by JJ** [comment]
El jue., 21 jun. 2018 a las 13:18, Zoffix Znet (<notifications@github.com>)
escribió:

> if it's Rakudo specific or not. And if they are, generally they get low
> priority over other things.
>
> How many rakudo-specific things are there? Other than dd, some env vars,
> and Telemetry stuff I can hardly think of any, yet your description
> suggests there's a whole ton.
>

Well, CompUnits also. And I don't really know. Is that all?

**Comment by zoffixznet** [comment]
> Well, CompUnits also

That leads back to my original comment:

> FWIW, I don't think CompUnit types are meant to be rakudo specific

Just because something is currently not specced, doesn't mean it's supposed to be Rakudo-only, often the reason is that the implementor did not also write the spec.

**Comment by JJ** [comment]
I'm seeing now, for instance, [`Rakudo::Iterator`](https://github.com/rakudo/rakudo/blob/ec5e51c8b720d5072684ee9542da2447e7c9c239/src/core/Rakudo/Iterator.pm6). Huge class, with lots of roles and functions defined. It would *really* help if that was documented. Even if it's internal, or precisely because it's internal, documentation would help us writing perl6 documentation to find more easily what some undocumented functions do. I've found this one, for instance, while trying to solve perl6/doc#1195

**Comment by lizmat** [comment]
FWIW, I consider *all* of the `Rakudo::` classes as Rakudo specific implementation details.  I think they don't really have a place in the Perl 6 documentation, as they can change between releases, or even commits.  There's a reason they're put in the `Rakudo::` namespace: there's **NO** guarantee that they will stick around for any amount of time!

**Comment by JJ** [comment]
El sáb., 30 jun. 2018 a las 10:17, Elizabeth Mattijsen (<
notifications@github.com>) escribió:

> FWIW, I consider *all* of the Rakudo:: classes as Rakudo specific
> implementation details. I think they don't really have a place in the Perl
> 6 documentation, as they can change between releases, or even commits.
> There's a reason they're put in the Rakudo:: namespace: there's *NO*
> guarantee that they will stick around for any amount of time!
>

Actually, I was asking for documenting them somewhere other than Perl6 doc
repo. In this repository, or maybe in a Rakudo specific part of the Perl6
doc repo if we want it that way. Even if they are guaranteed to be
ephemeral, or not guaranteed to be permanent, some documentation that help
us understand what they do (in order to document some function where they
are used, or create new implementations, or actually use them in other
parts of Rakudo, in general, whatever documentation is used for) is better
than no documentation at all and having to navigate through source code and
the repo to understand them.

**Comment by jnthn** [comment]
> I'm seeing now, for instance, Rakudo::Iterator. Huge class, with lots of roles and functions defined. It would really help if that was documented.

If folks want to document those, I think that should be done with additional comments in the code; at least that way there's some chance it'd stay up to date (or at the very least deleted if the code changes and invalidates it). It should absolutely not be documented in any way that makes it look like these are APIs people can use or depend on. I think you *should* have to go and dig through source code to find these, because the only place they should be used, and the only place they have meaningful context, is in the Rakudo source code.

The Rakudo team go to quite some lengths to avoid breaking ecosystem modules. However, we *must* have somewhere to put implementation details and be able to refactor them at will, without worrying about compatibility. `Rakudo::Internals` is such a place, and a module breaking because it used `Rakudo::Internals` would not be a release blocker (and I'd be liable to publicly call it out as an example of what *not* to do). Of course, I'd rather we don't have this situation in the first place - so please, whatever you do, please work minimize the discoverability of stuff inside `Rakudo::Internals` to general Perl 6 users.

If this does really become a problem, of course we can resort to technical measures (for example, using `Rakudo::Internals::RANDOM`, where RANDOM changes every release, or finding some way to block use of `Rakudo;:Internals` outside of the setting). But I'd rather not have to do those, since they'd be liable to get in the way of Rakudo developer's work.

**Comment by ugexe** [comment]
If someone cannot figure out how an undocumented API works by going through the source code -- newbie or not -- they probably aren't  shouldn't be using it. The suggestion of documenting implementation details for new rakudo developers as a way to lower the barrier entry also misses an important point: the barrier to entry for both *new and old* rakudo developers would actually increase because now they must also document any implementation details.

I'll steal a line from the python folks: "It is dangerous to add too many implementation details to a language reference document — the implementation may change, and other implementations of the same language may work differently."

**Comment by JJ** [comment]
I would just like to add that documenting classes like CompUnit would help things like perl6/doc#502 make sense.

**Comment by zoffixznet** [comment]
> an undocumented API 

Pretty much all of `Rakudo::` stuff isn't just an undocumented API, it's **internal** API. Users shouldn't be using it at all. `Rakudo::Iterator` is really just `Rakudo::Internals::Iterator`, but with shorter name.\

> Well, any documentation is better than no documentation

Not true. Documentation is a fairly large maintenance burden and wrong documentation is much worse than no documentation. There's no API stability requirements for `Rakudo::Internals`, thus it can change freely and documentation will get out of sync fairly quickly.

> they could be used too by new developers of Rakudo who might want to use this or that feature

The dev docs should be more conceptual—that describe the "big idea" behind some feature—not documentation for API that can be simply gleaned from the actual source.

**Comment by JJ** [comment]
OK. I see your point. And I have actually found *some* documentation that will help me. Thanks for the enlightening discussion. I think it's better now if I close this issue.

**Comment by ToddAndMargo** [comment]
Just an idea.  How about a separate section in the documentation titled "Rakudo Extensions"?
