### ISSUE TITLE
%(), @(), $() are evil/weird

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#1946]
I thought I had filed something like the following as an issue before, or at least raised it, but I've failed thus far to find it. These really need to be known as evil/weird so at the risk of filing a duplicate...

Here's a design doc reference: http://design.perl6.org/S05#line_3070

`%()` is the worst.

    'aa'  ~~    / . /; 
    say %();

displays:

    Map.new(())

And:

    'aa'  ~~    / $\<foo\>=. /;
    say %();

displays:

    Map.new((foo => ｢a｣))

It doesn't expect the list that `:g` returns. It either gets confused:

    'ab'  ~~ m:g/        . /; say %(); # {a => ｢b｣}

Or really confused:

    'abc' ~~ m:g/ . /; say %(); # Odd number of elements found where hash initializer expected:
                                # Found 3 (implicit) elements:
                                # Last element seen:
                                # Match.new(list => (), made => Any, pos => 3, ...

Now let's really pile on.

Some are recommending `%(...)` as a best practice alternative to `{...}` as a hash constructor.

Docs even refer to `%(...)` as `%()`.

Also, use of `{}` is slightly frowned upon as looking like an empty block -- and a natural inclination based on best practice comments is to use `%()`. Uhoh.

Worse, `%()` will sometimes actually return an empty hash -- when it doesn't return a populated read-only hash instead.

(I noticed someone somewhere wondering why the warning message on `{}` that said one should use `%()` instead was removed. Now you know why.)

Anyhow, `%()` is the most evil of these three.

`@()` is the least evil. It's an alias for the numbered sub-matches of `$/`.

'a' ~~ m:g/ . /; say @() =:= $/[]; # True

But it's still thoroughly weird.

Though not as weird as `$()`. That stores a copy of `$/.ast.Str`. If `$/` is a list, it borks:

'a' ~~ m:g/ . /; say $()

displays

No such method 'ast' for invocant of type 'List'

**Comment by AlexDaniel** [comment]
Please just deprecate this.

[IRC discussion](http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-06-21#l196).

**Comment by zoffixznet** [comment]
These have been on the 6.d-prep chopping block for quite a while: https://github.com/perl6/6.d-prep/blob/master/TODO/FEATURES.md#remove--magicalness-from--and-

> I thought I had filed something like the following as an issue before, or at least raised it, but I've failed thus far to find it.

It's https://rt.perl.org/Ticket/Display.html?id=131392

**Comment by AlexDaniel** [comment]
OK well… maybe it's not that easy if we want to allow `%()` to mean an empty hash. I'm actually not sure what's the easiest way out, but I'm convinced that the current behavior has to go.

**Comment by JJ** [comment]
So, let me see if I got all the facts lined up:

- The behavior of %() and @() is going to be deprecated soon.
- Right now, there's no way to declare an empty hash using just brackets. {} is ambiguous, and %() will depend on what $/ contains. Also, %(...) does not seem to work.

**Comment by jnthn** [comment]
`{}` always means an empty hash, so no ambiguity at all. In fact, there's also no formal ambiguity around whether `{...]` declares a block or hash in general: the compiler follows the same set of rules every time to make the decision, and the reader can do just the same. It's just that one has to remember the rules (first item must be a syntactic `Pair` or a variable with a `%` sigil, `$_` must not be used even implicitly, no declarations should be made), and some folks wish for a form that's always a hash literal without having to remember the rules.

That form could be the coercion syntax `%(...)`, which isn't too bad, but as this ticket notes, `%()` is currently assigned a different meaning, that is of dubious value, so the approach of using the coercion syntax as a general way to write a hash literal breaks down at that point. Deprecating that meaning would, in the long run (because this would be a multi-year process), let `%()` mean an empty...well, something hash-y, either `Hash` or `Map`. I don't think the `%(...)` coercion form was originally intended to become a widely used alternative to `{...}`, thus why it taking another meaning probably wasn't seen as a problem.

Of course, `hash()` and `hash(a => 1, b => 2)` is a sure bet, as is `().hash` and `(a => 1, b => 2).hash`.

**Comment by AlexDaniel** [comment]
@jnthn while what you've said is true, *maybe* it's worth mentioning that in *other* cases `{}` can as well mean an empty block, like `if True {}`.

**Comment by AlexDaniel** [comment]
As well as in the statement modifier form:
```perl6
say do {} for ^5 # Nil Nil Nil Nil Nil, not empty hashes
```

**Comment by jnthn** [comment]
> if True {}

Hah, I didn't even think about this case, because we're not even looking to parse a term in that construct. :)

> Same in the statement modifier form:
> 
> say do {} for ^5 # Nil Nil Nil Nil Nil, not empty hashes

That's because the block was taken as the block for `do`. Add parens so that doesn't happen, and it's a `Hash` as expected

```
$ perl6 -e 'say do ({} for ^5)'
({} {} {} {} {})
```

**Comment by raiph** [comment]
Ah, so I *had* written something about this before (in the RT, which I'd failed to find). Thanks Zoffix several times over.

Everyone else, thank you too and I'm closing this on the basis it's fully covered by the existing RT and 6.d item and new issues to doc these three and to redo related style guide aspects.

**Comment by AlexDaniel** [comment]
@raiph actually, I'll reopen this one and close the ticket on RT.

**Comment by raiph** [comment]
I've just realized a small issue related to `%()` et al. One can't use `$/` in the regex slang so:

my regex foo { $/ } 
my regex foo { $/[] } 
my regex foo { %$/ }

etc. won't compile. We should still deprecate them but we can't use `%$/` in the regex slang. (

**Comment by raiph** [comment]
(Apologies for the accidental close and noise.)

**Comment by zoffixznet** [comment]
No more magic in 6.d as of https://github.com/rakudo/rakudo/commit/bb88a0324ee8fd73c2f566811fa08d237c831487 propspec https://github.com/perl6/roast/commit/79e86e5f14
