### ISSUE TITLE
array is a type

### ISSUE THREAD

**Issue by Juerd** [rakudo/rakudo#1949]
## The Problem

array is a type

## Expected Behavior

`array` constructs an array, just like `hash` constructs a hash and `list` constructs a list.

```
.say for hash, list, array;  # expected: {}  ()  []
```

## Actual Behavior

```
.say for hash, list array;  # actual: {}  ()  (array)
```

**Comment by lizmat** [comment]
I’m afraid we’re past fixing that now  -(

I would argue that hash and list are actually at fault here.

**Comment by AlexDaniel** [comment]
> I’m afraid we’re past fixing that now -(

I think there's no need to be pessimistic about this. I can totally see how `array` can be tweaked to do something else in future language releases (maybe after a couple of them), of course if that's something we decide to do.

**Comment by zoffixznet** [comment]
A broader list of the inconsistencies:


| Name | Method form coercer | Sub form coercer | mandatory parens for no arg call | Type | Is Native | Can be created with `thing.new` | 
| -------- | -------------------------- | ---------------------- | ----------------------- | ------- | ----------- | --- | 
| `set`   |  ✗ |  ✓ | ✓ | ✗ | ✗| ✓ (indirectly, by calling on return type) |
| `bag`   |  ✗ |  ✓ | ✓ | ✗ | ✗| ✓ (indirectly, by calling on return type) |
| `mix`   |  ✗ | ✓ | ✗| ✗ | ✗| ✓ (indirectly, by calling on return type) |
| `hash`   |  ✓ | ✓ | ✗ | ✗ | ✗| ✓ (indirectly, by calling on return type) |
| `pair`   |  ✗ | ✓ | N/A | ✗ | ✗| ✓ (indirectly, by calling on return type) |
| `list`   |  ✓ | ✓ | ✗ | ✗ | ✗| ✗| ✓ (indirectly, by calling on return type) |
| `array`   |  ✗ | ✗ (tries to call method) | N/A | ✓ | ✓| ✓ (if parametarized) |
| `int`   |  ✗ | ✗ (REPR error) | N/A | ✓ | ✓| ✗|
| `int8`   |  ✗ | ✗ (REPR error) | N/A | ✓ | ✓| ✗|
| `int16`   |  ✗ | ✗ (REPR error) | N/A | ✓ | ✓| ✗|
| `int32`   |  ✗ | ✗ (REPR error) | N/A | ✓ | ✓| ✗|
| `int64`   |  ✗ | ✗ (REPR error) | N/A | ✓ | ✓| ✗|
| `num`   |  ✗ | ✗ (REPR error) | N/A | ✓ | ✓| ✗ |
| `num32`   |  ✗ | ✗ (REPR error) | N/A | ✓ | ✓| ✗ |
| `num64`   |  ✗ | ✗ (REPR error) | N/A | ✓ | ✓| ✗ |
| `str`   |  ✗ | ✗  (REPR error) | N/A | ✓ | ✓| ✗ |

**Comment by pmichaud** [comment]
I don't know the current state of things, but originally ```hash``` and ```list``` were deemed "contextualizers", not "constructors".  So I wouldn't necessarily expect them to do the same as ```array``` .

So part of the difference (and confusion) may be that we use the same words ("hash / list") to refer to both a context and a type.

Pm

**Comment by jnthn** [comment]
What @pmichaud said: `hash` and `list` are contextualizers. That's why `.list` on an `Array` and `.hash` on a `Map` are both identity. It's also why there's a `set` sub (also seen as a contextualizer), but not a sethash sub.

Many types come in a mutable and shallow-immutable form (`List`/`Array`, `Map`/`Hash`, `Set`/`SetHash`), and in all of these cases there's a single conextualizer. If there's an odd one out, it's `hash`, which is named after - and by default produces - the mutable thing. For obvious reasons, we couldn't use `map` for that. It does, however, produce by default the type you'd think that it would from the name (a `Hash`), if it isn't in an identity situation.

There's also a consistent pattern of the boxed/object form of a type, say `Int`, having its native form in lowercase (`int`). The `Array`/`array` is also a case of this.

Thus asking for `array` to be a `sub` that creates an array is asking for two other consistent patterns to be broken. This doesn't strike me as a win.

**Comment by lizmat** [comment]
I feel this ticket can be closed.
