### ISSUE TITLE
Can't race certain code

### ISSUE THREAD

**Issue by coke** [rakudo/rakudo#1950]
## The Problem

Adding race to some code causes a failure.

## Expected Behavior

Race should transparently work, even if it's not actually racing,.

## Actual Behavior

```
A worker in a parallel iteration (hyper or race) initiated here:
  in block <unit> at bin/unifind.p6 line 6

Died at:
    Cannot find method 'Any' on object of type Match
      in block  at bin/unifind.p6 line 12
```

## Steps to Reproduce

This version doesn't have a race (pass in "cat" as the arg)

https://github.com/coke/p6-unicode-mangler/blob/master/bin/unifind.p6

It works, but slowly.

This version throws the error shown above:

https://github.com/coke/p6-unicode-mangler/blob/1.0.0/bin/unifind.p6

## Environment

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77
$ perl6 --version
This is Rakudo version 2018.05-123-gcf10780da built on MoarVM version 2018.05-131-g9fb02c950
implementing Perl 6.c.
```

**Comment by coke** [comment]
See also: https://rt.perl.org/Ticket/Display.html?id=125978#txn-1365512

**Comment by zoffixznet** [comment]
This is because `<$regex>` uses `&EVAL` and `&EVAL` is currently not thread safe: https://github.com/rakudo/rakudo/issues/1391

You can extract the regex itself outside the... race track... (and looks like a single use of it is needed as well, to compile it?). I get no crashes when I do that.

Also, you're converting to `.chr` and then calling `.uninames` which is for multi-char strings. Since you're only working with a single char, you can drop the `.map(*.chr)` and use singular `.uniname` right on the `Int`. Makes it about 23% faster.

```perl6
sub MAIN($search, Bool :w($word)) {
    my $regex = $word ?? "<< $search.perl() >>" !! $search;
    "" ~~ (my $re := rx:i/<$regex>/);
    ^0x110000
        .race
        .grep({.uniname ~~ $re})
        .map: {say "{.chr} : U+{.fmt: '%04X'} {.uniname}"}
}
```

**Comment by ronaldxs** [comment]
Possible simplification of workaround based on SO question:

```Perl6
sub MAIN($search, :w($word)) {
    my $regex = $word ?? "<< '$search' >>" !! $search;
    "" ~~ my regex re {:i <$regex> };
    ^0x110000
        .race
        .map(*.chr)
        .grep({$_.uninames ~~ &re})
        .map({say "$_ : U+{$_.ord} {$_.uninames}"})
}
```
