### ISSUE TITLE
Map.new(name => "Tison", truth => 42) produces Map.new(())

### ISSUE THREAD

**Issue by W4anD0eR96** [rakudo/rakudo#1957]
https://github.com/rakudo/rakudo/blob/c441d8d8b00ca258ab980d02794cb2d346ecb709/src/core/Map.pm6#L11-L15

but why? shouldn't it results the same as `Map.new((name => "Tison", truth => 42))` which produces `Map.new((name => Tison, truth => 42))`

**Comment by niner** [comment]
*@args  does not take named arguments into account. `name => '"Tison"` however is just the same as `:name<Tison>`
`Map.new("name" => "Tison", "age" => 42)` on the other hand calls Map.new with 2 Pairs as arguments and produces the desired result.

**Comment by W4anD0eR96** [comment]
is there a way we are able to get all named arguments to make it work? though it might be unnecessary  but reasonable.

**Comment by niner** [comment]
This would work:
```
    multi method new(*%nameds) {
        my $self := nqp::create(self);
        nqp::bindattr($self, Map, '$!storage', nqp::hash);
        $self!STORE_MAP(%nameds) if %nameds;
        $self
    }
    multi method new(*@args, *%nameds) {
        my $self := nqp::create(self).STORE(@args);
        $self!STORE_MAP(%nameds) if %nameds;
        $self
    }
```
This just leaves the question: do we want this feature and the associated performance cost?

**Comment by zoffixznet** [comment]
> but why?

Performance reasons and language expectations. Don't just look at `Map.new`, look at the entire language.

Named args don't get special treatment in any of these cases that I recall off the top of my head. There are likely a lot more:
```
<Zoffix__> m: dd .new: :42foo for Hash, Array, List, Set, Bag, Mix, SetHash, BagHash, MixHash
<camelia> rakudo-moar e9351cbaa: OUTPUT: «{}␤[]␤()␤().Set␤bag()␤mix()␤().SetHash␤().BagHash␤().MixHash␤»

<Zoffix__> m: dd DateTime.new: 2018, 6, 7, :5hour, :20minute
<camelia> rakudo-moar e9351cbaa: OUTPUT: «Cannot resolve caller new(DateTime: Int, Int, Int, :hour(Int), :minute(Int)); none of these signatures match:␤    (DateTime: \y, \mo, \d, \h, \mi, \s, :$timezone = 0, :&formatter, *%_)␤    (DateTime: :$year!, :$month = 1, :$day = 1, :$hour = 0, :$…»

<Zoffix__> m: dd (:foo, :bar, :ber).grep: :foo
<camelia> rakudo-moar e9351cbaa: OUTPUT: «Cannot resolve caller grep(List: :foo); none of these signatures match:␤    ($: Bool:D $t, *%_)␤    ($: Mu $t, *%_)␤  in block <unit> at <tmp> line 1␤␤»
```

So if you teach the user they can ignore the difference between named and positional pairs in `Map.new`, you have to follow through and perform the same treatment with all the QuantHashes. Now the user is confused why named pairs dissappear in `List.new` and `Array.new`—they work in 6 other types now, after all. You say, well Maps and QuantHashes are not ordered but Lists are, so you don't know in which order to stuff those named params. So there you hit the first limitation, and now half the language takes named pairs and the other half doesn't. But the user then says, why doesn't DateTime take nameds the way I wrote above? It does take all-named and it does take all-positionals, surelly I should be able to mix them. That's perfectly implementable, but would be slower, so now along with the inconsistency, you're taking a larger performance drop. Now the user finally gets to .grep example above, and says, well, in most of the other language, you try to do the best you can when I pass pairs as nameds even though I meant to pass them as positionals. Surely you can do something here with .grep, where obviously I meant to smartmatch with a Pair. And now you implement that and try to implement that on any routine that does not have a zero-positional args meaning, while leaving it unimplemented on those that do. And now you have an entirely inconsistent language and without memorizing a huge list of options the user has no good way of knowing whether named pairs would be treated as positionals, and so we're actually back to where we started—`Map.new`—and this poor user is still calling it as `Map.new: (:42foo, :70bar)` because they just can't remember if that's one of the routines that accepts arbitrary named pairs. So the language is now slower and codebase is harder for core devs to maintain, but the user received no benefits. The cities crumble, the oceans boil, and the Sun grows to a Red Giant and consumes the Earth.

> This just leaves the question: do we want this feature and the associated performance cost?

I don't. It didn't take me much effort to learn to write `Map.new: (:42foo, :70bar)` and I'm not some genius. The positional-vs-named pairs is already listed on as a trap on the traps docs page, and trying to do the best we can in some cases will only create more confusion, as the trap would seemingly not apply in some cases (it doesn't with `hash :42foo`, but since it's a contextualizer it makes sense that it has this extra behaviour, even if it's actually implemented in Rakudo as simply a routine).

**Comment by W4anD0eR96** [comment]
> So if you teach the user they can ignore the difference between named and positional pairs in Map.new, you have to follow through and perform the same treatment with all the QuantHashes.

Right, I confound hash with named arguments.
