### ISSUE TITLE
Empty set()/bag()/mix() do not return a unique object

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1959]
This is a recent change in https://github.com/rakudo/rakudo/commit/8a4df16204eaddeeea5fb28364c8b5a88b3a9a91 and it results in program-wide action-at-a-distance if you modify the returned object by mixing a role. Any place that used a `set()` will now have a `Set` that returns `"foo"` for `.Str`:

```
<Zoffix__> m: my $a := set(); my $b := set(); $a does 'foo'; $b.print
<camelia> rakudo-moar e9351cbaa: OUTPUT: «foo»

<Zoffix__> m: my $a := set(1); my $b := set(1); $a does 'foo'; $b.print
<camelia> rakudo-moar e9351cbaa: OUTPUT: «1»
```

If the commit is reverted, there are likely more changes that will need to be removed as well, as for example `Set.perl` checks whether the object is the object from `set()`: https://github.com/rakudo/rakudo/issues/1958#issuecomment-399769123

**Comment by lizmat** [comment]
The empty set/bag/mix are just that: immutable empty Set/Bag/Mix, and as such special (and we should only need one of each for the lifetime of a process).

Now, the behaviour with `does` is unfortunate, and a bit of DIHWIDT, but I think we can fix *that*

**Comment by zoffixznet** [comment]
> The empty set/bag/mix are just that: immutable empty Set/Bag/Mix, and as such special

Out of curiosity, what's so special about them that we want them to always use the same object?

**Comment by zoffixznet** [comment]
> Now, the behaviour with does is unfortunate, and a bit of DIHWIDT, but I think we can fix that

In fact, it's not just `does`. You can mutate with `.^mixin` too: 

```
set().^mixin: role { method Str { "meow\n" } }; print set()
```

The behaviour of `=:=` is also affected:

```
$ perl6 -e 'sub get-parts { set |("part" xx 3.rand) }; dd unique :with(&[=:=]), get-parts() xx 10'
(set(), ("part").Set, ("part").Set, ("part").Set, ("part").Set, ("part").Set, ("part").Set, ("part").Set, ("part").Set).Seq
```

**Comment by zoffixznet** [comment]
> a bit of DIHWIDT

I also don't understand this judgment. What's DIHWIDT about mixing in out of band data? That's exactly what `does` is for. `App::GymScheduler` uses it liberally to earmark relevant `DateTime` objects; were it working with `Set`s instead, it'd be broken.

**Comment by AlexDaniel** [comment]
Yes, there's nothing wrong with using `does` on an empty set. This is a bug that should be fixed.

**Comment by lizmat** [comment]
It's DIHWIDT when you try to do it in **the** *immutable* empty set, aka `set()`.

It's ok when you do it on **a** *mutable* empty set, aka `Set.new`

**Comment by lizmat** [comment]
@AlexDaniel: if you want that bug fixed, we would need to remove the concept "**the** empty set" and always return a new, immutable `Set`.  Before we do that, I would like to have the views of masak and jnthn.

**Comment by AlexDaniel** [comment]
@lizmat maybe you're right…

```perl6
my $x = ‘foo’ does 42;

say ‘foo’.Int # 42
```

😮

**Comment by lizmat** [comment]
@AlexDaniel: interesting

Perhaps we could make the type object `Set` stand-in as the empty set?

**Comment by lizmat** [comment]
Or maybe have an optional flag on objects to indicate that they cannot be mixed into?  And set that on the empty set, and on fixed strings?

**Comment by zoffixznet** [comment]
> the concept "the empty set"

I never even knew we had such a concept, nor do I see it documented ([`set()`](https://docs.perl6.org/routine/set), [`bag()`](https://docs.perl6.org/routine/bag), [`mix()`](https://docs.perl6.org/routine/mix)).

What does it let us accomplish that would otherwise be impossible? This sort of magical special casing is what sucks in Perl 5 IMO and it would be beneficial for us to avoid.

**Comment by AlexDaniel** [comment]
I think it does work with Strs if you use `but` instead of `does`, and that is probably important. Docs say that `does` “Requires $obj to be mutable”, so maybe there's no big issue with Strs as long as we clearly recommend `but`? The empty set is an issue with both `but` and `does` though.

**Comment by zoffixznet** [comment]
> The empty set is an issue with both but and does though.

That's IMO a third bug: the `.clone` method the user would explicitly use to make a clone is special-cased to return "the" empty set if there are no elements: https://github.com/rakudo/rakudo/blob/e6e9daf1c/src/core/Set.pm6#L86

```
$ perl6 -e 'dd Set.new.clone =:= set()'
Bool::True
```

What's the beneficial usecase for all of this special-casing?

**Comment by lizmat** [comment]
Why do we make sure that literal strings only exist once in memory?  So that we only need one of them.

If jnthn decides that all special cases for immutable QuantHashes needs to go, I'm fine with that.

Meanwhile, I think @AlexDaniel has pointed to a deeper problem involving literal hashes.  So maybe this whole issue is just another expression of a deeper underlying issue.

**Comment by jnthn** [comment]
A few quick points.

1. We don't currently have a way to forbid `does` on immutable objects. We should design and implement one. It ties into various other open problems (providing immutability information at the VM level, and trying to work out how to make `but` not needlessly trigger global deopt) that I've been considering, so I'd like to be involved in that design process. I am quite sure it belongs in meta-space, however, rather than some kind of `Immutable` role (that can't work since `Set` is immutable, but `SetHash ~~ Set` and `SetHash` is mutable).
2. It's fine to use `but` on an immutable object, since it makes a clone and performs the type-changing operation on that. However, for that to work it's essential that the `clone` method actually does make a copy. Any `clone` method trying to cheat on that wants fixing: `clone` returning identity won't work out.
3. It's fine to intern immutable literal objects. We do that with `Str` and `Int`, for example. The empty set being considered an immutable literal doesn't immediately strike me as wrong, so long as we consider `Set` immutable once we have the mechanism to do that. I think making people use `but` instead of `does` for that is right anyway; it's one letter shorter to type, and going forward we can make `but` perform a great deal better than `does`.

**Comment by zoffixznet** [comment]
> It's fine to intern immutable literal objects.

What are `literal` objects? Would it be correct to say that "an implementation may intern objects that have the same .WHICH"?

I think around the end of 2017, there was work to make `List.WHICH` depend solely on the `.WHICH`es of the elements, so that this behaviour would've been observed:

```
$ perl6 -e 'say +Set.new: (42, "foo"), (42, "foo")'
1
$ perl6 -e 'class Foo {}; say +Set.new: (42, Foo.new), (42, Foo.new)'
2
```

Right now that gives `2` for both versions, yet I notice we do the `.WHICH`-based-on-contents for `Map`s and `Set`s already. How come `List` is an exception?

```
$ perl6 -e 'class Foo {}; say Set.new: Map.new((foo => Foo.new)), Map.new((foo => Foo.new))'
set(Map.new((foo => Foo.new)) Map.new((foo => Foo.new)))

$ perl6 -e 'class Foo {}; say Set.new: Map.new((foo => 42)), Map.new((foo => 42))'
set(Map.new((foo => 42)))

$ perl6 -e 'class Foo {}; say Set.new: Set.new(42), Set.new(42)'
set(set(42))
``

**Comment by FCO** [comment]
What about not a `Immutable` role, but a `Mutable` one? A type that extends
a mutable immutable type can be mutable but can a type that extends a
mutable type be immutable?




Just another Perl Hacker,
Fernando (SmokeMachine)

2018-06-27 12:48 GMT-03:00 Jonathan Worthington <notifications@github.com>:

**Comment by lizmat** [comment]
@jnthn: fwiw, `dd SetHash ~~ Set   # Bool::False`, so that argument does not apply.  `Set` and `SetHash` both do the `Setty` role.

I will fix the QuantHash.clones that do not actually clone.

**Comment by lizmat** [comment]
@FCO: as @zoffixznet pointed out, the problem really lies in the underlying `.^mixin` meta-method.  As long as you can mixin anything into something that is considered Immutable at the HLL, we have a problem.  A HLL `Immutable` role will not fix that.

**Comment by jnthn** [comment]
> What are literal objects? 

Those that are dependent solely on information available at compile time, and immutable from then on. I was trying to make clear that while `set()` could potentially be interned, `set($a)` could not be since it depends on a runtime value (well, unless `$a` is a constant).

> Would it be correct to say that "an implementation may intern objects that have the same .WHICH"?

That's seem fair, though in reality the implementation for interning things like `Int` and `Str` at present relies on knowing their semantics - in part because it needs to compile the setting, so we need some bootstrapping allowances.

> fwiw, dd SetHash ~~ Set # Bool::False, so that argument does not apply. Set and SetHash both do the Setty role.

Aha, glad that was done with roles, not inheritance. It still would apply to `Map` and `List`, though.

**Comment by lizmat** [comment]
> Aha, glad that was done with roles, not inheritance. It still would apply to Map and List, though.

Yeah, never understood why a mutable class would depend on an immutable class.  Perhaps something to fix for 6.d ?

**Comment by masak** [comment]
I'm unable to take in all the intricacies of this issue in one go, but I will say that I'm completely surprised by the assertion that `set()` would return something immutable. I'm fairly sure this is the first I hear of that.

As @zoffixznet points out, [the doc page for set()](https://docs.perl6.org/routine/set) doesn't say anything about immutability either. So at least whoever wrote that page may be as surprised as I am.

Pretty sure I've even used `set(@elems)` to create mutable `Set`s on numerous occasions.

**Comment by lizmat** [comment]
Then that must have been 3 years or longer ago: `Set`s have become immutable since then.  If you want a mutable `Set`, you need to create a `SetHash`:

    my $s = set(1,2,3,4,5); $s<a> = True'
    # Cannot modify an immutable Set (set(1 2 3 4 5))

    my $s = (1,2,3,4,5).SetHash;
    $s<a> = True;
    dd $s'
    # SetHash $s = (3,"a",1,4,2,5).SetHash

**Comment by masak** [comment]
@lizmat Ah! It appears you're right, of course. And [the documentation for Set](https://docs.perl6.org/type/Set) is very clear, even in its first sentence: "A Set is an immutable set...".

But, then I don't understand your earlier sentence:

> It's ok when you do it on **a** _mutable_ empty set, aka `Set.new`

What is it about `Set.new` that makes it semantically different from `set()`? Where is this documented? In which sense is `Set.new` mutable? I thought Sets were immutable.

The Set doc page has this sentence:

> `Set`s can be composed using the set subroutine (or `Set.new`, for which it is a shorthand).

From which I at least would conclude that it doesn't make an obserable difference if you use `set()` or `Set.new()`. But you seem to be saying it does.

Offhand, my intuitive feeling is that since `set()` is a function call, it should return a _fresh_ immutable empty set every time as a baseline. If you want a "the empty set", then you should use a constant somewhere.

I guess this is doubly true of `Set.new()` &mdash; here you're _explicitly_ asking for a newly constructed object, distinct from previous ones.

But I do note that the conclusion of the thread seems to be to double down on immutability, forbid `does` on immutable things, and generally build a world in which `set()` _can_ be a unique object and can never be mutated through `does` or other mechanisms, so that the fact that it is the same interned object becomes an unobserable-ish implementation detail rather than a bug.

I wish that effort good luck &mdash; unfortunately I'm a bit jaded because I feel that Perl 6's efforts to track immutability are not super-strong and tends to lead to compromises along the way. But it's entirely possible that that says more about me than about the viability of interning empty sets! So carry on, I guess. :wink:

**Comment by lizmat** [comment]
>> It's ok when you do it on a mutable empty set, aka Set.new
> What is it about Set.new that makes it semantically different from set()? Where is this documented? In which sense is Set.new mutable? I thought Sets were immutable.

I should have said "mixinnable" :-)

> Offhand, my intuitive feeling is that since set() is a function call, it should return a fresh immutable empty set every time as a baseline. If you want a "the empty set", then you should use a constant somewhere.

Currently, `set()` and `∅` are the same thing: the immutable empty set (aka  `BEGIN nqp::create(Set)`.

Finally, there is a subtle difference between `.Set` and `Set.new`: the former is a coercer and has special handling for `Pair`s, the latter takes things at face value:

    my %h = a => 1, b => 0;
    dd %h.Set;            # ("a").Set, aka only put keys with truthy values in the Set
    dd Set.new(%h);  # (:b(0),:a(1)).Set, aka just put every element in the Set

FWIW, this is consistent with `.Bag` / `Bag.new` and `.Mix` and `Mix.new`.

**Comment by masak** [comment]
Heh, I wasn't even thinking about `.Set` the coercer. That bit makes sense to me, by the way.

But (at the risk of repeating myself), the docs as they stand today seem to believe that `set()` and `new Set()` are synonyms, and it seems from the discussion in this issue that they are not. Most likely it is the docs that need to be updated.

Specifically, I suspect the docs currently don't have any wording to the effect that `new Set()` is "mixinnable", but `set()` is not. It feels like an important enough distinction that it ought to be lifted to a policy/principle, and we should make sure to document it.

**Comment by zoffixznet** [comment]
> It feels like an important enough distinction that it ought to be lifted to a policy/principle, and we should make sure to document it.

Added a note on the docs for `does` https://github.com/perl6/doc/issues/2128#issuecomment-401323634 and to make it a more general comment that objects with same `.WHICH` might be interned by implementations.

I think this Issue has been resolved not as not-a-bug
