### ISSUE TITLE
Windows roast hang on `ok 2 - Supply.merge on signals does not crash`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1975]
The `t\spec\MISC\bug-coverage-stress.t` file hangs on Windows based on output, looks like it hangs on `ok 2 - Supply.merge on signals does not crash` (note: the failed test might be just buggy windows `is-run` test script and not the mutex failure).

Based on my [earlier stresstest run](https://github.com/perl6/roast/issues/320#issuecomment-400471736) it looks like this test hung for 10+ hours that time.

Test is now fudged in https://github.com/perl6/roast/commit/1817ad8b383c7329f9a27462e1cac8a04b2c30fa so you'll need to remove that fudge to reproduce the problem.

```
C:\rakudo>perl t\fudgeandrun t\spec\MISC\bug-coverage-stress.t
t\spec\MISC\bug-coverage-stress.rakudo.moar ..
1..11
    1..2
    ok 1 - program did not hang
    not ok 2 - STDOUT    # Failed test 'STDOUT'
    # at C:\rakudo\t\spec\packages\Test\Util.pm (Test::Util) line 265

    # expected: "pass"
    #  matcher: 'infix:<~~>'
    #      got: ""
    # Looks like you failed 1 test of 2
not ok 1 - no deadlock while acquiring mutex
# Failed test 'no deadlock while acquiring mutex'
# at C:\rakudo\t\spec\packages\Test\Util.pm (Test::Util) line 258

```

**Comment by jstuder-gh** [comment]
I've pushed up a PR (found [here](https://github.com/rakudo/rakudo/pull/1995)), that addresses the hanging issue on Windows, but doesn't get the test to pass. Unfortunately, the test can't pass on Windows given the way that "signals" work.

The problem with the way signals work on Windows is that they are entirely emulated in libuv, and not a mechanism involving the kernel. So attempting to send a signal to a another process will not invoke the signal handler (or sending a signal to the same process for that matter; I think I wrote up a decent explanation you can see [here](https://github.com/rakudo/rakudo/issues/1960/#issuecomment-399775398)). In this case since the proper output is sent only upon invoking the sighandler, it will never work the way it is intended.
