### ISSUE TITLE
Roadmap for Regex/Grammar optimizations

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1999]
Looking at [survey results](https://docs.google.com/forms/d/19qSBpGWWc9RNruxPWySHkmy3tppaqeqUNGfZpHhdsMs/viewanalytics), a lot of people consider grammars to be their favorite feature in Perl 6, and at the same time there is some demand for faster grammars.

This is a meta ticket to gather more information on what can be done, and also to track our progress. Thoughts and comments are welcome.

**Comment by AlexDaniel** [comment]
There was something @TimToady was working on (something about not parsing the next token over and over again?), does anybody have any link or info about that?

**Comment by MasterDuke17** [comment]
Here's come comments about regexes https://www.reddit.com/r/perl6/comments/5naomy/where_can_i_start_looking_to_speed_up_regular/

**Comment by AlexDaniel** [comment]
Related RT tickets:
* [RT#125974](https://rt.perl.org/Ticket/Display.html?id=125974) [new]: [PERF] Closures in regex cost a lot of CPU cycles.
* [RT#128693](https://rt.perl.org/Ticket/Display.html?id=128693) [new]: [PERF] Regex optimizer on \s+$ is "dumb as bricks"
* [RT#132219](https://rt.perl.org/Ticket/Display.html?id=132219) [new]: [@LARRY] [REGEX] non-ratchet right-hand branch of `||` causes backtracking into the alternation

**Comment by jnthn** [comment]
> There was something @TimToady was working on (something about not parsing the next token over and over again?), does anybody have any link or info about that?

I don't have a link, but I do understand the issue. Consider a case like this:

```
grammar G {
    ...
    proto token t { * }
    token t:sym<aa> { a <a> }
    token t:sym<ab> { a <b> }

    proto token a { * }
    token a:sym<x> { x }
    token a:sym<xx> { xx }

    ...
}
```

When we parse `t`, we ask the NFA to tell us which of the alternations (in this case specified as `token`s) to try and in what order. It runs and figures that out. However, LTM is defined recursively, so as part of figuring it out it also looks into the NFA of token a, which is itself an alternation of two other things.

Suppose we were parsing `axx`, then we'd select `t:sym<a>` and call it. Here's the first in-efficiency: it re-parses the 'a' even though it was already parsed. This is not such a simple problem to solve as "just don't re-check that", since we also have cases where it's something like `a+` and, even though that's solvable, we also have the situation that a rule can be called directly (e.g. `G.parse($blah, :rule<< t:sym<a> >>)`).

After that, it calls `a`. We do need to make that call really, since we capture and need the match object. However, the `proto token a` will then do LTM from the current position to decide which candidate to take. Then once it does decide, we again will re-parse the `xx`.

All in all, we considered some of the characters (the final two `x`s) four times. Ideally, we'd consider them once.

Doing this will probably require some fairly significant changes to how we currently work with NFAs; at the moment, there's just not a way to convey the information to where it needs to be.

**Comment by lizmat** [comment]
This feels like it needs a fresh look at in the far future, so closing for now as the world will undoubtedly have changed by then
