### ISSUE TITLE
Native parameters perform boxing

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2007]
This is already know by some, but filing a ticket, so we don't forget about it.

Currently, native-typed parameters perform boxing, which makes native stuff actually slower than regular one:

```
23:04 | Zoffix | m: class Foo { method z (int $x) {} }; my int $z = 42; for ^10_000_000 { Foo.z: $z; }; say now - ENTER now
-- | -- | --
23:04 | camelia | rakudo-moar 4bdb9787d: OUTPUT: «4.0402742␤»

23:04 | Zoffix | m: class Foo { method z (int $x) {} }; my $z = 42; for ^10_000_000 { Foo.z: $z; }; say now - ENTER now
23:04 | camelia | rakudo-moar 4bdb9787d: OUTPUT: «2.2502544␤»
```

This was found by user experiencing slower program when making loop variable native, because it was being used as argument to `native_array.push`

**Comment by jnthn** [comment]
This case is actually because it's taking a native ref because we don't know if there will be an `is rw` parameter on the callee side, and methods are late-bound. However, it's a very similar problem to unrequired boxes and unboxes.

Here's a quick progress report on how far along I am with solving this.

I recently put DU chains into the MoarVM specializer, which let us easily find out, given an operation like a box or a reference take, what uses it. So that is a step towards being able to eliminate such things post-inline. I did implement the box/unbox case. However, some further work is required to make the optimization actually valuable: at the moment, the box is often kept alive by guards or similar. Fixing that involves a re-work of how we track what information we need at the point we de-optimize (this is done in the correctness sense, but the algorithm is a bit costly, so needs some performance engineering). It then needs a re-work of guards to allow us to drop some that we can prove will always be true with information we gain from taking a cross-inline view.

Finally, once all that is done, the box/unbox case should usefully optimize away boxings across inline boundaries, and then I'll be able to take a look at the reference case too.

**Comment by lizmat** [comment]
Afaik this has been done
