### ISSUE TITLE
Inconsistent behaviour of `zip` and friends

### ISSUE THREAD

**Issue by mscha** [rakudo/rakudo#2016]
## The Problem

`zip` and related constructions behave inconsistently when running on a list of one list.

For instance, I was trying to add a list of vectors:

```
> [Z+] (1,2),(3,4),(5,6),(7,8)
(16 20)
> [Z+] (1,2),(3,4),(5,6)
(9 12)
> [Z+] (1,2),(3,4)
(4 6)
```

So far so good.

```
> [Z+] (1,2),
(3)
```

Oops.  The expected result of adding a single vector `(1,2)` is simply `(1,2)`.

~~A bare `zip` behaves the same:~~

```
> zip <a b>, <c d>, <e f>, <g h>
((a c e g) (b d f h))
> zip <a b>, <c d>, <e f>
((a c e) (b d f))
> zip <a b>, <c d>
((a c) (b d))
> zip <a b>,
((a b))
```

~~The last one should consistently be `((a) (b))`.~~
**Edit:** As smls notes, this is a user error.  `zip (<a b>,)` behaves correctly.

Since `roundrobin` is just a variation of `zip`, it has the same issue.

## Expected Behavior

`zip` and its variations should do what they say, zipping a list of iterables, even if that list only contains one iterable.

I understand that this is an incompatible change, but can this please be fixed in 6.d?

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`): This is Rakudo Star version 2018.04.1 built on MoarVM version 2018.04.1 implementing Perl 6.c.

**Comment by AlexDaniel** [comment]
Right. This is documented as a trap here: [Using […] metaoperator with a list of lists](https://docs.perl6.org/language/traps#Using_[%E2%80%A6]_metaoperator_with_a_list_of_lists). The issue comes up fairly often, IIRC there was a nice stackoverflow explanation with possible solutions (can't find it now).

For every trap we can try to think of a way to improve the situation. That's what `detrap` label is for, and this is the first actual ticket labeled as such. So… any thoughts on what can be done here in terms of tweaking the language? Brainstorming is welcome.

**Comment by smls** [comment]
Explanation on SO: https://stackoverflow.com/a/44831926

Doc ticket: https://github.com/perl6/doc/issues/1400

RT (with some discussion on how it could be made to DWIM): https://rt.perl.org/Public/Bug/Display.html?id=131686#txn-1471068

**Comment by smls** [comment]
I opened up a new issue for a proper RFC: https://github.com/rakudo/rakudo/issues/2025

Also, note that this is only about the part with `reduce`.

Regarding bare `zip`/`roundrobin`, I think you're mistaken:

<blockquote>bare zip behaves the same:
<pre>> zip <a b>, <c d>, <e f>, <g h>
((a c e g) (b d f h))
> zip <a b>, <c d>, <e f>
((a c e) (b d f))
> zip <a b>, <c d>
((a c) (b d))
> zip <a b>,
((a b))</pre>
The last one should consistently be <code>((a) (b))</code>.</blockquote>

The last one is actually calling `zip` with two arguments.  
To call it with the single argument `<a b>`, write:

```
> zip (<a b>,)
(a b)
```

And voila, it returns a two-element list, consistent with the other ones.
(It doesn't coerce the two elements to `List` themselves, but since any non-list value van be treated as a one-element list in Perl 6, that does not really matter.)

**Comment by mscha** [comment]
Thanks for all the links and explanations, and smls especially for the well-reasoned RFC.
It'd make me very happy if this were fixed in 6.d.

**Comment by AlexDaniel** [comment]
It didn't make it to 6.d, but we can make it happen in 6.e. Just need a hero to do it :)
