### ISSUE TITLE
Warn on literal assignment in conditional

### ISSUE THREAD

**Issue by Juerd** [rakudo/rakudo#2064]
## The Problem
Perl 6 does not help you when you're using = instead of == in a condition. This is such a common mistake to make, that many programming languages either warn about it, disallow assignment in conditionals, or have a different syntax for assignment in expressions. Several code checkers (linters) flag this too. 

There are even people who suggest using so-called "Yoda style" comparisons such as `0 == $x` instead of `$x == 0` to catch the mistake of accidentally leaving out one of the two "=" signs.

Perl 5 emits a warning (when warnings are enabled) when you do `if ($x = 0) { ... }`, and very clearly instructs the programmer to use `==` instead: `Found = in conditional, should be ==`. It does not warn when assigning a non-literal value.

In at least one comic strip, this common syntax mistake has lead to a robot becoming a crazy murdering robot http://oppressive-silence.com/comic/oh-no-the-robots so maybe it should even be a fatal error instead of a warning ;-).

## Expected Behavior

    1;0 juerd@cxien:~$ perl6 -e'my $x = 0; if $x = 0 { say "meh" }'
    WARNINGS for -e:
    Condition is always False because of assignment in "if".
    Did you mean "==" instead of "="? (line 1)
    1;0 juerd@cxien:~$ 

## Actual Behavior

    1;0 juerd@cxien:~$ perl6 -e'my $x = 0; if $x = 0 { say "meh" }'
    1;0 juerd@cxien:~$ 

## Assignment of non-literals

Only assignment of a literal value is very likely to be a mistake, but it might make sense to warn for any assignment in conditions, and to suggest rewriting `while $x = func() { ... }` as `while func() - > $x { ... }` to more clearly avoid ambiguity. I'm not so sure about this part, though, because TIMTOWTDI, and assignment in expressions is a common pattern for those who come from other languages and are not yet accustomed to Perl 6's arrow notation with conditionals.

**Comment by zoffixznet** [comment]
> Dear @zoffixznet, why the thumbs-down?

Because I'm against this warning, but I don't care about this issue enough to resist it more strongly by stating the reasons why it's bad, hence the thumbs-down.

-----------

All that these obnoxious warnings do for me is make perfectly valid code invalid for arbitrary reasons that the authors of the warning assumed must apply to everyone. For example, I never wrote a single line of C++ code in my life, yet if I write perfectly valid Perl 6 construct while creating a class, I get this arbitrary error:

```perl6
$ perl6 -e 'my $o := new class { … }:'
===SORRY!=== Error while compiling -e
Unsupported use of C++ constructor syntax; in Perl 6 please use method call syntax
at -e:1
------> my $o := new class ⏏{ … }:
```

If I write this perfectly valid Perl 6 construct, I get another arbitrary error:

```
$ perl6 -e 'say set'
===SORRY!===
Argument to "set" seems to be malformed
at -e:1
```

If I write this perfectly valid Perl construct, I get another arbitrary warning:

```
$ perl -wlE 'my @products = qw/33-32323  44-4433434 44#323232/'
Possible attempt to put comments in qw() list at -e line 1.
```

The above is especially obnoxious when you regularly work with data that frequently uses the `#` char.


And this Issue proposes we add another arbitrary warning when I write this perfectly valid Perl 6 construct:

```
$ perl6 -e '
    sub get-stuff { rand }
    if my $r := get-stuff() { say "wow! This is extra good stuff!" }
    say "Here is your stuff: $r"
'
WARNING: you wrote perfectly valid stuff, but I'm an opionated, yet dumb compiler,
so I'm going to pollute your output with crap, forcing you to go back and change your
perfectly valid stuff into more verbose one that's harder to read.
Hope you don't make a mistake in that change! MUAHAHAHA, sucker!
Here is your stuff: 0.31672673963771747
```

-------------------------------

Unlike many other languages, in Perl 6 the `if my $foo = 42 {}` doesn't scope the variable to the inner block, it's scoped to the same level that `if` is in. That means if I need to add more statements in code like:

```perl6
    do-stuff if my $mississippi-depth-at-target = 42;
    say $mississippi-depth-at-target;
```

I can just select, cut, paste, add braces, add more statements:


```perl6
    if my $mississippi-depth-at-target = 42 {
         do-stuff;
         do-more-stuff;
    }
    say $mississippi-depth-at-target;
```

But if I do it with this Issue's suggestion implemented, I will get garbage added to my program's output, requiring me to change my perfectly valid Perl 6 program into this: (I know about `do`, but it would place the conditional *after* all the code it applies to)

```perl6
    my $mississippi-depth-at-target = 42;
    if $mississsippi-depth-at-target {
         do-stuff;
         do-more-stuff;
    }
    say $mississippi-depth-at-target;
```

Just because someone thinks writing `=` instead of `==` is a "common mistake" for me. Yet, I have more issue with duplicating variable names that might not get duplicated correctly, requiring me to go back and fix yet another error. In fact, I did make that error above. Did you notice it?

I'm assuming you're proposing `do-stuff if my $foo = 42;` also warns, which introduces the variable duplication issue as well.

-----

There is [a bunch of uses](https://gist.github.com/Whateverable/6f5c9dc8620ae2e4e398fcf6d0d38a4c) of `if my $… = … { … }` in the ecosystem that should've been `if … -> $… {` instead, but IMO that's almost a stylistic difference not worthy of a core warning by default. And in a [larger sample](https://gist.github.com/zoffixznet/82a28c74a22e3fd92a24aeb3a67e24bf) I don't see a single case of this "common" `=` vs. `==` error being made despite no warning produced by us.

------

The commonality of this uncommon "common" error is even less in Perl 6, because:

1. Unlike C and JS, in Perl 6 `==` is only used with numeric values
2. We have smartmatch, and some people write `~~ 5` instead of `== 5`
3. We have `$_` and `when`, which avoids explicit use of any operators in comparisons
4. You generally would bind immutable values instead of placing them into containers, thus generating an error if such a variable is used with incorrect operator in the conditional:

```
$ perl6 -e 'my $x := 42; if $x = 42 {}'
Cannot assign to an immutable value
```

------

In summation, this Issue proposes we make the language more complex by making an arbitrary combination of perfectly valid constructs all of a sudden invalid, requiring the user to write more code and making them potentially make more bugs in it.

The reasoning for this issue is in languages where `==` is used for comparing everything under the moon writing `=` is a common mistake (unsurprisingly). I.e. it uses theydoittooisms and vague general statements instead of actual data that applies to Perl 6 to justify the breaking of valid constructs with a warning.

But as I don't care much about it, I just put a thumbs down instead of writing all of this.  I'm also going to unsubscribe from this Issue, as I don't care about participating in the discussions about this Issue.

**Comment by lizmat** [comment]
@zoffixznet: FWIW, I think the warning was intended to be **ONLY** issued when:

- the left hand side of an *assignment* is an already defined variable
- the right hand side has a compile-time value

So, `if my $foo = 42 {` doesn't fall under that, `if $foo := 42 {` doesn't, `if $foo = bar() { ` doesn't.

I understand your feelings, but I think all of the cases you mention, would not fall under this proposal, except maybe the `my $x := 42; if $x = 42 {` case, which would be great if it complained at compile time.

**Comment by T1S0N** [comment]
if these warnings bother, it could be considered implementing `use warnings<...>;`/`no warnings<...>`, like `@SuppressWarings(...)`

**Comment by vendethiel** [comment]
> Dear @zoffixznet and @vendethiel, why the thumbs-down?

The error/warning "condition is always true/false" is one that's interesting to have, I think this warning is an uninteresting special-case of this.
