### ISSUE TITLE
LTA: &[~] is used for both Blobs and Strs / propspec for 1-arg &[~]

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2140]
Came across [propspec defining `&[~]` for 1-arg `Blob`](https://github.com/perl6/roast/commit/b51d3a63a)

Don't know if we can/should do anything about `Blob` using `~` op (given they *are* `Stringy`), but we have this LTA case where if you use `my Blob := [~] @bunch-a-blobs`, it will crash if `@bunch-a-blobs` is empty, because in that case `[~]` will return an empty `Str` (the 1-arg case used to crash the same before https://github.com/rakudo/rakudo/commit/77e9d4b545 )

In addition `my Blob $a; $a ~= Blob.new: 42` always crashes, because when `$a` is undefined, a zero-arg `&[~]` is used to gen the initial value, but that value is a `Str`, not a `Blob`.

Filing in case anyone has any good ideas on what we can do with this op to avoid these warty edge cases. Will just close closer to 6.d release, if nothing comes up.

**Comment by AlexDaniel** [comment]
Documented trap: https://docs.perl6.org/language/traps#Using_[~]_for_concatenating_a_list_of_Blobs

My initial understanding was that the easiest way to resolve this is to make `~` Str-only. The issue comes from the fact that the identity element for `~` is `‘’`, which is not a Blob (a hack could be to have some sort of an EmptyBlobStr which `is` Str and Blob…).

However, after thinking about it, I realize that the same is true for many other operators:
```perl6
my Num $x = [+] ()
```
```
Type check failed in assignment to $x; expected Num but got Int (0)
  in block <unit> at -e line 1
```

**Comment by zoffixznet** [comment]
> However, after thinking about it, I realize that the same is true for many other operators:

Oh right. Didn't even think of that.
