### ISSUE TITLE
open() fails in REPL

### ISSUE THREAD

**Issue by xelak6** [rakudo/rakudo#2184]
## The Problem
Opening a file in REPL fails as follows:
```
$ echo 'Hello World!' >/tmp/hw.txt
$ perl6 -v
This is Rakudo version 2018.06-329-g85050ac2b built on MoarVM version 2018.06-375-g46edb6f63
implementing Perl 6.c.
$ perl6

To exit type 'exit' or '^D'
> my $fh = open('/tmp/hw.txt', :r)
Failed to write bytes to filehandle: Bad file descriptor

> my $fh = '/tmp/hw.txt'.IO.open
Failed to write bytes to filehandle: Bad file descriptor

> '/tmp/hw.txt'.IO.open.slurp
Hello World!

> 
```
## Environment
* Operating system: 
Distributor ID:	LinuxMint
Release:	19
Codename:	tara
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.06-329-g85050ac2b built on MoarVM version 2018.06-375-g46edb6f63
implementing Perl 6.c.

**Comment by zoffixznet** [comment]
Would you be interested in fixing this bug yourself? We have [a short Guide for fixing bugs](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6).

What happened is [this commit changed from the code `say $value` to `$value.say`](https://github.com/rakudo/rakudo/commit/9ea427a36fea8c7ba980393c7cd43216176384d6#diff-f8e5e0790cdff70931a4cf8cb86697fdR399). So now, when the REPL tries to print that value, instead of printing its gist, it's trying to write an empty line into the read-only file handle we opened.

So to fix the bug, we need to change it back to `say $value`.

The tests for this Issue would go into Rakudo's test suite, [`t/02-rakudo/repl.t`](https://github.com/rakudo/rakudo/blob/master/t/02-rakudo/repl.t) is a good place and it has a helper routine for testing the REPL.
