### ISSUE TITLE
Substitute Rakudo::Internals::is-win to $*DISTRO.is-win for easier (or possible) testing of code when possible.

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2190]
## The Problem

Since it's impossible to change the value of  Rakudo::Internals::is-win, it's impossible to test that code unless you are in an actual machine that causes that value to be true.

## Expected Behavior

It would be ideal if we could test all code, or most of it, in a single machine. In all cases where there is no actual interaction with the OS, it should be possible to check from a single machine the behavior of Win and non-Win OSes.

## Actual Behavior

In most cases Windowness is detected using `$*DISTRO.is-win`, which can be modified in runtime to test that particular code, but in 5 cases (so far) it uses that other method to detect Windowness. Maybe that's also easy to change through the lexpad, but anyway it would be better to detect Windowness through a single method throughout all the code for testing purposes, if that's not a significant impact in overall performance.

**Comment by ugexe** [comment]
Testing is only possible because it is the way it is. If it was changed as suggested then rakudo would barely function, since `BEGIN $*DISTRO does role :: { method is-win { True } }; say $*DISTRO.is-win` would then affect internal stuff like path handling, choosing HOME/TMP, etc that has nothing to do with an external test.

**Comment by JJ** [comment]
$*DISTRO is used all over the place to check what OS Rakudo is on,
including some kernel functions:
https://github.com/rakudo/rakudo/blob/c71fa17d8da36b8cfcbd85584cee32566f25f059/src/core/Kernel.pm6
That's bound to be affected if you do stuff like that, but it also allows
to test that code even if you're not using Windows. Using
Rakudo::Internals::IS-WIN is, in fact, relatively rare.

**Comment by raiph** [comment]
I think the following is sound logic and guidance. If not, I apologize.
> It would be ideal if we could test all code, or most of it, in a single machine.
Obviously not _all_ code, because some of it is OS specific, as you point out.
> In all cases where there is no actual interaction with the OS, it should be possible to check from a single machine the behavior of Win and non-Win OSes.
In academic theory, sure. But that implies indirections for everything, and indirections slow things down, so it's very likely there's code that will stymie some such testing in the name of performance or simplicity or both. Given that there's always going to be _some_ code that requires running on the actual OS, and that attaining the academic theoretical "ideal" has both performance and code complexity costs, I think you'll find you'll end up needing to very carefully justify each change you propose to core code to enable/ease increasing text coverage using a single OS.

**Comment by JJ** [comment]
OK, in that particular case, `$*DISTRO` is not available yet. I'm testing others.
