### ISSUE TITLE
Series of perf regressions on 2018-07-09

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2210]
@dogbert17++ for finding this.

Here is the snippet: https://gist.github.com/AlexDaniel/227c34f20d638d0b339947c744d05bc8

This script was getting slower and slower after several commits, all of which I bisected.

Basically:
* ≈2.1s on 2018.06
* ≈2.1s→≈3.0s (≈0.7x as fast) – (2018-07-09) https://github.com/rakudo/rakudo/commit/d3c5381b747169f951db578bebbfd0c5d8165116
* ≈2.9s→≈3.4s (≈0.85x as fast) – (2018-07-09) https://github.com/rakudo/rakudo/commit/ebc6b1249f63e5bc99cd323607f2a0495c761b13
* ≈3.3s→≈3.6s (≈0.92x as fast) – (2018-07-09) https://github.com/rakudo/rakudo/commit/523ffae84c25e3214b1c4e885ebdc5906addf491
* ≈3.7s→≈4.2s (≈0.88x as fast)  – (2018-07-09) https://github.com/rakudo/rakudo/commit/8d6527617dc3aea81a3d6e3f47575c6b7f7d03f1
* ≈3.9s on HEAD(80a7cff)

FWIW https://github.com/rakudo/rakudo/commit/523ffae84c25e3214b1c4e885ebdc5906addf491 is a parent of https://github.com/rakudo/rakudo/commit/8d6527617dc3aea81a3d6e3f47575c6b7f7d03f1.

I didn't bisect speedups, so overall it's just ≈2.1s→≈3.9s which is not as bad as what individual slowdowns would cause.

Raw timings (a bit noisy, but the picture is still very clear): https://gist.github.com/Whateverable/003e226de37b20358fb9b4f51256bed6 (`sha^` means parent of `sha`, so it's before and after every bisected commit)

**Comment by AlexDaniel** [comment]
Possibly related ticket: https://github.com/rakudo/rakudo/issues/2155

**Comment by jnthn** [comment]
I've analyzed it. It's down to a combination of:

1. Much greater dependence on specialization for operations around `Scalar` containers (this was always going to be a change with a lot of immediate fallout, since they're *everywhere* in Perl 6; alas, "do nothing" is not an option, since the next round of significant improvements depends on us being able to properly analyze `Scalar` operations, and before they were mostly chunks of impenetrable C code along with a hard-to-specialize data structure design)
2. The specializer needing more attention with its handling of natives in various situations, and especially when they appear in signatures (this has long been sub-optimal, but 1 means we're noticing it much more in this particular benchmark)
3. A long-standing OSR limitation where it doesn't handle two hot loops one after the other well (same comment as for 2)

My home VM the `now - INIT now` comes in at 4.767s on HEAD. However, tweak it to consistently use natives and avoid the one-loop-after-another weakness:

```
use v6;

my int @cache;
my int $sum89 = 0;

sub prepare {
  for (1..567) -> int $i {
    @cache[$i] = calc-chain($i);
  }
}

prepare;

for (1..400_000) -> int $i {
  $sum89++ if @cache[get-sq-sum($i)] == 89;
}

#say $sum89;
my $x = now - INIT now;
say $x;
#exit 42 if $x > 3.4;

sub calc-chain(int $n) {
  my int $sq-sum = get-sq-sum($n);
  $sq-sum != 1|89 ?? calc-chain($sq-sum) !! $sq-sum;
}

sub get-sq-sum(int $i is copy) {
  my int $sum = 0;
  while $i > 0 {
    $sum += ($i % 10) ** 2;
    $i = $i div 10;
  }
  $sum;
}
```

And it reports 0.77s. I've no idea if it gets the right answer if you do this, since it may depend on big integers. This tweaks just provide evidence for points 2 and 3 above.

Given there's also been a request to not commit much in the way of optimization to MoarVM HEAD before release, and dealing with 2 or 3 would certainly count as somewhat significant optimizer work, I'm not sure what best to do. We've plenty of evidence of performance improvements in a lot of other cases, including some decidedly more real-world examples than this particular code. Dealing with both 2 and 3 are near the top of my performance todo list anyway, so I guess one option is I prepare one or both (depending on how much time they take) in branches and delegate deciding on what the lesser evil is to @AlexDaniel. Though maybe most sensible is to live with it for this release.

**Comment by AlexDaniel** [comment]
I'm fine with leaving it like this for this release. It is unfortunate, but given that other things got noticeably faster (even if not by the same amount) I think it is temporarily fine.

**Comment by AlexDaniel** [comment]
It is now around ≈0.8s.

> \<dogbert11\> so the perf regression is fixed and then some

Bisected to this bump: https://github.com/rakudo/rakudo/commit/ace87cb5d99c4a80b6d093cd92c73d5b952f1093

Generally this is resolved, but I'd love to see this included in some kind of a test. Maybe part of perl6-bench or something like that, it's a nice small benchmark.
