### ISSUE TITLE
state scalar isn't really state if used in a trait_mod

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#2211]
## The Problem

A scalar declared with `state` in a `trait_mod` doesn't keep it's value through compilation stage. Seeming gets reinitialized on every unit compilation. For example:

stateA.pm:
```
     #no precompilation;
     unit module stateA;

     multi trait_mod:<is> ( Attribute:D $attr, :$foo ) is export {

         state Bool $touched = False;

         note "Applying";

         unless $touched {
             $touched = True;
             say "TOUCHED";
         }
     }
```

stateB.pm:
```
     unit module stateB;
     use stateA;

     class FooB is export {
         has $.bar is foo;
     }
```

state.p6:
```
     #!/usr/bin/env perl6
     use lib '.';
     use stateA;
     use stateB;

     class FooMain {
         has $.bar is foo;
     }
```

## Expected Behavior

The output is expected to be:

```
Applying
TOUCHED
Applying
```

## Actual Behavior

```
Applying
TOUCHED
Applying
TOUCHED
```
## Steps to Reproduce

The behavior is dependent on precompilation. To experience it in clear form the `.precomp` directory must be deleted prior script execution:

```
# rm -rf .precomp; ./state.p6
```

uncommenting 'no precompilation' in stateA.pm6 produces the expected output.

## Environment
* Operating system: macOS 10.13
* Compiler version (`perl6 -v`): This is Rakudo version 2018.06 built on MoarVM version 2018.06

**Comment by jnthn** [comment]
Precompilation does not preserve lexicals (except those that are closed over), and `state` is stored as a lexical. Even if we were to somehow find a way to serialize `state` variables, I don't think it'd end especially well, because consider the following separate compilation steps, each taking place in a new process (which is, in the limit, how precompilation will happen):

* A module A with a state variable initialized to S1
* A module B that uses A and changes it to S2
* A module C that uses A and changes it to S3
* A module D that uses B and C. What is the value of the state variable?

When writing trait modifiers, one is participating in the compilation process. Sometimes, that will turn out to matter.

**Comment by vrurg** [comment]
Fair enough. Would be great to have this documented though.

Anyway, closing the issue then.

**Comment by zoffixznet** [comment]
> Would be great to have this documented though.

Filed doc Issue: https://github.com/perl6/doc/issues/2262
