### ISSUE TITLE
Make `quit` work like `exit` in the REPL

### ISSUE THREAD

**Issue by sarna** [rakudo/rakudo#2214]
## The Problem
Many developers coming from other languages (eg Python, Ruby) are used to typing `quit` to exit the REPL. Currently we only support `exit`, which is fine, but making `quit` work in the same way would save some papercuts for many people who are just starting out.

## Environment
* Operating system: Ubuntu 18.04.1 LTS
* Compiler version (`perl6 -v`): `This is Rakudo version 2018.06 built on MoarVM version 2018.06
implementing Perl 6.c.`

**Comment by zoffixznet** [comment]
FWIW, `exit` is an actual Perl 6 routine to exit a program, not a special REPL command.

Somewhat related tickets: https://github.com/rakudo/rakudo/issues/1969 https://github.com/rakudo/rakudo/issues/1677

**Comment by lizmat** [comment]
Fixed with 7c75ab8e44 .  FWIW, I don't think #1969 and #1677 are really related, as they are specific to  Windows.

**Comment by sarna** [comment]
Thank you @lizmat!

**Comment by zoffixznet** [comment]
https://github.com/rakudo/rakudo/blob/7c75ab8e44986b27a814a3c73e912d3b2588bfca/src/core/Exception.pm6#L1064-L1070

**Comment by zoffixznet** [comment]
We have [a bunch of custom suggestions in `X::Undeclared::Symbols` error](https://github.com/rakudo/rakudo/blob/7c75ab8e44986b27a814a3c73e912d3b2588bfca/src/core/Exception.pm6#L1064-L1070). 

Instead of introducing special REPL commands, we could simply add a custom suggestion when the routine is `quit`

**Comment by sarna** [comment]
A custom suggestion would be nice, but it still wouldn't make lives of those with `quit` in their muscle memory any easier.

**Comment by ugexe** [comment]
Adding `quit` doesn't help those with `\q` stuck in their muscle memory.

**Comment by sarna** [comment]
Well, yeah, but `quit` is the second most popular option :) It just would be nice if it worked. Ruby works like this and people love it. But if implementing this feature is problematic, I think a custom suggestion would do just fine.

**Comment by zoffixznet** [comment]
> But if implementing this feature is problematic

It's more of: implementing all of the features to please everyone will end up in a mess.

I've just tried `python` and `irb` they don't actually tell the user they can type something to exit and in python you have to include parentheses too. Seems the "standard" exit strategy is just closing STDIN; and it's the same with us, the whole `type exit` thing works simply because the language has an actual `exit` routine:

```
$ perl6
You may want to `zef install Readline` or `zef install Linenoise` or use rlwrap for a line editor

To exit type 'exit' or '^D'
> exit 42
$ echo $?
42
```

And here's my recent sqlite session struggling to quit that features neither of those exit keywords:
```
sqlite> q
   ...> .q
   ...> ^C^C;
Error: near "q": syntax error
sqlite> ^C
sqlite> ^C^C^Czoffix@leliana~$
```



-------------------

My parting vote is to reject this Issue and not do anything :smile_cat:

**Comment by sarna** [comment]
@zoffixznet I'm convinced :)

**Comment by lizmat** [comment]
Reverted with b7190f6497

**Comment by AlexDaniel** [comment]
@lizmat But why can't we add it [here](https://github.com/rakudo/rakudo/blob/7c75ab8e44986b27a814a3c73e912d3b2588bfca/src/core/Exception.pm6#L1064-L1070)?
