### ISSUE TITLE
duration ctor or addition with duration sensitive to rat/num rand (?)

### ISSUE THREAD

**Issue by robertlemmen** [rakudo/rakudo#2221]
don't quite understand what is going on, but:

```
srand(42);

my $time = DateTime.new(1534447684).utc + Duration.new(0.002);
for ^100 -> $i {
    $time = $time + Duration.new(2.rand);
    say "$i $time";
}
```

gives me:
``` 
0 2018-08-16T19:28:04.551037Z
1 2018-08-16T19:28:05.684497Z
2 2018-08-16T19:28:07.604283Z
3 2018-08-16T19:28:07.911050Z
4 2018-08-16T19:28:09.078071Z
5 2018-08-16T19:28:09.513809Z
Type check failed in assignment to $!tai; expected Rat but got Num (1534447727.7935638e0)
  in block <unit> at ./golf line 7
```

my perl is  2018.04.1-33-ga957b712c built on MoarVM version 2018.04-39-gc702f4c66

**Comment by MasterDuke17** [comment]
committable results: https://gist.github.com/Whateverable/28d5489d61b59f9c7eca0523da462c13

**Comment by zoffixznet** [comment]
Golfs to:

```perl6
dd DateTime.new(<14324937243230497380352387879/9335565490898839500>) + Duration.new(<1043/815>)
```

Addition of two `Rat`s degrades (by design) to a `Num` if the resultant denominator would be over 64 bits (after reduction):

```perl6
    dd <14324937243230497380352387879/9335565490898839500> + <1043/815>;
    # 1534447727.7935638e0
```

And what's happening here is the addition actually produces such a `Rat`, and we end up with an attempt to assign a `Num` into a ` Rat` attribute (the `$.tai`). 

One possible fix would be to use `Rat.new` with the summed up numerators denominators, because `Rat.new` allows "overloaded" denominators that are larger than 64 bits and it won't degrade to a `Num`. However, we still end up with `.tai` that contains a `Rat` that'd degrade  to a `Num` in math operators, so perhaps that's a bad idea.

```perl6
my $a := <14324937243230497380352387879/9335565490898839500>;
my $b := <1043/815>;
dd Rat.new: $a.numerator + $b.numerator, $a.denominator + $b.denominator;
# <14324937243230497380352388922/9335565490898840315>
```

The other fix would be to have all the `.tai` operations coerce to a `.Rat`, so we force the `Num` back to a `Rat`, but that's losing some precision due to this roundtrip.

Haven't thought about this much, so there might be much better solutions available.

**Comment by lizmat** [comment]
Appears fixed, test added with https://github.com/Raku/roast/commit/b79213fe17
