### ISSUE TITLE
Rerevert “Throws X::Multi::NoMatch if a proto routine is defined without multis”

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2227]
Discussion: https://github.com/rakudo/rakudo/pull/1868#issuecomment-413386084

**Comment by AlexDaniel** [comment]
I reverted the commit for now because I don't know what would be the rightest solution. Please feel to rerevert once a fix for roast is ready.

Ping @jsimonet @timo @zoffixznet.

**Comment by zoffixznet** [comment]
@AlexDaniel which test was failing? 

The PR was not merged by mistake, but it did reveal a previously hidden bug: https://github.com/rakudo/rakudo/issues/2216

**Comment by AlexDaniel** [comment]
@zoffixznet This one: https://github.com/perl6/roast/blob/894a56c87b208d8e5017150eeac4bf142c03cf5e/S32-exceptions/misc.t#L48

**Comment by zoffixznet** [comment]
Weird. It exists on master too, but I thought the spectest was passing for the PR.

I'm not sure, but the optimizer might be already too late a place to use lang-version-specific behaviours with [our current means](https://github.com/rakudo/rakudo/blob/5af3c5011946db73a43afea2dfe8d11d11413dcf/src/Perl6/World.nqp#L485-L493).

But if we can leave the old behaviour in 6.c, then for 6.d, I'd propose moving this test to spec [APPENDICES](https://github.com/perl6/roast/tree/master/APPENDICES), because I'd guess not all implementations would want/be able to examine all the candidates and check if we only got the proto.

**Comment by jsimonet** [comment]
If you change the `Str` type to an `Int`, the generated exception is the same but without the signature proposition.
```
perl6 -e 'proto sub foo(Int) {*}; foo 42;'
===SORRY!=== Error while compiling -e
Calling foo(Int) will never work with declared signature 
at -e:1
------> proto sub foo(Int) {*}; ⏏foo 42;
```

I changed the exception because to me, it's not a `X::TypeCheck::Argument` exception.
