### ISSUE TITLE
What should the * twigil do as a parameter?

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2276]
Pointed at by #2275, it appears that this code is legal:

    sub a($*a) { dd $*a.VAR.dynamic };
    a 42  # Bool::False

Discussion: http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-09-14#l144

One assumption was that inside `sub a`, `$*a` should act as a dynamic variable.  That would be nice.  Perhaps that could be as simple as marking the Scalar as "dynamic" ?

Other approach could be that this should not be allowed.

Perhaps other opinions about this?  Or is there something in the spec that I've missed?

**Comment by lizmat** [comment]
FWIW, the specs state in S02-bits:

> Names may also be declared in the signature of a function.  These are
> equivalent to a C<my> declaration inside the block of the function, except
> that such parameters default to readonly.

**Comment by jnthn** [comment]
Not only legal, but used, even in the Perl 6 grammar itself. :-)

Dynamic variables are just lexicals that can be looked up along the dynamic chain (that is, callers). In storage, they're just ordinary lexicals, however, so the code we generate to bind them in signatures is identical.

Everything declared with the `*` twigil is implicitly dynamic. The whole `.dynamic` introspection is very dubious, because something like `my $*foo := 42` is clearly dynamic, but `42` is just an `Int`. It's a property of "the variable", except that concept doesn't really exist by runtime.  So the rules for whats available as a dynamic are effectively:

* `$/`, `$!`, and (6.c only) `$_`
* Anything with the `*` twigil
* Anything with a container bound that claims to be `dynamic`

But only the last one is reliably introspectable with `.dynamic`. Question is if we can provide a reliable mechanism for this, and if so, what it looks like.

**Comment by lizmat** [comment]
Ah, indeed:

    $ 6 'sub a($*a) { dd $*a.VAR.dynamic; b }; sub b() { dd $*a }; a 42'
    Bool::False
    42

Turns out that adding `is copy` makes the introspection work properly.

    $ 6 'sub a($*a is copy) { dd $*a.VAR.dynamic; b }; sub b() { dd $*a }; a 42'
    Bool::True
    Int $*a = 42

**Comment by jnthn** [comment]
Yes, the `is copy` forces there to be a `Scalar` container there, but we shouldn't force that on all parameters.

**Comment by lizmat** [comment]
Ok, so the only issue appears to be that you cannot introspect a parameter that is not `is copy` this way.  Closing this now.

**Comment by jnthn** [comment]
Do we have any spectests covering that a `sub foo($*a) { }` works, by the way?

**Comment by lizmat** [comment]
Could't find any, so I added some: https://github.com/perl6/roast/commit/d3ad9146ad
