### ISSUE TITLE
Missing API functionality on Array

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2288]
Having just tried to take implementing my own version of `Array`s to the extreme, while using the `Positional` and `Array` API  [Array::Agnostic](https://modules.perl6.org/dist/Array::Agnostic:cpan:ELIZABETH) and [Array::Sparse](https://modules.perl6.org/dist/Array::Sparse:cpan:ELIZABETH)) I really found some functionality missing in the `Array` API:

- CLEAR
A method to be called whenever the underlying structure should be reset.  Typically called from `STORE`, but other uses might be possible.  Without such a method, the only way to clear the underlying data-structure, is to call `DELETE-POS` on all elements.  Which sucks.

- :existing
The `:v` functionality on zen-slice should be a abstracted into a named parameter (proposal: `:existing`) for the `.values`, `.keys`, `.kv`, and `.pairs` methods.

If no-one objects, I will implement / document / test these features after the 2018.09 release.

**Comment by jnthn** [comment]
I don't get the need for `CLEAR`; it's just spelled `STORE(Empty)`, or `STORE(())`. And a custom array type probably needs to implement `STORE` anyway?

**Comment by zoffixznet** [comment]
> CLEAR

FWIW, there was a short related discussion for `.clear` method here: https://github.com/perl6/6.d-prep/issues/6

> The :v functionality on zen-slice should be a abstracted into a named parameter (proposal: :existing) for the .values, .keys, .kv, and .pairs methods.

I'm always a bit weary of mass-extending of arguments. How much benefit would that provide to `Array`-implementors? Unless it's something huge, I feel like we shouldn't be adding more arguments to things. We're already known as the "big" language. We shouldn't be making it even bigger willy-nilly.

The methods you listed would also create an inconsistency in `.antipairs`, `.head`, `.squish`, `.rotor`, `.map`, `.grep`; and well, probably all the methods that don't ignore holes. Why do the four methods you listed get special treatment and get an `:existing` named arg, but the rest of the methods don't? This is especially bad because unsupported named args in methods are ignored, so a user writing `.antipairs: :existing` might have a bug in their code and not know it until they come across an array with a hole in it.

**Comment by lizmat** [comment]
@jnthn: re `CLEAR`, fair enough, I'll just keep it part of the `Array::Agnostic` API, which implements a `STORE` for consumers, so they don't have to.

**Comment by lizmat** [comment]
Thinking about this more, I think I'll just implement / document :existing for `Array::Sparse`, or possibly always the standard methods only use existing elements.

So closing this now, thanks for the feedback, sorry for the noise.
