### ISSUE TITLE
Anon state vars don't work as return value for `is rw` subs

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2372]
I was expecting these two forms to be equivalent in this case, but they aren't:
```
<Zoffix_> m: sub term:<🤔> is rw { state $x = 1; $x }; 🤔++; say 🤔
<camelia> rakudo-moar 00cb3315c: OUTPUT: «2␤»


<Zoffix_> m: sub term:<🤔> is rw { $ = 1 }; 🤔++; say 🤔
<camelia> rakudo-moar 00cb3315c: OUTPUT: «1␤»
<Zoffix_> m: sub term:<🤔> is rw { $ }; 🤔++; say 🤔
<camelia> rakudo-moar 00cb3315c: OUTPUT: «1␤»
```

Is this a bug or is this just a subtle difference between `state` and anon state vars?

**Comment by jnthn** [comment]
It's not even a difference between the vars, but rather than the `=` in any declaration has semantics dependent on the declarator, rather than being a straight assignment operator. The semantics of `=` in a declaration like `state $x = 1` are to only run the assignment on the first time the current closure clone is entered. (Note how `has` semantics are "run it per object created", and with `constant` the `=` actually means binding rather than assignment.)

By contrast, the `=` in `$ = 1` is a straight assignment. It's more like `(state $x) = 1`.
