### ISSUE TITLE
`return`-ing out of a block and LEAVE phaser (“identity”‽)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2380]
Code:
```perl6
sub bar(&some-code) {
    LEAVE { say ‘left’ };
    some-code()
};
sub foo {
    bar { return 42 } # this is a block of code that `return`s from `foo` but is executed in `bar`
};

for ^2 { say foo }
```

Output on all releases:
```
¦«2016.01.1,2016.02,2016.03,2016.04,2016.05»:
left
42
left
42

¦«2016.06,2016.07.1,2016.08.1,2016.09,2016.10,2016.11,2016.12,2017.01,
  2017.02,2017.03,2017.04.3,2017.05,2017.06,2017.07,2017.08,2017.09,
  2017.10,2017.11»:
left
0
left
42

¦«2017.12,2018.01,2018.02.1,2018.03,2018.04.1,2018.05,2018.06»:
left
1
left
42

¦«2018.08,2018.09,HEAD(e1ebffe)»:
left
identity
left
42
```

I was expecting `left 42 left 42` or possibly an error saying that I can't do that.

**Comment by AlexDaniel** [comment]
I don't know if this should be a blocker or not, but I added a label to make sure I take a look again.

**Comment by AlexDaniel** [comment]
Removing the label because it seems like we had this issue for quite a while.

**Comment by AlexDaniel** [comment]
> \# this is a block of code that `return`s from `foo` but is executed in `bar`

Is it actually what it should mean? Or should `return` always return from the outer sub? I'm confused reading my own ticket.

**Comment by jnthn** [comment]
The `return` applies to the nearest *lexical* routine, so in this case its target is `foo`.

**Comment by vrurg** [comment]
I think I got into the vary same bug. Though in my case things are slightly more complicated and it gets triggered only as a result of combination of factors: exception, `LEAVE` with a loop, `CATCH` with return:

     sub bar ( $v ) {
         die "don't like it" if $v == 3;
         LEAVE {
             note "LEAVE";
             (1..2).map: { "ok" }
         };
         "[" ~ $v ~ "]"
     }

     sub foo ( $v ) {
         my $str = bar( $v );
         CATCH {
             note "CATCH";
             default {
                 return "«oops»";
             }
         }
         $str
     }

     sub foobar {
         return [~] (1..10).map: {
             note "---";
             foo( $_ );
         };
     }

     say foobar;

In this form this script outputs:

>`[1][2]1[4][5][6][7][8][9][10]`

instead of

>`[1][2]«oops»[4][5][6][7][8][9][10]`

A couple of remarks which hopefully would help in smashing the bug:

1. Replacing `.map` in `LEAVE' with a `for` loop fixes this script.

   Though I wasn't that lucky with my real code where I had to replace 'LEAVE' with more complex code involving 'CATCH` and `.rethrow`. Commenting out all looping works around the bug in the real code too.

2. In the sample code `LEAVE` and `CATCH` report about themselves. This way I discovered an oddity about the order of execution because `CATCH` is run _before_ `LEAVE`. To my view it's absolutely contra-intuitive as it goes against both stack- and lexical-wise relations between `foo()` and `bar()`. 

   I would cautiously assume that this order could be related to the cause of the bug: in some way `LEAVE` operates on a wrong stack frame, damaging the return value from another block belonging to that very frame.

**Comment by dakkar** [comment]
Possibly related:
```perl6
sub foo() {
    do {
        my IO::Handle $h = $?FILE.IO.open();
        LEAVE { .close with $h};
        return 1;
    }
}

sub bar() {
    my IO::Handle $h = $?FILE.IO.open();
    LEAVE { .close with $h};
    return 1;
}

say foo();
say bar();
```

produces:
```
The 'ForeignCode' class is a Rakudo-specific
implementation detail and has no serviceable parts inside
1
```

To me, it looks like the `LEAVE` inside the `do` block leaks into the return value *somehow*.

**Comment by dakkar** [comment]
Simpler (there's no need for `IO::Handle`):
```perl6
sub thing() { return 5 }

sub foo() {
    do {
        LEAVE { thing() };
        return 1;
    }
}

sub bar() {
    LEAVE { thing() };
    return 1;
}

say foo();
say bar();
```

this, on Rakudo 2019.11, prints:
```
5
1
```

**Comment by dakkar** [comment]
Voldenet on IRC noticed that:
```perl6
sub foo() {
    do {
        LEAVE { thing() };
        1;
    }
}
```
returns 1. So `LEAVE` interferes with an explicit `return` out of its block?

**Comment by AlexDaniel** [comment]
It changed a bit: https://gist.github.com/437bc3541029c32c559c89888d2ff9ba

```
¦«2019.03.1,2019.07.1,2019.11,2020.01,2020.02.1,HEAD(9429728)»:
left
The 'ForeignCode' class is a Rakudo-specific
implementation detail and has no serviceable parts inside
left
42
```

Bisected: (2018-12-31) https://github.com/rakudo/rakudo/commit/588037f065b7a6afa7f50263e474abc9170af9e7

@dakkar++, @patrickbkr++

**Comment by patrickbkr** [comment]
I guess it's the same issue, so I comment here instead of creating a new one:

On 2020.02.1:

    sub m() { { return 5; LEAVE {say 'L'} } }; say m();

Results in:

    L
    The 'ForeignCode' class is a Rakudo-specific␤implementation detail and has no serviceable parts inside

This only happens with the `LEAVE` phaser. `CATCH` works fine. Also this does *not* happen when executing the code in the REPL.

Here is a list of the output of different versions that shows in what steps the output broke over time:

https://gist.github.com/Whateverable/77da4633c3494bfd4383803b46f04b69

Bisect of when this moved from returning the wrong result to returning an error:

https://gist.github.com/Whateverable/3b7acf6615179b5d22afb1cbf3a47e7d

Offending commit: https://github.com/rakudo/rakudo/commit/8d6527617dc3aea81a3d6e3f47575c6b7f7d03f1

**Comment by lizmat** [comment]
This appears fixed, tests added with https://github.com/Raku/roast/commit/c3e2e7685b
