### ISSUE TITLE
CompUnit...load($key, :since($instant)) not working

### ISSUE THREAD

**Issue by finanalyst** [rakudo/rakudo#2428]
## The Problem
An attempt to get a Nil handle fails.  
I understood the following code should return a Nil handle if the instant in `:since` is later than the time of the precompilation
```
my $handle = $precomp.load($id, :since($io.modified))[0];
```
## Expected Behavior
If `$io` refers to a path to a file and the file has been modified since the last precompilation, then the `$handle` is Nil.

## Actual Behavior
The value of the handle is not affected by the value of `:since`

### In test-comp.p6
```
use v6.c;
use nqp;
my $precomp-store = CompUnit::PrecompilationStore::File.new(prefix=>'cache'.IO);
my $precomp = CompUnit::PrecompilationRepository::Default.new(store=> $precomp-store );
my $key = nqp::sha1('test.pod6');
'test.pod6'.IO.spurt(q:to/--END--/);
=begin pod
=TITLE More and more
 
Some text
 
=end pod
--END--
$precomp.precompile('test.pod6'.IO, $key, :force);
my $mod1 = 'test.pod6'.IO.modified;
my $handle = $precomp.load( $key )[0];
my $resurrected = nqp::atkey($handle.unit,'$=pod')[0];
say $resurrected ~~ Pod::Block::Named;
'test.pod6'.IO.spurt(q:to/--END--/);
=begin pod
=TITLE More and more
 
Some more text added
 
=end pod
--END--
say "modified first: " ~ $mod1;
say "modified next: " ~ 'test.pod6'.IO.modified;
my $new-handle = $precomp.load($key, :since('test.pod6'.IO.modified))[0];
with $new-handle { say 'new-handle exists'} else { say 'no new-handle'};
put $handle;
put $new-handle;
``` 
 
### Output is
```
$ perl6 comp-test.p6
True
modified first: Instant:1540539480.589026
modified next: Instant:1540539480.689027
new-handle exists
CompUnit::Handle<140206592874160>
CompUnit::Handle<140206592874160>
```
## Environment
* Operating system (`uname -a`): Linux merlin 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`perl6 -v`): This is Rakudo Star version 2018.06 built on MoarVM version 2018.06
implementing Perl 6.c.

**Comment by ugexe** [comment]
You've already precompiled a unit by the same name, so whatever you get for the first result you will continue to get.

https://github.com/rakudo/rakudo/blob/e0633a0de9156a01a3b02d92d01d693af59e5797/src/core/CompUnit/PrecompilationRepository.pm6#L177-L186

**Comment by finanalyst** [comment]
So what is the purpose of :since?
In `pod2onepage` which is in the rakudo bin directory, there is the line
```
            my $handle = $precomp.load($id, :since($io.modified))[0];
```
It seems from the code that the cache should be renewed if the file has been modified since it was cached. I am trying to do exactly the same thing: trying to discover whether the cache was before or after the modification instant of the file.

I also tested to see whether adding `sleep(2)` between the cache and the request for a handle. The thought was that the :since argument is coerced to an integer, meaning seconds, and that my test code was failing because it was happening too quickly after the code had been cached. Same result. :since appears to have no effect.

**Comment by niner** [comment]
The whole precompilation infrastructure was written with loading code in mind. In that scenario it usually wouldn't be a good idea to load different versions of a module just because it got updated in between compilation of `use` statements. Our users's code will in general not be prepared for that. Besides checking the file system every time would be quite costly in terms of performance. So we rely heavily on in-process caches.

What we do check however is of course the on-disk cache the first time we need to load a certain module during a process' lifetime. That's where :since comes in. Or to be more precise, came in. Since timestamps have a couple of drawbacks like 2 second granularity on FAT32, we don't use them anymore and rely solely on sha1 checksums of source code instead. $since is left because it's party of a published API and is used by several POD related tools.

Right now I don't have a good idea for when you do want to pick up changes even within runtime of a process. But I'm not even through my first coffee today, so there's still hope...

**Comment by finanalyst** [comment]
@niner Thanks. My test, and the responses here, indicate that the value provided via `:since` does not seem to be taken into account.  
I am developing a pod caching system for the documentation suite. There is no need for in-process updating, but updates are common between caching runs. It's actually easier to trap the time when a new file is added to cache and store that, than to query the cache.

Now I am looking for a way to remove code from a cache given only the sha1 key of the file name.

**Comment by ugexe** [comment]
It has already been loaded once and keyed on an id that is being reused to reload it -- it will never reach any :$checksum logic for the same reason it doesn't reach :$since logic. But this also consistent with how the other core CURs work:

https://github.com/rakudo/rakudo/blob/1c1527f42609e13f7929e21648bde832780cf1d1/src/core/CompUnit/Repository/FileSystem.pm6#L159-L168

https://github.com/rakudo/rakudo/blob/1c1527f42609e13f7929e21648bde832780cf1d1/src/core/CompUnit/Repository/Installation.pm6#L502-L510

https://github.com/rakudo/rakudo/blob/1c1527f42609e13f7929e21648bde832780cf1d1/src/core/CompUnit/Repository/AbsolutePath.pm6#L12-L20

**Comment by JJ** [comment]
I would say this is solved?
