### ISSUE TITLE
Custom .new method is not reflected in standard .perl

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2448]
class Point {
        has $.x;
        has $.y;
        method new($x,$y) {
            self.bless(:$x,:$y)
        }
    }
    say Point.new(42,66).perl  # Point.new(x => 42, y => 66)

The standard .perl should probably look at the signature of the .new method, then look for positional parameters and see if the names match with any attribute names.  So that:

    say Point.new(42,66).perl  # Point.new(42,66)

**Comment by zoffixznet** [comment]
> signature of the .new method ... and see if the names match with any attribute names.

That sounds extremely fragile. Even with a basic signature, consider:

```perl6
    method new($x,$y) {
        self.bless: :x($x+42),:y($x*100-$y)
    }
```

I think https://github.com/rakudo/rakudo/commit/adc9683773 that makes default `.perl` create a stub is a great solution to the OP problem, unfortunately, it creates at least two more:

1. `&infix:<eqv>` uses `.perl` and now it gives `True` for any two instances of a class that has custom `.new`. Filed as https://github.com/rakudo/rakudo/issues/2449
2. `Mu.gist` uses `.perl` and now it gives fairly useless information, while in the past it gave you a snapshot of attribute values, even if the `.new` call the information was presented in was bogus. Personally, I use `dd` instead of `say` for debugging, so it's mildly annoying to have that debugging aid now effectively broken, but if `.gist` shows the same information too, that means to dump the guts of a custom class you now have to implement your own `.perl` and presumably list all the used attributes in that implementation.

**Comment by lizmat** [comment]
Part 2 of this should fix this.  Working on that now

**Comment by jnthn** [comment]
As a follow-up to my earlier suggestion about `bless`, I think maybe best is:

* If there's no custom `new` then do what we already were doing
* If not, then make it use `bless` instead of `new`

That still stands a decent chance of round-tripping when the constructor was simply used to make positionals into nameds.

**Comment by zoffixznet** [comment]
> That still stands a decent chance of round-tripping when the constructor was simply used to make positionals into nameds.

(as discussed in https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-10-31#l276 )

That doesn't cover all the cases though, and in the remaining cases you get bizarre errors and only-partially initialized objects, causing potentially bug-at-a-distance problems in user's code.

IMO the stub saying custom `new` is in use + params dump is the best option. I rather the code dies right away and tells me to implement a `.perl` instead of it having it maybe do the right thing and a chance to fail in unpredictable ways.

Even looking at core code, `Failure.new(...).perl.EVAL` already crashes with a strange error and we have a gazillion iterators that do `!SET-SELF(...)` on private attributes inside `.new`.

**Comment by lizmat** [comment]
I will look at making it work right for custom new if the number of parameters in .new matches the public attributes.  Any diversion from that will cause an execution error telling to create your own .perl method.  Is that a plan?

**Comment by lizmat** [comment]
Now I'm confused.  So what is the problem with using "bless" then if there is a custom "new" ?

**Comment by jnthn** [comment]
> Any diversion from that will cause an execution error 

Note that a large number of uses of `.perl` - probably the majority - are for debug output, *not* for data structure serialization. An error is too harsh for that case.

**Comment by lizmat** [comment]
So just doing the best we can, and then a ... so it will bomb when actually EVALled ?

**Comment by lizmat** [comment]
BTW, even if there is no custom "new" method, then we cannot be sure it will roundtrip.  For instance, if we have a method TWEAK:

    $ 6 'class A { has $.a; method TWEAK() { $!a = !$!a } }; say A.new(:a).perl'
    A.new(a => Bool::False)
    $ 6 'class A { has $.a; method TWEAK() { $!a = !$!a } }; say A.new(:a).perl.EVAL.perl'
    A.new(a => Bool::True)
