### ISSUE TITLE
Would be nice to have a |Z operator

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2465]
(1,2,3) |Z (4,5,6)   # should return (1,4,2,5,3,6).Seq

**Comment by zoffixznet** [comment]
`flat`?

On its own, that feels like a strange wart on the language's landscape, considering `|` is a prefix op.

Are there other prefixes that would make sense to be used on the result of the metaop?

**Comment by jnthn** [comment]
We never try to parse an infix and prefix at the same time, so there'd be no formal ambiguity in having an infix operator called `|Z`. But of course, many things are possible, but not all are wise.

I'm half-hearted about the idea. I can see the use of it, but this only feels useful on `Z` itself, not on any of the other meta-forms of `Z`, so this doesn't seem to generalize well.

I don't think this is common enough to complain that `flat (1,2,3) Z (4,5,6)` is too much to type, especially because if you're typing that you've already spent 4 characters too many on superstitious parentheses anyway (`flat 1,2,3 Z 4,5,6` works just the same).

**Comment by lizmat** [comment]
The reason I think the functionality would be nice, is in that you could do:

    for @a |Z @b |Z @c -> $one,$two,$three {   # @a stands for any (complicated) Iterable / Seq
    }

and handle each "zip" separately without needing to create intermediate lists

**Comment by zoffixznet** [comment]
https://colabti.org/irclogger/irclogger_log/perl6?date=2018-11-03#l423


> \<TimToady\> ~/me agrees that \|Z is problematically ambiguous with lots of other infixes, and notes that he was reserving F in his head for a generalized flattening metaop, in the absence of any better suggestion
\<jmerelo\> TimToady: why not _? As in, well, flattening to the ground
\<TimToady\> yes, _ is another possibility that I've considered, and could yet settle on, if we decide that flat() is inadequate

**Comment by lizmat** [comment]
FWIW, /me likes `F`
