### ISSUE TITLE
Make "Malformed double closure" a warning

### ISSUE THREAD

**Issue by nwellnhof** [rakudo/rakudo#2487]
I'm seeing:

    say { * + $_ }(2)(5);        # 7
    say -> $n { * + $n }(2)(5);  # 7
    say { * + @_[0] }(2)(5);     # Malformed double closure
    say { * + $^n }(2)(5);       # Malformed double closure

AFAICS, there's nothing wrong with double closures if that's really your intention. So shouldn't it be a warning instead of an error?

**Comment by AlexDaniel** [comment]
Added `useless useless` label because it's the closest one I could find.

**Comment by AlexDaniel** [comment]
FWIW I think this issue is low priority. It'd be nice to have a justification on why this particular code gives an error instead of a warning, but generally users are unlikely to write something like this on purpose. One place where this may be useful is code golf, but that by itself is not a good argument.

**Comment by nwellnhof** [comment]
> FWIW I think this issue is low priority.

Fair enough.
