### ISSUE TITLE
LTA $! variable is not set on failure for file open / create operations

### ISSUE THREAD

**Issue by thundergnat** [rakudo/rakudo#2491]
## The Problem

File open / create operations do not set the error variable `$!` on failure despite long history in the Perl5 culture and implying that it does in various places in the docs.

`my $fh = open('./bogus/directory/file.txt', :r) or die $!;`

should die with:  '**No such file or directory  in block _whatever_ at line _whatever_**'

Instead it dies with ' **in block _whatever_ at line _whatever_**', because $! wasn't set.

At the very least, the docs are misleading and lacking. They state that "$! is the 'error variable...  failures outside a CATCH block set $!" and that failed file IO operation return a failure, with the strong implication that one follows the other

It **is** possible to catch and report errors now. Either: 

`my $fh = open('./bogus/directory/file.txt', :r) or die $fh;`

or

`my $fh = open('./bogus/directory/file.txt', :r) orelse die $_`

will report the failure; but it is extremely jarring to someone coming from a long perl5 background that $! is not set.  I probably have at least 50 scripts, some in the wild (on RosettaCode), that are erroneously using $! to report file handle errors. I guess I have just been very lucky up to this point and never had any failures before.

If it is decided the this is NOTABUG. I will submit changes to the docs documenting the actual behavior.  At the very least, the Perl5 to Perl6 docs will need some verbiage. I plan to anyway because there isn't anything documenting file operation failure handling right now, I just don't want to document current behavior if it is in error.

**Comment by zoffixznet** [comment]
> If it is decided the this is NOTABUG.

Yes, it's definitely not a bug. Unlike other languages like Perl 5, our IO system (and many other language components) use the `Failure` mechanism instead of `$!` variable.

You showed two examples where you get the desired output, but by-design those aren't needed. There's no explicit error detection required and you just write:

```perl6
my $fh = open('./bogus/directory/file.txt', :r)
```

Now, if that open did in fact fail, the first attempt to use that `IO::Handle` will actually cause the same error to be thrown that you get with your explicit die version:

```perl6
$ perl6 -e '
my $fh = open("./bogus/directory/file.txt", :r);  # does not throw; gives Failure
$fh.get.say # trying to call a method on Failure blows it up.
'
Failed to open file /home/zoffix/bogus/directory/file.txt: No such file or directory
  in block <unit> at -e line 1
```

That's how you're meant to use the IO facilities, but say the code is more complicated and you want to ensure that any failures blow up sooner rather than later. You have to facilities to accomplish that. First, you can call `.self` method. That method exists on all objects and will just return the value itself without doing anything. On `Failure` values however, it will cause the failure to explode, just like calling most other methods on failure would:

```perl6
my $fh = open('./bogus/directory/file.txt', :r).self # throws
```

You can also use the `use fatal` pragma. It's a lexical pragma that automatically fatalizes Failures, so your code would throw right away:

```perl6
use fatal;
my $fh = open('./bogus/directory/file.txt', :r); # throws

**Comment by thundergnat** [comment]
Ok, I'll look into updating the docs a bit. 

> Now, if that open did in fact fail, the first attempt to use that IO::Handle will actually cause the same error to be thrown that you get with your explicit die version:

The actual code that caught me out was:

```
my $fh = open('bad/filename.txt', :w);
$fh.print: 'Whatever';
```
Which fails with "Too many positionals passed: expected 1 but got 2"

Which certainly is a failure, but wasn't very helpful.

**Comment by zoffixznet** [comment]
> Which certainly is a failure, but wasn't very helpful.

I filed that as a separate Issue: https://github.com/rakudo/rakudo/issues/2492

**Comment by thundergnat** [comment]
Zoffix++ for very clear explanations. (And everything else you do.)

On a somewhat tangential note: What actually _does_ set $! ? On a fairly close examination of the docs, I can't really find anyplace where it states that $! is definitely set. There are several places that vaguely suggest that there _are_  operations that set it, but I can't find anything concrete.  It seems like a similar situation to the file / IO operations.

Does Perl 6 even use or need $! ? Should it be deprecated and removed?

**Comment by zoffixznet** [comment]
> What actually does set $! ?

Good question that perhaps warrants another issue to examine.

For example, intuitively I'd say the `$!` is set to the most recent thrown exceptions (it's not set in IO operations, because no exceptions are thrown and Failure mechanism is used).

However, I have a hard time refining that description of `$!`. For example, I wanted to say it's the most recent exception in this *lexical scope*. However, that's not the case in this code, where throwage is inside a block, yet `$!` is still set:

```
$ perl6 -e '{ try die }; say $!.^name'
X::AdHoc
```

The same is not the case if you switch up to a sub instead of a block though:

```
$ perl6 -e 'sub foo { try die }(); say $!.^name'
Nil
```

And I can imagine that has to do with the same reasons of why you can `return` from a sub but not a block, but someone else can probably formulate a much better description of how and when `$!` is set.

**Comment by thundergnat** [comment]
Documentation added to 5to6nutshell
