### ISSUE TITLE
No such method 'payload' for invocant of type 'X::Parameter::InvalidConcreteness'

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#2531]
## The Problem

2018.11 regression causes the error "No such method 'payload' for invocant of type 'X::Parameter::InvalidConcreteness'" when `zef` encounters any dependency in the format e.g. `openssl:from<native>`

## Steps to Reproduce

```
$ perl6 -e 'use NativeCall; try sub :: is native(sub{ $*VM.platform-library-name("openssl".IO).basename }){}(); $!.payload'
No such method 'payload' for invocant of type 'X::Parameter::InvalidConcreteness'
  in block <unit> at -e line 1
```

Caused by one of:
https://github.com/rakudo/rakudo/commit/edc4c0547fb5c8bd7361aca06c2c34ae15a80ac6
https://github.com/rakudo/rakudo/commit/6aafe18d5544f9fbc9f75b6cc5a9f85d5d1fe7b2
https://github.com/rakudo/rakudo/commit/f8be2fa0671a27adc078cde82e355cbb6564e26a
https://github.com/rakudo/rakudo/commit/656a80457c15720b746157ee049eb9c699915ae7
https://github.com/rakudo/rakudo/commit/09cceb9826a8b20e7492ae79b5bdd6dede6881e6
https://github.com/rakudo/rakudo/commit/bb43acdb75f3ab7ed0bba22c1102fe254788db9d

**Comment by niner** [comment]
The reason is this optimization: https://github.com/perl6/nqp/commit/a20a0a14a8c12ae0cabb883f10026c883edf6a91

Basically this makes us compile an invoke_v op when the return value of a method is not being used anyway. The same optimization existed for call and I took the opportunity to do the same for callmethod.

How this can cause the mentioned error is still a mystery though.

**Comment by AlexDaniel** [comment]
@niner any thoughts on what should be done with this in terms of the upcoming release?

**Comment by niner** [comment]
@AlexDaniel yeah, unless we find out how exactly this case breaks, we should just revert that optimization.
