### ISSUE TITLE
Should =~ be a warning rather than an error?

### ISSUE THREAD

**Issue by GuyJoKing** [rakudo/rakudo#2556]
In some cases, when you have a `~` right after a `=` in your code, there's a error. For example, `my $a=1;$a=~$a` results in:

```Error while compiling - Unsupported use of =~ to do pattern matching; in Perl 6 please use ~~```

Is there a reason this is a full on error, rather than a warning? Especially for someone who has only worked with Perl 6 and doesn't know what `=~` has to do with pattern matching.

**Comment by AlexDaniel** [comment]
It can be an error, personally I don't care about that. But it should be hidden under `use training-wheels <perl5>`.

**Comment by lizmat** [comment]
It's already covered by `use isms <Perl5>', but there seems to be a bug in the grammar handling:

    $ perl6 -e 'use isms <Perl5>; my $a=1; $a=~$a'
    ===SORRY!===
    This representation (P6int) does not support attribute storage (for type BOOTInt)

which goes deep into the bowels of NQP  :-(

**Comment by lizmat** [comment]
Added `infix:<=~>` with df748ea76f .  If the entire `<.obs('=~ to do pattern matching', '~~')>` is taken out of the grammar, it becomes clear that we actually need that because otherwise the optimizer stage starts complaining.

So it appears that somehow the return from `<.obs('=~ to do pattern matching', '~~')>` causes some internal issues, that in turn cause the `This representation (P6int) does not support attribute storage (for type BOOTInt)` error.

**Comment by lizmat** [comment]
This appears to be a generic issue with the use of `<.obs>`:

    $ perl6 -e 'use isms <Perl5>; foreach 1,2,3 { }'
    ===SORRY!===
    This representation (P6int) does not support attribute storage (for type BOOTInt)

**Comment by lizmat** [comment]
Fixed with af868f8470

**Comment by lizmat** [comment]
tests added with https://github.com/perl6/roast/commit/4cbeca811f , tests run with c9fe9463e6
