### ISSUE TITLE
SIGFPE when rounding a 0/0 Rat

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2569]
Code:
```perl6
say <0/0>.round
```
Result:
```
(signal FPE)
```

It used to die correctly with:
```
Attempt to divide by zero using div
    in block <unit> at /tmp/eqvUfDh3Xy line 1
```

Bisected: (2018-07-31) https://github.com/rakudo/rakudo/commit/097826ef7bd985e4febdb106d7a6fa7dfa4fc5d7

**Comment by lizmat** [comment]
Fixed with 11da0fb489 .

**Comment by zoffixznet** [comment]
FYI, there was a very similar bug involving the same NQP ops in [R#2280](https://github.com/rakudo/rakudo/issues/2280).

That was fixed by https://github.com/MoarVM/MoarVM/commit/ad3a80cb6e615b191b741a311616e00a4a2d3f12 . Perhaps that fix missed some case that is causing this bug? The commit message has details on what was going on.

**Comment by lizmat** [comment]
Added test with https://github.com/perl6/roast/commit/38beb38576
