### ISSUE TITLE
Is the dynamic variable $*FULL-PRECISION a good solution to Rat -> float/FatRat discussion?

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2580]
The following code will no longer upgrade `Rat`s to `Num`s, but instead to `FatRat`s.

    diff --git a/src/core/Rat.pm6 b/src/core/Rat.pm6
    index 42c5850..b04f087 100644
    --- a/src/core/Rat.pm6
    +++ b/src/core/Rat.pm6
    @@ -70,19 +70,21 @@ sub DIVIDE_NUMBERS(Int:D \nu, Int:D \de, \t1, \t2) {
     # For such cases, we can use this routine, to bypass normalization step,
     # which would be useless.
     sub RAKUDO_INTERNAL_DIVIDE_NUMBERS_NO_NORMALIZE(\nu, \de, \t1, \t2) {
    -    nqp::if(
    -      nqp::istype(t1, FatRat) || nqp::istype(t2, FatRat),
    +    nqp::stmts(
    +      (my \type := nqp::if(
    +        nqp::istype(t1, FatRat)
    +          || nqp::istype(t2, FatRat)
    +          || nqp::isge_I(de, UINT64_UPPER),
    +        FatRat,
    +        Rat
    +      )),
           nqp::p6bindattrinvres(
    -        nqp::p6bindattrinvres(nqp::create(FatRat),
    -          FatRat,'$!numerator',nu),
    -        FatRat,'$!denominator',de),
    -      nqp::if(
    -        nqp::islt_I(de, UINT64_UPPER),
    -        nqp::p6bindattrinvres(
    -          nqp::p6bindattrinvres(nqp::create(Rat),
    -            Rat,'$!numerator',nu),
    -          Rat,'$!denominator',de),
    -        nqp::p6box_n(nqp::div_In(nu, de))))
    +        nqp::p6bindattrinvres(nqp::create(type),type,'$!numerator',nu),
    +        type,
    +        '$!denominator',
    +        de
    +      )
    +    )
     }
 
The fallout in the spectests is rather small.  Since this is one of the major disappointments for people using Perl 6 because of the `Rat`'s, it feels to me that this should be considered, perhaps (de-)activatable by a pragma / DYNAMIC var?

**Comment by MattOates** [comment]
Coming from a scientific programming background I can 100% support this as much more desirable behaviour. I'd prefer to have an out of memory error when I expected Rat like behaviour than floating point errors *sometimes* when running some code. Especially as the sorts of operations where you might get FatRat level it will be highly sensitive to input parameters if something spirals into a pathological case so it will be a weird numeric heisenbug for anyone who doesn't know the details.

**Comment by AlexDaniel** [comment]
Also, this change will need to be versioned (it is likely to break existing code), which is why I added `6.e` label. Perhaps #1289 is a problem (assuming that we decide to go ahead with the proposed change).

> Since this is one of the major disappointments for people using Perl 6 because of the Rat's

I don't think I've seen that often, is there a link? I have only seen [this](https://www.evanmiller.org/a-review-of-perl-6.html):

> Another oddity crops up if you inspect $total closely. It begins life as an Int, becomes a Rat in the first loop iteration, and is converted to a Num around the 46th iteration. There’s some subtle type trickery going on behind the scenes, and one senses the benign presence of Larry Wall, whose skulduggery with strings and numbers in the original version of Perl made it such a hit with programmers weary of scanf and sprintf.

**Comment by colomon** [comment]
On Wed, Jan 2, 2019 at 9:27 AM Aleks-Daniel Jakimenko-Aleksejev <
notifications@github.com> wrote:

> I'd prefer to have an out of memory error when I expected Rat like
> behaviour than floating point errors sometimes when running some code
>
> It won't run out of memory, at least I've never seen that. It will just
> become extremely slow.
>
> Try something like this:
>
> my $x = ([+] 1.FatRat X÷ 1..9999); dd $x
>
> Right, the current behavior was very carefully thought out when it was
designed.

Rat is designed to prevent the stupid gotchas that basic floating point
arithmetic has, without compromising performance too much.  It degrades to
Num instead of FatRat because Num performs vastly better and is accurate
enough for most real world uses.

If you actually WANT rationals throughout, the correct approach is to
explicitly use FatRat.  Perhaps we need better education on this point.
(And I know at one point I suggested we should have a shorter FatRat
constructor ... dunno if I ever implemented one or if someone else has.)

--Sol

-- 
Solomon Foster: colomon@gmail.com
HarmonyWare, Inc: http://www.harmonyware.com

**Comment by MattOates** [comment]
@colomon think of perhaps other equivalences. Imagine if a Str when a certain length became a buf.  The deeper question to answer is: Is Perl 6 a typed language with defined type safety? If the answer is yes, then a Rat should always have rational semantics, not floating point. For me its that simple. The best case might be to just raise an exception when Rat is exhausted rather than have any magic at all. The decision on if Num is accurate enough for my real world use case is defined by me using a float literal OR specifying a Num type and more likely a binary num64 type (more likely). Its for me as the programmer to decide that based on type, not for the designers of Perl 6 to choose without any obvious recourse for me as the programmer. FatRat is likely to be slower than how Rat could be implemented for example, so why would I wish to take the added hit on performance for smaller Rats in my program 90% of the time. If the accuracy were good enough for most real world use cases then why use Rats at all in Perl 6?

**Comment by japhb** [comment]
Relevant [commentary](https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2019-01-02#l152) from #perl6-dev:

14:17 | AlexDaniel | Ulti: you can have Rat typecheck whenever you want to ensure precision
14:17 | AlexDaniel | m: my Rational $x = ([+] 1 X÷ 1..99); dd $x
14:17 | camelia | rakudo-moar d195e1462: OUTPUT: «Type check failed in assignment to $x; expected Rational but got Num (5.177377517639622e0)␤ in block <unit> at <tmp> line 1␤␤»
14:17 | AlexDaniel | m: my Rational $x = ([+] 1.FatRat X÷ 1..99); dd $x
14:17 | camelia | rakudo-moar d195e1462: OUTPUT: «FatRat $x = FatRat.new(360968703235711654233892612988250163157207, 69720375229712477164533808935312303556800)␤»

Essentially, if you want to ensure that you don't accidentally degrade silently to Num, type constraints are a decent workaround.  Yes, more bother than some might like -- and I understand the desire to change the default behavior -- but you *can* without too much effort prevent silent degradation in critical calculations.  Mind you, this workaround converts silent degradation into runtime type checking and exceptions, each with its own pain (performance loss and crashing for some inputs).  Still, for the 6.d timeframe at least, that may be a trade some users are willing to make.

**Comment by AlexDaniel** [comment]
Also keep in mind that FatRats are infectious, so the moment you introduce a FatRat every other operation with it will return a FatRat too.

**Comment by lizmat** [comment]
Please note that there is currently **no** execution speed difference between `FatRat` and `Rat` if you're using `FatRat`s in the `Rat` range.  Although the implementation implies that the denominator of `Rat`s should be a native int, in reality it is not.  So there is **no** implementation difference between `Rat` and `FatRat` at the moment, other than the conversion to `Num` for `Rat` once a certain threshold is reached.

**Comment by japhb** [comment]
For background to lizmat's comment above, there's discussion about the reasons Rat doesn't currently use native uint denominator at https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2019-01-02#l246 .

**Comment by lizmat** [comment]
Perhaps we need a `use precise` pragma that will case codegen to generate `FatRat`s in that scope, instead of `Rat`s.

**Comment by ugexe** [comment]
Something to consider is what each option means for module authors and how their code can integrate with other modules / user code. My impression after quicking reading this over is that module authors should avoid `Rat` and prefer `FatRat` or always provide multis to handle each case, since they cannot know if the caller is more interested in performance or speed.

**Comment by AlexDaniel** [comment]
> My impression after quickly reading this over is that module authors should avoid Rat and prefer FatRat or always provide multis to handle each case, since they cannot know if the caller is more interested in performance or accuracy.

I'm not sure, I think it depends. Consider this sub:

```perl6
sub divide($a, $b) is export {
    $a ÷ $b
}
```
It will return Fat or FatRat depending on what is passed as `$a` and `$b`. So the user decides if they're interested in performance or accuracy, and perhaps in many cases no action from module authors is required. But I have no proof of that.

**Comment by colomon** [comment]
On Wed, Jan 2, 2019 at 11:15 AM Aleks-Daniel Jakimenko-Aleksejev <
notifications@github.com> wrote:

> My impression after quickly reading this over is that module authors
> should avoid Rat and prefer FatRat or always provide multis to handle each
> case, since they cannot know if the caller is more interested in
> performance or accuracy.
>
> I'm not sure, I think it depends. Consider this sub:
>
> sub divide($a, $b) is export {
>
>     $a ÷ $b
>
> }
>
> It will return Fat or FatRat depending on what is passed as $a and $b. So
> the user decides if they're interested in performance or accuracy, and
> perhaps in many cases no action from module authors is required. But I have
> no proof of that.
>
Right.  If you're just doing normal math, things should just work out.
Want FatRat?  Pass in FatRat.  Want speed?  Pass in Num.

--Sol

PS That said, there certainly are spots where it might pay module authors
to think carefully about this.  A lot of math functions return Num no
matter what the input is -- think the trig functions, or sqrt.  Of course,
there's also no precise answer for those functions in the general case.

-- 
Solomon Foster: colomon@gmail.com
HarmonyWare, Inc: http://www.harmonyware.com

**Comment by smls** [comment]
Making decimal literals an exact type (Rat) that is promoted to an approximating type (Num) once the denominator grows too much, is a deliberate part of the Perl 6 design.
As colomon mentions, it is meant as a compromise to try and give good behavior in practice for Perl 6 users who just use number literals and operators liberally without thinking too much about the underlying types and their own algorithm's precision requirements.

I.e. it means that many (most?) real-world calculations will end up using perfect precision, and it makes the Perl 6 REPL a better calculator app than the Python REPL ;)...
...but when you write an algorithm that makes the denominator grow and grow, then at some point it takes the pragmatic route of continuing with imperfect precision rather than bogging down performance to completely unreasonable levels.

[S02#Numeric_Types](https://design.perl6.org/S02.html#Numeric_Types) talks about his a bit:

> For pragmatic reasons, Rat values are guaranteed to be exact only up to a certain point. [...]
A Rat64 that would require more than 64 bits of storage in the denominator is automatically converted either to a Num or to a lesser-precision Rat, at the discretion of the implementation. 
[...]
For applications that really need arbitrary precision denominators as well as numerators at the cost of performance, FatRat may be used

Also, I'd like to point out that *if* it was decided to change this design and make rational numbers *always* stay at perfect precision when transformed by math ops that can return rationals, then "lets promote Rat to FatRat" wouldn't be a sensible way to do this. Rather, it would be "lets make Rat behave like FatRat, and deprecate the FatRat name". Because the entire reason for the separate FatRat type is to support the current Rat->Num design.

**Comment by lizmat** [comment]
All noted.  Since then I've added a dynamic variable:

    $*FULL-PRECISION

If you set this to a True, then in that dynamic scope a `Rat` will be silently upgraded to `FatRat` instead of downgraded to float (`Num`) when it hits the 64 bit barrier for the denominator.

I'm renaming this ticket to make this about keeping this dynamic variable or not.

**Comment by smls** [comment]
I take it it has to be a dynvar instead of a lexical pragma like `use full-precision;`, because it should affect not only what is returned by built-in Perl 6 math operators / routines used in that lexical scope, but also those used inside **third-party modules** which the user might call from that scope?

Are there any action-at-a-distance problems that might crop up when downstream code can change the type promotion behavior of math ops inside module code?
(Just spit-balling here.)

**Comment by lizmat** [comment]
I would argue that `$*FULL-PRECISION = True` would *reduce* the possible problems of third party libraries, as floats will not appear "out of nowhere".  Typechecking does remain a problem, as `FatRat ~~ Rat` is `False` (which I consider to be a bug, really).

**Comment by lizmat** [comment]
Reverted before release
