### ISSUE TITLE
Uncertainty about submethods in roles

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#2677]
## The Problem

I'm working on a fix for #2250 . While the problem itself was easily tracked down to `add_method` (and, possibly, a nqp bug), the general fix requires clear understanding of what happens to submethods when a role consumes another role. While things are pretty straightforward for `method`s, which are copied over from the source role to the target, for `submethod`s not everything is so clear in my understanding. Let's consider the following setup:

```
role R1 { submethod foo { "R1::foo" } }
role R2 does R1 { }
class Foo does R2 { submethod foo { "Foo::foo" } }
```

Imagine a code which would like to execute all `submethod`s of all classes and their roles. Normally, it would traverse `mro` and all role concretizations of each class from `mro`. In the example above such code in its most basic form would call `submethod foo` from `R1` twice: for `R2` and `R1` itself! Of course, there is a workaround for this as the copy of `foo` from `R1` will have its `.package` set to `R1`. But what sense does this copying makes? When a role gets applied to a class it does make some sense when we talk about `BUILD`/`TWEAK`/`DESTROY`. Though if #2241 gets implemented (and I'm willing to take this task) then even this use case will be obsoleted.

So, to have a comprehensive fix for #2250 I'd like to find out how to handle `submethod`s when a role is applied to a role: either I leave them untouched where they're, or I get them copied alongside with methods.

My choice is to not copy the `submethod`s and make them the sole property of the role/class where they were declared. This would also solve the need of resolving conflicts when consuming 2+ roles with same `submethod` in them. Ideally, copying from a role to a class would be avoided too. In order to provide backward compatibility with respect to construction/destruction I would develop a solution for #2241.

**Comment by vrurg** [comment]
@b2gills made a comment in [#2250](https://github.com/rakudo/rakudo/issues/2250#issuecomment-461858556) which rather belongs here.

**Comment by jnthn** [comment]
I need to think this through some more, but some initial thoughts:

* `.^mro` absolutely should *not* be returning roles; that would break rather a lot
* #2241 makes a fairly compelling argument that `submethods` should be given different composition semantics to methods, such that roles can factor out their own construction logic
* It's tempting to have all `BUILD`/`TWEAK`/`DESTROY` from roles be called. However, we have some questions to answer if we want to go in that direction, including:
    * The ordering question mentioned in #2241, but I think the answer is to consider the role structure as a DAG and then do a topological sort (there may be ways to get equivalent semantics without doing that, but it's a neat definition).
    * Should we enforce coalescence, or should we provide an opt-out? If so, how?
    * It should be something that happens at a language version change (so, 6.e), which in itself is not too hard, but we need to consider cases where the class is 6.e code but the role in 6.d, and vice versa. I suspect that we'd just make `submethod`s not participate in composition, and coalescence to take place in the final composition into a class, meaning that it'd be the class that matters. But it's worth thinking through a bit more.
    * What do we expect of `lookup` vs. `find_method`? Should `lookup` on a class with no `TWEAK`, but composing roles that have a `TWEAK`, return anything, since it's about inspecting declarations? Clearly `find_method` has to.
    * How can we synthesize the thing return from `find_method` so that it can be executed efficiently? (Answer: probably via the compiler services interface, with some closure-based fallback if that's not available.)

**Comment by vrurg** [comment]
No doubts about `.^mro` default behavior. But what about a modification with a named parameter? 

    my @mro := self.HOW.mro($obj, :with_roles);

I'm currently experimenting with rewriting `compute_mro` where `.^mro` is just a proxy for another method.

I would try to answer some of your questions from my point of view.

- Ordering and topological sorting.

    Current MRO implementation already does the topological sorting. Just throwing in roles seems to do pretty well. The only 'but' here is the fact that there is no way to determine the initial order or classes/roles intermix as it was specified by the user. The parser doesn't preserve the sequence (it never needed to) and the metamodel treats and stores them separately. On the other hand, they _are_ different with roles being more like a part of the class (a symbiont?). Therefore I see it absolutely normal to have immediate parent classes follow roles as the starting point of topological sorting.

    Say, if a user defines:

    ```
    class C0 does R0 is C1 is C2 does R1 { ... }
    ```

    then final order would be obtained from `R0 R1 C1 C2`. So far, my experimental code does this kind of sorting pretty well.

- Unfortunately, I don't understand the question about coalescence and opt-out. Could you, please, help me with it? With "coalescence" I understand it's what is happening to the role now. But "opt-out" is beyond me. 

- I agree that cross-revision compatibility needs some thinking about it. I have no doubt that class is the priority here.

  What comes into mind is that any new role created as **6.e** must be consumed by a **6.e** class only. What would be the point of preserving older version on a new compiler as it wouldn't obviously be possible to use the class with an older one?

  Things turning to worse for roles which were pre-existing as **6.d** and turning into **6.e**. So far, I can only see one way to resolve this: have a way to declare backward (in)compatibility. Something like: 

    use 6.e;
    role R1:compat<6.d> { }

would signal that the creator took measures to preserve backward compatibility for the older code. Otherwise the core would sink in the sea of possible version combinations in the future and in attempts to resolve them all.

- `lookup` must find any declaration, no matter it's role or class where it finds it. I mean, it would simply make no sense if one can `self.foo` but would fail on `self.lookup('foo')`, wouldn't it?

BTW, alongside with `submethod`s, a fix could be generated for private methods (#2663) too.

**Comment by jnthn** [comment]
> No doubts about `.^mro` default behavior. But what about a modification with a named parameter?

I think it's the wrong hook to hang it off, since...

> Current MRO implementation already does the topological sorting. Just throwing in roles seems to do pretty well.

I think that's going to do the wrong thing. Role composition is flattening; the handwavey explanation normally used is "as if the stuff in the role was declared in the class". So if I have:

```
role R {
    has $!a;
    submethod BUILD() {
        say "here";
        $!a = 42;
    }
}
class C1 does R { }
class C2 is C1 does R { }
C2.new
```

Then there are two `$!a` attributes, one for each class, and so `BUILD` must run for each of them, and I'd expect `here\nhere\n` as the output. In fact, `R` is generic, and after role instantiation there are actually two concrete roles, and two concrete `BUILD` submethods.

By the time we get to doing a method dispatch, anything that involves the role's contributions should be pretty much settled, which is why I think MRO is an odd place to put this. Roles are immutable, so by the time we've composed, there's nothing to resolve any more involving the roles themselves anyway.

> Unfortunately, I don't understand the question about coalescence and opt-out. Could you, please, help me with it?

By "coalescence" I mean that all of the `BUILD`/`TWEAK`/`DESTROY` submethods from all roles are run. In fact, we'd be doing this for `submethod` in general, so if you have:

```
role R1 {
    submethod foo() { say "R1" }
}
role R2 {
    submethod foo() { say "R2" }
}
class C does R1 does R2 {
    submethod foo() { say "R3" }
}
C.foo
```

Then we'd expect the output to be like `R1\nR2\nR3` (although it'd be arguable that the ordering of the first two should be deliberately unstable to shake out ordering bugs).

By opt-out, I mean: should there be a way to not have these semantics, and instead have the method-style semantics (that is, the way submethods behave in `6.d`)? I'm not convinced there should, though if there was it'd be a way to ask for 6.d semantics in 6.e, perhaps in a more fine-grained way than a `:compat` style trait would give us.

> I mean, it would simply make no sense if one can `self.foo` but would fail on `self.lookup('foo')`, wouldn't it?

That situation already exists today thanks to `FALLBACK`, or even a `method ^find_method` written in a class, for that matter. The idea is that `.^find_method` returns something that we can invoke, while `.^lookup` answers the question "what's declared here", and that's for introspection purposes rather than dispatch purposes. Arguably, then, synthetic things aren't for `.^lookup` to return.

Taking a concrete example, considering:

```
role R1 {
    submethod foo() { say "R1" }
}
class C does R1 {
    submethod foo() { say "C" }
}
```

I'd expect `C.^find_method` to return something that, when invoked, runs the submethod from the role and the one from the class, but I'd expect `C.^lookup` to return the `foo` declared on the class. That'd imply that:

```
role R1 {
    submethod foo() { say "R1" }
}
class C does R1 {
}
```

Would have `C.^find_method('foo')` return...well, it could actually optimally return the appropriate instantiation of the submethod in `R1`, but it's OK if in the immediate there's a level of indirection. But `C.^lookup('foo')` probably wants to return nothing, to be consistent.

These things taken together probably mean that we need a table (hash in the metaclass) for submethod invocation targets (that is, the synthetic "call all the submethods" thing), which `find_method` would use, while `lookup` continues to just look at the `submethods` table.

**Comment by vrurg** [comment]
First of all, excuse me for being not being really clear with regard to `.^mro` use. Speaking of applying C3 to roles I meant sorting roles on a per-class basis. That came from the fact that roles might have pretty complex dependencies as well:

```
role R0 { }
role R1 does R0 { }
role R2 does R0 { }
role R3 does R1 does R2 { }
class C0 does R3 { }
class C1 does R1 is C0 { }
```

For this graph my experimental code generates the following sequence now:

>```
>C1 R1 R0 C0 R3 R1 R2 R0
>```

The only case where `BEGIN`/`TWEAK`/`DESTROY` won't be duplicated is class `C0`, obviously. The reason is the same you're pointing at: the structure must flatten down into `C0` including any attributes defined in `R0`. Though for this moment the attributes will collide and cause a "big boom" - as currently reported in #2694.

BTW, due to compatibility matters, I had to implement `.^rmro` method and make `.^mro` and `.^mro_unhidden` its proxies.

It also seems like we have different view on how `submethod`s are to be used. Your point is that calling a `submethod` on a object must result in calling all same name `submethod`s of all roles. 

My view is that this must be done manually. The reason? `submethod`s may be returning values. An example for my real life use case: a framework collects static properties of an object (command line option definitions). The class/role relations of the object are not known to the framework beforehand and it has to walk the MRO and call `submethod`s where they exists. And must admit that a `submethod` like this:

```
submethod props {
    prop1 => 'val1',
    prop1 => 'val2,
}
```

looks way better than:

```
submethod props ($collector) {
    $collector->append(
        prop1 => 'val1',
        prop1 => 'val2,
    )
}
```

which I would have to use with "call 'em all" approach. Besides, the first variant might also be safer in certain cases with regard to possible corruption of some data outside of the method scope.

Within my model your approach could easily be implemented by a special routine. Or, perhaps, by a special call operator or a modification of the existing `.+`/`.*`. In either case, this two would not require any other modification but calling another `.^mro` modification (it would be `.^rmro` in my case).

I also would suggest preserving both `find_method` and `lookup` in their current form as much as possible. With my proposal for MRO their logic would simply be slightly extended to cover the roles. Not only this would preserve as much of backward compatibility as possible but won't surprise inattentive users who don't read Changelogs carefully enough.

**Comment by TimToady** [comment]
I agree with jnthn insofar as the intent of submethods is independent, automatic infrastructure, so this naturally extends to calling all role submethods automatically by default.  The clunky example of returning values could be cleaned up with a gather/take, but I think if you're going to actually do data processing, normal methods shadowed by a master method (or submethod) in the class work fine for this.  Since they are shadowed, they are effectively visible only to the class's shadowing method.  In any case, BUILD, TWEAK, and DESTROY have to be automatic.

I will agree with vrurg that a canonical order of the roles within the class is a good idea if we allow dependencies or if you're going to start returning lists of values from submethods.  Perhaps submethods should default to --> Nil and suppress autocall if some other return type is defined, though there could be inconsistencies with that approach.  Or, silly idea, maybe we only autocall the ones in ALLCAPS, which would naturally be consistent among all submethods of the same name.  :)

**Comment by vrurg** [comment]
It doesn't look good for me if we give special meaning to all AUTOCAPS methods. That's a convention for them to be language-specific things but not a constraint. I think the special case must be applied to few named ones like constructors and destructor. I.e. one knows that all 'BUILD's are called during construction – and that's documented and ok. 

I also don't think it'd be a good idea to break the current default where `$foo.submethod` only calls the first found one. Why can't we use `.+` and `.*` as I proposed above? Or we can provide a new submethod-specific one `.@` which would return a lazy sequence of return values where `Nil`s will be in place of the calls where submethods return nothing. This would also avoid confusion of an end user. I think it's much easier not to remember what kind of method is being called with `.` and not be afraid of any possible side effect. Whereas `$foo.@submethod`, `$foo.+submethod`, `$foo.*submethod` would be clearer and self-explanatory.

**Comment by vrurg** [comment]
Closing with #3348
