### ISSUE TITLE
Does not fail with spesh disabled, fails 100% with MVM_SPESH_BLOCKING

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2704]
I'm not sure why we haven't seen it before.

Bisected: eb3917c260bce1cb56e2ee40abebd12c4dbcd9b2

```
===> Searching for: ANTLR4::Grammar
===> Found: ANTLR4::Grammar:ver<0.6.1>:auth<github:drforr> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: ANTLR4::Grammar:ver<0.6.1>:auth<github:drforr> to /home/alex/Blin/data/zef-data/tmp/1550518536.11122.9020/perl6-ANTLR4.git
===> Extraction [OK]: ANTLR4::Grammar to /home/alex/Blin/data/zef-data/store/perl6-ANTLR4.git
===> Testing: ANTLR4::Grammar:ver<0.6.1>:auth<github:drforr>
t/01-parse.t .............. ok
t/02-corpus.t ............. ok
===SORRY!===
Type check failed in binding to parameter '$a'; expected Any but got VMNull (?)
# Looks like you planned 48 tests, but ran 2
t/03-corpus-compile.t ..... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 46/48 subtests 
t/04-use-parser.t ......... ok
t/10-basic-grammar.t ...... ok
t/11-concatenation.t ...... ok
t/12-alternation.t ........ ok
t/13-grouping.t ........... ok
t/14-grammar-modifiers.t .. ok
t/15-rule-modifiers.t ..... ok
t/16-term-modifiers.t ..... ok
t/17-modes.t .............. ok
t/meta.t .................. ok

Test Summary Report
-------------------
t/03-corpus-compile.t   (Wstat: 65280 Tests: 2 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 48 tests but ran 2.
Files=13, Tests=100, 79 wallclock secs ( 0.13 usr  0.01 sys + 59.92 cusr  1.40 csys = 61.46 CPU)
Result: FAIL
===> Testing [FAIL]: ANTLR4::Grammar:ver<0.6.1>:auth<github:drforr>
Failed to get passing tests, but continuing with --force-test
===> Installing: ANTLR4::Grammar:ver<0.6.1>:auth<github:drforr>
===> Install [OK] for ANTLR4::Grammar:ver<0.6.1>:auth<github:drforr>
```

**Comment by lizmat** [comment]
This gets weird:

$ perl6 -Ilib t/03-corpus-compile.t 
1..48
ok 1 - ANTLRv4Lexer.g4
ok 2 - ANTLRv4Parser.g4
===SORRY!===
Type check failed in binding to parameter '$a'; expected Any but got VMNull (?)
# Looks like you planned 48 tests, but ran 2

However, if you run this with —ll-exception, it runs fine!

$ perl6 --ll-exception -Ilib t/03-corpus-compile.t 
1..48
ok 1 - ANTLRv4Lexer.g4
ok 2 - ANTLRv4Parser.g4
ok 3 - ATL.g4
ok 4 - bnf.g4
…

This is the first time I see —ll-exception make a difference in execution.

**Comment by lizmat** [comment]
I’ve also run this with a modified rakudo that did not have a custom Parameter.new (basically the situation from before eb3917c): no change.  I succeeds with —l-exception, and fails at the same location (but where??) without it.  So I’m afraid eb3917c being the cause, is not entirely believable.

**Comment by lizmat** [comment]
Finally found where the code is going wrong:

    sub greed-to-string( $a ) {
        $a.greed ?? '?' !! ''
    }

    sub modifier-to-string( $a ) {
        ( $a.modifier // '' ) ~ greed-to-string( $a )
    }

The problem is a typecheck fail on the $a parameter in "greed-to-string", which is being called from “modifier-to-string”.  Since these all refer to the same thing, I’m surprised that if “greed-to-string” gets a VMNull, why didn’t it complain already when it was received by “modifier-to-string” ?

Also: using —ll-exception makes it run ok:

$ perl6 -e 'use MONKEY; use lib q/lib/; use ANTLR4::Grammar; EVAL ANTLR4::Grammar.file-to-string("corpus/ATL.g4”)
Type check failed in binding to parameter '$a'; expected Any but got VMNull (?)
  in sub greed-to-string at /Users/liz/Github/perl6-ANTLR4/lib/ANTLR4/Grammar.pm6 (ANTLR4::Grammar) line 54
  in sub modifier-to-string at /Users/liz/Github/perl6-ANTLR4/lib/ANTLR4/Grammar.pm6 (ANTLR4::Grammar) line 59
  in method to-lines at /Users/liz/Github/perl6-ANTLR4/lib/ANTLR4/Grammar.pm6 (ANTLR4::Grammar) line 86
  in method to-lines at /Users/liz/Github/perl6-ANTLR4/lib/ANTLR4/Grammar.pm6 (ANTLR4::Grammar) line 152
  in method to-lines at /Users/liz/Github/perl6-ANTLR4/lib/ANTLR4/Grammar.pm6 (ANTLR4::Grammar) line 165
  in method to-lines at /Users/liz/Github/perl6-ANTLR4/lib/ANTLR4/Grammar.pm6 (ANTLR4::Grammar) line 177
  in method to-lines at /Users/liz/Github/perl6-ANTLR4/lib/ANTLR4/Grammar.pm6 (ANTLR4::Grammar) line 193
  in method file-to-string at /Users/liz/Github/perl6-ANTLR4/lib/ANTLR4/Grammar.pm6 (ANTLR4::Grammar) line 226
  in block <unit> at -e line 1

$ perl6 --ll-exception -e 'use MONKEY; use lib q/lib/; use ANTLR4::Grammar; EVAL ANTLR4::Grammar.file-to-string("corpus/ATL.g4")’
$

**Comment by lizmat** [comment]
We haz an official flapper:

$ perl6 -Ilib -e 'use MONKEY; use ANTLR4::Grammar; EVAL ANTLR4::Grammar.file-to-string("corpus/ATL.g4”)

fails about 50% of the time.  However, with MVM_SPESH_DISABLE=1 I can’t get it to fail:

$ MVM_SPESH_DISABLE=1 perl6 -Ilib -e 'use MONKEY; use ANTLR4::Grammar; EVAL ANTLR4::Grammar.file-to-string("corpus/ATL.g4”)'

With MVM_SPESH_BLOCKING=1 it fails 100% of the time:

$ MVM_SPESH_BLOCKING=1 perl6 -Ilib -e 'use MONKEY; use ANTLR4::Grammar; EVAL ANTLR4::Grammar.file-to-string("corpus/ATL.g4")'

**Comment by jnthn** [comment]
It turned out to be an (extremely silly) bug in merging materialization tables during inline, which caused it to deopt wrongly. https://github.com/MoarVM/MoarVM/commit/04982f6e9c fixes it.
