### ISSUE TITLE
rmdir error in Windows

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2771]
## The Problem

From JJ/p6-pod-load#5: 

```
===> Testing: Pod::Load:ver<0.4.0>
# Testing strings
Failed to remove the directory 'C:\Users\naoum\AppData\Local\Temp\B93E2E259914003CBED764A23AD228BC90C786BE': Failed to rmdir: directory not empty
  in sub load at C:\Users\naoum\Desktop\rakudo-star-2019.03\modules\p6-pod-load\lib\Pod\Load.pm6 (Pod::Load) line 81
  in sub load at C:\Users\naoum\Desktop\rakudo-star-2019.03\modules\p6-pod-load\lib\Pod\Load.pm6 (Pod::Load) line 64
  in sub do-the-test at t/01-basic.t line 19
  in block <unit> at t/01-basic.t line 40

===> Testing [FAIL]: Pod::Load:ver<0.4.0>
```

That line uses `delete-by-compiler` which is implemented here: 
https://github.com/rakudo/rakudo/blob/e9351cbaa961c4d1e4ef8b4cb52418d55766a8d6/src/core/CompUnit/PrecompilationStore/File.pm6#L245-L254

## Expected Behavior

It works correctly in Linux. It seems to be a Windows-only problem. 

## Environment

See above.

**Comment by hankache** [comment]
Hello everyone,

Since `Pod::To::HTML` now depends on `Pod::Load` and according to @JJ `Pod::Load` is affected by this issue; `Pod::To::HTML` no longer works on Windows.
This is blocking me from releasing Rakudo Star. Is there anything we can do about this issue? If not should we redirected the focus to `Pod::Load`?

Thanks.

**Comment by ugexe** [comment]
It is a regression caused by `Pod::Load`, not rakudo, so one solution is to revert the changes that broke things on windows (which again is in `Pod::Load`).

For instance we can see `Pod::Load` do things like attempt to *load* module/pod code (which doesn't make much sense to me but that is besides the point) -- but on windows you cannot delete a path if a handle to it is still opened. Internally there is great care taken to keep track of possibly-open handles before calling things that try to delete paths, whereas `Pod::Load` is treating the method as a type of `rm -rf`.

**Comment by hankache** [comment]
@ugexe thanks
@JJ can you please take care of this then?

**Comment by JJ** [comment]
Ok

**Comment by hankache** [comment]
@JJ if you're using the method as a generic `rm -rf` can you instead use https://github.com/labster/p6-file-directory-tree, there is a method called `rmtree`. Will this fix the issue?

**Comment by hankache** [comment]
In all cases let's move the discussion to https://github.com/JJ/p6-pod-load/issues/5 since it is not a Rakudo issue.

**Comment by JJ** [comment]
Also, I don't really understand why the whole tooling for rendering the
documentation to HTML is included in Rakudo Star. There's this proposal for
splitting perl6/doc https://github.com/perl6/doc/issues/2542 In principle,
all you would need is p6doc, right?

**Comment by JJ** [comment]
Anyway, just released 0.5.0 which does not use precomp. It is available
from the repo now (tag 0.5.0), it should hit the ecosystem in the next
update in a couple of hours or so. It's also working in Windows (according
to Appveyor). Sorry for all the inconvenience, and thanks for the report.

**Comment by JJ** [comment]
0.5.1 should be hitting the repos any time now. Please check and close if it fixes the problem.

**Comment by hankache** [comment]
Shouldn't we close this ticket?

**Comment by JJ** [comment]
Right. Thanks!
