### ISSUE TITLE
Inline::Perl5 integration tests are no longer run

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2815]
It appears that since the relocatable build refactor, `make spectest` is no longer running the `Inline::Perl5` integration tests, even though `Inline::Perl5` **is** installed.

**Comment by lizmat** [comment]
I don't think this is a blocker.  Hopefully, we'll fix this at the PTS

**Comment by coke** [comment]
I'm seeing what may be a related issue:

```
make spectest
```
...
```
Inline::Perl5 not installed: not running Perl 5 integration tests
You can install Inline::Perl5 into the build directory with

    zef --install-to=inst#/Volumes/BUKKIT/Users/coke/sandbox/rakudo/t/../gen/build_rakudo_home/site install Inline::Perl5
```

but if I run this zef command, it tells me all the candidates are currently installed, and then rerunning the spectest shows the same error.

**Comment by vendethiel** [comment]
> it tells me all the candidates are currently installed

That's an issue with `zef --install-to=` I think, which doesn't use only that path to check if a module is installed. So if the module is installed somewhere else on your machine, `zef --install-to=` doesn't actually do something useful.

**Comment by coke** [comment]
FYI, added "--force-install" to that zef command, it installed... and then I got the same error from spectest, it's still not installed.

**Comment by ugexe** [comment]
@coke Can you try adding the `--contained` flag ala:
`zef --contained --install-to=inst#/Volumes/BUKKIT/Users/coke/sandbox/rakudo/t/../gen/build_rakudo_home/site install Inline::Perl5`?

```
--contained (BETA)      Install all transitive and direct dependencies regardless if they are already installed globally
```

Note that its BETA because it can have some issues installing to an existing repository (which it looks like you might be doing, but maybe it'll work).

**Comment by ugexe** [comment]
`make spectest` with `Inline::Perl5` works if manually set the lib -- `RAKULIB="inst#/Users/ugexe/repos/rakudo/t/../gen/build_rakudo_home/site" make spectest` after using the zef instructions. Something in `make spectest` should be setting that if it is going to tell users to install stuff to a specific location.

**Comment by vrurg** [comment]
All spectest targets in Makefile are using _t/harnessN_ scripts. I think they're the best place for the fix.

**Comment by patrickbkr** [comment]
The original solution to this problem was to set the `RAKUDO_HOME` env var in the build runners in [tools/templates/moar/rakudo-m-build.c.in](https://github.com/rakudo/rakudo/blob/master/tools/templates/moar/rakudo-m-build.c.in#L42). I'm wonder why that didn't have an effect (anymore?). Thus I'm not sure modifying the harness scripts is the correct fix...
