### ISSUE TITLE
Custom USAGE() should be allowed to return the exit value

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2817]
> Hmmm, if I use a USAGE() in Perl 6, my program exits with result code 0, not an error code.  I can do "exit 1" easily enough, but I wonder if this is a bad default.

https://twitter.com/jmaslak/status/1114336443831218176

**Comment by lizmat** [comment]
Changing https://github.com/rakudo/rakudo/blob/master/src/core/Main.pm6#L329 to read:

    exit +usage()

causes spectest breakages in: t/spec/S06-other/main-refactored.t , t/spec/S06-other/main.t , t/spec/S06-other/main-usage.t

**Comment by lizmat** [comment]
Changing that line to:

    my $exit := usage;
    exit nqp::istype($exit,Numeric) && $exit.Int;

produces the same set of test files with failures.

**Comment by b2gills** [comment]
Instead of just checking for `Numeric` you could check to see that it isn't `Bool`.

The problem is those tests return the value of a successful `print` statement, which returns `True`.
`True` is a subtype of `Int`, which is obviously `Numeric`.

```perl6
say print "";   # True

True ~~ Int;    # True
Int ~~ Numeric; # True
```

```perl6
sub USAGE () {
  print ''; # returns True
}

my $exit = USAGE();
exit $exit ~~ Numeric && $exit !~~ Bool && $exit.Int
```

---

Also those tests should probably make the return value of `USAGE` be `Nil`.

```perl6
sub USAGE ( --> Nil ) {
  print ''; # returns True
}
```

Which brings up another idea. Rather than checking the actual returned value, check the signature.

```perl6
sub USAGE ( --> 1 ) {
}

my $return = USAGE();
my $exit = &USAGE.signature.returns.WHAT =:= Int ?? $return !! 0;
exit $exit;
```

That way old code which didn't expect for the return value to be used will continue to work unchanged.

**Comment by ugexe** [comment]
`sub USAGE` should act like any other sub that can be called (which may not be through a CLI) and not have different/magical exit codes applied. `exit $foo` really is simple enough -- trying to add special handling when declaring the exit code in the e.g. return signature is more complicated and only saves 1 character of typing.

**Comment by b2gills** [comment]
The code I proposed above would also work with:

```perl6
sub USAGE ( --> Int ){
  return 1
}
```

The majority of `USAGE` subs don't care about the return value.
By checking the returns constraint, we make sure that the returned value was intentional on the person who wrote it.

---

Really the fact that defining a `USAGE` sub currently alters exit handling seems like an unintentional feature.

Honestly the argument handling should probably just always return a non-zero exit value if it failed to match a `MAIN` sub.
If someone wants something different they could write a fallback `MAIN` multi which matches anything, and they can write `exit …` in there.

**Comment by ugexe** [comment]
I am still against this. Even now tony-o is working on a plugin system that essentially has users declare their CLI in a module, and where the plugin consuming system calls subs (such as `MAIN` and `USAGE`) from the consumer. In neither case should an exit code be applied because *they don't know if they are exiting at all*

**Comment by ugexe** [comment]
Actually, I'm probably off base here. The required changes seem like they would only apply to the mainline automatically calling `USAGE` -- I don't have a good argument against this in such a scenario.
