### ISSUE TITLE
Metamodel::Primitives.rebless on classes created via Metamodel::Primitives.create_type broken

### ISSUE THREAD

**Issue by niner** [rakudo/rakudo#2839]
Seems like merging the identify-mixin-types branch broke Inline::Perl5:

```
nine@sphinx:~/Inline-Perl5 (master=)> perl6 -I. /home/nine/Inline-Perl5/t/inherit.t
1..14
ok 1 -
New type P6Bar for Foo is not a mixin type
  in method new at /home/nine/Inline-Perl5/lib/Inline/Perl5/ClassHOW.pm6 (Inline::Perl5::ClassHOW) line 48
  in block <unit> at /home/nine/Inline-Perl5/t/inherit.t line 28
```

I create the type here:
https://github.com/niner/Inline-Perl5/blob/d89367c8e413a744b9f134555bdaca30cd169d60/lib/Inline/Perl5/ClassHOW.pm6#L27
And later on want to rebless an object of that type in:
https://github.com/niner/Inline-Perl5/blob/d89367c8e413a744b9f134555bdaca30cd169d60/lib/Inline/Perl5/ClassHOW.pm6#L48

**Comment by niner** [comment]
TBH what I do here has probably always been kinda fishy and with Inline::Perl5's current structure there is a way to get an object of the subclass without rebless. Could even be that this way I can get rid of special handling for `new` altogether. Would be nice though to keep already deployed Inline::Perl5 versions up and running.

**Comment by jnthn** [comment]
As of https://github.com/rakudo/rakudo/commit/4702c245f0 it's now possible to pass a `:mixin` option to `Metamodel::Primitives.create_type`, and such a type can be used as the `Metamodel::Primitives.rebless` target. There was no previous spec for `Metamodel::Primitives.rebless`. I've [added this spectest](https://github.com/perl6/roast/commit/c78326fa14) so that now there is. This means there's now some definition of what can be expected to work, and which `Inline::Perl5` can rely on.

> Would be nice though to keep already deployed Inline::Perl5 versions up and running.

Since unknown named parameters are ignored, but `:mixin` was not required on previous Rakudo versions, then it would be possible to make a new `Inline::Perl5` release that can work on previous Rakudo versions as well as the upcoming one, so there can at least be back-compat. I don't think there's any way of keeping things working for existing `Inline::Perl5` versions without reverting the whole bunch of work across all 3 repositories (MoarVM, NQP, Rakudo) for the upcoming release, and putting it back afterwards. That's not something I'm personally interested to do, but I don't mind if somebody else does it, to give an extra release worth of upgrade time. Please re-open the ticket if wishing to take that path.

**Comment by niner** [comment]
Unfortunately passing :mixin doesn't help in this case as the rebless is done on a subclass of the one created via Metamodel::Primitives.create_type. The subclass uses the normal Perl6::ClassHOW.

I'm working on a major refactor to get rid of the rebless hack in the first place. I'm reopening this issue so the release manager is aware of there being no working Inline::Perl5 on rakudo's release candidate.

**Comment by jnthn** [comment]
> The subclass uses the normal Perl6::ClassHOW.

Do you create that class using the MOP? You can pass `:is_mixin` to `Perl6::ClassHOW.new_type` if so.

**Comment by niner** [comment]
No, it's for this situation:
```
use Foo:from<Perl5>;
class Bar is Foo { }
```

**Comment by lizmat** [comment]
Closing as this appears fixed, please re-open if this assumption is incorrect
