### ISSUE TITLE
Invocation used to run Perl 6 code under remote debugger broken

### ISSUE THREAD

**Issue by jnthn** [rakudo/rakudo#2850]
## The Problem

The only current way to launch remote debugging is through invoking MoarVM with `perl6.moarvm` followed by arguments. A typical invocation line looks like this:

```
/home/jnthn/dev/MoarVM/install/bin/moar --debug-port=9999 --debug-suspend --libpath=/home/jnthn/dev/MoarVM/install/share/nqp/lib --libpath=/home/jnthn/dev/MoarVM/install/share/perl6/lib --libpath=/home/jnthn/dev/MoarVM/install/share/perl6/runtime /home/jnthn/dev/MoarVM/install/share/perl6/runtime/perl6.moarvm -Ilib /home/jnthn/foo/foo.p6
```

## Expected Behavior

This invocation works, as it did in 2019.3 and many prior releases.

## Actual Behavior

It doesn't find installed modules. Output:

```
===SORRY!===
Could not find Cro::HTTP::Log::File at line 1 in:
    file#/home/jnthn/op/easii/easii/lib
    inst#/home/jnthn/.perl6
    inst#/share/perl6/site
    inst#/share/perl6/vendor
    inst#/share/perl6
    ap#
    nqp#
    perl5#
```

Those paths starting with `/share` look broken. I suspect this regressed as part of the work on relocation. That work is very welcome, but we should support existing workflows too.

## Steps to Reproduce

Construct an invocation line like the one above. Or, if you have [Comma](https://commaide.com/download), just try to debug anything that uses an installed module. The 1-line program `use NativeCall;` will do it.

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2019.03.1-228-g30e97a5 built on MoarVM version 2019.03-82-g7b112da
implementing Perl 6.d.

**Comment by patzim** [comment]
Just as info: It is possible to start the remote debugger directly with perl6. The `--debug-port=9999 --debug-suspend` arguments are understood and processed accordingly.
It's a bug moarvm has wrong repos non the less.

**Comment by jnthn** [comment]
> Just as info: It is possible to start the remote debugger directly with perl6

Oh, I wasn't aware that was possible; is that very new? It sounds like a much nicer way to do things going forward.

**Comment by patzim** [comment]
That was also part of my relocatable work.
I can reproduce the error btw

**Comment by patzim** [comment]
My relocatability work broke this.
This is kind of complicated and might need some design decision when we want this   +to work as before.

Before the relocatability work rakudo relied on the `libdir` configuration variable
+to determine the repository paths.
The current rakudo knows about two environment variables: `PERL6_HOME` and          +`NQP_HOME`. Those can be used to hint rakudo where the repositories (and core lib  +dirs) are located.
When they are not passed it tries to determine them starting from the executable    +path. 

So when calling perl6 in the old way by calling moar directly it is now necessary   +to set the environment variables NQP_HOME and PERL6_HOME pointing to               +`<install_path>/nqp` and `<install_path>/perl6` respectively.
(One could also pass `--execpath=/installdir/bin/perl6` to moar, which would cause  +perl6 to determine the correct paths for NQP_HOME and PERL6_HOME by itself, just   +as happens when calling perl6 the normal way).

Question is, how to fix this? (Question to myself, that is)

**Comment by Altai-man** [comment]
I think there might be no need to fix this, at least for Comma case: we'll just change it to `perl6 --debug...` and it will be a lot easier for us to do it this way, in fact.
On the other hand, if there are more similar cases, that's another issue.

**Comment by jnthn** [comment]
@Altai-man We'd need to do version detection at the very least, though, to make sure we didn't break on older versions of Rakudo without that flag. (There is, in fact, no Rakudo release where we can use the `perl6 --debug` flag yet.)

But yes, it's true that we can fix this in some "hacky" way for now, and consider it just there for a migration period, and remove it in some months time.

**Comment by kawaii** [comment]
I plan on cutting a release candidate build for 2019.04 on Monday so in the absence of a patch should we remove the blocker label from this issue @jnthn, @Altai-man?

**Comment by jnthn** [comment]
@kawaii I still consider this a blocker, in so far as it'd likely lead to me recommending against us using this release at $dayjob projects due to broken debugging.

**Comment by patzim** [comment]
I've thought about this some more and I'm not sure how to progress here. I'm grateful for any ideas on what might be a good way forward.

The problem at the core is, that without relying on configure time absolute paths (the way rakudo worked before the relocatability refactor), there is no clear way to determine the repository paths in this situation.
The way it's designed now (after the relocatability refactor), rakudo determines these paths automatically relying on the executables location (that's why passing `--execpath=/install_dir/bin/perl6` makes this work). The locations can be overridden using environment variables.

**Comment by patzim** [comment]
Ping @niner, @timo

**Comment by jnthn** [comment]
> The problem at the core is, that without relying on configure time absolute paths (the way rakudo worked before the relocatability refactor), there is no clear way to determine the repository paths in this situation.

Is there a reason why we can't, for a migration period, fall back to the configure time absolute path if there's nothing else provided (no `--execpath`, no env var)?

**Comment by patzim** [comment]
jnthn: I like that idea. I'll see what I can do.
