### ISSUE TITLE
"Unknown QAST node type NQPMu" when missing a comma hash initialization

### ISSUE THREAD

**Issue by voldenet** [rakudo/rakudo#2863]
## Description
When "," is ommited in hashes containing angle brackets, you get useless error about it.
```perl6
say {:a<A> :b<B>, :c<C>}
```
```
(exit code 1) ===SORRY!===
Unknown QAST node type NQPMu
```

This works as expected:
```perl6
say {:a<A> :b("B"), :c("C")}
```
```
{a => A, b => B, c => C}
```

## Expected
`Missing comma in hash initializer` or success.

## Environment
evalable6 at freenode, rakudo-moar cac95fbbc

**Comment by 0racle** [comment]
This is potentially related to RT#130069 which I raised back on 10 Nov 2016 21:03:43.

The bug was found when I was creating a Hash of Rat's

```
> (:foo(11) :bar(22))    # OK
(foo => 11 bar => 22)
> (:foo(1.1) :bar(2.2))
Unknown QAST node type NQPMu
```

Zoffix at the time identified that the first value is accepted ok, but a Rat (or even a constant like `pi`) in any of the subsequent values will also trigger the issue

```
> (:foo(1.1) :bar(22) :baz(33))    # OK
(foo => 1.1 bar => 22 baz => 33)
> (:foo(1.1) :bar(22) :baz(3.3))
Unknown QAST node type NQPMu
```

While I was testing something, I also found another curious issue. Expressions in any other than the first value do not parse correctly

```
> (:foo(1+1) :bar(3+3))
(foo => 2 bar => 3)
> (:foo(1+1) :bar(3+3+3))
(foo => 2 bar => 6)
```

Again, this issue only crops up when omitting the comma.

**Comment by skids** [comment]
Please see (and try out) PR#1858.

**Comment by 0racle** [comment]
I tested your PR and confirmed it resolves the issue... however PR will still need to be reviewed by one of the core dev's before it can be merged.

Below are some quick cheks after merging PR#[1815](https://github.com/rakudo/rakudo/pull/1858/) locally.  
All of the following checks fail in some way on `master`.
```
To exit type 'exit' or '^D'
> say {:a<A> :b<B>, :c<C>}
{a => A, b => B, c => C}
> (:foo(1.1) :bar(2.2))
(foo => 1.1 bar => 2.2)
> (:foo(1.1) :bar(22) :baz(3.3))
(foo => 1.1 bar => 22 baz => 3.3)
> (:foo(1+1) :bar(3+3))
(foo => 2 bar => 6)
> (:foo(1+1) :bar(3+3+3))
(foo => 2 bar => 9)
```

**Comment by skids** [comment]
Yep... understandably core dev attention is a valuable commodity, but hopefully some TUITs will shake free for this... sometime...

Thanks for confirming.

**Comment by lizmat** [comment]
Added test with https://github.com/perl6/roast/commit/56dd56ad41
