### ISSUE TITLE
"is default" seems to work correctly only on scalars

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2871]
## The Problem

It scalarizes arrays and lists if passed as an argument:

```perl6
my @array is default( 1,2,3 ) = <a b c>;
say @array;    # [a b c]
@array = Nil;
say @array;    # [(1 2 3)]
```

## Expected Behavior

Should try and coerce the arguments to the type of the variable, I guess, or at least the general role.

## Environment

`This is Rakudo version 2019.03.1 built on MoarVM version 2019.03`

**Comment by jnthn** [comment]
The `is default` on an array or hash is (by design) talking about the default for the individual elements, and the elements in an array or hash are themselves `Scalar` containers.

Assignment into an `Array` is a copying operation: we iterate the thing on the right, assigning each value into a `Scalar` container in the `Array`. The same happens when we assign `Nil`: we ask for an iterator, and since `Nil` is not `Iterable` so we get an iterator that produces a single `Nil` on iteration, and thus that `Nil` is assigned into a `Scalar` at element 0. The assignment of the `Nil` results in the `Scalar` container taking on its default value, as set.
