### ISSUE TITLE
'a' ~~ / a & a/ # gives Nil. I expected it to match

### ISSUE THREAD

**Issue by cognominal** [rakudo/rakudo#2901]
Tested on the command line. Golfed problem, work around (albeit with sequence point)
> 'a' ~~ / a & a /
Nil
> 'a' ~~ / a && a /
｢a｣

## Environment
Probably irrelevant
* Operating system: MacOS mojave
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.12-245-g94995d60e built on MoarVM version 2018.12-35-gc001ce23c
implementing Perl 6.d.

**Comment by taboege** [comment]
FWIW, quotes around the junction arguments also do the trick:
``` perl6
'a' ~~ / 'a' & 'a' /  #= ｢a｣
```

**Comment by Altai-man** [comment]
Judging from --target=ast, in && case it correctly compiles the expression into `conjseq`, but when `&` is alone, it thinks that `&` is an anonymous variable and tries to match concatenation of `a`, `&` anon var and `a`.

**Comment by Altai-man** [comment]
The bug is somewhere in https://github.com/perl6/nqp/blob/master/src/QRegex/P6Regex/Grammar.nqp rules that produce `concat` in https://github.com/perl6/nqp/blob/master/src/QRegex/P6Regex/Actions.nqp instead of `conjseq`.
So likely all rules that produce `concat` should be checked.
I can't, apparently, debug it further, so don't mind if someone else will look into it.

**Comment by Altai-man** [comment]
Thanks to @jnthn's help at
https://colabti.org/irclogger/iraclogger_log/perl6?date=2019-05-17#l815
https://colabti.org/irclogger/iraclogger_log/perl6?date=2019-05-17#l815
there is a solution, let me send those patches...

**Comment by Altai-man** [comment]
Ok, so fix is available at:
https://github.com/perl6/nqp/pull/540
https://github.com/rakudo/rakudo/pull/2907
and a test is available at
https://github.com/perl6/roast/pull/539
