### ISSUE TITLE
Configure.pl fails with NQP in a different prefix

### ISSUE THREAD

**Issue by niner** [rakudo/rakudo#2919]
```
nine@sphinx:~/test/build/rakudo (master=)> perl Configure.pl --prefix=/home/nine/test/build/install/rakudo/ --with-nqp=/home/nine/rakudo/install/bin/nqp

===SORRY!===
No active backends found. Please, report this bug!

 at /home/nine/test/build/rakudo/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
        NQP::Config::__ANON__("\x{a}===SORRY!===\x{a}No active backends found. Please, report this b"...) called at /home/nine/test/build/rakudo/3rdparty/nqp-configure/lib/NQP/Config.pm line 162
        NQP::Config::sorry(NQP::Config::Rakudo=HASH(0x56552c722f68), "No active backends found. Please, report this bug!") called at /home/nine/test/build/rakudo/3rdparty/nqp-configure/lib/NQP/Config.pm line 312
        NQP::Config::active_backends(NQP::Config::Rakudo=HASH(0x56552c722f68)) called at /home/nine/test/build/rakudo/tools/lib/NQP/Config/Rakudo.pm line 64
        NQP::Config::Rakudo::configure_backends(NQP::Config::Rakudo=HASH(0x56552c722f68)) called at Configure.pl line 92
```

**Comment by vrurg** [comment]
Question similar  to perl6/nqp#544: would it make sense to pick up `nqp` from `PATH`?

**Comment by kazcw** [comment]
The next problem I'm encountering is that current nqp still reports its version as "2019.03" (https://github.com/perl6/nqp/blob/master/VERSION), while rakudo's nqp_want compares as newer: "2019.03-177-g6372077". I presume the solution is to bump nqp's VERSION, although I don't know the conventions around doing that.

Looking at the source, I think it works when gen-nqp is enabled because that code path has a different way of checking the version: it tries to fetch $nqp_want from the git repo, and then assumes what is obtained is the correct version. Maybe it would be prudent to check nqp's reported version even if it has been built from git, so that nqp must pass the same version test no matter where it came from?

**Comment by vrurg** [comment]
@kazcw Could you please provide me with more details about the `VERSION` situation? I don't see what's wrong with it. Are you trying to build against the last release?

Otherwise if you could give a try to #2927. It's very likely not ready yet but at least it builds with `./Configure --with-nqp ~/perl6/bin/nqp --prefix ./install`.

**Comment by kazcw** [comment]
> Could you please provide me with more details about the VERSION situation? I don't see what's wrong with it. Are you trying to build against the last release?

[I've fixed that](https://github.com/kazcw/nixies/commit/0c239c); it was a problem with my packaging. moar was falling back to reporting a less precise version because it didn't have access to its `.git` files when `Configure.pl` ran.

**Comment by kazcw** [comment]
> Otherwise if you could give a try to #2927. It's very likely not ready yet but at least it builds with ./Configure --with-nqp ~/perl6/bin/nqp --prefix ./install.

That's building successfully for me, but there are 2 gotchas before I can run the resulting perl6:
- I have to set NQP_HOME, because otherwise it's looking in a path relative to perl6's prefix
- It's trying to inject some modules into the nqp installation via a path relative to perl6's prefix. As a result, the needed modules wind up in 3 different directories:
    - $nqp_prefix/share/nqp/lib
    - $rakudo_prefix/share/perl6/runtime
    - $rakudo_prefix/share/nqp/lib

If I work around those two issues by copying all the .moarvm files into one hierarchy and pointing NQP_HOME at it, I get a working perl6.

**Comment by vrurg** [comment]
So far I conclude to the following: use of `nqp` from a location different to defined with `--prefix` is a very special case and it is not functional. With or without `--no-relocatable` `perl6` binary cannot dynamically link against `libmoar` unless its and nqp installation prefixes points at the same location. This is what I get on both macOS and Linux. On macOS this couldn't be fixed with an environment variable due to extremely strict rules about where dynamic libraries can be loaded from.

I ended up adding a warning message that non-functional `perl6` is expected if `--prefix` is not where `nqp` found. With `--no-relocatable` it could as well die at this point. But I decided that as long as it compiles and installs a warning should do well enough. I'm finalizing some minor changes and gonna merge them into the `master` today.

With regard to `NQP_HOME` and `.moarvm` modules – I'm not sure if there is any pretty solution to this. Basically, to have things running I had to use both paths to precompiled modules: from `nqp` location and from current build. Perhaps the latter is redundant but as long as it works I don't have time for extra checks. As I see the problem, as long as both `nqp` and `rakudo` install their precompileds two sets of libraries are inevitable. But then again, I'm still pretty much a newbie in this area and can easily miss a thing.

**Comment by vrurg** [comment]
BTW, with regard to your script: `--backends=moar` is not needed when `--with-nqp` is used because in this case the backend would be chosen based on what `nqp` reports.

**Comment by kazcw** [comment]
Separate perl6/nqp/moar directories works on Nix even if it shouldn't because the modus operandi of Nix is to take regular packages that expect to be bathed in one big library soup and install them alone in their own clean spaces, so the Nix stdenv automatically does things like patching the binaries to point at the right dependencies :smile:.

**Comment by vrurg** [comment]
I see... Ok, tell me if the latest changes do the job for you. With regard to modules - it's not something I can help you with now, unfortunately.

**Comment by kazcw** [comment]
Yeah, current master is working for me! I've packaged zef and I'm on to packaging core modules from CPAN. Soon you'll be able to use Nix to do with Raku everything that virtualenv does for python (and more, actually--Nix is crazy powerful)...

**Comment by vrurg** [comment]
Frankly, no idea what Nix is but would have to have a look at now. 

Ok, I'm closing this now. Thank you!

**Comment by niner** [comment]
Configure.pl works now but still throws a huge warning:
```
===WARNING!===
  Installation directory '/home/nine/test/install/rakudo' is different from '/home/nine/rakudo/install' where nqp is installed.
  This may result in non-functional perl6 binary.
  Make sure this is REALLY intended.
```

The same warning reappears multiple times during the build. And indeed the perl6 that gets installed is non-functional:
```
nine@sunshine:~/test/fresh/rakudo (master=)> /home/nine/test/install/rakudo/bin/perl6 -e ''
/home/nine/test/install/rakudo/bin/perl6: error while loading shared libraries: libmoar.so: cannot open shared object file: No such file or directory
```

Re-opening the ticket as the underlying issues are not really fixed.

**Comment by vrurg** [comment]
@niner But the perl6 built this way cannot be functional because it is linked against `libmoar` which is not accessible by `perl6` binary. `LD_LIBRARY_PATH` could have this fixed perhaps on Linux and BSD. But on macOS the only solution is to symlink necessary .dyld into appropriate location. Do we really need this?

**Comment by niner** [comment]
@vrug it may not be functional now but it certainly was quite functional and a normal thing to do just a couple of weeks ago. Thus the issue report for this regression.

**Comment by vrurg** [comment]
@niner No idea how could it be:

```
$ git checkout 'master@{2019-04-10}'
$ ./Configure.pl --prefix ./install --with-nqp ~/perl6/bin/nqp
$ make install
```

ends up with:

>```
>"/Users/vrurg/perl6/bin/moar" --libpath="blib" --libpath="/Users/vrurg/src/Perl6/rakudo-master/install/share/nqp/lib" perl6.moarvm --nqp-lib=blib --setting=NULL --ll-exception --optimize=3 --target=mbc --stagestats --output=CORE.setting.moarvm gen/moar/CORE.setting
>Unhandled exception: While looking for 'ModuleLoader.moarvm': no such file or directory
>   at <unknown>:1  (perl6.moarvm:<dependencies+deserialize>)
>```

My build at least get around this matter. Might it be that you have remains of a previous build in your `--prefix` which left a `libmoar` and precompiled modules behind?

**Comment by niner** [comment]
Then that version was already broken.
I've just tried it with version 2019.03 of MoarVM, nqp and rakudo and everything works as expected. No warnings and the three cooperate even with different prefixes.

**Comment by patzim** [comment]
I think this currently can't work when building the stack relocatable. I don't think there is much of a point to try to support that.
It should work though when building the stack non-relocatable. I'll have a look in the evening.
I'm pondering whether we should make `--no-relocatable` the default and add a `--relocatable` arg instead.

**Comment by vrurg** [comment]
Considering that installation into a stable directory is the most popular use case making `--no-relocatable` the default makes sense to me.

**Comment by patzim** [comment]
I debugged my way trough the NQP and Rakudo build. I got stuff mostly working. But now I am confronted with a conceptual problem.

In the case of separate prefixes for NQP and Rakudo the concept of the home dirs falls apart. Rakudo is in part written in NQP and thus installs NQP libraries. Those are currently installed into `PREFIX/share/nqp/lib/Perl6`. The `share/nqp` folder is the so called `NQP home dir`. So Rakudo installs stuff into the NQP home. That's fine until one tries to install Rakudo into a different prefix than NQP. In that case we have two different `share/nqp` folders. One in NQP PREFIX and one in Rakudo PREFIX.

Different approaches come to mind:
- Scratch the idea of `NQP home` and `Rakudo home` altogether.
- Let Rakudo install its NQP libraries into the NQP prefix. (That is probably a bad idea.)
- Don't allow installation into different prefixes.

@niner, @vrurg, @kazcw Do you have any suggestions / input?

**Comment by patzim** [comment]
The changes I did to get it working (with the exception of the above described problem) are in:
https://github.com/patzim/rakudo/tree/reloc-fix
https://github.com/patzim/nqp/tree/reloc-fix
https://github.com/patzim/nqp-configure/tree/reloc-fix

**Comment by vrurg** [comment]
How can you scratch the concept of homes? Whatever we change the fact that both NQP and Rakudo install precompiled modules won't change. Moreover, the `ModuleLoader.moarvm` Rakduo initialy compiles into `blib` is not accepted as a valid one when requested by a building Perl6 script. To get it running I had to add `nqp` directories to `perl6-m` runner command line. 

I'm not happy about Rakudo installing into NQP unless they're installed under the same prefix.

I currently don't see a good solution for all this. Surely not for the relocatable build. Perhaps your third option is applicable here.

The non-relocatable one could be made happy by hard-coding library paths into the binary and the scripts.

**Comment by kazcw** [comment]
[What I've been doing](https://github.com/kazcw/nixies/blob/master/perl6/rakudo.nix#L30) is taking the `Perl6` directory that rakudo tries to put into NQP_HOME and moving it into PERL6_HOME with rakudo's other modules. This seems to be working, but I don't know if there's some reason not to do it this way.

**Comment by vrurg** [comment]
@kazcw That seems to be ok with Nix where you basically create a single package out of moar+nqp+rakudo (if I'm not mistaken here). But for most other packages it could be very confusing of occasionally rakudo would overlap with nqp by a couple of files.

**Comment by kazcw** [comment]
@vrurg I'm building them as 3 separate packages; each installs to its own immutable directory. That's why the fixup is needed: rakudo normally tries to install modules into nqp's namespace, but that isn't allowed on Nix, so it ends up putting them in a directory like $rakudo_prefix/share/nqp. My one-liner fix moves the contents of that franken-directory into $rakudo_prefix/share/perl6.

**Comment by patzim** [comment]
@vrurg I'm only concerned about the non-relocatable case here.

The *homes* idea I was talking about has nothing to do with user homes or some such. It's a new concept I introduced when doing the relocatability refactor. The idea is that both, Perl6 and Rakudo have a folder called their home folder. They are `$PERFIX/share/nqp` and `$PREFIX/share/perl6` respectively. All the files they need are located somewhere in those home folders. All those "Where are my files?" questions are reduced to "Where is my home folder?". The non-relocatable case just has them hard-coded. In the relocatable case they are searched. It's also possible to set them with environment variables.

Droping the idea of these home directories means just having a list of library search paths and a list of repository paths. Those lists are then not part of any larger concept anymore. That's the way it was before I started the refactor.

@kazcw I think I don't fully know the reasoning for the separate `nqp` and `perl6` directories. Currently the `nqp` dir contains files that where originally written in the NQP language and the `perl6` directory only contains files that where originally written in Perl6. The distinction is not that meaningful, as they are both compiled to some bytecode which is indistinguishable from then on. There might be another reason for having the files separated this way. Maybe @niner or @ugexe can shed some light here. If there are no other reasons we might just be able to install the `share/nqp/lib/Perl6` files into `share/perl6/lib/` or `share/perl6/lib/Perl6` right away. I'm adding that as a fourth option above.

**Comment by patzim** [comment]
@vrurg There are two `ModuleLoader.moarvm`s. The one of NQP and the one of Rakudo. Rakudo needs both. To get a working perl6 it is necessary to have NQP in the library search paths (as most of Perl6 is written in NQP).

**Comment by niner** [comment]
share/perl6 is managed by CompUnit::Repository::Installation, same as share/perl6/vendor and share/perl6/site. In hindsight I would very much have liked to split them into share/perl6/core, share/perl6/vendor and share/perl6/site, i.e. get rid of the nesting. Maybe we can still do this and thus make space for a share/perl6/lib? The core repository only contains the couple of modules that are shipped with rakudo, i.e. something that gets installed with the new rakudo version anyway. Leaving behind the old files may not be pretty, but also not really do any harm.

**Comment by patzim** [comment]
@niner Just so I understand correctly:
- share/perl6 is a CURI
- share/perl6/lib is under CURI control and currently can't be repurposed
- share/perl6/[runtime,vendor,site] just happen to not be used by CURI and are thus ok to exist
- You propose to move the CURI in share/perl6 to share/perl6/core which frees up all folders in share/perl6
- Doing that just might not cause much backwards compatibility breakage because only rakudo core stuff is installed there which would be installed into the new location with every new build.
- The old stale CURI files in share/perl6 may be tolerable.
- You are in favor of [the fourth approach above](https://github.com/rakudo/rakudo/issues/2919#issuecomment-496312812) to move the stuff in share/nqp/lib/Perl6 to share/perl6/lib(/Perl6?)

**Comment by niner** [comment]
@patzim it's all correct except for the bit about share/perl6/lib. That directory is not used by CURI. Looks like it's actually a leftover from the pre-CURI era. We used to install the precompiled Perl 6 modules there that ship with rakudo (i.e. Test.moarvm)

**Comment by patzim** [comment]
@niner The task to move the share/perl6 CURI to share/perl6/core and the task to install the things in share/nqp/lib/Perl6 to share/perl6/lib are unrelated? If yes we can tackle them separately. I'd start with installing the share/nqp/lib/Perl6 things into /share/perl6/lib as that's what is blocking my work on this ticket.
