### ISSUE TITLE
Error when loading module via -Ilib when lib/ contains symlinks (linux)

### ISSUE THREAD

**Issue by dmaestro** [rakudo/rakudo#2960]
## The Problem
I have a test directory where `lib` contains syminks
I attempt to load a module referenced through this symlink.
```
perl6 -Ilib -MModule::Loader -e {}                         
```
## Expected Behavior
No errors.

## Actual Behavior
```
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.

Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.

===SORRY!===
Cannot resolve caller new(IO::Path:U: Any:U, :CWD(Str)); none of these signatures match:
    (IO::Path: Str $path, :$SPEC = { ... }, Str:D :$CWD, *%_)
    (IO::Path: Str $path, :$SPEC = { ... }, :$CWD = { ... }, *%_)
    (IO::Path: Cool $path, :$SPEC = { ... }, :$CWD = { ... }, *%_)
    (IO::Path: :$basename!, :$dirname = "", :$volume = "", :$SPEC = { ... }, :$CWD = { ... }, *%_)
    (IO::Path: *%_)
```
perl6 -v
doug@ender:~/opensource/perl6/test$ uname -a
Linux ender 4.4.14 #2 SMP Fri Jun 24 13:38:27 CDT 2016 x86_64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz GenuineIntel GNU/Linux

## Steps to Reproduce
```
lib
├── Math -> ../../Math-Precise/lib/Math
├── Module -> ../../Module-Loader/lib/Module
...
```
This works fine with Rakudo* 2018.10
## Environment
* Operating system: 
uname -a
Linux ender 4.4.14 #2 SMP Fri Jun 24 13:38:27 CDT 2016 x86_64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz GenuineIntel GNU/Linux
* Compiler version (`perl6 -v`): 
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by ugexe** [comment]
fwiw I'm leaning towards DIHWIDT. It ""worked"" fine in rakudo 2018.10 in that it did what you expect in this specific scenario, but you cannot e.g. put symlinks in META6.json so there should be no expectation that you can do this with `-Ilib` (which attempts to create a META6 representation). At best it could **ignore** anything that isn't a file, because everything in a distribution must share a common root/prefix.

**Comment by dmaestro** [comment]
OK, I've got a bit more to learn about how distributions are defined and used - I'm actually studying that now, but haven't found good resources explaining it so far. Trying to figure it out by experimenting. So, the behavior I'm seeing changed in the newer version of Perl 6 is intended and "more correct"? The explanation about the relationship between -I and META6 is helpful.

**Comment by ugexe** [comment]
Parts of the newer version of Perl 6 are indeed "more correct". Nothing specifically was changed for handling symlinks, but the fact they worked before was coincidence and not an intentional design choice.

I'm not sure there is any good resources explaining module loading. Consider that best practice is to use `-I.` (pointing at a META6.json containing directory). When using `-Ilib` it cannot look 1 directory up for a `META6.json` file because then there is a conflict if the *current* directory also contains a `META6.json`. So `-Ilib` (pointing at a directory *not* containing a `META6.json`) will attempt to create a META6 representation, and that itself involves something like `$repo-prefix ~ '/' $module-relative-path` (with the expectation that `$module-relative-path` is *not* outside of `$repo-prefix`). You can probably extrapolate some more information by looking at `CompUnit::Repository::FileSystem` (which handles `-I.` / `-Ilib`). Run the following two examples from the root of a distribution and note the differences:

```
say CompUnit::Repository::FileSystem.new(prefix => $*CWD.absolute).distribution.meta
```
```
say CompUnit::Repository::FileSystem.new(prefix => $*CWD.add('lib').absolute).distribution.meta
```

For instance: In the second case the `version` is `*` even though the first version will show whatever version is in the `META6.json` because the version cannot be guessed like we do creating module names from paths.

**Comment by dmaestro** [comment]
@ugexe Thanks for the help. I'll close this, and consider adding to the docs if I find something essential missing.
