### ISSUE TITLE
Lazy Load Included Subroutines?

### ISSUE THREAD

**Issue by kawaii** [rakudo/rakudo#2973]
In many of my projects I generally end up having a `common.pm6` unit package with some subroutines which are used all over the code-base, it mostly just helps to avoid code duplication. Can we perhaps theorise ways the optimiser can be extended to only load subroutines from included packages that are actually used?

**Comment by jnthn** [comment]
This already effectively happens, though in a way such that Rakudo itself barely has to care. Until the first call of a sub, MoarVM won't bother:

* Deserializing most of metadata about register/lexical types in the sub (saving time and memory)
* Parsing and validating the bytecode (saving time)

Furthermore, imports are placed into the lexpad, and we don't deserialize things referenced there until their first access either, which also saves some time and memory.

Similar happens with types too, which is why we can have the hundreds of exception types in `CORE.setting` and not spend time on their deserialization/bytecode unless we actually need them.
