### ISSUE TITLE
has-phasers doesn't return true for some phasers (e.g., CATCH, CONTROL)

### ISSUE THREAD

**Issue by MasterDuke17** [rakudo/rakudo#2990]
`{ LEAVE { when X::IO { note "i/o error"; } } }.has-phaser("LEAVE").say;` returns `1`, but `{ CATCH { when X::IO { note "i/o error"; } } }.has-phaser("CATCH").say` returns `0`.

**Comment by lizmat** [comment]
True.  But that’s because CATCH / CONTROL are special phasers, that maybe even shouldn’t be  called phasers.  In any  case, CATCH/CONTROL are **not** called wrt something that happens with the Block they are associated to.  So they don’t need to be in there, for that reason.

However, maybe it *is* an idea to actually add them to the Block for introspection purposes.

**Comment by lizmat** [comment]
@jnthn thoughts about the performance effects of adding `CATCH` and `CONTROL` phasers to the `Block` phasers hash, purely for introspection purposes?

**Comment by jnthn** [comment]
`has-phaser` and similar methods are very much an implementation detail and not part of the language spec. The whole mechanism of them being attached to a `Block` was not added to give folks a way to introspect them, but rather because parts of the standard library or other internals needed to be able to obtain them and invoke them.

I'm planning a re-work of how `LEAVE` and friends are implemented in the not too distant future to address various performance issues, and it's not clear that they should remain in the runtime phasers hash beyond that, because the new approach won't need them to be there. Moreover, having to install them in the phasers hash forces thunking even block-less `LEAVE` phasers, whereas in principle we should be able to generate code without doing that.

Probably we do need to spec a way to get hold of phasers like `LAST`, `FIRST`, and `NEXT` for the sake of those implementing `map`-alike things on custom types. For everything else, I'd say that if there is a desire to do stuff with them, it'd be an AST-level access, where of course they are represented and introspectable and tweakable (including `CATCH` and `CONTROL`), but without implying memory overhead by having to keep them in the hash until runtime.
