### ISSUE TITLE
1..^* needs to give a warning

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3010]
See https://github.com/rakudo/rakudo/commit/35b69f074b9db3ffeb1638fc8a548fc2c0643d5a and related tickets.

Basically, `1..^*` is identical to `1..*` meaning that in the most cases it is a user error (it does not DWIM). Therefore, it needs an error message that suggests to use `*-2`.

**Comment by taboege** [comment]
The commit you mention makes a `0..^*` range subscript return the same as the `0..*-1` whatever code subscript. So, just to clarify, the suggestion in the warning should be to use `*-1` not `*-2`?

**Comment by AlexDaniel** [comment]
@taboege `*-2`, because looking at the things I had to fix ([one](https://github.com/Kaiepi/p6-Digest-BubbleBabble/pull/1), [two](https://gitlab.com/uzluisf/quine-mccluskey/merge_requests/1)), people seem to actually want that kind of behavior (“a bunch of elements except last”). But maybe the warning can actually suggest both (“use * to mean all elements or *-2 for all elements except last”).

**Comment by taboege** [comment]
Ah, right, I confused myself into thinking `*-1` was already the second-to-last element — even though admittedly the English languages makes it hard to make this mistake :-)

**Comment by lizmat** [comment]
Please note that you can also use `.head` to not show the last `N` elements of a `Seq`:

    $ perl6 -e 'dd (^10).head(*-3)'
    (0, 1, 2, 3, 4, 5, 6).Seq

**Comment by lizmat** [comment]
Looking into the previous fix, I think we're on the wrong path here  :-(

- `1..*` should be *exactly* the same as `1..Inf`
- `1..^*` should be *exactly* the same as `1..^Inf`
-  `^*` should be *exactly* the same as `0..^Inf`

And I think the latter is wrong, as it produces a `WhateverCode` rather than a `Range`.  Call this `WhateverCode` with a value, and you get a `Range`:

Also, many people (myself included) have used `^Inf` as a short way write `0..Inf`.

I think this is worthy of a problem solving repo entry, and I'm afraid not a very good first issue  :-(

**Comment by lizmat** [comment]
Closing since nobody was interested to make this a problem solving issue
