### ISSUE TITLE
Infinite loop when passing a pair with a junction in the key to a sub with destructuring

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3027]
Code:
```perl6
sub ztask( (:$key, :$value) ) {}; ztask ‘foo’.any => ‘bar’;
```

Result:

Infinite loop with one core at 100%

Bisected: (2016-09-21) https://github.com/rakudo/rakudo/commit/3ed51de3973d1bd46a6f94dad84f30f2d7de41d5

Previously:
```
cannot stringify this
  in sub ztask at /tmp/TNpwF1HLY2 line 1
  in block <unit> at /tmp/TNpwF1HLY2 line 1
```

Which isn't particularly great but at least it errors out instead of hanging forever.

**Comment by jnthn** [comment]
This one too:

    sub foo([$a]) { }
    foo([1.any])

Basically, any time you destructure something and there's a junction on the inside of it. The auto-threader doesn't know how to do such involved cases of auto-threading, and making it do so would be pretty fraught. Probably for now we should simply detect the case of a sub-signature wishing to auto-thread and promote it to an (informative) error.

The commit in question fixed a problem where the majority of errors reported in a sub-signature bind would explode with "cannot stringify this" instead of giving a useful error. It was just luck that this bug prevented the infinite recursion being reached.

**Comment by jnthn** [comment]
Bed time for me now, but I suspect an easy fix is to replace the `return $result` just below the error-handling code in the linked commit with `return $BIND_RESULT_FAIL`.

**Comment by melezhik** [comment]
if this it's supposed to throw _now_?

```
[r3@6523d917496c r3tool]$ RAKUBIN=/tmp/whateverable/rakudo-moar/15d372e2f666d837d1437f49a3ac8eeaabd19349/bin/raku tomty  3027
[repository] :: index updated from file:///home/r3/repo/api/v1/index
==================================================
[https://github.com/rakudo/rakudo/issues/3027]
==================================================

[3027] :: cat $root_dir/task.bash
[3027] ::
[3027] :: $RAKUBIN -v
[3027] ::
[3027] :: $RAKUBIN -e 'sub ztask( (:$key, :$value) ) {}; ztask ‘foo’.any => ‘bar’;'
[3027] ::
[3027] :: Welcome to Rakudo(tm) v2021.05-20-g15d372e2f.
[3027] :: Implementing the Raku(tm) programming language v6.d.
[3027] :: Built on MoarVM version 2021.05-14-g0a62f0c6a.
[3027] :: stderr: Type check failed in binding to parameter '$key'; expected Any but got Junction (any("foo"))
  in sub ztask at -e line 1
  in b
[3027] :: stderr: lock <unit> at -e line 1

[3027] :: task exit status: 1
[3027] :: task 3027 FAILED
```

**Comment by lizmat** [comment]
Yeah, that was the intent.

**Comment by melezhik** [comment]
Something changed here on the latest Rakudo?

The example used to fail with

```
Type check failed in binding to parameter '$key'; expected Any but got Junction (any("foo"))
```

Now it still fails ( correct behavior ) but does not now show any message 

```
20:40:44 :: [https://github.com/rakudo/rakudo/issues/3027]
20:40:44 :: ==================================================
20:40:44 :: 
20:40:44 :: [task run: task.bash - 3027]
20:40:44 :: [dump code: task.bash]
20:40:44 :: [1] 
20:40:44 :: [2] $RAKUBIN -v
20:40:44 :: [3] 
20:40:44 :: [4] timeout 2 $RAKUBIN -e 'sub ztask( (:$key, :$value) ) {}; ztask ‘foo’.any => ‘bar’;' 2>&1
20:40:44 :: [5] 
20:40:44 :: [6] echo
20:40:44 :: [7] 
20:40:44 :: [8] 
20:40:44 :: [task stdout]
20:40:44 :: 20:39:03 :: Welcome to Rakudo™ v2024.09.
20:40:44 :: 20:39:03 :: Implementing the Raku® Programming Language v6.d.
20:40:44 :: 20:39:03 :: Built on MoarVM version 2024.09.
20:40:44 :: 20:39:03 :: 
20:40:44 :: 20:39:03 ::   in sub ztask at -e line 1
20:40:44 :: 20:39:03 ::   in block <unit> at -e line 1
20:40:44 :: 20:39:03 :: 
20:40:44 :: 20:39:03 :: 
20:40:44 :: [task check]
20:40:44 :: stdout match (s) <Type check failed in binding to parameter '$key'; expected Any but got Junction (any("foo"))> False
20:40:44 :: stdout match (s) <in sub ztask at -e line 1> False
20:40:44 :: =================
20:40:44 :: TASK CHECK FAIL
```
https://sparky.sparrowhub.io/report/gh-melezhik-r3tool/22682

**Comment by melezhik** [comment]
^^ @lizmat

**Comment by lizmat** [comment]
Fixed again with https://github.com/rakudo/rakudo/commit/5ff3eafef4
```raku
% raku -e 'sub ztask( (:$key, :$value) ) {  }; ztask ‘foo’.any => ‘bar’'
Unknown binding error in sub-signature
```
Tried (in vain) to fix the binding error: the binder in the bootstrap (being one of the oldest pieces of code in what is now Raku) could probably benefit from a total rewrite at some point, with today's knowledge and example of how (not to) do it instead of the bootstrapping needed in 2011.
