### ISSUE TITLE
6.c and `Int < 0`

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3051]
There is a roast test that was recently changed: https://github.com/perl6/roast/commit/d60f851775c2e5944db00f946b39430250243809

It needs to be changed in 6.c-errata too, but I'm failing to find a good ustification for it.

Basically, things like `Int < 0` now only give a warning.

Output on all releases:
* `say Int < 0` https://gist.github.com/eaa77b6c023d8f6850956405b48dd214
* `say Int + 0` https://gist.github.com/e51dfe0c33cb5515befead515591d9e9

It does seem to make some things more consistent, like `my Int $x; say $x + 5` is now functionally similar to `my $x; say $x + 5`. That said, I think the argument can be made either way, so should 6.c spec be changed?

**Comment by AlexDaniel** [comment]
Ping @jnthn, @lizmat, @timo and others :)

**Comment by AlexDaniel** [comment]
Ah, for the record, Blin didn't find any module that is affected by this. However, it doesn't mean that there's no code out there depending on the previous behavior.

**Comment by vrurg** [comment]
I'm surely biased here because it was my change. But the point was, as you noticed, unification with other types where similar cases are resulting in "undefined in <type> context" warning. At the moment of impleneting the fix the error message was the middle one from Blin's output:

`Invocant of method 'Bridge' must be an object instance of type 'Int', not a type object of type 'Int'.  Did you forget a '.new'?`

Which is nothing else but pure confusion.

Sure, my vote would be in favor of migrating it into `6.c-errata`.

**Comment by AlexDaniel** [comment]
I filed https://github.com/perl6/problem-solving/issues/62. I don't think that something being inconsistent with other similar cases can be a justification for changing a released language version.

I think we're better off reverting it now and thinking of ways we can introduce the fix in a separate ticket (in the problem-solving repo).

**Comment by lizmat** [comment]
Since we're already post 2019.07 and I doubt we'll see a 2019.08 due to conference season, and we have a problem solving ticket, I think we can leave it in for now.

**Comment by AlexDaniel** [comment]
@lizmat we're not exactly post 2019.07. To release 2019.07, I need 6.c-errata tests to pass. They currently don't due to this issue. Either we revert this, or cherry-pick the change into 6.c-errata and 6.d-errata.

**Comment by lizmat** [comment]
Then by all means, revert.

**Comment by vrurg** [comment]
I'm for reverting then too.

**Comment by AlexDaniel** [comment]
OK, will do that shortly.
