### ISSUE TITLE
True xor True returns Nil

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3106]
## The Problem

Since this commit cefbda4b12d760722075cd904b3ab211be627ca2 that's what happens.

## Expected Behavior

It should return False. xor is a Boolean operation, it should always return a Boolean value.

**Comment by chloekek** [comment]
Would like to know the reasoning for the current behavior. Perhaps because then you can tell apart False xor False from True xor True?

Btw Roast has a test for this: https://github.com/perl6/roast/blob/b9bfe1844db25f65a4aeb351a0107f83689cb5c2/S03-operators/short-circuit.t#L161

**Comment by JJ** [comment]
Funnily enough, the test description does not match what is actually tested.

**Comment by pmichaud** [comment]
```xor``` is _not_ an operator with a Boolean return value; it's in the same category as ```infix:and``` and ```infix:or``` which return one of their arguments.  (Both ```infix:and``` and ```infix:or``` return their last argument if the condition isn't met; ```infix:and``` short-circuits and returns the first argument evaluating as false in boolean context; ```infix:or``` short-circuits and returns the first argument evaluating as true in boolean context. They don't coerce to a Boolean return value.)

The ```xor``` operator is also a chained operator such that it returns a "true" argument if it's the only true argument in the chain.  So, given an expression like

````$a xor $b xor $c xor $d```

the ```infix:xor``` operator returns whichever argument is true as long as it's the only one evaluating to true.  If all of the arguments are false then the last argument gets returned; upon reaching a second true argument ```xor``` short-circuits and returns ```Nil``` to indicate that the "exactly one is true" condition had failed.

This was a discussion point in the early design of Perl 6, it was decided that the chaining behavior was desirable because it's easy to use parens to get the non-chaining behavior from a chained ```xor``` but really hard to get the "exactly one" behavior otherwise.  It's also intended to be somewhat analogous to ```infix:^``` and ```one(...)``` junctions, which look for exactly one true argument from a sequence.

Hope this helps,

Pm

**Comment by JJ** [comment]
So @chloekek rationale went in the right direction, but in that case, and in true Perl 6 fashion, something like `False but Nil` should be returned, or maybe, as you mention, a Junction should be returned (one or none) instead of logical values. This Nil is not really coherent with the commonly accepted definition of xor.

**Comment by pmichaud** [comment]
To be clear:  I'm not suggesting that xor should return a Junction.   

To me it's okay that Perl 6 xor doesn't fit the commonly accepted definition; there was a time when Perl's || and && also didn't fit the commonly accepted definition of "or" / "and" (which were assumed to return boolean values).

```False but Nil``` feels wronger to me than either ```False``` or ```Nil```.

The notion that "xor" should return a boolean isn't consistent with the rest of Perl 6.  None of the other short-circuiting operators return booleans; many of them return undefined values.  It' s not clear why xor should be coerced to a boolean result.  And there are plenty of places where Perl intentionally goes against the "commonly accepted definition" of things in order to provide a more useful, consistent, and coherent semantic.

Pm

**Comment by lichtkind** [comment]
thanks pattrick, when first reading about this i was struggeling but yes this sounds reasonable. But i still looking for an easy exit out of this issue.

**Comment by chloekek** [comment]
A believe you can negate infix operators like this: x !^^ y

Can you also booleanize them like this? x ?^^ y

**Comment by GuyJoKing** [comment]
The operator you are looking for is [`?^`](https://docs.perl6.org/routine/%3F$CIRCUMFLEX_ACCENT):

> Boolean bitwise XOR operator: Coerces the argument(s) to Bool and performs logical XOR on them: it will return True if and only if just one of the argument is true. 

```
say True  ?^ True;   # False
say False ?^ True;   # True
say True  ?^ False;  # True
say False ?^ False;  # False
```

`x ?^^ y` is parsed as `x ?^ (^y)
