### ISSUE TITLE
It's apparently impossible to create a set of iterables.

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3118]
## The Problem

Arrays and lists can't be set elements:

```
> say set([True,True],[False,False])
set(False True)
> say set([1,0],[0,1])
set(0 1)
> say set((1,0),(0,1))
set(0 1)
> say set(<1 0>,<0 1>)
set(0 1)
> say set((<1 0>,<0 1>))
set(0 1)
> say set((<a b>,<b a>))
set(a b)
```

They are iterated over and a set with the elements of the array is created instead.

## Expected Behavior

In DWIM fashion, there's theoretical nothing that bans iterables from being elements of a set. It would be useful for certain operations.

## Actual Behavior

All iterables are iterated, and an array with its elements is created instead. If you itemize the arrays, it will work:

    say set($(1,0),$(0,1)); # set((0 1) (1 0))

It makes sense after the fact, but it's not too DWIM.

## Environment

perl6 2019.07.1

**Comment by vrurg** [comment]
`Set.new` works as expected.

[Documentation](https://docs.perl6.org/type/Set#sub_set) actually clearly states this behavior by providing `set`'s signature:

```
sub set(*@args --> Set)
```

To change this is it's like a finger click, I tested locally with `sub set(|c)` which would just shortcut to `Set.new`. The change passes spectests. But since it's one of the fundamental things it has to be passed through and approved on problem-solving.
