### ISSUE TITLE
Different defaults in IO::Socket::Async and IO::Socket::INET result in broken S32-io/socket-recv-vs-read.t

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#3128]
## The Problem

_S32-io/socket-recv-vs-read.t_ is broken if `localhost` resolves to IPv6 `::1`.

## Expected Behavior

Test must pass.

## Actual Behavior

Fails with:

```
No such method 'recv' for invocant of type 'Any'
```

## Notes

Test fails because `IO::Socket::Async` creates a listening socket on the (first?) address it gets from resolving `localhost`. If that resolves to `::1` then this is where we get the socket. Verified with `netstat`.

`IO::Socket::INET`, on the contrary, has explicit default to bind to IPv4 addresses.

The test creates a listening socket and then tries to connect back to it. Correspondingly, connection fails due to different socket families.

## Environment
* Operating system: macOS 
* Compiler version (`perl6 -v`): This is Rakudo version 2019.07.1-175-gac707d2ae built on MoarVM version 2019.07.1-72-g352ae27e4

**Comment by Kaiepi** [comment]
This was probably introduced with https://github.com/MoarVM/MoarVM/pull/1126/commits/d189b29bc3d1d6b9fbba92c02fb6c8b28f27ca29. `IO::Socket::INET` used to completely ignore the family passed to it and always use whatever the upper bits of the port happened to be as the family, which was usually `AF_UNSPEC`. Now that it actually uses the family given, it should probably be using that as the default instead of `AF_INET` to prevent more code like this from breaking.

**Comment by Kaiepi** [comment]
This should be fixed with https://github.com/rakudo/rakudo/commit/d7d8d37edd. I was able to get my FreeBSD box to resolve `localhost` to `::1` by default, so it's been tested.

**Comment by vrurg** [comment]
@Kaiepi confirm the fix for macOS too. Thank you!
