### ISSUE TITLE
Class with 'is hidden' trait doesn't dispatch to its parent.

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#3197]
## The Problem

If a class is declared with `is hidden` trait then methods of this class do not re-dispatch to a parent class.

## Steps to Reproduce

The code:

```
class Foo {
    method m { say "Foo" }
}
class Bar is hidden is Foo {
    method m { say "Bar"; nextsame }
}
Bar.new.m;
```

outputs just:

```
Bar
```

removal of `is hidden` trait produces expected output of:

```
Bar
Foo
```

Tested on HEAD, 2019.07, 2019.03.

**Comment by lizmat** [comment]
What *is* `is hidden` supposed to do on a class.  I can't seem to find any documentation on it?

**Comment by vrurg** [comment]
@lizmat [skips the class from method dispatch](https://docs.perl6.org/routine/hides).

**Comment by vrurg** [comment]
Though seemingly it's used nowhere, not even in the core. Wonder what is it supposed to be serving for?

**Comment by codesections** [comment]
I believe this is intentional (but under-doc'ed).  According to [S12](https://design.raku.org/S12.html#Interface_Consistency)

> If you mark a class "is hidden", it hides the current class from "nextsame" semantics

That's slightly vague about whether it's just supposed to prevent the `hidden` class's methods from being _called_ in by `nextsame` or if it should also prevent them from using `nextsame` (the current behavior).  But, because `is hidden` stops those classes from getting a `*%_` parameter (something I just learned recently and doc'ed in Raku/doc#4032), I'm pretty sure that `is hidden` is supposed to prevent the class from being either a re-dispatchee or a re-dispatcher.

If that's right, we can close this issue (though should add a note in the docs).

**Comment by lizmat** [comment]
@coke closing assuming a note was added

**Comment by coke** [comment]
the linked PR was merged by JJ, yes.
