### ISSUE TITLE
add auto pack/unpack capability for installed module resource files

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3200]
## The Problem

Currently installed modules have their resource/ files stored uncompressed.

## Expected Behavior

The installed modules resource directory files should be automatically packed when installed, and unpacked when needed by the user.  Such a capability should be made backwardly compatible with existing installations' resouce files.

## Actual Behavior

Resource directory files are not compressed.

**Comment by jnthn** [comment]
> The Problem
>
> Currently installed modules have their resource/ files stored uncompressed.

Please can you explain why this is a problem? Decompression has both the obvious cost of having to perform the decompression itself, but would also makes memory mapping less effective (multiple processes couldn't just share one mapped copy of the resource, but would all have to have their own decompressed copy in memory). Memory is typically a scarcer resource than disk space.

Also, there's nothing to stop a module that thought it could benefit from this from shipping its resources compressed and then decompressing them using its choice of compression library.

**Comment by ugexe** [comment]
There is already https://github.com/ugexe/Perl6-CompUnit--Repository--Tar as a proof of concept. However it has flaws.

1) There would be a start-up speed penalty for having to do this for every module. Hence you're unlikely to see such a thing in the core.

2) Unfortunately `%?RESOURCES` ended up where people were encouraged to use `%?RESOURCES<foo>.IO`. In `CompUnit::Repository::Tar` no files are ever extracted to disk -- everything is extracted as needed into memory -- *except* for resources because of this (see: [CURT resources implementation](https://github.com/ugexe/Perl6-CompUnit--Repository--Tar/blob/1593ff6ea779efae3d6a27da924a38373a8d5857/lib/CompUnit/Repository/Tar.pm6#L223-L240)). If `%?RESOURCES` worked similar to `$*DISTRIBUTION` by giving a Reader/Writer interface instead of an `IO::Path` this wouldn't be a problem, but changing that would be a story in itself (if possible at all).

3) Native libs often expect to be on the file system itself, not itself located inside an e.g. zip file or calling paths that are themselves in a zip file.

---

My guess is if you really need the compression then a different filesystem might be the better answer.

**Comment by tbrowder** [comment]
Okay, you both have convinced me.  I will happily close this. And thanks for listening.
