### ISSUE TITLE
allow human JSON (hjson) in META6.json file

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3203]
## The Problem

Currently, the META6.json file requires JSON formatting which is very strict and is
designed for machine-to-machine use. Consequently it does NOT allow such
niceties as comments, trailing commas in lists, bare strings without spaces, etc.

See module [JSON::Hjson](https://github.com/akyim/JSON-Hjson) for more information.

## Proposed Solution

Replace all instances of JSON\* with JSON::Hjson.

**Maybe this should be filed wherever tool chain issues are filed.**

**Comment by ugexe** [comment]
This would require any tooling (even non-perl6 tooling) to also support hjson instead of just the extremely common regular JSON. For instance: PAUSE/CPAN would need to be updated to allow hjson which I imagine they would not care to do.  

As an alternative one could create an e.g. META6.yaml file that they also have a script to generate the META6.json from (i.e. make an authoring tool handle it).

**Comment by tbrowder** [comment]
Good point ref CPAN, bummer!

**Comment by lizmat** [comment]
Hmmm... I'm not 100% sure that PAUSE actually looks at the insides of a META6.json file.  The fact that the file exists, means it's a Perl 6 distribution, which means it will be stored in an auto-generated "Perl6" subdirectory.  So allowing HJSON could possibly have no effect on PAUSE.

It **would** of course have implications for the `zef` backend logic.

**Comment by AlexDaniel** [comment]
> zef backend logic

A lot of other tools and scripts too. I have some for sure. Maybe these should use `zef` as a library to parse them, but I don't know if that's actually currently possible.

**Comment by vrurg** [comment]
@tbrowder If this helps, I use `META6` module and a script to generate `META6.json`. This allows for even more niceties.

**Comment by ugexe** [comment]
> Hmmm... I'm not 100% sure that PAUSE actually looks at the insides of a META6.json file.

Yes, it does. That is how the `source-url` gets set to the cpan url.

**Comment by niner** [comment]
There's a lot of code out there that processes META6.json files. For example https://github.com/niner/meta2rpm used for creating RPM packages for modules. Despite having been bitten by JSON's strictness myself, I still would not like to put the burden of complicated parsing on all the tools. A simple cleanup script that parses META6.json with JSON::Hjson and writes it out with JSON would fix the issue on the authoring side.

**Comment by lizmat** [comment]
Then I suggest we close this issue.

**Comment by tbrowder** [comment]
A cleanup script is one solution, but it doesn't lend itself to easy automation, depending on the user's dev setup. I just filed an issue with Metacpan asking them for a looser JSON standard for acceptance.

Maybe, in the interim, zef could have a JSON linter embedded.

**Comment by bbkr** [comment]
Do people have issues with JSON syntax?
Modules are developed by programmers.
I doubt taking template and replacing few strings is beyond their skills.

We should stay with pure JSON as waaaaaay more common standard.

BTW: Can we detect such mistakes on CI level? How about checking module structure (including META.json check) in default script before invoking actual _prove_ ?

**Comment by ugexe** [comment]
> Can we detect such mistakes on CI level? How about checking module structure (including META.json check) in default script before invoking actual prove ?

zef doesn't need a validation step because:

1) zef should not be seeing invalid META6.json if its connected to a well behaved ecosystem. If an ecosystem is serving distributions with bad META data then one is free to not use it.

2) zef is not an authoring tool, so authoring functionality is left to tools that specialize in it. If someone is writing bad `META6.json` then they should use an authoring tool.

**Comment by tbrowder** [comment]
Hokay, I give up!
