### ISSUE TITLE
I can slice with a list of slices, but only sometimes

### ISSUE THREAD

**Issue by grimnebulin** [rakudo/rakudo#3206]
## The Problem

Perl 6 allows me to slice with a list of slices, but only sometimes.

## Expected Behavior

No expected behavior, per se.  This is something I stumbled across that seems to behave inconsistently.

## Steps to Reproduce

> my @array = 9 ... 0
[9 8 7 6 5 4 3 2 1 0]
> @array[map { $_, $_ + 1 }, ^9]
((9 8) (8 7) (7 6) (6 5) (5 4) (4 3) (3 2) (2 1) (1 0))

This seems to show that I can provide a list of list of indices to postcircumfix:<[]> and get back a list of slices.  But when I tried to clean up my code a bit, it broke.

> my @index = map { $_, $_ + 1 }, ^9
[(0 1) (1 2) (2 3) (3 4) (4 5) (5 6) (6 7) (7 8) (8 9)]
> @array[@index]
(7 7 7 7 7 7 7 7 7)

Then I thought that map usually returns a Seq, so I tried:

> @array[@index.Seq]
(7 7 7 7 7 7 7 7 7)

Then I tried:

> @array[@index.List]
((9 8) (8 7) (7 6) (6 5) (5 4) (4 3) (3 2) (2 1) (1 0))

That works again, but it's unclear why it works in some cases but not others.  Arguably, slicing shouldn't "work" the way it does in my first example, since I'm not aware that giving a list of slices is an intended feature, so that may be the actual bug.  Either way, there's an apparent lack of consistency.

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`): 2019.03.01

**Comment by jnthn** [comment]
This is a result of two consistently applied behaviors:

1. An array is made up of `Scalar` containers for each element, so the assignment into the array itemizes each assigned value. Iterating the array thus gives `$(0 1)`, `$(1 2)`, etc. (Thus `@index.Seq` would not be expected to change anything, since it obtains `.iterator` on `@index` and wraps it in a `Seq`.)
2. Indexing respects itemization - that is, it will not descend into an item, but rather treat it as something to index with - and thus numify. This where the index `2` comes from: each sublist has 2 items, and lists numify to their element count. This is a general behavior of indexing - and indeed respecting itemization is done consistently through the language.

The reason that `.List` changes things is that it produces a `List` that has each item of the array with its container removed.

There's multiple ways to do this more nicely, including not imposing any context:

```
my \index = map { $_, $_ + 1 }, ^9;
@array[index]
```

Or creating the `List` in the first place:

```
my @index is List = map { $_, $_ + 1 }, ^9;
@array[@index]
```

Both of which, as well as being correcter, are more efficient.
