### ISSUE TITLE
Please add "unit module MyModule;" to the checker

### ISSUE THREAD

**Issue by ToddAndMargo** [rakudo/rakudo#3296]
Dear Perl 6 Developers:

$ cat /etc/redhat-release 
Fedora release 31 (Thirty One)

Releases tested under Fedora 31:

From https://github.com/nxadm/rakudo-pkg/releases
    rakudo-pkg-Fedora29-2018.11-01.x86_64.rpm
    rakudo-pkg-Fedora29-2019.03.1-01.x86_64.rpm
    rakudo-pkg-Fedora30-2019.03.1-03.x86_64.rpm
    rakudo-pkg-Fedora30-2019.07.1-03.x86_64.rpm
    rakudo-pkg-Fedora31-2019.07.1-03.x86_64.rpm

From Fedora 31 repo:
    rakudo-0.2019.03-4.fc31.x86_64

To my absolute PANIC, after upgrading from Fedora 30 to Fedora 31, all my Perl programs that used my customer modules were failing.  The modules were found and read, but the subs inside the modules could not be found.  Most of these are used in system administration and IT WAS A REALLY BIG DEAL!  

An example:
$ GetPublicIP.pl6
===SORRY!=== Error while compiling /home/linuxutil/./GetPublicIP.pl6
Undeclared names:
RunNoShell used at lines 19, 23
WriteSecondaryClipboard used at line 24

And that was 90% or so of the time, depending on the moon overhead.  Most of the time my programs bombed out, like above but OCCASIONALLY THEY WORKED!  And they ALL worked in Fedora 30, ALL THE TIME!

An army of Perl experts jumped to my rescue.   I transpired that the problem was of my own doing.  I did not have "unit module _MyModule_;" (substitute module name for MyModule) declared as the first line of most of my modules.  Adding the line completely solved the issue.

You can see some of the help I got over at:
https://github.com/nxadm/rakudo-pkg/issues/58, and on
perl6-users <perl6-users@perl.org>:FC31 can't find my module subs

Considering the trouble I went through with Fedora 31 and the fact I could not reproduce on Fedora 30 and other could also not reproduce, would you consider adding "unit module _MyModule_;" as a compiler error (perl6 -c) for all modules encountered?

Many thanks,
-Todd

**Comment by treyharris** [comment]
@ToddAndMargo, your problem sounds quite frustrating, and as a system administrator myself I sympathize, but your request _to Rakudo devs_ is a bit difficult to understand as stated. If you don’t mind, let me try to restate your request in a more concrete a way?

The issue was that you made what you feel is an obvious and boilerplate error—namely, omitting the necessary `unit` package declaration for exports to work properly—and what you’d have liked is if Rakudo gave a warning of this mistake, which you feel is basically typographical so it should be possible to DWIM or at least infer you probably didn’t mean precisely what you said, correct? (If this paraphrase is inaccurate please stop me here, as the rest of what I write is irrelevant if my problem restatement is wrong.)

I’m sure I don’t need to tell you that modules are not the only kind of unit packages, nor that a `.pm6` file may include any number of non-unit package declarations—so it isn’t an error for a `.pm6` file to lack a `unit module` declaration—nor, in fact, a `unit` declaration of any kind. It might be a `unit package`, a `unit class`, `unit role`, `unit grammar` or even a `unit sub` (though arguably that last is only by analogy to the others since it doesn’t create a package). It could also lack any `unit` declaration at all, and instead declare one or more scopes using blocks (i.e., `module Foo { ... } class X::Foo { ... } grammar BarParser` etc.).

The question arises: is there usefulness in a `.pm6` file that never declares any packages at all? 

Well, one thing I wanted to check some time ago was if phasers were different in these two circumstances. Please refer to [treyharris/phaser-testing](https://github.com/treyharris/phaser-testing) to see the code I used to determine this. Two executables, _test-phasers_ and _test-unit-phasers_ do `use TestPhasers;` and `use TestUnitPhasers;` respectively, and, as the names suggest, _lib/TestPhasers.pm6_ contains bare code without any package declarations while _lib/TestUnitPhasers.pm6_ contains [the line](https://github.com/treyharris/phaser-testing/blob/f715b5a10a1663a11bcf63bee152f477da49831c/lib/TestUnitPhasers.pm6#L1):

```perl6
unit module TestUnitPhasers;
```

The answer to the phaser question is no—phasers do not behave differently in a `.pm6` compunit depending on the presence or absence of packages. But I’d direct you to another difference. Both scripts include a line

```perl6
foo();
```

and both scripts run with the same output. But while _TestUnitPhasers.pm6_ contains [the line](https://github.com/treyharris/phaser-testing/blob/be8c4233e9fae258a17772da213d1fddbe0f0561/lib/TestUnitPhasers.pm6#L13):

```perl6
sub foo () is export { say "foo() called" }
```

_TestPhasers.pm6_ contains instead [the line](https://github.com/treyharris/phaser-testing/blob/f715b5a10a1663a11bcf63bee152f477da49831c/lib/TestPhasers.pm6#L13)

```perl6
our sub foo () { say "foo() called" }
```

This last shows: there _is_ usefullness in `use`-ing a package-less `.pm6` compunit: it exists in the `GLOBAL` package, just as the main executable script does.

This can be useful in creating utilities, command-line interfaces (such as by including a `proto` for `MAIN` in the script and `multi MAIN` declarations in loaded files for an easy sort of plug-in support), and loading of constants or configuration-as-code.

All this was a roundabout way of saying, if I’ve correctly understood your request, it _can_ be done: Rakudo _could_ warn or fail if a `.pm6` file has neither any `unit` declarator nor any block package declarators. But if so, there is undoubtedly code (even in the ecosystem) that depends on the current behavior and would need to suppress the warning, or be entirely rewritten in the case of failure—rewritten in a way that could be argued is good from a software engineering standpoint, but quite annoying from either a TMTOWTDI or a Making the Easy Things Easy and the Hard Things Possible point of view.

Since packages that munge the language with slangs and pragmas are and have always been useful things in Perlish languages, it feels to me like this request should be carefully considered, and, if it’s actually judged desirable, phased in with an opt-in warning before becoming default behavior.

**Comment by ToddAndMargo** [comment]
Hi Tray,

I am afraid I am not smart enough to follow what you asked.

Maybe if I show how I import and declare module subs would help:

My PrintColors.pm6 module (now) starts with:

      unit module PrintColors;

and all the exported subs are declared suchlike:

     sub PrintGreen ( **@args ) is export( :PrintGreen ) { print color('bold'), color('green'), |@args, color('reset'); }

I import them suchlike:

      use PrintColors  :PrintGreen;

I do this purposely so that every sub I import can be located and no guessing where they came from.  This is for maintainability.

Under Fedora 31, but not prior versions, if my modules do not begin with “unit module MyModule;”, all heck breaks loose.  I reproduced this on a clean, never touch by Perl 6 Virtual machine of Fedora 31, as well.

Does this help what you are after?

-T

**Comment by treyharris** [comment]
> Under Fedora 31, but not prior versions, if my modules do not begin with “unit module MyModule;”, all heck breaks loose. I reproduced this on a clean, never touch by Perl 6 Virtual machine of Fedora 31, as well.
> 
> Does this help what you are after?

I may not have read every single thread of every linked issue (though I thought I did). It is unclear to me that the issue described as in this statement was reproduced in isolation.

So let’s just make 100% sure about this: can you please create a repo uploaded to GitHub containing code such that a _commented out_ line

```perl6
# unit module PrintColors;
```

works on pre-Fedora 31, but fails on Fedora 31, and verify with a cut-and-paste of the output (including error messages if any) that simply uncommenting this line—that one-character change, removing the comment marker—makes it work on both pre-Fedora 31 and Fedora 31?

**Comment by treyharris** [comment]
> So let’s just make 100% sure about this: can you please create a repo uploaded to GitHub containing code such that a _commented out_ line

A Gist is fine, too, if you can create a multi-file Gist. Or even an uploaded tarball.

**Comment by jonathanstowe** [comment]
It would also be useful to know which specific versions of Rakudo were packaged for which versions of Fedora so that this can be reproduced without having to change operating system.

**Comment by ToddAndMargo** [comment]
Still trying to figure out the other question, but this is the packages repo from Fedora 31:

# dnf whatprovides rakudo
Last metadata expiration check: 0:04:33 ago on Sat 16 Nov 2019 02:33:11 PM PST.
rakudo-0.2019.03-4.fc31.x86_64 : Perl 6 compiler implementation that runs on
                               : MoarVM
Repo        : fedora
Matched from:
Provide    : rakudo = 0.2019.03-4.fc31

# dnf whatprovides rakudo-zef
Last metadata expiration check: 0:04:48 ago on Sat 16 Nov 2019 02:33:11 PM PST.
rakudo-zef-0.7.4-2.fc31.x86_64 : Perl6 Module Management
Repo        : fedora
Matched from:
Provide    : rakudo-zef = 0.7.4-2.fc31

**Comment by ToddAndMargo** [comment]
Okay, that I have every one of my modules using "unit module MyModule", I can uncomment one modules unit line and get no issues either way.  Keep in mind that my problem was only repeatable 90% of the time.  If you keep running the same program over and over, sometimes it works (feels like and uninitialized variable).   Adding "unit module MyModule" to every one of my modules completely solved the issue.

Also, on the two remaining Fedora 30 servers I administer, I have not made the adjustment to my modules and they work perfectly.

So not to beg the issue, but is "unit module MyModule" SUPPOSE to be there or not?  I was led to believe by Tom that it was and he was the one that identified the problem for me.  If it "is" suppose to be there, then the checker (perl6 -c) should have kicked it out when it did not find it,

And When trying to put together a simple example to demonstrate the issue, I came up with something rather odd - - the opposite of what I would expect

<ModuleTest.pl6>
#!/usr/bin/env perl6
use lib '.';
use ModTest :ModuleTest, :ModuleTst;
ModuleTest;
ModuleTst;
</ModuleTest.pl6>

<ModTest.pm6>
#unit module ModuleTest;
sub ModuleTest() is export( :ModuleTest ) { say "ModuleTest"; }
sub ModuleTst()  is export( :ModuleTst )  { say "ModuleTst"; }
</ModTest.pm6>

$ ModuleTest.pl6
ModuleTest
ModuleTst

Removing the comment from ModTest.pm6:
$ ModuleTest.pl6
WARNINGS for /home/linuxutil/ModuleTest/./ModuleTest.pl6:
Useless use of constant value ModuleTest in sink context (line 4)
ModuleTst

And if I swap the two sub line (uncomment "unit"), I get
$ ModuleTest.pl6
WARNINGS for /home/linuxutil/ModuleTest/./ModuleTest.pl6:
Useless use of constant value ModuleTest in sink context (line 4)
ModuleTst

Uhhhh, there is no line 4 either

If you guys still want to see PrintColors.pm6 or CurlUtils.pm6, I can upload them to vpaste.

**Comment by ToddAndMargo** [comment]
And it gets weirder.  This is from my Fedora 31 qemu-kvm virtual machine that had never had Perl 6 on it before;

$ cat ModuleTest.pm6
unit module ModuleTest;
sub ModuleTst()  is export( :ModuleTst )  { say "Bye"; }
sub ModuleTest() is export( :ModuleTest ) { say  "Hi"; }

$ perl6 -I. -e 'use ModuleTest :ModuleTest, :ModuleTst; ModuleTest; ModuleTst;'
WARNINGS for -e:
Useless use of constant value ModuleTest in sink context (line 1)
Bye


$ cat ModuleTest.pm6
# unit module ModuleTest;
sub ModuleTst()  is export( :ModuleTst )  { say "Bye"; }
sub ModuleTest() is export( :ModuleTest ) { say  "Hi"; }

$ perl6 -I. -e 'use ModuleTest :ModuleTest, :ModuleTst; ModuleTest; ModuleTst;'
Hi
Bye

**Comment by ToddAndMargo** [comment]
> It would also be useful to know which specific versions of Rakudo were packaged for which versions of Fedora so that this can be reproduced without having to change operating system.

Did I forget to answer this?

I am currently using
https://github.com/nxadm/rakudo-pkg/releases
rakudo-pkg-Fedora31-2019.07.1-03.x86_64.rpm
