### ISSUE TITLE
Should sort *always* call the Callable given?

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#3318]
Currently, because of optimisation reasons, the `Callable` given in `sort` is **not** being called when trying to sort a list that has 0 or 1 elements:

    $ raku -e 'dd ().sort( &die )'
    ().Seq
    $ raku -e 'dd (1).sort( &die )'
    (1,).Seq
    $ raku -e 'dd (1,2).sort( &die )'
    12
      in block <unit> at -e line 1

Perhaps it should, for possible side-effects?

For reference, Perl does **not** call the given block either for 0 or 1 element arrays:

    $ perl -E 'my @a; say sort { die } @a' 

    $ perl -E 'my @a = (1); say sort { die } @a'
    1
    $ perl -E 'my @a = (1,2); say sort { die } @a'
    Died at -e line 1.

**Comment by vrurg** [comment]
I think it still shouldn't. Think of the following: the code block gets two parameters. What shall be passed in as an argument for a missing value? There is no good answer for this because any value could be held as an array value. And then how the code block distinguish the value we pass in as a "no value" from the same thing but coming from an array? Say, we choose to pass in `Nil`, then for the code block there be no difference between `(1,)` and `(1,Any)`, or between `( )` and `(Any, Any)`.

Besides, if our code knows that a list will always contain definite values then it's sufficient to have as simple as `sort { $^a cmp $^b }` piece of code. But if we would run it against <2 elem lists one would have to add extra checks to handle those situations properly. This is also likely to break some of the already existing code too.

As to your example with die, expecting it to explode is no different from expecting `if 1 < 0 { die }` to throw. And in either case, I don't feel it's right for the conditional block to die intentionally. Perhaps, the error condition is better be checked outside of the sort?

**Comment by jnthn** [comment]
I think it's entirely reasonable for `sort` to not call the block - even an arity-1 block - in the case of 0 or 1 values in the incoming iterable.

**Comment by lizmat** [comment]
Then I hereby close this issue.
