### ISSUE TITLE
trans method hangs when use `/^/` as left side of `=>`

### ISSUE THREAD

**Issue by ohmycloud** [rakudo/rakudo#3325]
## The Problem

`trans`  method hang and run forever when the left side of `=>` is `/^/`.

## Expected Behavior

At least the following code will return:

    'aabcc'.trans: /^/ => '-' # expected output: 'aabcc'

However, Perl's `tr` function works as expetced:

    my $string = 'aabcc';
    $string =~ tr/^/-/;
    print $string;  # aabcc

this [question/answer](https://stackoverflow.com/questions/57660797/trans-function-hang-forever-when-work-with-a-single-or) on stackoverflow have the similar confusion.

## Actual Behavior

    hangs and never returns.

## Steps to Reproduce

use raku shell or create a raku script:

    say 'aabcc'.trans: /^/ => '-'; 

## Environment

* Operating system:  macOS Catalina 10.15.1  
* Compiler version (`perl6 -v`): 

    This is Rakudo version 2019.11 built on MoarVM version 2019.11
    implementing Perl 6.d.

**Comment by taboege** [comment]
Let me say this first: the Perl code you posted works just as well with Raku (only by replacing Perl's binding with Raku's smartmatch). The reason for that is that the `tr///` operator treats its arguments as strings (in both languages). In Raku it would call `$string.trans: '^' => '-'`, note `'^'` vs. `/^/`, and give you the desired result. Transliteration based on regex matches is a specialty of `trans`, not of `tr`, and Perl doesn't support it, so you're comparing different things.

As for your actual problem: `/^/` as a regex is a guaranteed match of length zero (at the beginning of the string) all of whose matches you want to be replaced. This loops infinitely just like `"aabcc" ~~ /(^)*/` would: it matches, doesn't advance the cursor, matches again, …

Maybe lessons can be learned from [Perl in that regard](https://perldoc.pl/perlre#Repeated-Patterns-Matching-a-Zero-length-Substring) (because that last bit of code does terminate in Perl) but this would be a wider issue affecting how regexes in general match that I don't know whether it has been considered already.
