### ISSUE TITLE
implicit type change of uint8 to Int

### ISSUE THREAD

**Issue by MARTIMM** [rakudo/rakudo#3343]
## The Problem
When copying data from an CArray[byte] the values turn to Int instead of UInt. uint8, which is the same, has the same effect.

## Expected Behavior
```
> use NativeCall
> my CArray[byte] $ba .= new( 255, 254, 3, 4);
NativeCall::Types::CArray[byte].new
> $ba[0].WHAT
(UInt)
> $ba[0..*-1]
( 255 254 3 4)
```
## Actual Behavior
```
> use NativeCall
> my CArray[byte] $ba .= new( 255, 254, 3, 4);
NativeCall::Types::CArray[byte].new
> $ba[0].WHAT
(Int)
> $ba[0..*-1]
(-1 -2 3 4)
```
In addition, it is possible to initialize with negative numbers!
```
> CArray[byte].new(-1)[0]
-1
> [my uint8 $i=-1][0]
255
my uint8 $i=-1
255

```
Other tests also show problems but the values stay positive;
```
> uint8.WHAT
(uint8)
> [uint8][0].WHAT
(uint8)
> [my uint8 $i=255].WHAT
(Array)
> [my uint8 $i=255][0].WHAT
(Int)
> [my uint8 $i=255][0]
255
> [my UInt $i=255][0].WHAT
(Int)
```
## Steps to Reproduce
use REPL to see the results

## Environment
* Operating system:
```
> uname -a
Linux h03-fedora 5.3.6-100.fc29.x86_64 #1 SMP Mon Oct 14 21:48:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

* Compiler version (`perl6 -v`): This is Rakudo version 2019.11-133-gea575dacb built on MoarVM version 2019.07.1-403-g9442b1a7c
implementing Perl 6.d.

**Comment by chloekek** [comment]
This seems to happen with all types that smartmatch Int, due to this conditional:

https://github.com/rakudo/rakudo/blob/9a571b68513aecdcf7f9b5fd140ba8875ee53be8/lib/NativeCall/Types.pm6#L202-L204

Weirdly, int8 and int16 also smartmatch UInt:

```
> say $_ ~~ Int for (int8, int16, uint8, uint16);
OUTPUT: «True␤True␤True␤True␤»
> say $_ ~~ UInt for (int8, int16, uint8, uint16);
OUTPUT: «True␤True␤True␤True␤»
```

**Comment by niner** [comment]
No, the uint -> Int conversion issues go much deeper. Rakudo will happily turn native unsigned ints into signed Ints at the first opportunity. I think there are multiple issues leading to the same result. E.g. MoarVM only has an HLL mapping for Int, but not UInt. But even when I add that, the result is still the same, because of those other issues. UInt is just a subset of Int, which means that all UInts are also Ints. That's good for compatibility, but requires lots of care to not lose the type. It just shows that UInts were added later and support doesn't seem to be finished yet.

I fear that we need input from our architect @jnthn on whether the current subset approach can actually work and how the solution would look like, so that I or someone else interested in working with bytes can implement this.

**Comment by niner** [comment]
This is now fixed as of https://github.com/rakudo/rakudo/commit/8bba2aec43c14ad9a2ce5a00d2333b46cad30c14

While the array member's type gets still reported as `Int`, you will now get the correct values:
```
> use NativeCall
Nil
> my CArray[byte] $ba .= new( 255, 254, 3, 4);
NativeCall::Types::CArray[byte].new
> $ba[0].WHAT
(Int)
> $ba[0..*-1]
(255 254 3 4)
```

Would you be so kind to contribute a PR with a test to Rakudo?

**Comment by lizmat** [comment]
Test added with https://github.com/rakudo/rakudo/commit/0e9a0ee3e6
