### ISSUE TITLE
Supply.lines is surprisingly different from IO.lines

### ISSUE THREAD

**Issue by dakkar** [rakudo/rakudo#3384]
## The Problem

`Supply` has `method lines(Supply:D $self: :$chomp = True )`

`IO::Path` has `method lines(IO::Path:D: :$chomp = True, :$enc = 'utf8', :$nl-in = ["\x0A", "\r\n"], |c)` (that `|c` gets propagated to `IO::Handle.lines` which understands `$limit, :$close` or just `:$close`)

## Expected Behavior

The two methods should be more similar. In particular, `:enc` and `:nl-in` seem, to me, to not be file-specific: a socket's Supply, for example, is probably going to be used like a file stream.

## Environment
* Compiler version (`perl6 -v`): This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1

**Comment by AlexDaniel** [comment]
Yeah, and newline handling is by default different too, if I'm not mistaken.

**Comment by lizmat** [comment]
FWIW, I don't think `Supply.lines` should have an `:enc` parameter: that would seem to be more appropriate in how the `Supply` is actually created.  FWIW, am working on a `:nl-in` parameter implementation.

**Comment by dakkar** [comment]
`IO::Socket::Async::Supply` already has a `:enc` parameter, so we're good on that front

**Comment by lizmat** [comment]
Looks like I will need to add some extra functionality to `Str.split` to make that easier.

**Comment by dakkar** [comment]
alternatively, `Supply` (or a text-oriented subclass of it) could be made more similar to `IO::Handle`?

**Comment by lizmat** [comment]
Suggesting that indicates to me that you don't really grok the difference between a `Supply` and an `IO::Handle`  :-)

**Comment by lizmat** [comment]
c63d8a87d1 gives `Supply.lines` an `:nl-in` parameter that takes a `Cool`.  Multiple line-endings will have to wait until the next decade  :-)

**Comment by jnthn** [comment]
On a design note: since methods calls are interpreted according to the language of the receiving object, then their exact behavior and capabilities can be expected to vary somewhat. This isn't a reason for needless inconsistency, but it is a warning against foolish consistency. For example, `unique` on a `Supply` lets you talk about uniqueness per time, which makes sense in the asynchronous `Supply` paradigm, but not in the blocking iterative paradigm, so we'd not expect `Iterable.unique` to gain that.

For this particular example:

* It's natural that `IO::Path.lines` takes a few extra options, because its job is not just to obtain lines, but along the way to obtain a handle to the file too; thus, some of its arguments are not aimed at delegation to `lines`, but rather at `open`.
* A `:close` option on `Supply.lines` makes no sense, given how `Supply` resource management works
* It's true that `Supply.lines` could do with a way to indicate what we mean by a line, and that's the obvious missing thing here. I'm not so sure if `nl-in` makes sense as the name for it, alas. (It probably didn't for `IO::Path.lines` either, since in that use case it's obvious we're talking about input.)

**Comment by jnthn** [comment]
Ah, and I forgot: there's also [`Str.lines`](https://docs.raku.org/type/Str#routine_lines), which should arguably also get a way to define what a newline means.

**Comment by lizmat** [comment]
Well, as I said, maybe this kind of functionality should really be part of a `Supply.splt` ?

**Comment by jnthn** [comment]
@lizmat Perhaps so.

**Comment by jnthn** [comment]
@lizmat It's also telling that `nl-in` on `IO::Path.lines` is not actually an option aimed at the delegation to `IO::Handle.lines`, but rather at `IO::Handle.open`.

**Comment by lizmat** [comment]
Yeah, so really this is about splitting the incoming chunks, rather than abusing the `lines` metaphor for splitting on arbitrary strings, as the result will most likely not be a logical "line".

**Comment by lizmat** [comment]
Closing this now since we have an implementation of `Supply.split` now.  Please re-open if you disagree.
