### ISSUE TITLE
Direct token smartmatching produces unexpected .pos values

### ISSUE THREAD

**Issue by alabamenhu** [rakudo/rakudo#3410]
## The Problem

Smartmatching against token by itself (outside of a regex/grammar) seems to generate unexpected `.pos` values.  This was discovered in some stack exchange comments: https://stackoverflow.com/questions/59620302/is-it-possible-to-interpolate-array-values-in-token

## Expected Behavior

```
my $a = token { 'a' <?{ say self.pos }> 'a' }; 'xxxxxaa' ~~ $a;
my token b { 'b' <?{ say self.pos }> 'b' }; 'xxxxxbb' ~~ /<b>/;
```

This code should print `5` twice, as that is when the first token match occurs.

## Actual Behavior

Code prints `0` and then `5`.  In both cases, however, the `.orig` method indicates the *correct* original string, which means trying to capture previous characters by using some variant of `self.orig.substr( self.pos ± $foo )` will cause unexpected results.

## Steps to Reproduce
See above.  Code avaiable on [TIO](https://tio.run/##K0gtyjH7/z@3UkElUcFWoSQ/OzVPoVpBPVFdwca@WqE4sVKhODUnTa8gv1ih1g4sXmutoF4BAolATl0dUKM1F1A/RGsSSHMSDs1JSJqTksCa9W2S7PStuf7/BwA):

**Comment by jnthn** [comment]
The `self` that a token/rule receives is actually the cursor of its parent; it then creates its own (since backtracking is just throwing away the cursor). That is bound into `$/`, and so the correct way to write these is:

```
my $a = token { 'a' <?{ say $/.pos }> 'a' }; 'xxxxxaa' ~~ $a;
my token b { 'b' <?{ say $/.pos }> 'b' }; 'xxxxxbb' ~~ /<b>/;
```

Which both correctly output `6` (the `5` is actually also wrong with regards to the original string, just differently wrong because in this case it's the parent that is doing the scanning).
