### ISSUE TITLE
Figuring out +^

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3435]
## The Problem

While checking out Raku/doc#2177, I'm trying to figure out what +^ really does. The documentation says it performs two's complement, but according to the Wikipedia article it points to, it does nothing ot the sort. The actual code uses NQP's `bitneg`, which I assumed to be actual negation of bits, as in substitute every bit by its complement. However, that does not seem to be the case. 

The example in roast is:

    is +^1, -2, '+^1 == -2 as promised';

Which, apparently, puts a 0 in front of 1, turning it in 01, and then inverts it (10). Eventually it puts a - in front of the whole thing, which is kind of surprising. But let's try that hypothesis for 2: it returns -3, which is totally surprising. 2 is 10, let's put a 0 in front, 010, and then negate it, 101, which is 5 and not -3.

## Expected Behavior

I don't really know. It all boils down to bitneg, I guess. It that's the case, I'll have to check out the result.

## Actual Behavior

Not really sure. Uses bitneg.

## Environment
* Operating system: 
* Compiler version (`perl6 -v`): 

Latest version of Rakudo.

**Comment by JJ** [comment]
I'm checking out [tests in NQP](https://github.com/perl6/nqp/blob/c7f4dfe9e13d37a9d4886355f962927397abae0c/t/nqp/060-bigint.t) and apparently bitneg_I is always used with 1, or rather box(1). In [this code](https://github.com/rakudo/rakudo/blob/0e9f96ea9206a7431860bef888d6813b65778ab9/src/core.c/Int.pm6#L517), it's used with `Int`.

**Comment by niner** [comment]
The behaviour makes total sense in terms of bitwise negation (which it is implemented as), just not in terms of the documented two's complement.

What happens currently is that we just flip all the bits. To take a byte as example, decimal 1 would be 00000001 binary. The bitwise negation turns that into 11111110, which interpreted as a signed number would be -2 decimal (11111111b is -1d). To get to the promised two's complement, we'd have to add 1 to the result of the negation. Then +^1 will become 1.

I'm not sure however that we actually want the two's complement. The only thing requiring two's complement I can find in the design documents is "Note that Int assumes 2's complement arithmetic, so +^1 == -2 is guaranteed." in which the text does not match the code.

The part in Synopsis 3 is a little clearer:
"prefix:<+^>, numeric bitwise negation
    +^$x
Coerces to Int and then does bitwise negation on the number, returning an Int. (In order not to have to represent an infinitude of 1's, it represents that value as some negative in 2's complement form.)"

This no longer requires us to implement a two's complement, but only says that the result can be interpreted as a two's complement of _some_ number. The number to be determined by bitwise negation. Having `+^` create a two's complement wouldn't actually make sense, since we already have prefix `-` for that.

So I argue that the behaviour is actually correct, but the documentation is not. Prefix `+^` is a bitwise negation operator (that's actually one's complement).

**Comment by JJ** [comment]
El lun., 20 ene. 2020 a las 9:01, niner (<notifications@github.com>)
escribió:

> The behaviour makes total sense in terms of bitwise negation (which it is
> implemented as), just not in terms of the documented two's complement.
>
> What happens currently is that we just flip all the bits. To take a byte
> as example, decimal 1 would be 00000001 binary. The bitwise negation turns
> that into 11111110, which interpreted as a signed number would be -2
> decimal (11111111b is -1d). To get to the promised two's complement, we'd
> have to add 1 to the result of the negation. Then +^1 will become 1.
>

All the 8 bits? Closest multiple of 8 bits? Little endian or big endian?

We would have to add 1, and then negate it to go from -2 through -1 to 1.

I mean, you're OK with closing the issue. I just wanted to figure out what
it's doing.

> I'm not sure however that we actually want the two's complement. The only
> thing requiring two's complement I can find in the design documents is
> "Note that Int assumes 2's complement arithmetic, so +^1 == -2 is
> guaranteed." in which the text does not match the code.
>
And that's precisely what's in roast.

> The part in Synopsis 3 is a little clearer:
> "prefix:<+^>, numeric bitwise negation
> +^$x
> Coerces to Int and then does bitwise negation on the number, returning an
> Int. (In order not to have to represent an infinitude of 1's, it represents
> that value as some negative in 2's complement form.)"
>

OK, get it. Probably the existing explanation would have been extracted
from that.

This no longer requires us to implement a two's complement, but only says
> that the result can be interpreted as a two's complement of *some*
> number. The number to be determined by bitwise negation. Having +^ create
> a two's complement wouldn't actually make sense, since we already have
> prefix - for that.
>
> So I argue that the behaviour is actually correct, but the documentation
> is not. Prefix +^ is a bitwise negation operator (that's actually one's
> complement).
>
Thanks.

**Comment by JJ** [comment]
+^255 is -256. Which I guess is 1111 1110 0000 0000 That means it's extended to the closest 8-bit multiple, and then interpreted as a negative, so this becomes -256 (0000 0001 1111 1111) negated. 
OK, I think I get it now.  Thanks!
