### ISSUE TITLE
UTF-16 encoding emits non-UTF-16

### ISSUE THREAD

**Issue by fecundf** [rakudo/rakudo#3461]
## The Problem
`> "foo".encode('utf16')
utf16:0x<66 6F 6F>`
## Expected Behavior
Result should all be two-byte-wide UTF-16 chars, perhaps with a byte-order mark at the start
eg
`utf16:0x<66 00 6F 00 6F 00>`

## Actual Behavior
Invalid UTF-16 buffer

## Environment
* Operating system: OSX
* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.11 built on MoarVM version 2019.11
implementing Perl 6.d.

**Comment by jonathanstowe** [comment]
Isn't it just the way the gist is displaying it?  It is six bytes long.

**Comment by fecundf** [comment]
I'm only seeing 3 bytes
> "foo".encode('utf16').list
(102 111 111)

**Comment by lizmat** [comment]
$ r 'dd "foo".encode("utf16")'
utf16.new(102,111,111)

The `utf16` indicates two byte values.

**Comment by jonathanstowe** [comment]
Just to make it clear:

```
my $f = "xx".IO.open(:w, :bin);

$f.write: "foo".encode('utf16');
$f.close;

$f = "xx".IO.open(:r, :bin);

my $b = $f.read(6);

say $b;

say $b.decode('utf16');

```

Gives:

```
Buf[uint8]:0x<66 00 6F 00 6F 00>
foo
```

**Comment by ugexe** [comment]
```
$ perl6 -e 'say "foo".encode("utf16").bytes'
6
```

**Comment by samcv** [comment]
@fecundf what are you trying to achieve? As some others have hinted, utf16 buffers in Rakudo are stored as arrays of 16 bit unsigned integers.

How are you using the resulting buffer? In other words, is there some negative results you are seeing that I don't see written in your comment?

If the problem is just how `.gist` displays it, then this is probably not a bug. But then again there could be issues you haven't mentioned when you use the buffer.

**Comment by fecundf** [comment]
Thanks all, I wasn't seeing what was plainly in front of me, there is no bug here. jonathanstowe's example is especially helpful. Closing.
