### ISSUE TITLE
Incorrect path to set-env scripts in README.md

### ISSUE THREAD

**Issue by rypervenche** [rakudo/rakudo#3482]
I noticed that the scripts directory does not exist as the README.md file shows in three files:

tools/build/binary-release/Linux/README.md:    $(scripts/set-env.sh)
tools/build/binary-release/MacOS/README.md:    $(scripts/set-env.sh)
tools/build/binary-release/Windows/README.md:    C:\path\to\this\folder\scripts\set-env.bat
tools/build/binary-release/Windows/README.md:    . C:\path\to\this\folder\scripts\set-env.ps1

These should use "bin" instead of "scripts".

I wasn't sure if anything else needed to be changed.

**Comment by Altai-man** [comment]
Maybe @patrickbkr can confirm it is indeed a thinko / leftover rather than some other case?

**Comment by patrickbkr** [comment]
I'm actually not sure these should be in bin. Stuff in the bin folder will probably end up in PATH. I'm not sure people want that. Especially given that this script sets up PATH. So we have two alternatives:

- Put them in `bin/`
    - Con: The scripts will end up in PATH
- Put them in `scripts/`
    - Con: We litter the folder with a `scripts` folder.

Any opinions?

**Comment by vrurg** [comment]
I'd vote for `scripts` that would be an analog to `libexec`. 

BTW, `set-env.sh` itself is rather incorrect because it only considers Bourne shell family ignoring `csh` branch where they use `setenv`. Not talking about `fish` which is different from both. Thus, `scripts` would make more sense as over time we should get `set-env` versions for different shell families.

**Comment by patrickbkr** [comment]
OK. Then `scripts/` it is.
@rypervenche: Are you willing to create a PR?
