### ISSUE TITLE
`is rw` trait applied to roles does not work

### ISSUE THREAD

**Issue by voldenet** [rakudo/rakudo#3495]
## The Problem
`is rw` trait applied to roles does not work

## Expected Behavior
```
> role X is rw { has $.x; }; (X.new.x = 4).say
4
```

## Actual Behavior
```
> role X is rw { has $.x; }; (X.new.x = 4).say
Cannot modify an immutable 'Any' type object
  in block <unit> at <unknown file> line 1
```

## Environment
rakudo-moar 8c995febd
camelia on freenode

**Comment by lizmat** [comment]
What is wrong with `role X { has $.x is rw; }; (X.new.x = 4).say` ?

**Comment by vrurg** [comment]
@lizmat I think the question is about having a default for all role attributes.

The issue is actually actual for any role application. The initial approach was designed purely for classes, as it seems. The `rw` is set per-attribute by `compose_attributes` but should probably be done by `add_attribute`.
