### ISSUE TITLE
react/whenever is not serialized by default

### ISSUE THREAD

**Issue by rypervenche** [rakudo/rakudo#3547]
## The Problem
Using react with whenever does not produce a serialized Supply.

## Expected Behavior
The code block should only be run once, therefore only showing `"Test"` once.

## Actual Behavior
Runs the code block each time ctrl+C is pressed.

## Steps to Reproduce
```
react whenever signal(SIGINT) {
    say "\nTest";
    sleep 5;
    exit;
}
```
Running the code and then immediately pressing ctrl+C multiple times.

## Environment
Gentoo
```
This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
implementing Raku 6.d.
```

**Comment by AlexDaniel** [comment]
Oops.

**Comment by AlexDaniel** [comment]
OK, it's not as severe as I thought. @jnthn++ comment:

> \<jnthn\> AlexDaniel: Because there's a special case for a single-whenever react and apparently it's not doing the right thing

So, to clarify, if you have a multi-whenever react block then you won't see this bug.

**Comment by AlexDaniel** [comment]
Bisected with this command:
```
bisect: old=2018.01 new=2019.03 use v6.d.PREVIEW; start for ^3 { sleep 0.3; run ‘kill’, -SIGINT, $*PID }; my $a = -1; react whenever signal(SIGINT) { $a++; sleep 1.5; exit $a; }
```

(2018-03-06) https://github.com/rakudo/rakudo/commit/db010b847a2496ffd61e7ec0eb1e82482081c9ed

**Comment by jnthn** [comment]
Also, there aren't very many non-serialized supplies out there; the signal one must be one of the very few.

**Comment by jnthn** [comment]
Dug into it, and it turns out that it *is* just a problem with `signal` after all. There are two levels of `Supply` protocol compliance: serialized (one message at a time) and sanitized (follows the grammar `emit* [done|quit]` precisely). You can't be sanitized if you aren't serialized - but the `Supply` returned from `signal` claimed it was exactly that! So, not a general problem with `react`/`whenever` after all, it's just that it calls `.sanitize` (correctly), not `.serialize` (which I checked for, and led me to wrongly blame `react`/`whenever`).

**Comment by jnthn** [comment]
It's relatively easy to see it's fixed by doing:

```
react whenever signal(SIGINT) { say 42; my $i++ for ^100_000_000; exit 1; }
```

And seeing there's one line of output, *but* it's a little tricky to write a test for this.
