### ISSUE TITLE
Clones of wrapped routines lose their wrappers

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#3573]
## The Problem
`Trait::Traced` supports tracing of methods using `Routine.wrap`. The problem is an exception needs to be made for metamethods of classes, where the method doesn't get wrapped until after the package it belongs to gets composed, because otherwise metamethod calls do not get traced. The code golfs down to this:

```perl6
multi sub trait_mod:<is>(Routine:D $r is raw, :$foo!) {
    $r.wrap: -> | { say 'ok'; callsame };
}

class Foo { method ^foo(Mu) is foo { } }
Foo.^foo;
```

Wrapping of metamethods never worked in the first place, so this isn't a regression.

## Expected Behavior
This should output `ok`.

## Actual Behavior
This outputs nothing.

## Steps to Reproduce

Save the script as `test.raku` and run it.

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.6 GENERIC.MP#43 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2020.02.1-250-gaaa3fdcc3 built on MoarVM version 2020.02.1-50-g15e94eecb
implementing Raku 6.d.

**Comment by Kaiepi** [comment]
The reason behind the title is I found that this only happens because `NQPParametricRoleHOW` clones methods on specialization. The issue in the OP can be fixed by binding a callback to `@!compstuff[2]` to handle wrapping of the clone, but this won't work for runtime calls to `Routine.wrap`. Should there be something like a `$!clone_callback` attribute on `Code` similarly to `NQPRoutine` for dealing with wrapping of clones, or are there more efficient ways of dealing with this?

**Comment by vrurg** [comment]
Cloning of `$!wrappers` should work. Will try tomorrow.

**Comment by vrurg** [comment]
The thing I overlooked yesterday was the fact that wrapping takes place in a trait. The core of the problem is that traits are executed at compile time. At this moment a routine is not finalized yet and cannot be wrapped. For this purpose `wrap` installs a fixup/deserialize task which does the wrapping when the routine is ready.

The problem we have here is that the routine gets cloned before the compilation ends and thus it clones the unfinished routine with no wrapping applied.

I don't have a good solution for this yet. `@!compstuff` cannot be used because it doesn't support chaining. If anything gets installed into it it could be lost with no notice.

**Comment by vrurg** [comment]
Cloning of wrapped routines seemingly has another unforseen side effect. A `WrapHandle` is being produced once. What should happen when we unwrap? Shall all clones be unwrapped to?

**Comment by dogbert17** [comment]
This prints 'ok' when I run it. Tried a few older releases and they all work.

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/9d93090fee
