### ISSUE TITLE
MoarVM panic: Internal error: Unwound entire stack and missed handler

### ISSUE THREAD

**Issue by MARTIMM** [rakudo/rakudo#3592]
## The Problem
Crashes of Rakudo when using native call interface

## Expected Behavior
A nice stack dump

## Actual Behavior
Message as in the title of this issue

## Steps to Reproduce
Not so easy to reproduce but it comes down to the following situation; A Raku callback handler is called from a C library. This Raku handler has some mistake or whatever, where Raku normally has a proper message with a stack dump. Somehow Raku can not follow the stack back because, I think, the format there is different.
I can get a stack dump, however by putting a try block around the problem and catch it printing $_.note().
Isn't it possible to let Raku handle this automatically in such a situation?

## Environment
* Operating system (uname -a): **Linux h03-fedora 5.4.17-100.fc30.x86_64 #1 SMP Sat Feb 1 19:15:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux**
* Compiler version (`perl6 -v`): **Rakudo version 2020.02.1-330-g4524d0fdf built on MoarVM version 2020.02.1-71-g1bd5f19e0
implementing Raku 6.d**

**Comment by AlexDaniel** [comment]
Can you provide some code to reproduce the issue?

**Comment by MARTIMM** [comment]
I have removed a level of rethrowing in Gnome::N and several other modules from Gnome::Glib etcetera. This seems to help although still ending with the same error message. I still think that that message comes from the fact that Raku cannot follow the stack entirely through the C libs code. I will add a new comment when I encounter the same situation again (that is, error without stack dump).

**Comment by MARTIMM** [comment]
Unfortunately, I still experience this behavior. I understand that this is difficult to pinpoint the problem as is creating an example that is small enough. So I will keep the issue open and we'll see what the future brings.

**Comment by Xliff** [comment]
@MARTIMM , I feel your pain. 

Seeing as how we are working on related issues, here's what I've done to get around the problem:

Any time you are creating an event handler, add the following code to the TOP LEVEL BLOCK:

```perl6
CATCH { default { .message.say; .backtrace.concise.say } }
```

This will prevent the unwinding, give you a proper error message, and hopefully a location.

Hope this helps.

**Comment by jnthn** [comment]
A reliable reproduction without any dependencies is:

```
use NativeCall;

sub qsort(CArray[int32] $arr, size_t $elems, size_t $item-size,
          &callback (Pointer[int32], Pointer[int32] --> int32))
    is native {*}

my $arr = CArray[int32].new(10...1);
qsort($arr, $arr.elems, 4, -> $a, $b { die "oops"; $a.deref <=> $b.deref });
say $arr[^10];
```

Ultimately, the problem is that there's native code on the callstack between our callback and the calling Raku code. There's no exception mechanism in C that we can use in order to safely have it unwind those native stack frames. Therefore, libraries using native callbacks need to handle the exceptions and return the appropriate kind of value to indicate failure, or to otherwise decide how to take care of such exceptions.

While I think terminating the program is the right thing to do in this situation, the current panic message is entirely unhelpful in known which callback needs to be given exception handling. I've addressed that in 6546027, so now you get an explanation of what happened and a stacktrace before the VM exits, rather than a panic.

**Comment by jnthn** [comment]
Also tweaked the docs in https://github.com/Raku/doc/commit/45d04e5ea6 to forewarn folks about the importance of handling exceptions in native callbacks.

**Comment by MARTIMM** [comment]
@jnthn thank you very much for your replies and work, Reading your note about throwing exceptions is exactly what I have experienced.
@Xliff I've done just like that to get the stack dump but is, of course, more debug work.
