### ISSUE TITLE
Smartmatch on lazy Sequences does not stop if it's not able to match

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3652]
## The Problem

This:

```
my @fib = 1,1, *+* ... *;
say @fib ~~ /^9999/
```

will (possibly) never fail, taking for ever.

## Expected Behavior

Apparently, smartmatching sequences was introduced in 6.d, at least it's in the spec: Raku/doc#2632. 
The semantics of this smartmatch, however, is not established and maybe should be tweaked. The way it is now, it may lead to infinite loops, since it tries to smartmatch every single element. Timing out does not make a lot of sense, also... 

Another option would be to create another lazy sequence with the result of smartmatching every single element. No infinite loops, reasonable semantics.

Additionally, simply not allow smartmatching on infinite sequences.

## Environment
* Operating system: 
* Compiler version (`perl6 -v`): 

I guess that anything beyond 6.d will do this...

**Comment by lizmat** [comment]
But smartmatch is supposed to return `True` or `False`?  So how would that work?

**Comment by JJ** [comment]
@lizmat in Junctions, it returns a Junction, right?
It's a suggestion anyway.

**Comment by 0racle** [comment]
For my money, this is a DIHWIDT. Timing out makes sense here.

Smartmatch should not be assumed to be "smart" enough to know the match will never happen.

**Comment by vrurg** [comment]
I'm closing this because there is no way for a regex to know it would never match on a lazy sequence. Neither there is no way to know how long is "too long" to properly timeout. Just removing the caret `^` from the regex makes it stop on 271st iteration over the sequence's code block.

So, I don't see why this case should be different from many other cases of accidental indefinite loops.
