### ISSUE TITLE
Flapper: S16-io/watch.t

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#3713]
## The Problem
`S16-io/watch.t` is a test from Roast...

## Expected Behavior
...that should always pass...

## Actual Behavior
...but often fails when running `make spectest`. This doesn't seem to fail when running it with `fudgeandrun`.

## Steps to Reproduce

Run `make spectest`.

## Environment
* Operating system:
OpenBSD bastille.kennel.qt 6.7 GENERIC.MP#201 amd64
* Compiler version (`perl6 -v` or `raku -v`):
This is Rakudo version 2020.05.1-117-gdca8532b8 built on MoarVM version 2020.05-16-g45af267b5
implementing Raku 6.d.
(this is a branch that diverged from master around a week ago, but this has been an issue for a long time for me)

**Comment by vrurg** [comment]
Long-suffering _watch.t_... Can you try roast branch `rakudo_3713`?

**Comment by Kaiepi** [comment]
Still fails it seems.

**Comment by vrurg** [comment]
Did you try _the_ branch? Because I got time to give a try to my OpenBSD 6.5 in a VM. What I do is `perl t/harness5 --moar --fudge --verbosity=1 t/spec/S16-io/watch.t` in a loop which exits at the first detected failure.

First run on the master branch did fail somewhere around 350th repetition. Then I switched to `rakudo_3713` and had two times consequent runs of 1000 each, the current run is almost at 3200th repetition making already total of 5000, still no fail.

Apparently, flappers usually better reveal themselves under the load which `prove` in parallelizing mode implies. So, I'm gonna do a few loops of `make spectest` too. But so far I have little doubts that the branch does fix the problem.

**Comment by vrurg** [comment]
Update. `prove` does worsen things badly enough as to reveal a problem. But the problem is very unlikely to be the test itself.

Introductory, the test is most vulnerable to the initial stage. For it to pass we need:

- a file ready and open
- the react block to be set up and ready to accept events
- the writer thread to start writing not before the previous condition is fulfilled

What the branch test code does to do things right:

- the writer thread is starting first. When started if keeps a 'ready' promise
- the mainline awaits for the 'ready' promise to make sure writer thread is really ready to go; when it is a `react` block is prepared
- the writer thread now awaits for a 'start writing' promise
- to make sure the `react` block really ready to accept, we keep the 'start writing' promise in a `whenever` block because it won't run without prepared `react`
- here we loop 10 times
   - the writer awaits for the next 'proceed' promise. The first one has-been pre-kept and thus the first write happens immediately
   - the _watch_ `whenever` block receives a notification and keeps the next 'proceed' promise unlocking the writer

Now, the few failures I observed never happened at the initial stage. There were a few loops executed prior to the actual failure. Therefore I conclude that the failure happens somewhere between the writing into the file and tapping the `watch` `Supply`. The code responsible for this is so simple that I currently see only few possible reasons:

- the `write` is not taking place somehow
- the `whenever` block skips the event
- the `whenever` block never actually get the event because its not produced by libuv

I don't believe in failed `write`. It's the most unlikely reason.

It's hard to test for libuv failure, thus I can try and exclude the skipped event hypothesis. To do so I assumed that the next write might happen before the current `whenever` block finishes or `react` block starts the next loop. To make sure the `write` happens really late, I added .5 sec delay after `await`. And it seemingly helps because where it was failing no later than at 11th try I had to sop the testing at 27th successful loop.

So far, I can only conclude that we have a problem in the core. What confuses me is that if the delay really fixes the problem then it points at the likely cause somewhere in `react`/`whenever`/`Supply`. But if so why OpenBSD is the only affected platform? If it's libuv then how the delay helps to resolve the issue?

I'm gonna leave a linux VM running the test overnight alongside with OpenBSD.

**Comment by vrurg** [comment]
Final confirmation of the problem not being OpenBSD-specific. Linux failed on 55th repetition too. OpenBSD running the test with a delay before the write survived 891 repetitions when another test failure (_S16-io/print.t_, likely due to a crash of some kind) cancelled the loop.

I could sum up for now that most likely we have a problem delivering a change notification to the consumer. Where exactly the chain breaks is yet to be determined. Unfortunately, I'm not sure I'd have enough time for this.
