### ISSUE TITLE
rules apparently forget to ratchet in some cases.

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3726]
## The Problem

Theoretically, the difference between rules and regexes is that they ratchet. However, in some cases they don't.

This was originated in [this SO question](https://stackoverflow.com/questions/62051742/whats-the-real-difference-between-a-token-and-a-rule), which converted this token

```
  token TOP { <name> '@' [<subdomain> '.']* <domain> '.' <tld> }  
```

to a rule, making it immediately work for things like `a@b.c.d`

This can be golfed down to:

```
my rule r { [\w+ '.']* \w+ '.' \w+ }; say "a.b.c" ~~ &r
```

Again, it's not ratcheting. That does not seem to always be the case. Some examples mentioned [here](https://colabti.org/irclogger/irclogger_log/raku-dev?date=2020-05-28#l59) by @ShimmerFairy 
do ratchet and work as expected.

## Expected Behavior

`rule`s should always ratchet.

## Environment

According to commitable, the golfed expression works like that for every single release.

**Comment by ElectricCoffee** [comment]
Since I'm the original author of the SO question, I may as well follow along in here

**Comment by raiph** [comment]
Notes from my investigation of this. 

My best golf is `'a' ~~ rule  { .* a }`. This matches. That... surprises me.

It has matched since 2014.01 at least, and plausibly since the dawn of time. That... surprises me.

I browsed around the test files. The names of these suggested they might be relevant:

* https://github.com/Raku/roast/blob/master/S05-grammar/ws.t

* https://github.com/rakudo/rakudo/blob/master/t/01-sanity/10-regex.t

* https://github.com/Raku/nqp/blob/master/t/qregex/01-qregex.t

* https://github.com/Raku/nqp/blob/master/t/qregex/rx_basic

* https://github.com/Raku/nqp/blob/master/t/qregex/rx_backtrack

* https://github.com/Raku/nqp/blob/master/t/qregex/rx_quantifiers

**Comment by raiph** [comment]
See also IRC discussion I've begun at https://irclogs.raku.org/raku-dev/2023-09-22.html#02:03

**Comment by codesections** [comment]
I just opened Raku/problem-solving#390 to help resolve this issue.

Please note that, as I mention in that issue, the problem is **not** actually with `rule`s specifically but rather with `:sigspace` more generally.
