### ISSUE TITLE
Assigning a list without parentheses only assigns first value

### ISSUE THREAD

**Issue by ElectricCoffee** [rakudo/rakudo#3735]
## The Problem
If I understand things correctly, assigning a list without parentheses should be the same as assigning with them.

But it only assigns the first value:

```raku
my $lst = 1, 2, 3, 4;
```
should be the same as
```raku
my $lst = (1, 2, 3, 4);
```

## Expected Behavior
```raku
> my $lst = 1, 2, 3, 4;
(1 2 3 4)
> $lst
(1 2 3 4)
> my $lst = (1, 2, 3, 4);
(1 2 3 4)
> $lst
(1 2 3 4)
```
## Actual Behavior
```
> my $lst = 1, 2, 3, 4;
(1 2 3 4)
> $lst
1
> my $lst = (1, 2, 3, 4);
(1 2 3 4)
> $lst
(1 2 3 4)
```
## Steps to Reproduce
Open a repl and try it out

## Environment
* Operating system: macOS Catalina
* Compiler version (`perl6 -v` or `raku -v`):
```
This is Rakudo version 2020.01 built on MoarVM version 2020.01.1
implementing Perl 6.d.
```

**Comment by jnthn** [comment]
The precedence of the `=` operator is specified as depending on the sigil of the variable on the left; it may either be item assignment level or list assignment level. The `@` sigil is intended for use with positional things, and if that is used then you get the desired behavior:

```
> my @lst = 1, 2, 3, 4; say @lst;
[1 2 3 4]
```

Since it's a list assignment and the `=` binds looser than `,`. A `$` implies item assignment, so it binds tighter than `,`.

**Comment by ElectricCoffee** [comment]
Every guide I found used Lists with $ and arrays with @:
```
# making these two different constructs:
my $foo = (1, 2, 3, 4);
my @bar = [1, 2, 3, 4];
```
And the question is about the first, rather than the last

**Comment by jnthn** [comment]
The precedence level is a syntactic distinction based upon the sigil (or absence of one, in which case it's list assignment also). What's on the right had side can't influence matters (because we've already committed to a chosen level after parsing the `=`). This issue tracker is for compiler bugs - and this isn't one - though if guides are misleading please do make an issue in their tracker (for example, the docs one is at https://github.com/Raku/doc/issues.

**Comment by lizmat** [comment]
If you run it as  one liner, you get some excellent feedback:

    $ raku -e 'my $lst = 1, 2, 3, 4;'
    WARNINGS for -e:
    Useless use of constant integer 2 in sink context (lines 1, 1)
    Useless use of constant integer 3 in sink context (lines 1, 1)
    Useless use of constant integer 4 in sink context (lines 1, 1)

I w
