### ISSUE TITLE
Can support iOS system

### ISSUE THREAD

**Issue by ccworld1000** [rakudo/rakudo#3771]
Can support iOS system

**Comment by Prince213** [comment]
Do you have access to an macOS system? Have you tried to compile Rakudo for your iOS system? It's probably better if we know its current status on iOS.

**Comment by vrurg** [comment]
On a jailbroken iPhone? Yes, in theory. But in fact we definitely lacking resources trying it.

**Comment by FCO** [comment]
I don’t think that possible only on a jail broken one. There is a app a that brings python to iOS, why not Raku? https://apps.apple.com/br/app/pythonista-3/id1085978097?l=en

**Comment by vrurg** [comment]
Because Raku based on a bytecode VM. JS we don't consider. Java is not allowed. MoarVM would have to prove that it doesn't use JIT. Even though it doesn't on ARM, the presence of JIT in general would make things rather hard.

And then again, I don't believe we have resources for this kind of task now. There is little practical use in it. So, to my view, if somebody somewhen compiles Rakudo for iOS – that'd be marvelous! But until then no sense in keeping this ticket opened.
