### ISSUE TITLE
^methods and private methods.

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3801]
## The Problem

This is more a clarification than an actual issue. Documentation for [`^methods`](https://docs.raku.org/language/classtut#index-entry-$CIRCUMFLEX_ACCENTmethods) say:

> $o.^methods(:local) produces a list of Methods that can be called on $o

However, in this example:

```
class Privateed {
    method !private() { return "⌣"  }
    method public() { return "✓" };
    method methods() { return self.^methods };
}

my $obj = Privateed.new;
say $obj.methods;
```

it seems to return only * public * methods and submethods:

```
(public methods BUILDALL)
```

## Expected Behavior

`self` can obviously call a private method, so it looks like it means methods that can be called on an *instance* of an object.

On the other hand, that obvious explanation begs for another introspection method that is able to return _all_ methods. `^find_methods` can't find private methods either:

```
# Add this method
 method is-found($method ) { return self.^find_method( $method ); }

# Test it later
say $obj.is-found( "private" );
say $obj.is-found( "public" );
```
The first returns Mu, the second "public". 

So, three questions
1. Is that behavior expected?
1. Should the documentation be changed in that case?
3. Method introspection for private methods (and probably attributes), how can we do it?

**Comment by Altai-man** [comment]
1)Public and private methods have different API, so it seems this behaviour is expected.
2)Specs say about `:private` flag to `^methods`, see https://raw.githubusercontent.com/perl6/specs/master/S12-objects.pod but the implementation has regressed and is skipped in roast currently. The other API we have like `^private-methods` is not in spec.
3)`class A {}; A.HOW.^methods.grep({ .name ~~ /private/ })`

**Comment by jnthn** [comment]
Unlike in some languages where `private` is an accessibility modifier on a method, in Raku "private methods" and "methods" are quite different things - that is to say, it's better to read "private method" as a compound noun rather than an adjective describing a noun.

Of note, private methods:

* Have their own namespace; you can declare both `method foo` and `method !foo`
* Have a different declaration syntax (`method !`)
* Have a different call syntax (`self!foo`)
* Are not virtual, and so missing ones are detected at compile time

And supporting that in meta-space:

* They are stored separately
* They are added via `.^add_private_method`
* They are introspected via `.^private_methods` and resolved by `.^find_private_method`

> Specs say about :private flag to ^methods

Tests expecting a `:private` option to exist should be removed, or replaced with a passing test using `.^private_methods`, which is the API we ended up with.

> the implementation has regressed and is skipped in roast currently

I don't believe the implementation has ever supported this, so it's not a regression; I suspect the test was written speculatively, but the actual MOP design came out different. I think the current API better reflects the differences between the two. Further, adding a `:private` flag to just `.^methods` would suggest we want to add it to `.^add_method` and `.^find_method` too for consistency, and then would force everyone overriding those to account for the possibility they need to deal in private methods also.

**Comment by JJ** [comment]
Closing after opening #3521 above. Thanks a lot for the answers.

**Comment by JJ** [comment]
>     * virtual

@jnthn what do you mean by virtual here?

**Comment by jnthn** [comment]
@JJ Given:

```
class P { method !p() { 1 }; method m() { self!p } }
class C is P { method !p() { 2 }; }
```

Then both `say P.m` and `say C.m` will output `1`.
