### ISSUE TITLE
"No such method '!private' for invocant of type xxx Did you mean '!private'?"

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3802]
## The Problem

In this program:

```
class Privateed  {
    method !private() { return "⌣"  }
    method call-private( $method-name )  {
	self."!$method-name"();
    }
}

my $obj = Privateed.new;
say $obj.call-private( "private" );
```

There's an error with the LTA message:

```
No such method '!private' for invocant of type 'Privateed'. Did you mean '!private'?
  in method call-private at private-test.p6 line 10
  in block <unit> at private-test.p6 line 15
```

## Expected Behavior

A different kind of message. Also maybe an error indicating you can't call private methods that way. How I arrived to that contrived syntax was by using the exclamation-mark less version, simply writing "private".

Also, not clear there's a way to call private messages by name. Other attempts (using `self!"private"`, for instance) fail.

## Environment
* Operating system:
* Compiler version (`perl6 -v` or `raku -v`):

raku 2020.06

**Comment by Altai-man** [comment]
1)Your code doesn't have `does Privateer` definition.
2)It works with `self!"$method-name"();`, is it error message which is LTA?

**Comment by JJ** [comment]
1) Yep, that was copypasta. 
2) Only thing I probably didn't try. Thanks.

**Comment by vrurg** [comment]
I thought public/private in error message was taken care of. In fact, the report should be something like:

```
No such public method '!private' for invocant of type 'Privateed'. Did you mean private method '!private'?
```

**Comment by vrurg** [comment]
I have drafted a change to the exception error message in #3805. But don't like the way it looks. On my test it results in:

```
No such method '!private' for invocant of type 'Privateed'.  Did you
mean '!private'?  (A private method suggested for a public method call.)
  in method call-private at private-method.raku line 5
  in block <unit> at private-method.raku line 14
```

The numerous _private_ comes from the method name, apparently and is not the problem. But overall verbosity and no way of sending the final elaborative part to a new line makes the message overwhelming, to my view.

Unfortunately, the first sentence can't be changed because it is specced. I wonder if we have to spec the error messages at all, but that's off-topic.
