### ISSUE TITLE
%?RESOURCES should be user accessible for an installed module

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3821]
The **%?RESOURCES** variable is currently not available outside a module's compunit.

It would be convenient to access the variable through a fully-qualified name

    my $f = %?SomeModule::RESOURCES<bin/foo>;

**Comment by ugexe** [comment]
Without commenting on the usefulness... `%?RESOURCES` is tied to a *distribution* but the suggested use is treating it like its tied to a *module* (similarly to `$?DISTRIBUTION`) let alone every namespace in a file. For instance you can already do the following:

```
use Zef;

# Search for the module I want to access %?RESOURCES for
my $dist := $*REPO.repo-chain.map(*.?candidates(CompUnit::DependencySpecification.new(:short-name<Zef>)).Slip).head;

# Read the resource file using the `Distribution` API:
say $dist.content("resources/config.json").open.slurp
```

The above method isn't perfect either though... there is no guarantee the code above will grab the same version of `Zef` that a theoretical piece of code has already loaded (i.e. that we get the `%?RESOURCES` from the version we expect). Its a 90% solution. However, you could also do the following to ensure the distribution loaded will be used for looking up those resources:

```
# Replace `use Zef` with the following equivalent loading code so we can get access the CompUnit:
my $cu := $*REPO.need(CompUnit::DependencySpecification.new(:short-name<Zef>));

say $cu.distribution.content("resources/config.json").open.slurp
```

The above is probably a bit more verbose than one may like because of the `$*REPO.need(...)`, and loses some compile-time guarantees. So its not perfect either.

Note both the above solutions do work for non-installed distributions as well. Also note you do not access bin scripts via `%?RESOURCES` (re: `%?SomeModule::RESOURCES<bin/foo>`). You can however use the `Distribution` API:
```
my $cu := $*REPO.need(CompUnit::DependencySpecification.new(:short-name<Zef>));

say $cu.distribution.content("bin/zef").open.slurp

**Comment by tbrowder** [comment]
Nick, thanks for the enlightenment. That's what I was looking for.  Some questions and comments:

1. You say the last method:

    ...
    say $cu.distribution.content("resources/config.json").open.slurp

is not perfect because it loses some compile-time guarantees. Can you expand on that a bit or point me to more details?

2. Your last comment discussed bin scripts and pointed out how to access them. Good to know know since the file gets copied to a "shim" I believe you called it on IRC, and that might not be the one the user is looking for.

3. If your answer to **2** above is appropriate, would creating a public module to interrogate such local or public module data be practical? Or would a zef plugin be the way to go?

**Comment by ugexe** [comment]
> In discussing the method above you say it is not perfect because it loses some compile-time guarantees. Can you expand on that a bit or point me to more details?

`use My::Module` is compile time. `$*REPO.need(...)` is run time. I suppose one could instead use `my $cu := BEGIN $*REPO.need(...)` though...

> Your last comment discussed bin scripts and pointed out how to access them. Good to know know since the file gets copied to a "shim" I believe you called it on IRC, and that might not be the one the user is looking for.

Nothing about a bin script is copied to a shim. Instead a shim is installed for a given name, and that shim uses the CUR/Distribution APIs (similarly to what I've shown in previous examples) to load the appropriate code. Another way to put it is that the only way to access bin shim code is by doing something wrong (like modules assuming their directory structure instead of using the APIs).

> Given your answer to 1 above, and assuming the compile-time guarantee is not a show-stopper, would creating a public module to interrogate such local or public module data be practical? Or would a zef plugin be the way to go?

A module yes, but I'm not sure what a better API is other than shortening/removing the `CompUnit::DependencySpecification.new` boilerplate

**Comment by tbrowder** [comment]
> Nothing about a bin script is copied to a shim. Instead a shim is installed for a given name

But what happens when two different modules happen to have a bin file with the same name? Does zef disambiguate them somehow when creating the shim name? If so, how does an unsuspecting user know?

All I know is that recently @lizmat was going to use a certain bin name for her new Hash2Class module and I warned that there was already a bin file of the same name in my home directory in the usual zef-installed bin directory, but she changed the name before I got to observe the local effect of that installation.

**Comment by ugexe** [comment]
> But what happens when two different modules happen to have a bin file with the same name?

The same thing when you have 10 different versions of zef installed -- the shim looks for all distributions with a matching e.g.`bin/zef` and then loads the one with the highest version.

> Does zef disambiguate them somehow when creating the shim name?

zef doesn't create shims, rakudo does. And rakudo doesn't need to discriminate with the shim name because the shim is capable of loading any distribution with a matching file.

> If so, how does an unsuspecting user know?

Its an environment management issue. zef tells "unsuspecting user" what gets installed -- it doesn't try to manage the environment. An install-time message might seem helpful, but in reality its not because its entirely reasonable to install distributions into locations that are not located in `PATH` at all.

> but she changed the name before I got to observe the local effect of that installation.

As i've mentioned before -- in the normal case it will load the one from the distribution with the highest version (...from the first CU that has *any* version). Currently one can pass `--auth=...` `--ver=...` and get:
```
zef --auth=foo
===SORRY!===
No candidate found for 'zef' that match your criteria.
Did you perhaps mean one of these?
  Distribution | Version | Author(ity)
  zef          | 0.8.4   | github:ugexe
```
Notable is the lack of `--api=...`. That is because we need to rename `--auth` and `--ver` in the shim, as it prevents all raku scripts from accepting those (common-ish) names for input parameters... we need to rename them to something less huffmanized (like `--using-version` `--using-auth` `--using-api`) before we start to advertise that feature though. As far as "unsuspecting user" the best we could do is warn them every-single time the shim has multiple versions that could have been used every time that script is used, which doesn't seem like a good thing to do.

**Comment by tbrowder** [comment]
Thanks, Nick. Very enlightening and food for thought.
