### ISSUE TITLE
FETCH method of Proxy is called multiple times when returned from AT-POS member function

### ISSUE THREAD

**Issue by chromis** [rakudo/rakudo#3822]
Hello,

This issue is (to me) a peculiarity that may cause performance issues, so it may not be really regarded as a bug: I'm unsure where to ask/report this, I decided to try ask and report it here.

After asking https://stackoverflow.com/questions/62968829 (and during experiments related to this question), I encountered the following: when I return a `Proxy` object from my `AT-POS` implementation in the code below then the `FETCH` method of the proxy is called _multiple times_ when the resulting value is used in various (in this provided code, contrived) situations. This is the code:

```
class MyPositional does Positional
{
    method AT-POS(\position)
    {
        say "~~ AT-POS({\position})";

        return-rw Proxy.new:

            FETCH => method ()
            {
                say "~~ FETCH({\position})";
            },

            STORE => method ($v)
            {
                ...
            }
    }
}
```

I'm attempting to use it like this:

```
say "===";

my $test = MyPositional.new;

say $test[16];

say "---";

say $test[32];

say "---";

printf "{$test[16]}\n";

say "---";

printf "%d\n", $test[16];

say "---";

my $foo = "{$test[17]}";

say "===";
```

The output really surprises me: `AT-POS` is executed once (as expected) in each `---`-delimited "segment" in the output below... but the `FETCH` is executed multiple times (Depending on its use, apparently).

```
===
~~ AT-POS(16)
~~ FETCH(16)
~~ FETCH(16)
~~ FETCH(16)
~~ FETCH(16)
~~ FETCH(16)
~~ FETCH(16)
~~ FETCH(16)
~~ FETCH(16)
~~ FETCH(16)
True
---
~~ AT-POS(32)
~~ FETCH(32)
~~ FETCH(32)
~~ FETCH(32)
~~ FETCH(32)
~~ FETCH(32)
~~ FETCH(32)
~~ FETCH(32)
~~ FETCH(32)
~~ FETCH(32)
True
---
~~ AT-POS(16)
~~ FETCH(16)
~~ FETCH(16)
~~ FETCH(16)
~~ FETCH(16)
~~ FETCH(16)
True
---
~~ AT-POS(16)
~~ FETCH(16)
~~ FETCH(16)
~~ FETCH(16)
1
---
~~ AT-POS(17)
~~ FETCH(17)
~~ FETCH(17)
~~ FETCH(17)
~~ FETCH(17)
~~ FETCH(17)
===
```

What I would expect is this:

```
===
~~ AT-POS(16)
~~ FETCH(16)
True
---
~~ AT-POS(32)
~~ FETCH(32)
True
---
~~ AT-POS(16)
~~ FETCH(16)
True
---
~~ AT-POS(16)
~~ FETCH(16)
1
---
~~ AT-POS(17)
~~ FETCH(17)
===
```

Is this correct?

This code (and example) is contrived: in my actual code, this means that `NativeCall`ed code gets executed more times than necessary: hence my discovery,

This is on Rakudo version 2020.07-41-g3843a1e89 built on MoarVM version 2020.07, implementing Raku 6.d.

Thanks!

Regards,

Raymond.

**Comment by vrurg** [comment]
This is expected behavior. The confusion is usually caused by seemingly atomic nature of some operations whereas in fact they're multi-staged. I'll use a simplified example:

```raku
my $p := Proxy.new(
        FETCH => { say "FETCH"; 1 },
        STORE => { }
    );

say $p;
```

Because a) `say` is a `multi`; b) it invokes `gist` method on its argument – the value is taken from `$p`  by multi-dispatching subsystem first to determine which of `say` candidates is to be invoked; second, `gist` reads from `$p` to actually produce a string out of it. The outcome is expected:

```
FETCH
FETCH
FETCH
FETCH
FETCH
FETCH
FETCH
1
```

Even such a simple example:

```
multi foo(\x) { }
foo $p;
```

would result in two `FETCH` invocations. The operation which guarantees a single call to `FETCH` is assignment:

```
foo $_ = $p;
```

A funny note: I just have started an article about `Proxy`. Will try to cover this specific too in it.

**Comment by chromis** [comment]
Thanks for your explanation! I will surely be reading your article,

I found out about this because I'm experimenting with a "remote array contraption" (which I'd like to hide behind Raku syntax ;) my "works as expected"-alternative has a C++14 style `at` method): getting elements from this "remote array" is 'relatively expensive' (and causes a "round trip" e.g. messages on TCP/IP albeit on a reliable, local network),

Thinking more about this leads me to imply that implementing a `FETCH` that takes "some significant processing time" is not a good idea: I've now implemented memoization which - I suspect - makes much better sense, semantically (because not implementing memoization implies that a value that can "just change", which shouldn't be). It is also quite easy to do the actual value fetching at the "`AT-POS` level", though then I cannot really know if the `AT-POS` was called for `FETCH`ing or `STORE`'ing: the fetching may then turn out to be for nothing.

**Comment by vrurg** [comment]
That's true that in many cases `Proxy` is too expensive solution. But it's unlikely is your case. Without knowing all the details of your task it's hard to say how well `Proxy` fits into it, but one thing you may consider: earlier this year (if memory serves me right) support for subclassing `Proxy` was implemented. This made possible, in particular, caching semantics for your case. So that no matter if `FETCH` is called several times, the actual network operation would only happen once. Perhaps even just once over a `Proxy` instance lifetime, if conditions allow.
