### ISSUE TITLE
IO::Notification: What is it good for?

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3835]
## The Problem

This is a singular case [of a class with no attributes](https://github.com/rakudo/rakudo/blob/8134470538457c68164eb64f90e8d3e946d235a0/src/core.c/IO/Notification.pm6). All heavy lifting is actually done by IO::Notification::Change, which does have attributes. IO::Notification includes a method, `watch-path`, but it can be totally independent of the class itself. 

## Expected Behavior

I think the most appropriate data structure should be used for this. In this specific case, changing it to a module would probably have 0 impact, and would fit better.

There would be more impact if it's simply eliminated, watch-path converted into an independent subroutine, and then IO::Notification::Change would be left there, hanging; it might be upgraded to be called IO::Notification and refactored.

**Comment by Altai-man** [comment]
The described thing is not a problem at all.

>This is a singular case of a class with no attributes

Is there anything wrong with classes without attributes?

>IO::Notification includes a method, watch-path, but it can be totally independent of the class itself

It can be, but it can also be a method of IO::Notification class. Is there any evidence how the independent approach does any good, except that it breaks totally valid code we promote from [2015](http://jnthn.net/papers/2015-spw-concurrency.pdf#page=51&zoom=auto,-214,435) if not earlier (I'd bet on much more earlier) ?

What is the point here, to break people stuff because classes without attributes are suddenly bad somehow?

**Comment by JJ** [comment]
Well, they needn't be instantiated, and this is probably a souvenir of a past era, but I get your point. Closing.
