### ISSUE TITLE
Where is the dark space?  Feature creep.

### ISSUE THREAD

**Issue by rakool** [rakudo/rakudo#3836]
## The Problem

`$x ~~  m/ (<ws>+ <-ws>+ <ws>+ <-ws>+) <ws>+/;`

seems more readable with a dark space

`$x ~~ m/ (<ws>+ <ds>+ <ws>+ <ds>+) <wx>+/;`

which fits with the design structure used with similar opposing pattern character classes at this level.  And seems so basic as to be predefined.

**Comment by pmichaud** [comment]
This is just a note that (to my memory) it's a little bizarre to be writing ``` <ws>+ ```  with the + quantifier.  The ```<ws>``` regex already consumes all available whitespace with ratcheting, the quantifier doesn't serve any purpose here.  The ```<ws>``` regex also does things like enforce that whitespace must exist between two ```\w``` characters when it is encountered, so ```<ws>``` isn't _just_ a character class.

It's easy enough to define a "dark space"  as    ```token ds { \S+ }```  if you really want one.  I suspect most people will just write ```\S+``` in their regexes, it's actually shorter (and probably faster) than ```<ds>``` will be.

Pm

**Comment by ziuq** [comment]
@pmichaud,  thanks for setting me straight (or at least straighter).  I find by S05-regex, that your memory is accurate.  I was looking at the "Predefined character classes" table in [Regexes](https://docs.raku.org/language/regexes) which seems misleading.  It did say "Whitespace. This is actually a default rule."   Having only done a toy grammar for a four function calculator when Perl 6 became playable on top of  Parrot, I missed what that meant to signify.   And I would be less apt to catch that significance since I thought a "character class" instance would be a element matching a single character not a pattern matching a set of similar chars bounded by dissimilar chars.

This display of my ignorance is just to let you better judge if there is anything to correct besides me.

**Comment by pmichaud** [comment]
@ziuq Great catch -- the documentation on that page in Regexes definitely needs more clarity about the ```<ws>``` rule, or omit it altogether.  None of ```<wb>```, ```<ws>```, nor ```<ww>``` are "character classes" to my thinking of the term.  Both ```<wb>``` and ```<ww>``` are zero-width matching rules, for example.

I'll probably submit a pull request to clean up that section of the documentation tomorrow, if nobody beats me to it.

Pm

**Comment by JJ** [comment]
Please do that. Issue already created, as you can see above.

**Comment by alabamenhu** [comment]
> Looking forward to updates, however I'm not sure I understand why `<ws>` isn't a character class. Below is a quick and easy way to modify a string using `<.ws>`

It's because `<ws>` is actually a regex proper defined as `{ <!ww> \s* }` (and `<ww>` is, as @pmichaud mentioned similarly not a character class, but a zero-width assertion).

**Comment by jubilatious1** [comment]
> It's because `<ws>` is actually a regex proper defined as `{ <!ww> \s* }` (and `<ww>` is, as @pmichaud mentioned similarly not a character class, but a zero-width assertion).

We can look at the listing for "Character Classes" and see all sorts of "pre-defined character classes" listed: 

https://docs.raku.org/language/regexes#Character_classes

If <ws> isn't a character class, then neither should be `\h`  or `\H` and `\v` or `\V` , because they both belong to the `\s` or `\S` character class. They are subsets of the `\s` or `\S` character class.  And we can do this _ad nauseum_ until the collective wisdom of providing 'predefined character classes' is known only to the cognoscenti.

Or, @pmichaud can try to reasonably delineate that page into Pure Character Classes and Derived Character classes. And the lowly `<ws>` ? Well, it's defined as NOT being anchored by a zero-width assertion, followed by whitespace (either vertical or horizontal)...which is to say, it sounds like a Derived Character Class to me.

**Comment by ziuq** [comment]
@jubilatious1 ,  you are crying foul against decades of practice.   These categories are not organized in a hierarchy, they are utilitarian.

**Comment by jubilatious1** [comment]
Apologies @ziuq , but I don't think I understand. Didn't you open this issue with regards to `<ds>`  in order to request/investigate having one-or-more "pattern character class(es)" added to Raku? 

Or am I mis-understanding?

**Comment by rakool** [comment]
You are correct, I did make that request.

**Comment by rakool** [comment]
Although @jubilatious1 and  I both had some misunderstanding around this issue which  suggests some deficiency in the docs ( or us).   Responsive changes have been made and I am content that this issue be closed.
