### ISSUE TITLE
Object in a block passed to and called via a sub doesn't see the dynamically scoped variable in the sub when sunk

### ISSUE THREAD

**Issue by kjkuan** [rakudo/rakudo#3846]
## The Problem
```
class A { method sink(-->Nil) { say $*ABC } }
sub sss(&block) { my $*ABC = 123; block() }
#{ my $*ABC = 123; A.new }   # 123
sss { A.new }                # $*ABC not found
```
## Expected Behavior
Output: `123`

## Actual Behavior
```
Dynamic variable $*ABC not found
  in method sink at ./x.raku line 1
  in block <unit> at ./x.raku line 4
```

## Environment
* Operating system:  Ubuntu 18.04.4 LTS
* Compiler version (`perl6 -v` or `raku -v`):
This is Rakudo version 2020.07 built on MoarVM version 2020.07
implementing Raku 6.d.

**Comment by kjkuan** [comment]
NOTE: It seems to work if I `sink block()` in the sub.

**Comment by niner** [comment]
That's because without that the object is not sunk in the sub at all but returned from the sub (it's the last value) and then sunk at the place of the call to sss.

Both of these would work as you expect:
`sub sss(&block) { my $*ABC = 123; block(); True };`
`sub sss(&block -->Nil) { my $*ABC = 123; block() }`
