### ISSUE TITLE
Warning on Hash[non-str, non-str].new( ... more than one pair ...)

### ISSUE THREAD

**Issue by fecundf** [rakudo/rakudo#3885]
## The Problem

$ `raku -e "(my Regex %t{Regex}=/'y'/,/1/, /'z'/,/0/).raku.say"`
Regex object coerced to string (please use .gist or .raku to do that)
  in block <unit> at -e line 1
Regex object coerced to string (please use .gist or .raku to do that)
  in block <unit> at -e line 1
(my Regex %{Regex} = /'y'/ => /1/, /'z'/ => /0/)
_why warnings there? ⬆︎ The warnings are the problem._

By contrast, this doesn't warn
$ `raku -e "(my Regex %t{Regex}=/'y'/,/1/).raku.say"`
(my Regex %{Regex} = /'y'/ => /1/)

## Expected Behavior
warning-free "raku" call:
$ `raku -e "(my Regex %t{Regex}=/'y'/,/1/, /'z'/,/0/).raku.say"`
(my Regex %{Regex} = /'y'/ => /1/, /'z'/ => /0/)

## Musing

I'd think that whatever the fix is, it should go in the Associative role, so that all derived classes will "freeze" warning-free.

## Environment
* Operating system: Mac OSX
* Compiler version (`perl6 -v` or `raku -v`): This is Rakudo version 2020.07 built on MoarVM version 2020.07
implementing Raku 6.d.

**Comment by alabamenhu** [comment]
So I've tracked this down and it affects a lot more than this small apparent edge case.

The issue is caused because `Hash.gist` uses `Hash.sort`, which [uses `Rakudo::Sorting.MERGESORT-REIFIED-LIST-AS`](https://github.com/rakudo/rakudo/blob/fc75105fb47b79414d1c25f7e15a15aa3b9f9087/src/core.c/Hash.pm6#L613).  This will return the original if there's only one item — sparing us the error.

But if there's more than one, the problem is that it [uses `cmp`](https://github.com/rakudo/rakudo/blob/fc75105fb47b79414d1c25f7e15a15aa3b9f9087/src/core.c/Rakudo/Sorting.pm6#L238) which in turn [uses `.Stringy`](https://github.com/rakudo/rakudo/blob/8134470538457c68164eb64f90e8d3e946d235a0/src/core.c/Order.pm6#L13), which of course does not work for objects of certain types (Regex and Nil in particular).  These are actually assigned the empty string for comparison purposes.

A quick fix would be to change the `&mapper` for the mergesort to be `*.key.gist`, but since `gist` may not show all of an item's content (lists would only stringify 50 or 100 or whatever the limit is), the sort results may be inaccurate — not that they are today either, though.  Alternatively, we could accept that a `Regex` should stringify to *something*, and make `Stringy` give the same as `.gist`.  Or we could modiify compare to handle the edge case that an object doesn't like to go stringy, but handles being gisted.

I'm not sure which of the solutions is the better (the third is certainly a non-starter), although maybe someone will come up with another.  Either way, need to be careful because `cmp` and `Regex` and `Hash` are all rather foundational classes.

**Comment by fecundf** [comment]
Thanks for exposing the root cause, those warnings are a side-effect of sorting the keys.

Adding ideas:
## "cmp knows things"
1. Add `multi &infix:<cmp>(Positional $a, Positional $b)` that does pair-wise `cmp` on the elements.
2. Add `multi &infix:<cmp>(Regex $a, Regex $b)` that compares regexes reasonably.
3. Add any other  `multi &infix:<cmp>(::T $a, ::T $b)` that makes sense
The [docs say `cmp`](https://docs.raku.org/routine/cmp#language_documentation_Operators) is already a

> Generic, "smart" three-way comparator.
> 
> Compares strings with string semantics, numbers with number semantics, Pair objects first by key and then by value etc.

Will adding a few more cases to `cmp` fix these key-sorting-warnings?

## "Give coders more power"
1. add a named argument default-True _'canonical'_ or _'sort-keys'_ to `gist`
2. document that `gist` sorts keys of Associative-derived objects
3. let coders turn off sorting via adverb

With this the author can turn off any attempt at sorting keys, useful for keys that don't sort like Complex, or user-defined objects that don't make sense to define a comparison.

## gimmie moar
It makes sense to implement all of these ideas! Changing the `&mapper`, stringifying `Regex`, adding `cmp` candidates, and allowing `gist` to skip sorting all have non-overlapping benefits beyond fixing this warning.
