### ISSUE TITLE
Sigil-less variable v1 is interpreted as version constant

### ISSUE THREAD

**Issue by wimvanderbauwhede** [rakudo/rakudo#3919]
## The Problem

When using `v1`, `v2` etc as sigil-less parameters, they are interpreted as version constants.
This behaviour breaks referential transparency.

## Expected Behavior

    > ->  \v1 { v1 }(42)
    42

## Actual Behavior

    > ->  \v1 { v1 }(42)
    v1

With any other name it works as expected 

    > ->  \x1 { x1 }(42)
    42

## Version:

This is Rakudo version 2020.08.2 built on MoarVM version 2020.08
implementing Raku 6.d.

**Comment by wimvanderbauwhede** [comment]
Just to say that this is still the case in 2022.06 

Here is a much simpler example:

      my Int \v1=42;
      say v1;

Expected: "42"; Actual "v1". No warnings or errors.

**Comment by lizmat** [comment]
````raku
my \v1 = 42;
say v1;  # 42
say v2;  # v2
````

**Comment by vrurg** [comment]
I would rather consider prohibiting declarations of `v<num>` variable because it is a reserved syntax. But a test with `if` reveals that it works. Though context matters in this case because `my \if = 1; say if , 2` dies and `my \if=1; say if, 2' works. The problem with `v` is that there is no context for it unless a `.<num>` is used. Otherwise both interpretations of `v<num>` are values and thus they're equivalent in rights. From this perspective the one being a syntax construct must have a preference.

**Comment by lizmat** [comment]
We can override almost all of the core tokens, so why not these?

**Comment by lizmat** [comment]
FWIW, *I* would find it very confusing, but since it's all lexical, there is no real issue.

**Comment by vrurg** [comment]
Probably, you're right. Lexicality gives it more sense.

**Comment by wimvanderbauwhede** [comment]
I don't really mind if it is allowed or not, but it should not silently do the wrong thing. If I say 

```perl6
my Int \v = 42;
```
Then I expect `v` to be an Int or else get a type error, or some error telling me I can't do this. I have a slight preference for being allowed to do it, because we can also override built-in function names etc, so that would seem more consistent.
