### ISSUE TITLE
Intersection meta-ops behave like union

### ISSUE THREAD

**Issue by nwellnhof** [rakudo/rakudo#3945]
say 1..3, 1..3 Z∩ 2..4, 2..4 # OUTPUT: (set(1 2 3 4) set(1 2 3 4))
    say zip with=>*∩*, (1..3, 1..3), (2..4, 2..4) # OUTPUT: (set(2 3) set(2 3))

There are similar issues with X meta-ops. Also, baggy multiplication ⊍ meta-ops behave like baggy addition.

**Comment by lizmat** [comment]
Found the reason for the observed behaviour.  The code:

    1..3, 1..3 Z(&) 2..4, 2..4;

winds up in the **single** argument `(&)` candidate, which coerces its parameter to a `Set`.  So you basically get:

    (1..3, 2..4).Set

And it doesn't pass the `zip` operator logic at all, so that's why you *do* see the correct behaviour with `zip`.  I assume something similar is happening with the `X` metaops.

**Comment by lizmat** [comment]
Thanks for the report, this should be in the 2020.10 release of Rakudo.
