### ISSUE TITLE
New Trademark font characters are right-clipped in the REPL producing an unfortunate visual result

### ISSUE THREAD

**Issue by bazzaar** [rakudo/rakudo#3986]
I've just installed rakudo 2020.10 on a new 14" Dell laptop with HiRes screen running openSUSE Leap 15.2. Unfortunately, when I fire up the repl, in the default bash shell, with no modifications having been made to either the font type or font size displayed, I am greeted by two messages that appear to refer to "Faku/Fakudo" in nice bold embellished font. 

Copying the text into an editor, the characters are in fact "Raku/Rakudo", as expected. So what appears to be the case is that there is clipping to the right side of each character that is in the fancy font-type. I thought I'd better raise it as an issue, before someone or other jumps on it.

**Comment by lizmat** [comment]
Related: https://github.com/Raku/problem-solving/issues/193  and https://github.com/rakudo/rakudo/commit/80a4ada62ea08f7a3b17d1f8dee55800b6beb3d5

**Comment by Kaiepi** [comment]
I had a similar issue to this one. Here's Raku losing its temper over my xterm setup on OpenBSD:
![2020-10-28-025524_399x66_scrot](https://user-images.githubusercontent.com/34197615/97473368-e661a300-1918-11eb-922f-8c679e5c478e.png)

Firefox seemed calm enough in comparison, so I figured it would be a problem specific to xterm at first:
![2020-10-28-025542_377x35_scrot](https://user-images.githubusercontent.com/34197615/97473399-efeb0b00-1918-11eb-94b7-94049f1ed1f3.png)

But I had already set up my locale and `.Xdefaults` for Unicode ages ago, so I figured that there was other configuration involved that I had overlooked. I found a couple config settings for xterm that become relevant when displaying this text:
![2020-10-28-030250_297x33_scrot](https://user-images.githubusercontent.com/34197615/97495280-6d247900-1935-11eb-8f9e-f1e737746ec0.png)

While they make the text render, these were introduced to xterm to handle quirks in Xft's font rendering, which would indicate to me the issue's more with configuration for my fonts, not so much my terminal. The problem was that `DejaVu Math TeX Gyre`, the font that was being selected as a fallback when rendering this text, is *w i d e*; too wide for even single-width characters like that "R" to fit in one cell when selected in favour of the narrower monospace ones that xterm stubbornly defines their boundaries with. Blacklisting DejaVu fonts so friendlier fonts for my setup get the chance to display makes the text readable for me:
![2020-10-28-180042_395x68_scrot](https://user-images.githubusercontent.com/34197615/97496289-c04afb80-1936-11eb-8315-f390cfbdbbc3.png)

But this isn't a problem unique to xterm: urxvt and Konsole can fail to render glyphs in similar scenarios. I think font configuration is likely to be the culprit behind this issue as well.

**Comment by Altai-man** [comment]
This is unfortunate, but not a blocker for the release.

**Comment by lizmat** [comment]
Please note that the `raku -v` output only uses ASCII since 329e47f4354aedbd69 and now in the 2020.11 release.  I don't see the text change for the REPL case any time soon, so I'm going to close this issue.  Please re-open if you disagree.

**Comment by Altai-man** [comment]
@bazzaar can you please check latest release?

**Comment by bazzaar** [comment]
> @bazzaar can you please check latest release?

I'll upgrade to 2020.11 once the pkg becomes available in

https://dl.bintray.com/nxadm/rakudo-pkg-rpms/openSUSE/15.2/x86_64

and then report back.
