### ISSUE TITLE
Trademark (™) text added to Raku version strings

### ISSUE THREAD

**Issue by atweiden** [rakudo/rakudo#3992]
```
$ raku --version
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.10.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2020.10.
```

[80a4ada6][80a4ada6] appends the trademark symbol to Raku and Rakudo in `raku` version strings.

I have never seen an open source programming language — whether mainstream or not-so-mainstream — tag its version string with **™**. This change is an extreme departure from common convention.

I'm opening this issue because I think it'd be in the best interests of the Raku ecosystem to avoid ™ing its version string per [80a4ada6][80a4ada6].

I do not have any objection to trademarking Raku or Rakudo.

[80a4ada6]: https://github.com/rakudo/rakudo/commit/80a4ada62ea08f7a3b17d1f8dee55800b6beb3d5#comments

**Comment by lizmat** [comment]
https://github.com/Raku/problem-solving/issues/193

**Comment by atweiden** [comment]
What are the chances this version string can be removed post trademark application?

**Comment by lizmat** [comment]
> I'm opening this issue because I think it'd be in the best interests of the Raku ecosystem to avoid ™ing its version string

@atweiden Could you elaborate how having a ™ in the Rakudo version string is not in the best interests of the Raku ecosystem?

**Comment by atweiden** [comment]
Simple: there are no other open source programming languages which TM the version string. Given TMing the version string is an unprecedented and extreme departure from accepted standard practice, the onus is on the proposer to justify doing it.

**Comment by niner** [comment]
@atweiden the justification is simply that the trade mark lawyer requested it. We're following their legal advice.
Which concrete problems does using the trademark symbol create that we would have to weigh against the legal requirement?

**Comment by atweiden** [comment]
IANAL, but is it really the case that, of all the open source programming langauges on the planet, Raku was the *only one* that has *ever* had to TM its version string to get a trademark application through? Why? Why was that the *one* and only way to do it? The onus is on our lawyer friend to justify the extreme departure from accepted standard practice.

**Comment by lizmat** [comment]
@atweiden Still not sure why this is a problem in any way.  Are you afraid that other programming languages will follow?  And if not, why not.

Seriously, if we're talking about threats to open source, I would worry more about e.g. Github being owned by Microsoft.  Or some other issues that the EFF has put on the agenda.  So, colour me confused?

**Comment by ugexe** [comment]
I think the question of 'why' stands regardless, so perhaps getting an answer for that from the lawyer would make more sense than debating if its a problem.

**Comment by niner** [comment]
In my experience it's better to treat legal matters like fuzzy logic or quantum theory. Gray is much more common than pure black or white. E.g. you can follow an image license to the letter, but at the end of the day the judge may still read it differently. And that's assuming that the license even makes a clear statement. So what you do is simply trying to maximize your chances (within your budget of course). And that's what we do here.

We're trying to get a trademark on a common Japanese word. That means we need to demonstrate:
* that we use it in the first place
* that it's associated with our product and
* that we're doing our best to defend it.
Because if you don't defend your trademark against improper use, you will lose it. First step in defending is to make it clear that it's yours.

Like I said, there rarely is a "the law says that you absolutely have to do precisely this". It's rather more ambiguous and you have to work with that. And if in doubt, "do what the lawyer says" is usually really good advice.

On the other hand, we still don't know which concrete problems using the trademark symbol does create that we would have to weigh against the legal requirement. @atweiden please tell us. Raku and Rakudo both have departed from standard practice in a lot of areas. Indeed, the whole point of creating yet another language was to do things differently. Otherwise, what would we gain? Why is this matter different?

**Comment by lizmat** [comment]
What @niner said.  Having been taken to court because of name / trademark issues, I can only concur.  The initial reaction of our lawyer was: you will never win this.  We went ahead and won twice.  And that was all because in the end the trademark was insufficiently defended.

**Comment by atweiden** [comment]
@niner completely agreed: Raku's developer experience is Perlish, which is i.e. the opposite of enterprisey and Java-esque. IMO TMing the version string of a Perl heritage programming language is rather out of character, to put it mildly. Again IANAL, but maybe there's some way to remove the TM after the trademark application goes through.

**Comment by lizmat** [comment]
Removing the (tm) after the trademark application goes through, is equivalent to not defending the trademark.  So not a good thing to do, I'd say.

It becomes a different story should the trademark be denied.

**Comment by lizmat** [comment]
````
$ raku
Welcome to Rakudo™ v2021.12.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.12.

To exit type 'exit' or '^D'
> 
````
This is what it boiled down to in the end.  Closing now.
