### ISSUE TITLE
use v6.e.PREVIEW does not allow mixin of custom roles

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#3998]
```
use v6.e.PREVIEW;
role R {};
my $a = Int but R;
```

fails with:
```
Type object Int+{R} of v6.c is not compatible with R of v6.e
  in block <unit> at /home/dex/tmp/tmp3.raku line 3
```

The expected output is none.

It would be nice to have this sorted before Christmas or testing modules before the release of v6.e might be difficult. I did not check if there are futher problems with precomp.

**Comment by lizmat** [comment]
See also: https://github.com/rakudo/rakudo/issues/3990

**Comment by vrurg** [comment]
What is seen here is totally expected and legal behavior. Looks I should've postponed many things and eventually write that article about roles... The problem is that `Int` is a core class and as such belongs to 6.c and expects a role applied to it to be a 6.c/6.d one. Here is why:

```raku
use v6.e.PREVIEW;
# use v6.c;

role R {
    submethod TWEAK { say "init R" }
    submethod foo { say "foo is here" };
}

class C does R {
    submethod TWEAK { say "init C" }
    method bar {
        self.foo;
    }
}

C.new.bar;
```

Depending on which version pragma is activated the outcome of this snippet would be different. A class developed for 6.c would expect a submethod from consumed role to be incorporated. But a role from 6.e would, on the contrary, expect its submethods to remain its sole property.

What solutions are possible for mixins? One I mentioned already in #3990: declare a role to be mixed in into a core class in an external module under `use v6.c` pragma. Certainly not a solution for a one-liner. But a way to go for a bigger project.

Otherwise it is apparent that mixins were somewhat overlooked when the big role overhaul was discussed and implemented. More focus were given to typeobject versioning with respect to parameters matching, etc. Another thing to mention with this respect is that any cross-language interaction is a problem by definition which hardly has a good solution.

So, what we need for this ticket sample to work? Both class and role must be on the same side of language boundaries. And a boundary means a language version transition which brings in incompatible changes. In our case it's one boundary and it is placed between 6.c/d and 6.e. So, either role gets 6.c or 6.d language version or the class get 6.e. The latter is generally speaking possible because mixins are implemented by cloning a typeobject and setting the original class as mixin's parent.

Let's consider the role first. It's language revision can be set with `R.^set_language_revision($rev)`, except that it is only allowed once and if not done early at the role's composition time then `.^compose` enforces it with what's current compiler revision is. This is how we get 6.e for `R` in the example. So, what could be done is:

```raku
use v6.e.PREVIEW;

multi trait_mod:<is>(Mu \r, Str:D :$rev) {
    r.^set_language_revision($rev);
}
role R is rev<c> { };

my $v = 0 but R;
```

This works. `rev`, or `revision`, or `lang-rev` could be made a core trait. Note that it would change `R` behavior and none of 6.e role implementation perks will be available to `R`.

Alternatively it could be possible to introduce `:rev` adverb: `role R :rev<c> { }`, but if memory serves me right, not clear decision has been made if such adverb wouldn't be harmful.

The solution which involves change of mixin behavior is in spectesting right now. It was initially setting mixin class language revision based on the source class. I.e. mixin of `Int` had revision `c` derived from it. Simply removing this functionality do fix the case. It is also likely to pass all spectests with no complains. Yet, I'm not 100% sure if it's safe. If spectests are ok then perhaps a Blin run would provide more inforamtion about the state of things.
