### ISSUE TITLE
Why is a parameterized role body run twice in some cases?

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#4062]
Given this role:

    role Foo[|c] { dd c }

The following outputs are given on these inputs:

    Foo.new;
    # \()

    Foo[:bar].new
    # \(:bar)

    Foo[42].new
    # \(42)
    # \(42)

This appears only to happen if a **positional** value is given in the parameterization of the role.

**Comment by lizmat** [comment]
A bisect points to https://github.com/rakudo/rakudo/commit/41f6f9eaae8477a4955fb468d9a52ae6dff208b3

**Comment by vrurg** [comment]
A quick check shows that the first call comes from optimization and is a result of some kind of typechecking it does. The second is the actual puning. I don't remember all the details, but there was a problem with `;;` in role signature which required an extra parameterization to be done in order to get correct typechecking.

Is it really a problem? It only happens in case of punning.

**Comment by lizmat** [comment]
Well, it feels like a problem to me, as one does not expect this.  And if the role uses some external resources, it might waste them being called twice.  Or if it does some extensive setup, having that being done twice may also be a significant performance sink.

@jnthn should this considered to be a problem or not?

**Comment by AlexDaniel** [comment]
FWIW this isn't considered as a bug, or at least wasn't:
```raku
multi sub foo($x where say ‘hello’) { }
foo 42
```
```
hello
hello
```

**Comment by lizmat** [comment]
That feels at least as an optimization opportunity ?

**Comment by AlexDaniel** [comment]
If there's only one multi, then yes. But how many *multi* are there with just one candidate? It is a slight optimization opportunity, but the actual optimization opportunity is not doing what it currently does :)

**Comment by lizmat** [comment]
Ok, I may be dense.  But why would it make a difference whether the sub is a multi or not?

    > sub foo($x where say ‘hello’) { }; foo 42
    hello

    > multi sub foo($x where say ‘hello’) { }; foo 42
    hello
    hello

Note that these are all runtime.

**Comment by AlexDaniel** [comment]
Yes, you are right. Runtime checks should only run once, that's common sense. In fact they should preferably run zero times, but at least we can probably all agree that more than once is inferior. But in case of multis, I think the extra call is somehow needed to figure out which multi to run, and for the reason I can't remember now, it is not possible/hard to eliminate that. My guess is that you can relatively easily optimize it so that it doesn't run it twice in case of a single multi, but most multis probably have more than one candidate (otherwise why were they marked as `multi` in the first place?), so that kind of optimization probably brings very little benefit.

BTW, fixing it for good will probably break some code that relies on setting stuff from `where`, or something along those lines. My opinion is that things like this should be outright banned, but yes, I myself wrote code that relies on that.

What's complete news to me is that *every* multi seems to be running twice:
```raku
multi sub foo($x where /{say ‘hello’}4/) { say $/ };
multi sub foo($x where /{say ‘world’}9/) { say $/ };
foo 9
```
```
hello
hello
world
world
｢9｣
```

OK now that is just weird.

**Comment by lizmat** [comment]
Circling back to the original question: it looks like indeed only roles with positional parameters are the ones that are cached: anything else will just not be cached:

    https://github.com/rakudo/rakudo/blob/master/src/Perl6/Metamodel/ParametricRoleGroupHOW.nqp#L59

**Comment by lizmat** [comment]
Possibly related, given:

    role A[|c] { }

    > A[42] =:= A[42]
    True
    > A[:foo] =:= A[:foo]
    False

Now, it looks like the `A[:foo]` *is* a compile time value at the given call site.  But if so, what is the point then of caching parameterized roles otherwise?  Perhaps we should not cache them at all?

**Comment by vrurg** [comment]
> Circling back to the original question: it looks like indeed only roles with positional parameters are the ones that are cached: anything else will just not be cached: https://github.com/rakudo/rakudo/blob/master/src/Perl6/Metamodel/ParametricRoleGroupHOW.nqp#L59

It looks like the reasoning behind the comment is better be asked from @jnthn. Here is my speculation based on the code: `nqp::parameterizetype` can't handle nameds. So, if any is used in role's signature then they're pushed at the end of role arguments array and this is used as parameterization key. The problem is that each time when the parameterization happens a new hash is created. And that hash is considered as the last positional argument, making two identically parameterized role candidates different. So, that's what @lizmat observed in the last comment with `A[:foo] =:= A[:foo]`.

Rewinding back a little to Alex note on multies. There is no wonder you have to calls to `where`. The first call comes from binder which looks up a candidate by matching a capture to the signature. Apparently, full check involves invocation of `where`. The second time happens when actual bind takes pace and argument value is typechecked against `Parameter` type for validity.

_Off-top_ It just crossed my mind that perhaps there is no need to re-check bindings on multis because the dispatcher has done this for us. OTOH, it can't be fully avoided as a multi-candidate could be invoked directly.

Anyway, back to the initial matter. As to something being invoked multiple times behind the scenes the best example would be 5-6 invocations of `Proxy::FETCH` when passed to `say`. The thing which will likely to be confusing to any newbie (mine is not an exceptio :) ). And within the current implementation of `Proxy` I don't see a way for this situation to be improved for as long as there is no way to hint the compiler that the next `FETCH` is going to return the same value.

Similar situation takes place here. Except for the named parameters issue, otherwise things work as they should. The commit the issue was bisected down to, is a fix for old problems about typematching of roles consuming other roles. To be done correctly it required all the consumed roles to be parameterized alongside with the consuming one. The proper parameterization requires a `type_env` and that's why an "incomplete" role invokes it's body in first place. 

BTW:
1. bodies of consumed roles will be invoked as well
2. if where is `where` constraint used in a role signature it will be invoked even more times because of multi-dispatch used to find the correct candidate

The second invocation of the body is a result of actual specialization of a curried role. At this point typeenv is obtained for the second time. And as I look into the code right now, it seems that this invocation could possibly be avoided _if_ it's guaranteed that the curried role metaclass instance is always operating on the same arguments.

**Comment by vrurg** [comment]
Unfortunately, I don't see how a typeenv could be re-used. It has to be saved in an attribute of `Metamodel::CurriedRoleHOW`. But `BOOTContext` is not a serializeable thing and being stored in an attribute causes a panic at `mast` stage of compilation. So, I currently don't see a way to optimize out the double-call case.

**Comment by coke** [comment]
```
20:42 < [Coke]> m: multi sub foo($x where say 'hello') { }; foo 42
20:42 < camelia> rakudo-moar 21271aa5f: OUTPUT: «hello␤»
```

I think this is one of the cleanups that new-disp brought.

I only tested one of the early variants, however. Is this safe to close?

**Comment by vrurg** [comment]
@coke It's only a single fix. Role parameterization is still done the old style and thus the original issue remains unresolved.

**Comment by jnthn** [comment]
> It looks like the reasoning behind the comment is better be asked from @jnthn. Here is my speculation based on the code: nqp::parameterizetype can't handle nameds. So, if any is used in role's signature then they're pushed at the end of role arguments array and this is used as parameterization key. The problem is that each time when the parameterization happens a new hash is created. And that hash is considered as the last positional argument, making two identically parameterized role candidates different. So, that's what @lizmat observed in the last comment with A[:foo] =:= A[:foo]

In general with multiple dispatch, only the types of positional arguments are considered as part of the declarative aspect, with named arguments being handled imperatively (e.g. by invoking the candidate and seeing if it binds). The parameterization mechanism is similarly restricted.

**Comment by lizmat** [comment]
Test added with https://github.com/rakudo/rakudo/commit/91f2f3c19a
