### ISSUE TITLE
Coercion  vs Subset Dispatch Ordering

### ISSUE THREAD

**Issue by Xliff** [rakudo/rakudo#4074]
## The Problem

The way I am interpreting the spec, I would expect subsets to be more restrictive than coercion on a given Parameter value, however this is not how it is currently handled in HEAD. See below:

## Expected Behavior

```raku
subset IntegerStr where Int | Str; 
multi sub a (IntStr $arg) { say 'IntStr' }; 
multi sub a (Num() $arg) { say 'Num' }; 
a('Hi');  # returns IntStr
a(42);  # returns IntStr
a(pi)    # returns Num
```

## Actual Behavior

```raku
subset IntegerStr where Int | Str; 
multi sub a (IntStr $arg) { say 'IntStr' }; 
multi sub a (Num() $arg) { say 'Num' }; 
a('Hi');  # returns Num
a(42);  # returns Num
a(pi)    # returns Num
```

### Suggested Fix

Would it be possible to order Coercive parameters to be slightly higher in dispatch order than a Parameter with no type requirement. This would solve the problem with, I hope, not much change in the code.

In the case where both a Coercive and a No-Type parameter are given in the same multi, ala:

```raku
multi sub a (Num() $arg) { say 'Num' }; 
multi sub a ($arg) { say 'Not typed' };
```

A warning should be returned warning the user that the last multi will never get executed.

**Comment by vrurg** [comment]
I'm not an expert in multi-dispatch algorith, but to my view it works as it must. The, not sure what exactly `IntegerStr` does in your snippet. I could expect it to either be a leftover from other experiment; or where you use `IntStr` you meant it to be `IntegerStr`. Let's consider both options.

### The `IntStr`  case

It's really simple. Neither `"42" ~~ IntStr` nor `42 ~~ IntStr`. But `<42> ~~ IntStr` is true. So,

```raku
a(<42>); # IntStr
```

As they say in Mythbusters: Busted! :)

### `IntegerStr` case

It actually works as expected.

```raku
subset IntegerStr where Int | Str; 
multi sub a (IntStr $arg) { say 'IntStr' }; 
multi sub a (Num() $arg) { say 'Num' }; 
a('Hi');  # returns IntStr
a(42);  # returns IntStr
a(pi)    # returns Num
```

Output:

```raku
IntegerStr
IntegerStr
Num
```

### The warning

```raku
multi sub a (Num() $arg) { say 'Num' };
multi sub a($v) { say "Any" }
a('Hi');  # returns IntStr
a(42);  # returns IntStr
a(pi);    # returns Num
```

This results in:

```
Ambiguous call to 'a(Str)'; these signatures all match:
  (Num(Any) $arg)
  ($v)
  in block <unit> at multi.p6 line 6
```

Which I consider as a correct one because trully, both signatures accepts it. It is not relevant that there gonna be an error if the actual coercion is attempted because all what matters for the signature binding is wether constraints are applicable to the argument.

I think it's ok to close this issue, but feel free to re-open if I missed something.
