### ISSUE TITLE
Warning on use of `contains` or `index` with collections; and other traps due to naming?

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#4098]
Imo the warnings that are displayed when `contains` or `index` are called on `List`s (or subtypes thereof) are an excellent solution to the corresponding entry on the traps page.

----

I recently encountered [this](https://www.reddit.com/r/adventofcode/comments/k6nbmv/2020_day_4_part2_raku_off_by_one/) in the 2020 AdventOfCode, with the following bug and comment by the adventering Scala dev:
```
when /^(<digit>+)'cm'$/ { take (150..193).contains($/[0].Int) }
```

> I'm glad I asked for help, because I would not have found that myself!

Perhaps this is a perfect example of how we don't have to drive Raku into being a nanny PL. Someone can get stuck, ask, and it becomes a communal learning process, and that's OK.

But, maybe we do want to do something, and I imagine it's already been discussed:
```
say (10..30).contains: 5;                    # True
say (10..30).index: 5;                       # 16
say {:1a, :2b, :!c, :d, :e}.contains: 's';   # True
say {:1a, :2b, :!c, :d, :e}.index: 'b';      # 4
```

I've looked for, but have been unable to find, discussion of the above, and having warnings if these two routines are called on other `Iterable`s.

----

I can well imagine that several discussions have been had and I've just failed to find them. And that the decision, if the above examples were discussed, was that producing warnings when `contains` or `index` were applied to `List`s and `Array`s was sufficient, at least for the near term.

After all, the underlying technical issue is that these routines silently coerce to string, and, more generally that Raku fully embraces weak typing. So devs who guess what a routine does without checking the doc may get bit, and that can be perfectly cromulent, even if those used to strong static typing by default for all built ins might be put off.

And/or, that having warnings when these routines are applied to `List`s may well be just the right and sufficient touch, because newbies will likely quickly bump into the issue, and either see the warning, or be pointed to the warning if they don't spot it, or can be pointed to the `List` warning if they encounter the problem with some other collection type that doesn't warn, so perhaps it's all good.

----

While I'm writing this I can't help but also wonder if there are other routines or type names that are plausibly similarly problematic, and, if so, if a warning is plausibly the right solution for any of these but no warning has yet been introduced.

Specifically, Raku routines, types,, keywords, constants, etc with a name that is familiar to coders in other major PLs, but such that what that name implies in those PLs is sufficiently awkwardly inconsistent with what it implies in Raku that it may also deserve a warning.

To be clear, I don't think this applies to things like `Regex`. Yes, it's a common name for something that devs are familiar with, but Raku regexes are different. But most devs know what a "regex" is varies among PLs, so I don't see this as an issue.

Similarly `Int`. Yes, a dev will guess it means *integer*, and may be familiar with integer behaviour in other PLs, but they should, again, know the details vary among PLs.

And it doesn't matter if they think, say, that `sub` means subtract. If they try it in that way they'll quickly be disabused of that idea.

Instead I just mean things that are good candidates for the traps page, and a warning can potentially assist with that documentation or even lead to its removal from the traps page.

----

Fwiw, I suggest this issue is closable if the conclusion is that, for now, nothing further will be done, or if `contains` and `index` on ranges and hashes (and sequences? `Iterable`s?) will warn.

**Comment by AlexDaniel** [comment]
Here's [the discussion](https://github.com/Raku/doc/issues/992) with all the downvotes. However, maybe people's stance has changed since then, because nobody seemed to be complaining about the warnings that were added some time later. That's good.

> And that the decision, if the above examples were discussed, was that producing warnings when contains or index were applied to Lists and Arrays was sufficient, at least for the near term.

Yes, but… there was actually no decision. The warnings were just committed almost randomly and nobody objected because there was no discussion during that time. :)

Yes, it is pretty obvious that the operation that is being performed on non-Strs is extremely useless and outright misleading, and that the user should be explicit if they actually want it (`.Str.contains`). Yes, all such operations should at least produce a warning, although I wish they did not work at all in the first place.

**Comment by raiph** [comment]
> Here's the discussion

Thanks. :)

> with all the downvotes.

"all"? ^1

> nobody seemed to be complaining about the warnings that were added some time later. That's good.

\o/ ^2

> The warnings were just committed almost randomly

(But wisely, right? ^3)

> and nobody objected because there was no discussion during that time. :)

.oO( Or there was no discussion, and has been none since, because nobody objected... )

> Yes, it is pretty obvious that the operation that is being performed on non-Strs is extremely useless and outright misleading

Do you agree it makes sense for `contains` and `index` to work on non-Strs with sensible `.Str` coercions and/or warn for all `Iterable`s? ^4

Fwiw I'm pretty sure I *would* steadfastly argue *against* `contains` or `index` having non string related meanings when applied to non-Strs. Aiui you would vote against that too, and the thread you link demonstrates pretty solid consensus among Raku core devs in agreement that it having two distinct semantics would be completely inconsistent with Raku's general approach.

As another detail, I think `starts-with` and `ends-with` are fine without warnings, because:

* Unlike `contains` and `index`, they are not names that have standard meanings among PLs, so folk are much less likely to jump to conclusions about what they do, and folk would have to ignore `first``;

* Pretty much all plausible `.Str` coercions of objects, even `Iterable`s, produce a single string per element, and most of them add a space between elements, so `starts-with` and `ends-with`  will not only generally work as intended, but will continue to do so as the data changes, with the only exception being when both haystack elements and the needle have spacing in them, and, well, someone would then learn a potentially painful lesson they need to learn. :)

----

All in all I suspect that for `contains` and `index`, a relatively friendly consensus could be built around one of these options:

* **Leave things as they are now.** As I wrote in my first comment in this issue (with the addition of a bit in [...]):

> ... having warnings when these routines are applied to `List`s may well be just the right and sufficient touch, because newbies will likely quickly bump into the issue, and either see the warning, or be pointed to the warning if they don't spot it, or can be pointed to the `List` warning [and the traps page] if they encounter the problem with some other collection type that doesn't warn

* **Accept Liz's PR.** That is to say, add warnings when using `contains` or `index` on `Range`s and `Map`s. And perhaps add further refinements.^4

> the user should be explicit if they actually want it (.Str.contains). Yes, all such operations should at least produce a warning, although I wish they did not work at all in the first place.

I too wish we'd never gotten these problematic routine names in the first place -- their very *names* have the sort of ambiguity between strings and collections that Larry was trying to avoid in Raku.

But they're in, and I would expect them to stay in until there's consensus (if ever) that Raku folk are ready (if ever) to deprecate them in some clean fashion (which I'm thinking might be `Iterable`s).

It's ultimately far more important to develop and sustain a friendly community vibe for consensus building than it is what the consensus is. Otherwise Raku will end up with the worst of all worlds, which is to say, fighting, which will drive away those who ultimately wish to enjoy themselves participating in a volunteer endeavour.

----

^1 At the time of writing this comment, I see count 22 upvotes, a lot of constructive discussion, a heart, and just 2 downvotes in that thread. Are you saying there were originally a bunch of downvotes and they've since been cleared? The two remaining downvotes are by the same person. The downvoter did not contribute any comments in the thread, so it's not easy to know what they objected to. The downvoter had already by then established some history of reacting with strong negative opinions to some of the things they thought they had just learned about Raku, and then not really getting what those familiar with Raku tried to explain to them. If I were you, I'd largely ignore their feedback.

^2 Imo the added warnings were a solid compromise step forward given the rough consensus expressed in the thread you linked. To the degree I'd qualify my opinion, or talk about possible additional steps, this issue is where I'm doing so.

 ^3 I would characterize the existing warnings to be the sort of change that constitutes an (easily reversible) tentative decision presumably made with humility and wisdom. I would have thought such commits are important for projects like Raku, especially given that, afaik, Rakudo commit bits are harder to come by than were, say, PUGS commit bits.

While I think it's appropriate that folk work to build consensus before committing anything significant, especially if turns out there's pushback by some folk in response to the very idea, the converse seems true too. That is to say, imo, if a committer is reasonably sensible, and deems a commit to be relatively insignificant, and deems it to be in accord with rough consensus on what should be committed to Raku(do), and acts on the basis that they won't mind their commits being challenged and/or reverted, then forgiveness > permission applies. After all, it's all under revision control, with various social processes surrounding our activity, so there's pretty limited likelihood that constant significant disruption due to unwise or otherwise inappropriate commits will overwhelm the benefits of devs steadily improving things without undue bureaucracy.

That all said, Liz has clearly decided not to commit the additional warning change she's prepared in response to me opening this issue but instead prepare a PR. So she presumably felt this needed sensitive handling. Or perhaps this is the new normal for Raku work, which would imo be fair enough if y'all arrived at that new normal via consensus building.

^4 With consensus building in mind and cf https://github.com/rakudo/rakudo/pull/4099#issuecomment-742093925

**Comment by AlexDaniel** [comment]
> "all"?

Well, there are also 3 upvotes for “I don't understand what about this is a trap.”, which is essentially the rever… wait, 2 upvotes now? Yeah, I guess people have changed their minds on this since then, which is good. But from what I remember, the message at the time was very clear. Something along the lines that it's how Perl 6 works and by suggesting something different I either misunderstand it or try to turn it into something completely different (well, yes, I'd still like to change it into something that is better, but that's a different topic). Though even in that thread you can see that even back then I gave up suggesting to change the language, and instead suggested to merely change the documentation.

> (But wisely, right? ^3)

It's a step in the right direction.

> Do you agree it makes sense for contains and index to work on non-Strs with sensible .Str coercions and/or warn for all Iterables? ^4

It should at the very least warn, but I don't agree that it should do .Str coercions. In short term it could continue working for backcompat, but in general, providing functionality that users shouldn't use and that linters will highlight as wrong just doesn't make sense (instead just don't provide the misleading functionality, as simple as that).

> Aiui you would vote against that too, and the thread you link demonstrates pretty solid consensus among Raku core devs in agreement that it having two distinct semantics would be completely inconsistent with Raku's general approach

That's correct, the method shouldn't have different functionality depending on what you call it on, or so I think. It simply shouldn't exist for non-Strs. Yes, I know that Cool provides it, but that just means that something about Cool is wrong (perhaps the idea of it altogether). That's probably one of the reasons why people get so negative in these discussions – everything boils down to the very core decisions that we can now see are wrong.

> As another detail, I think starts-with and ends-with are fine without warnings

These perform a useless and inefficient operation. If there is any rare use for that, you can always do an explicit `.Str.starts-with` or even better `[0].starts-with` (these are obviously different, but the latter doesn't stringify the whole potentially big array).

> well, someone would then learn a potentially painful lesson they need to learn

No, the user is not wrong, the language is.

> It's ultimately far more important to develop and sustain a friendly community vibe for consensus building than it is what the consensus is.

I agree, but so far there has been a well-sustained and consistent vibe for not *changing* the language at all, only *adding* more stuff to it. The warnings for Cool traps happily slipped through and that's fantastic, but that's far from consensus building that would eventually steer the language into a healthier state.

**Comment by raiph** [comment]
> I gave up suggesting to change the language, and instead suggested to merely change the documentation.

Given that the title of your issue was about just changing the doc, that seems reasonable.

That said, I see an overwhelming majority, by both comments and votes, suggesting that the language *should* be changed. I see *no one* arguing it should *not*.

> in general, providing functionality that users shouldn't use and that linters will highlight as wrong just doesn't make sense (instead just don't provide the misleading functionality, as simple as that).

I agree with that as a *general* principle, but if friendly consensus regarding a breaking change to the language has not been built then it is *not* "as simple as that".

> so far there has been a well-sustained and consistent vibe for not changing the language at all, only adding more stuff to it.

The support for language change is clear in the thread you linked. So at least back then, the vibe you described was not evident in that thread.

I do recall you and Zoffix both expressing frustration about that at some points, and I hear the frustration. I well recall posting a comment in which I merely noted a *very* sensible additional parameter for a method that would make it something in the order of a thousand times as fast as any other built in option for a *very* fundamental string operation. Zoffix just about bit my head off.

But I also recall seeing Zoffix switch dramatically and very successfully to consensus building. That was very heartening (even if the hostility aimed at him during the 6.d release was almost enough to drive me out of the Raku community, and was certainly a contributing factor to me generally just minding my own business).

> The warnings for `Cool` traps happily slipped through and that's fantastic, but that's far from consensus building that would eventually steer the language into a healthier state.

I presume you would agree that you were not trying to build consensus about language change in your 2016/2017 thread, right? You were really just focusing on the doc, right?

Afaik you recently took a step away from contributing as a core Raku dev, but if I'm wrong, or even if that's right, could you see yourself being at least part of an attempt to build consensus on language change related to this in 6.f?

**Comment by AlexDaniel** [comment]
> I presume you would agree that you were not trying to build consensus about language change in your 2016/2017 thread, right? You were really just focusing on the doc, right?

Correct. Consensus to make the required change wasn't an option. Even the idea of documenting the issue as a trap wasn't very welcome. I explained it more [here](https://github.com/Raku/problem-solving/issues/67#issuecomment-627361890). With that ticket my idea in general was to plant some seeds to change the mentality – stop defending language decisions even if they're bad and start planning long-term changes. I failed, it wasn't successful.

> The support for language change is clear in the thread you linked. So at least back then, the vibe you described was not evident in that thread.

I don't see how it can not be evident. I created a ticket that immediately got at least one downvote. Then another comment saying “I don't understand what about this is a trap.” and at least three people immediately upvoting that. You might think they misunderstood (the OP didn't have any description, just a code example), but let me assure you they knew full well what the issue is about, especially given that there was an IRC discussion about it as well (OK, except the person who wrote the initial comment, they seem to actually didn't understand). Then another comment saying “The majority opinion seams to be no-trap”. And from IRC: “I don't think you could get very far in Perl 6 without realizing that it works in that way.” which besides being false can be said about pretty much anything.

Don't get me wrong, I like your optimism, but the reality is what it is. Maybe the vibe we're talking about is even more evident when considering all the other discussions where a very similar thing was happening. If we look at just the Cool traps then it may indeed seem OK, after all the warnings were added, right.

> could you see yourself being at least part of an attempt to build consensus on language change related to this in 6.f?

My understanding is that I was explicitly [excluded](https://github.com/Raku/Raku-Steering-Council/commit/0475d105ae2045cd41192f925b56e5e33fa1742f) from anything like that, and possibly anything at all. It isn't very clear. Thing is, you wondered if there were any discussions, and I just happened to have started a discussion on that exact topic. So I mentioned it and cleared some related things up. Can't do anything else, sorry.

**Comment by niner** [comment]
On Freitag, 11. Dezember 2020 02:12:53 CET Aleks-Daniel Jakimenko-Aleksejev 
> > The support for language change is clear in the thread you linked. So at
> > least back then, the vibe you described was not evident in that thread.
> 
> I don't see how it can not be evident. I created a ticket that immediately
> got at least one downvote. Then another comment saying “I don't understand
> what about this is a trap.” and at least three people immediately upvoting
> that.

It's exactly this contorted representation that led to the RSC decision about 
your involvement. It's very obvious why there was a downvote and why someone 
didn't understand what the trap would be about. In the initial comment you 
listed precisely those cases where the methods in question actually gave the 
expected result, i.e. the cases where regardless of whether you treat the 
input as a string or as a list, you get the same results.

So where's the trap? Of course there is one. But you spectacularly failed to 
show it.

> You might think they misunderstood (the OP didn't have any
> description, just a code example), but let me assure you they knew full
> well what the issue is about, especially given that there was an IRC
> discussion about it as well (OK, except the person who wrote the initial
> comment, they seem to actually didn't understand).

Except the person who wrote the initial answer to your issue. And except the 
person who down voted your initial comment. And except the 2 people who up 
voted the "I don't see the trap" comment. And except the one who wrote the 
second answer to your issue. So who is "they"?

Sounds more like two distinct groups of people had two completely different 
reactions to this topic. The group who only knew about your failed examples 
had a negative reaction and the actual core developers group which knew about 
the trap actually discussed the topic and found plenty arguments for both 
sides and explored options. But that doesn't fit the narrative you want to 
sell, does it?

> Then another comment
> saying “The majority opinion seams to be no-trap”. And from IRC: “I don't
> think you could get very far in Perl 6 without realizing that it works in
> that way.” which besides being false can be said about pretty much
> anything.

Also a long and nuanced discussion with explanations of why it's probably 
better to live with what we have, rather than to replace it with other 
inconsistencies. AFAICT there was universal agreement on there being trade 
offs.

**Comment by lizmat** [comment]
This latest interaction of AlexDaniel has made the enact the banning of AlexDaniel (as decided by the RSC) from the rakudo repository.  AlexDaniel is now no longer a member of the rakudo organization on GitHub and has been banned from accessing anything from the rakudo organization.

**Comment by raiph** [comment]
Thanks Liz.

Given Liz's merge of her PR, this issue now leads to many plausible follow up concerns, but I don't see any that merit immediately opening a new issue, and none that warrant keeping this one open.
