### ISSUE TITLE
String to enum conversion silently returns enum type object

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#4116]
## The Problem
This:
```
raku -e 'enum Foo <Bar Baz>; sub foo(Foo(Str) $foo) { dd $foo }; foo("Bar")'
```
prints "Foo"

## Expected Behavior
Either
* It throws an `X::Coerce` exception
* It successfully converts to `Foo::Bar`

## Actual Behavior
It converts almost any string to the type object `Foo`

## Environment
```
Welcome to Rakudo(tm) v2020.11.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.11.
```

**Comment by vrurg** [comment]
Looks like the new coercions revealed an old issue. On 2020.10 and earlier releases `enum Foo <Bar Baz>; say Foo("Bar")` results in `(Foo)` too whereas `Foo(0)` results in correct `Foo::Bar`. 

It looks like the core of the problem is `Enumeration` method `!FROM-VALUE` which is by default accepts any value.

Another side of the problem is that we lack any specs related to `enum` behaviors in such cases. The current outcome is what `EnumHOW` thinks would be appropriate to return when it finds no match. Checking against f4837f5310cf5b002d816aaaa9c35c0ac6130149 I could guess that it was a quick fix for a problem, not a well-thought decision. So, I think it should be possible and even necessary to work out a definitive spec.

**Comment by Altai-man** [comment]
Is it a blocker?

**Comment by Leont** [comment]
> Is it a blocker?

I wouldn't consider it so, as this never worked before

**Comment by Leont** [comment]
It's perfectly possible to convert `Str` to an enum using `$type.WHO{$str}`, it's just a very counter-intuitive way of doing so.

**Comment by vrurg** [comment]
Preliminary, I played with making enum return a `Failure` on 'no key found' event. Then I considered the possibility of coercion to throw on failures and it proves to be no-go option because it breaks numerous specs where a `Failure` is expected to bypass coercion typechecking.

The current options to consider would be:

- enums throw on no key
- enums return a `Failure` and it is expected to leak into a parameter for later user handling or exploding

I currently have no personal preferences to either of the two. Both have advantages and issues.

With regard to supporting strings in enum coercion, I'll try to look into it when get some time.

**Comment by Leont** [comment]
> Then I considered the possibility of coercion to throw on failures and it proves to be no-go option because it breaks numerous specs where a Failure is expected to bypass coercion typechecking.

If it only throws on `COERCE` and not on `CALL-ME` I think nothing should break?

**Comment by vrurg** [comment]
We must not be selective on what types make coercion throw, and what don't. It'd be inconsistent. I'm currently in favor of preserving the current "`Failure` bypass" and implementing support for stringy keys.

**Comment by vrurg** [comment]
I looked deeper into the problem today and the final verdict is against `Foo("Bar")` doing lookups on enumeration keys. Two reasons behind it.

First, `Foo.enums<Bar>` does it for us. This is certainly better than `.WHO` alternative.

Second, `enum` values can be of any type, not necessarily `Int`. I.e., for `enum Foo (:a<A>, :b<B>, :c<C>)` there is no clear way to tell wether `Foo("A")` is a key or a value lookup kind of operation. However confusing would be a declaration like `enum Foo (:A<B>, :B<A>)` but the outcome of `Foo("A")` must be predictable.

I still consider it be the right thing for enums to result in a `Failure` when coercing from a non-existing value. It requires me to get a failing spec fixed. But otherwise it's the only change I consider necessary for get this issue straighten out.

**Comment by Leont** [comment]
> Second, enum values can be of any type, not necessarily Int.

Right, I had forgotten about that.

> I still consider it be the right thing for enums to result in a Failure when coercing from a non-existing value.

Yeah that makes sense.

**Comment by vrurg** [comment]
#4130 should take care of this issue.
