### ISSUE TITLE
Bool ~~ Enumeration is false

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#4124]
## The Problem
Despite `Bool.HOW ~~ Perl6::Metamodel::EnumHOW`, `Bool` isn't an `Enumeration`, unlike other enums.

## Expected Behavior
~~~
raku -e 'say Bool ~~ Enumeration'
True
~~~

## Actual Behavior
~~~
raku -e 'say Bool ~~ Enumeration'
False
~~~

## Environment
```
Welcome to Rakudo(tm) v2020.11.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.11.
```

**Comment by vrurg** [comment]
`Bool` stands on its own because it's a bootstrap type. `Enumeration` gets declared at a later stage, when `6.c` core is compiled. 

Basically, sharing the same metaclass doesn't mandate any relations between type objects. Same way we can create class which wouldn't inherit from `Mu` and yet be backed by `ClassHOW`.

Besides, what'd be the advantage of `Bool` consuming `Enumeration`?

**Comment by Leont** [comment]
> Besides, what'd be the advantage of Bool consuming Enumeration?

It's just an expectation based on «Bool is an enum» and «\[Enumeration] is the role implemented by the enum-pairs in the enum type.»

**Comment by vrurg** [comment]
Unfortunately, I can't tell if this expectation was broken intentionally or because it's technically hard to fulfill it. But as I don't see any advantages in `Bool` to be an `Enumeration` neither I don't foresee it to change any time soon. Therefore, if you don't mind, I would close the issue by now. But feel free to re-open if you don't agree. Though in this case I'd rather consider opening a problem-solving ticket because it's more a matter of language design.

**Comment by lizmat** [comment]
It's very hard to implement because of bootstrapping issues.  It *is* already a lot better than it used to be, perhaps @niner would like to chime in, has he's the one who made `Bool` an actual `enum`.

**Comment by jnthn** [comment]
> It's very hard to implement because of bootstrapping issues

I was going to say "is it", but looked, and yeah, it kinda is, because the `Enumeration` role brings state, so you can't just add it with `augment`.

**Comment by jnthn** [comment]
The current state of affairs is, however, unfortunate, IMO. I agree it probably *should* do `Enumeration`.

**Comment by Leont** [comment]
> The current state of affairs is, however, unfortunate, IMO. I agree it probably should do Enumeration.

Does that mean this issue should be reopened? (even if it's unlikely to be fixed any time soon)

**Comment by pmichaud** [comment]
FWIW, the definition and treatment of boolean types has _always_ been an issue in Rakudo's design and implementation (and possibly in Raku as well).

IIRC, $Larry used to refer to the cruftiness of the boolean type as just one of those things that had to be shimmed in (in his words, using a "circularity saw").  I remember banging my head against the definitional issues as far back as 2005.  (!)

Pm

**Comment by niner** [comment]
On Dienstag, 22. Dezember 2020 23:58:58 CET Vadim Belman wrote:
> Unfortunately, I can't tell if this expectation was broken intentionally or
> because it's technically hard to fulfill it.

There were 2 reasons, none of them was intention. Getting it to where we are 
now was already hard and the final step would have been even harder. The other 
reason was simply that I didn't fully understand how enum, Enumeration and 
EnumHOW were related. Back then our documentation was in its infancy and the 
speculations were already outdated (and don't mention the Enumeration role at 
all).
