### ISSUE TITLE
Accessing a private class method from a role is at least 10x as slow

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#4133]
It looks like something is blocking optimization of calling a private method in a consuming class from the role that is being consumed.  Take this code:

```raku

role C {
    method !foo { ... }
    method bar() { self!foo for ^1000000 }
}

class A does C {
    method !foo { 42 }
}

class B {
    method !foo { 42 }
    method bar() { self!foo for ^1000000 }
}

my $then;

$then = now;
A.bar;
my $role = now - $then;

$then = now;
B.bar;
my $class = now - $then;

say "role is { sprintf "%.2fx", $role / $class } slower"
```

This shows that a method from a role calling a private method from the consuming class is at least **50x** as slow, as a method of a class calling a private method of that class.

Since role composition should make no difference in this respect (I would say, but please correct me if I'm wrong) we seem to have some low hanging fruit for making things faster.

Changing the privateness of the method being called, *does* improve things (only about **6x** as slow), but still, that shouldn't be the case either, I'd say.

**Comment by lizmat** [comment]
Some further looking at this, it looks like `method !foo` is **not** gettings speshed, let alone being JITted (it stays red in a profile).  Also, `dispatch:<!>` is at the top in such a profile at 40+%.  Not sure which one is cause or effect, but there you go.

**Comment by jnthn** [comment]
The speedup of private method dispatch is done by a spesh plugin; the rewrite into the spesh plugin on the MoarVM backend is done as an optimization pass. My recollection is that the optimizer does not look into roles, due to some issues around them being run as part of the compilation.

One option for a fix is "just wait"; the new RakuAST compiler frontend will just generate the spesh plugin call on the MoarVM backend unconditionally rather than expecting it to be rewritten, and will probably not have the same optimization restrictions as exist for roles today anyway.

**Comment by lizmat** [comment]
Progress!
```
% raku scriptt
role is 9.35x slower
% RAKUDO_RAKUAST=1 raku script
role is 0.90x slower
```
