### ISSUE TITLE
Concatenated regexes' `.raku` output prints the unexpanded regex

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#4137]
## The Problem
Concatenated regexes' `dd` output prints the unexpanded regex. This makes debugging such regular expressions very difficult.

## Expected Behavior
```
raku -e 'my $foo = /a/; my $bar = /b/; dd /$foo$bar/'
Regex $baz = /ab/
```

## Actual Behavior
```
raku -e 'my $foo = /a/; my $bar = /b/; dd /$foo$bar/'
Regex $baz = /$foo$bar/
```

## Environment
```
Welcome to Rakudo(tm) v2020.12.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12.
```

**Comment by lizmat** [comment]
Isn't that just a problem with `Regex.raku` ?   `dd foo` is basically just short for `note foo.raku` with some bells and whistles.

**Comment by Leont** [comment]
> Isn't that just a problem with Regex.raku ? dd foo is basically just short for note foo.raku with some bells and whistles.

Fair, updated the title.

**Comment by jnthn** [comment]
Regexes aren't strings, but rather code; when we have a variable mentioned in a regex, it compiles into a lookup and, if that lookup happens to resolve to something of type `Regex`, then it is called (otherwise it is stringified and the string is matched at that point).

Even if we figured a way around that to somehow get the values of the variables closed over by a particular closure of the regex, it'd be hugely misleading to stringify them just by substituting the variables with their content; of note, any captures in the interpolated things are not captures of the enclosing regex, but rather captures in separate `Match` objects (which in the example given are discarded).

fwiw, once we have macros, I was inclined to submit a proposal that regexes do *not* end up with the source code string 
attached to them any longer, and `like` (from `Test`) - which is the main motivator for the code being stashed away - would become a `macro`, which can then keep the source around on a case by case basis. A debugging module could be written on the same terms (and probably there'd be some elegant way to figure out the mentioned variables and have those possible to dump too).

**Comment by Leont** [comment]
> Regexes aren't strings, but rather code

Fair point. I guess

What I really need I guess is a regex builder (the code that caused me to run into this converts a glob pattern into a regex), regex concatenation is the best tool I currently have for that.

Arguably, when RakuAST arrives, I should look into rewriting it to use that.
