### ISSUE TITLE
Nil<a> gives Nil. It should trigger an error

### ISSUE THREAD

**Issue by cognominal** [rakudo/rakudo#4167]
I think that should trigger an error.
I hit that when dealing with a failed match. Discussion below.
But I think Nil is not a hash anyway so I think it is an incorrect behavior

On the mistaken assumption that a match has succeeded, on can think
it has accessed a possible submatch using `$<a>`.
This is different  from a non existing submatch on a successful match which 
gives a Nil,  similar to using a non existing key on a regular hash.

```
  > 'b' ~~ / $<a>=a /; say $<a> # should fail
 Nil
 > 'b' ~~ / $<b>=a /; say $<a> # does and should give some form of undefined
 Nil
 > my %a; say %a<a>               # ...like for a vanilla hash
 (Any)
```

lucasb remarks on #raku that it is an expected behavior.
acording to https://docs.raku.org/type/Nil :

```
The value Nil may be used to fill a spot where a value would normally go, 
and in so doing, explicitly indicate that no value is present.
It may also be used as a cheaper and less explosive alternative to a Failure. 
(In fact, class Failure is derived from Nil, so smartmatching Nil will also match Failure.)
```
This leads back to the failed match which is not litteraly a Failure value... but is somehow a failure.

**Comment by salortiz** [comment]
As the mildest form of "failure", the user must be used to the nature of `Nil` in raku:

```raku
# You can call almost any method on it
Nil.succ ~~ Nil; # True
# Even nonexistent ones
Nil.foo ~~ Nil; # True
# Nil isn't an Array but
Nil.[42] ~~ Nil;  # True
# In the same way that a vanilla Nil array;
my Nil @a; @a[42] ~~ Nil; # True;
```
So the behavior observed when treated as a a `Hash` should be expected.

In the particular case of an unssucceful  match the user should check if `$/ ~~ Nil` or `$/.defined` before using it.

**Comment by vrurg** [comment]
@cognominal salortiz explained it very well. `Nil<a>` is actually nothing but `Nil.AT-KEY("a")` which is `Nil`. Overall, this fits nicely into the common use of regexes for which failing to match is not a failure whatsoever. I.e. in your example `"b" ~~ /a/` returning a `Failure` would be pretty much an overkill. Same could be told about failing on a non-exiting key on a `Match` object. I.e. `"a" ~~ /$<a>=a/; say $<b>` must not die for obvious reasons.

The situation is different when it comes to grammars. That's why in `6.e` a grammar will return a `Failure` if can't parse a string.

No bug in here, I'm closing the issue.
