### ISSUE TITLE
Promise appears to confuse Test::proclaim

### ISSUE THREAD

**Issue by jonathanstowe** [rakudo/rakudo#4176]
## The Problem

It seems that `proclaim` in Test is unable  to determine the callframe when e.g. `ok` is called in a Promise `then` when the test fails.

## Expected Behavior

Test should report `not ok`

## Actual Behavior

```
not ok 1 - fail
An operation first awaited:
  in block <unit> at -e line 1

Died with the exception:
    No callframe at level 11
      in sub proclaim at /usr/local/share/perl6/core/sources/2D4A7CA10695CD2B374573413D261A660E282E2A (Test) line 776
      in sub ok at /usr/local/share/perl6/core/sources/2D4A7CA10695CD2B374573413D261A660E282E2A (Test) line 138
      in block  at -e line 1

Actually thrown at:
  in sub proclaim at /usr/local/share/perl6/core/sources/2D4A7CA10695CD2B374573413D261A660E282E2A (Test) line 776
  in sub ok at /usr/local/share/perl6/core/sources/2D4A7CA10695CD2B374573413D261A660E282E2A (Test) line 138
  in block  at -e line 1

```

## Steps to Reproduce

```
raku -e ' use Test;  await Promise.in(1).then({ ok False, "fail"; True; })'
```

## Environment
* Operating system: Fedora 32 (Workstation Edition) 5.10.7-100.fc32.x86_64
* Compiler version:

```
[jonathan@menenius CheckSocket]$ raku -v
Welcome to Rakudo(tm) v2020.12-35-g4d40e23e0.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12-16-g34f9d8c7a.
```

**Comment by vrurg** [comment]
I produced a PR to fix this, but must make a note that using tests this way isn't a good practice. The core `Test` module isn't designed to work in a concurrent environment. And because `Promise.then` can and likely will fire in a thread there is a non-zero chance that any test sub invoked in it will disrupt test output. I've seen this kind of problem in action. It happens because the module doesn't do atomized output to the console.

I have addressed these issues in `Test::Async`. It's somewhat slower than the core module, but much safer and can do more. So, I'd either recommend to use it instead (it's a drop-in replacement for 99% cases), or just set some kind of a boolean flag in the `Promise.then` and test it later, when it's safe.

**Comment by jonathanstowe** [comment]
In the particular case I have the `.then` basically runs *all* the tests after a promise in another thread is kept after some initialisation.  I actually flipped it setting some booleans when I noticed this, but it had previously been working fine for some five years or so.
