### ISSUE TITLE
`say` of result of hyperop applied to shaped array fails

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#4205]
## The Problem
```
say my @array[1] = 1; # [1]
say @array>>++;       # Type check failed in binding to parameter '@dims'; expected Positional but got Any (Any)
```
## Expected Behavior

That it works.

## Actual Behavior

Without the (second) `say`, it works. But with it it fails.

**Comment by lizmat** [comment]
Problem golfed to:

    (my @a[1]>>++).raku

The problem appears to be that the `.shape` method on the array is all of a sudden returning `Any`.  So it looks like the hypering creates an array of similar type, but loses the shape information in the process.

**Comment by lizmat** [comment]
Further golfed to:

    my Int @a[1] = 42;
    @a.new.raku;

It looks like calling `.new` on a defined shaped array does *not* copy the shape information.

**Comment by jnthn** [comment]
> It looks like calling .new on a defined shaped array does not copy the shape information.

I'd not expect it to; copying attributes isn't what `new` generally does.

**Comment by lizmat** [comment]
But that's what happens in the bowels of `>>`, and then we wind up with a shaped array without shape, which then barfs on `.raku` or `.gist`, causing the issue as shown by the op.

**Comment by jnthn** [comment]
> we wind up with a shaped array without shape

It should probably be an error to construct one without providing the shape.

> that's what happens in the bowels of >>

Probably it should pass along the shape to `new`.

**Comment by lizmat** [comment]
Also, with regards to not copying attributes: this already happens with `Array.new`, which does not actually copy the descriptor, but creates a new one like the old one (well, presumably, it doesn't actually check).

Anyways, this is the source of the issue: https://github.com/rakudo/rakudo/blob/master/src/core.c/Rakudo/Internals.pm6#L1658

**Comment by lizmat** [comment]
So, why *does* `>>." not return a simple `List` ???

If I make `>>.` return a `List` always, then there are 4 spectest failures, all related the fact that the check assumes an array will be returned, and now there's a List instead.  Please note that **all** of these tests are checking the `.gist` of the result with an `is`, and are not using an `is-deeply`:

````
t/spec/S03-metaops/hyper.rakudo.moar                            (Wstat: 768 Tests: 412 Failed: 3)
  Failed tests:  106, 108, 112
  Non-zero exit status: 3
t/spec/S32-list/deepmap.t                                       (Wstat: 256 Tests: 8 Failed: 1)
  Failed test:  7
  Non-zero exit status: 1
```` 

Now, the behaviour of the `xxxmap` functions, has been a source of discussion for a long time.  And in some ways, I think this aspect has been overlooked in the GLR.

This is the patch to have `>>.` always return a `List`:

```` raku
diff --git a/src/core.c/Rakudo/Internals.pm6 b/src/core.c/Rakudo/Internals.pm6
index 93e935656..a2254f847 100644
--- a/src/core.c/Rakudo/Internals.pm6
+++ b/src/core.c/Rakudo/Internals.pm6
@@ -1646,16 +1646,20 @@ implementation detail and has no serviceable parts inside"
             }
         }
     }
-    multi method coremap(\op, \obj, Bool :$deep) {
+    multi method coremap(
+      \op,
+      \obj,
+      Bool :$deep,
+      :$type = nqp::istype(obj, List) ?? obj.WHAT !! List # keep subtypes of List
+    ) {
         my \iterable := obj.DEFINITE && nqp::istype(obj, Iterable)
           ?? obj
           !! obj.list;
 
         my \result := CoreMap.new(op, iterable.iterator, $deep);
-        my \type := nqp::istype(obj, List) ?? obj.WHAT !! List; # keep subtypes of List
         my \buffer := nqp::create(IterationBuffer);
         result.push-all(buffer);
-        my \retval := type.new;
+        my \retval := $type.new;
         nqp::bindattr(retval, List, '$!reified', buffer);
         nqp::iscont(obj) ?? retval.item !! retval;
     }
diff --git a/src/core.c/metaops.pm6 b/src/core.c/metaops.pm6
index 616acc96a..3e6bcbad1 100644
--- a/src/core.c/metaops.pm6
+++ b/src/core.c/metaops.pm6
@@ -526,7 +526,7 @@ sub HYPER(\operator, :$dwim-left, :$dwim-right, |c) is implementation-detail {
 
 proto sub deepmap($, $, *%) {*}
 multi sub deepmap(\op, \obj) {
-    Rakudo::Internals.coremap(op, obj, :deep)
+    Rakudo::Internals.coremap(op, obj, :deep, :type(List))
 }
````

Since `>>.` is supposed to be able to actually have multiple threads run the mapper, it feels more natural to actually have it return a `Seq` rather than a `List`, as that would allow results to be returned before the last batch is actually finished.

**Comment by raiph** [comment]
> So, why does >>. not return a simple List ???

Perhaps I'm missing something, but I think changing it would mean at least the following three negatives:

* Breaking existing code in the wild (at a guess; I'd be amazed if it there wasn't a ton of breakage that relies on in-place mutation;

* Switching from what seem to me to be unsurprising semantics (in-place mutating operations can be hypered) to what seem to me to be surprising or at least disappointing semantics (in-place mutating operations become non-in-place when hypered);

* Eroding the strength of Raku's principle of providing first class support for mutability. (I love the work going on to beef up Raku's support for immutability, but would be sad to see it come at a cost of such an excellent use case for mutability as mutation via hypers.)

> Now, the behaviour of the xxxmap functions, has been a source of discussion for a long time. And in some ways, I think this aspect has been overlooked in the GLR.

Right. Perhaps it would be good to have a separate set of 6.f oriented discussions focused on how coherence might be improved over the longer term regarding nested processing, with each of the maps, plus hypers, getting their own issues. Discuss matters carefully over the next few years. Perhaps some stuff such as a deprecation or two, maybe something bigger, gets extracted out in prep for 6.e. Perhaps we do better than that.

> Since >>. is supposed to be able to actually have multiple threads run the mapper, it feels more natural to actually have it return a Seq rather than a List, as that would allow results to be *returned before the last batch is actually finished*.

Hyper semantics are that you don't mind what order results are generated in, provided they are *returned* in correct order. Hyper semantics are *eager*, not *lazy*, and `Seq`s are more about being lazy.

**Comment by raiph** [comment]
`@foo` is clearly getting rebound to the clone post hypering:
```
my @foo = 1;
my $where = @foo.WHERE;
say @foo.WHERE == $where; # True
@foo>>++;
say @foo.WHERE == $where; # True
say (@foo>>++).shape; # (*)
say @foo.shape;  # (*)
```
When the first line is changed to a shaped array (`my @foo[1];`) the WHERE lines still display `True`, and the last line displays `(1)`, but the `say (@foo>>++).shape;` displays `(Any)`. What's up with that?

**Comment by raiph** [comment]
I looked in roast but did not find any testing of hypers applied to shaped arrays.

**Comment by raiph** [comment]
Perhaps the following should be in another issue but it feels best to keep everything here for now.

The result of binary hypers is unshaped:

```
my @foo[1] = 1;
my @bar[1] = 1;

my @baz = @foo <<+>> @bar;

say @baz.shape; # (*)
````

The binary hypers that insist their operands are length compatible complain based on array contents encountered at run-time during the hyperoperation
```
my (@foo, @bar);
sink @foo >>+<< @bar; # OK
@foo = 1;
sink @foo >>+<< @bar; # Lists ... not of the same length
```
They ignore shapes. That is to say this error:
```
my (@foo[1], @bar[2]);
sink @foo >>+<< @bar; # Lengths ... not of the same length
```
is due to hyper encountering the mismatch, not due to it paying attention to the `.shape`s.

Presuming that the operator being applied by a hyperoperator never itself alters the shape of the resulting hyperoperation, couldn't the hyperops that care about size:

* See at the start if both operands are shaped, and, if so:
* If they *aren't* the same shape, then immediately complain/fail;
* If they *are* the same shape, then elide any checking overhead..

?

**Comment by lizmat** [comment]
@raiph:  That's a lot of comments.  I'll try to answer all of them.  Please let me know if I missed anything.

Returning a `List` does **NOT** mean mutability is changed.  Observe:

    my $list = (my $, my $, my $);
    $list = (1,2,3);
    say $list;  # (1 2 3)

Making it return a `List` **ONLY** breaks 4 spectests, which implicitly check for an `Array` being returned.  And these tests fail only because their `.gist`s don't match, because `Array`s gist differently from `List`s.

So:

> Breaking existing code in the wild (at a guess; I'd be amazed if it there wasn't a ton of breakage that relies on in-place mutation;

It won't break code because of that, as in-place mutation is still possible.

> Switching from what seem to me to be unsurprising semantics (in-place mutating operations can be hypered) to what seem to me to be surprising or at least disappointing semantics (in-place mutating operations become non-in-place when hypered);

Also, not an issue.  There is **no** change in that respect.

> Eroding the strength of Raku's principle of providing first class support for mutability. (I love the work going on to beef up Raku's support for immutability, but would be sad to see it come at a cost of such an excellent use case for mutability as mutation via hypers.)

There will be no eroding.  For instance, hypers on `Seq`s *already* return `List`s:

    my @a = ^10;
    say (@a.Seq>>++).^name;  # List
    dd @a;  # Array @a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

> Right. Perhaps it would be good to have a separate set of 6.f oriented discussions focused on how coherence might be improved over the longer term regarding nested processing, with each of the maps, plus hypers, getting their own issues. Discuss matters carefully over the next few years. Perhaps some stuff such as a deprecation or two, maybe something bigger, gets extracted out in prep for 6.e. Perhaps we do better than that.

Well, I would agree with that sentiment: the GLR was a good initial step, but it was also little bit under stress of the upcoming first release.  And we've learnt (well, at least I have) about the corner cases and problems in making the implementation faster.

Your remarks were sparked by the misconceptions that `List`s can only contain immutable values.  This is **NOT** True, although many people live under that misunderstanding.  This is the reason I made a `Tuple` module, so you *can* have a `List`-like object that is a value type.

Even worse, although one cannot `push` or `shift` from a `List`, the size of a `List` is **not** immutable, as it can have a reifier that can grow the underlying `nqp::list`.  All of these architectural considerations I feel have their basis in the earliest implementation based on Parrot.  With what we know now, I feel we probably wouldn't have developed the whole `List` / `Array` / `Array::Typed` / `Array::Shaped` architecture.

But changing this will be **hard**.  But I think at one point we *will* have to do that.

> Hyper semantics are that you don't mind what order results are generated in, provided they are returned in correct order. Hyper semantics are eager, not lazy, and Seqs are more about being lazy.

`Seq` are **not** about being lazy.  `Seq`s are about wrapping iterators, and iterators can be lazy or not.  Now, if nothing is asking the iterator to produce any values, then nothing will happen.  So I guess you can call them lazy in that sense.  In practice, it's become pretty hard to create situations that do not cause iterators to produce values  :-)

> `@foo` is clearly getting rebound to the clone post hypering:

That is incorrect.  `@foo` is asked to produce its values, which in the case of an `Array` are containers.  These are then passed to the `Callable` that is used to hyper (in your original example, `&postfix:<++>`).  The result of the call to the `Callable` is then collected in something akin to the source if it is a (sub)type of `List`.  Otherwise, the result is collected in a `List`, and *that* is being returned.  The source is unchanged, except if we call something with side-effects, such as `++`.

> but the say `(@foo>>++).shape`; displays `(Any)`. What's up with that?

**THAT** is why you see the problem that you originally described.  The `>>.` process called `.new` on its source, and produces something that sorta looks like a shaped array, but is incomplete.  Observe:

    my @a[1] = 42; dd @a.shape, @a.new.shape;  # (1,) Any

> The result of binary hypers is unshaped:

That is an entirely different piece of code, and probably a different kind of problem.  So that would be best kept in a different issue.

**Comment by raiph** [comment]
@lizmat++

> Your remarks were sparked by the misconceptions that Lists can only contain immutable values.

No. I well know that lists can be mutable. I just misunderstood what you meant by "simple" when you wrote "simple List". (Btw it would be great if you could read it and comment (on SO) about anything that's misleading in [my answer to the StackOverflow question "Array vs. list data type?"](https://stackoverflow.com/questions/49580177/array-vs-list-data-type/49580888#49580888). It's the accepted answer, and perhaps influential in terms of what folk think is or isn't true about arrays and lists.)

> Seq are not about being lazy.

Fair enough. What I meant was that, aiui, hypers formally promise eager semantics and informally promise implementation evolution (over, say, the next decade) toward high performance computing. Maybe I'm wrong about one or both of those notions, or maybe a Seq is compatible with both?

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/3c9f655860

**Comment by lizmat** [comment]
Commented on the SO post and fixed up some stuff there.  I think this issue can now be closed.  I think the issues mentioned here warrant separate issues.

**Comment by patrickbkr** [comment]
Can someone clarify what the contract wrt `new` is?
I assumed, that `new` is always meant to behave the same irrespective if it's called on an object or the class. (Similar to how constructors behave in e.g. Java or C++, there they can't even be called on an object.) I do see the logic behind shaped arrays copying their type and dimensions. (In the sense as typing and shape can be perceived to be part of the type and not the content. They are specified on the left side of the `=` and not to the right of it.)

I'd really like for this to be consistently handled in the core of the language.

**Comment by lizmat** [comment]
I think in the case of shaped arrays, the problem really is that the shape is *not* part of the type, hence needing to create this workaround.

BTW, the same issue (and workaround) exists with typed arrays:

```` raku
my Int @a;
say @a.raku;         # Array[Int].new()
say @a.CREATE.raku;  # Array[Mu].new()
say @a.new.raku;     # Array[Int].new()

I think we will have to live with this until we revisit how lists / arrays / sequences interact in Raku

**Comment by raiph** [comment]
> I assumed, that `new` is always meant to behave the same irrespective if it's called on an object or the class.

Oh that's not right. Methods called on an object *default* to whatever is used to construct it, but it's free to react to method calls in any way it chooses.

> (Similar to how constructors behave in e.g. Java or C++, there they can't even be called on an object.)

That reflects a fundamental difference between Raku and those languages. There are two schools of OO epitomized by Simula on the one hand and Smalltalk / Actors on the other. C++ and Java originally chose just one school, JavaScript originally chose the other, and now both are slowly painfully evolving to integrate some of the other school. Somewhat like CLOS, Raku unified them from the get go and that was a deeply wise decision imo.

> I do see the logic behind shaped arrays copying their type and dimensions.

I'd say it depends on the situation. I'm with jnthn on it being appropriate to not presume such things but rather allow them as optional (named) arguments of constructors, even `.clone` despite the usual connotations of "clone".

> I'd really like for this to be consistently handled in the core of the language.

I agree, provided "consistent" doesn't mean foolishly so but rather consistent with the language's overall design.

**Comment by lizmat** [comment]
FWIW, this does not appear to be the case for hashes or object hashes.

**Comment by lizmat** [comment]
> provided "consistent" doesn't mean foolishly so but rather consistent with the language's overall design.

I believe the change I made in https://github.com/rakudo/rakudo/commit/623d4c1276e62f4f9cf2f0119c708d27c7f9286c is consistent with the language's overall design.  The fact that the shape is not part of the type, is an unfortunate implementation detail, I'd say.

**Comment by lizmat** [comment]
Closing now since it appears fixed.  Please re-open if disagree.
