### ISSUE TITLE
DateTime method 'hh-mm-ss' should have option for showing fractional seconds

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#4322]
## The Problem

DateTime method *hh-mm-ss* shows only the integral parts of a day.

## Expected Behavior

The method should have an option to show the seconds as a fractional value.

## Actual Behavior

Only integral parts are shown.

## Steps to Reproduce

    my $t = DateTime.new: :year(2021), :second(1.2);
    say $t.hh-mm-ss
    '00:00:01'

**Comment by lizmat** [comment]
The `ss` in name sorta implies the format?

**Comment by Altai-man** [comment]
Cannot it be done with a custom formatter?

**Comment by tbrowder** [comment]
How about another method: 'HMS' or 'HMSss' or similar:

    my $t = DateTime.new: :2021year, :second(1.2);
    say $t.HMSss
    00:00:00.20

**Comment by vrurg** [comment]
> How about another method: 'HMS' or 'HMSss' or similar:

We shouldn't produce a method for every possible use case. I'd rather be happy to see `strftime`-like formatting method.

**Comment by Altai-man** [comment]
```
> my $t = DateTime.new: :year(2021), :second(1.2), formatter => sub ($self) { sprintf "%05f", .second given $self };
1.200000
> say $t
1.200000
```

There is already a builtin option to format a DateTime object in any possible way you want via providing a custom `formatter` routine.

**Comment by vrurg** [comment]
I know about formatter. And consider it a big mistake. One should be able to easily represent same `DataTime` object differently depending on context. Whereas the concept of formatter implies that to change the representation one has to clone it because it's not even specced if the attribute can be changed in any way!

Simply put, we gave `.fmt` method to `Cool` objects, but we denied it for `DateTime`. Why??

**Comment by lizmat** [comment]
> Why??

No idea.

**Comment by vrurg** [comment]
BTW, a little correction. It's not the formatter itself which I consider a mistake, but it being the only entity responsible for `DateTime` stringification is what's wrong. Otherwise it is potentially beneficial for l10n purposes, even though we currently have no appropriate support for this.

**Comment by Altai-man** [comment]
>I know about formatter. And consider it a big mistake

For the record, I was referring to the originally raised issue about fractional seconds displaying, trying to convey we don't need a special method or really any additional code in Rakudo to do what the ticket starter wants (and it is not even an ugly solution, it's a tiny patch). Whether it is a good idea for all possible use cases is entirely different issue.

>One should be able to easily represent same DataTime object differently depending on context

I guess you are aware of workarounding with something like

```
my $*FORMAT = 2;
say DateTime.new(now, formatter => sub ($self) {
    given $*FORMAT {
        when 1 { .second ~ " hehe" given $self }
        when 2 { .second ~ " te-he" given $self }
        default { "Boo!" }
    }
})
```

I think where `fmt` is more restrictive rather than `formatter` is that it takes only a format string and you need to maintain context logic from the outside in every place if you need to have different outputs.

**Comment by vrurg** [comment]
> I guess you are aware of workarounding with something like

That's terrible because it's more like magic to me. In a big-to-huge codebase one would have to remember all these variables, what their values mean, don't forget to set them where needed to what is right. Maintain them properly if the same object is used in two different outputs within same codeblock...

Phew... Gimme a break! ;)

Really, these are two different mechanisms with different purposes. Whereas formatter is really good for an uniform app with same approach to `DateTime` formatting across it, `.fmt` or alike is for where external control makes more sense. One doesn't exclude another.

**Comment by tbrowder** [comment]
Maybe a new module is the answer--something like 'DateTime::Extended'.

**Comment by alabamenhu** [comment]
> BTW, a little correction. It's not the formatter itself which I consider a mistake, but it being the only entity responsible for `DateTime` stringification is what's wrong. Otherwise it is potentially beneficial for l10n purposes, even though we currently have no appropriate support for this.

Well, depends on your definition of *we* [;-)](https://github.com/alabamenhu/IntlFormatDateTime) 
 Localized formatting of dates is the singularly most complicated of all the international modules I have, so it should stay as far away from core as possible ^_^  

Personally, I think the `formatter` for `Datish` should be deprecated.  The stringification of a value type should be consistent — `Datish` is the *only* built in with this option. In exchange, perhaps, a `.fmt` could be addedthat uses the same semantics as a standard tool like POSIX's `date` (itself based in part on ISO C). A `Date`/`DateTime` isn't really a single number/string like what `Cool.fmt` expects (probably answers your earlier question), so it makes sense to have it follow a different, though equally standardized, format.  That way users could easily have year-week-dayofweek formatting in lieu of year-month-day, for instance, by doing `$date.fmt('%Y-%V-%u')` (output: `2021-23-7` for today).  Realistically, too, most users would probably be caring about the formatting after creation rather than during, so it would be more intuitive.

**Comment by alabamenhu** [comment]
@tbrowder you may wish to take a look at https://github.com/alabamenhu/DateTimeFmt which is my working repository for adding a `.fmt` method that uses POSIX formatting syntax (once I polish it up more in the next few days, I'll propose it formally as an addition to Raku).  To do the formatting you'd want:

```raku
$date.fmt: '%H:%M:%s.%L'; # 12:34:56.789
$date.fmt: '%H:%M:%s.%f'; # 12:34:56.789012
$date.fmt: '%H:%M:%s.%N'; # 12:34:56.789012345
```

Where `%H` = 24-hour (`%I` is 12-hour), `%M` = minute, `%S` = seconds.  

There are three fractional elements, `%L` for mi**LL**iseconds (pioneered by Ruby), `%f` for **F**racional microseconds (hat tip to Python), and `%N` for **N**anoseconds (thanks Perl).  The latter allows for precision via its width parameter, so if you only wanted a tenth of a second or a femtosecond (lol):

```raku
$date.fmt: '%H:%M:%s.%1N';  # 12:34:56.7
$date.fmt: '%H:%M:%s.%15N'; # 12:34:56.789012345678901
```

**Comment by b2gills** [comment]
To bring it back to the original problem with `.hh-mm-ss` only producing whole seconds.

I see two solutions.

1. Have a named argument.
    ```raku
    my $t = DateTime.new: :year(2021), :second(1.2);
    say $t.hh-mm-ss(:fractional);
    # 00:00:01.2
    ```
2. Punt on this and instead rely on a generic formatter like `:formatter` or `.fmt` or `.date-fmt` etc.
    Ignore what the exact name of this is, only pay attention to its ability to generate the correct string result.

    In which case we can just close this issue. (And ignore everything following this.)

---

If we go with 1. we would have to decide on the name of the named argument.  
We could could use `:fractional`, `:f`, `:frac`, or something else.  
I think `:frac` is a bad name for the same or similar reason that `.uniq` was a bad name.

Since `.hh-mm-ss` was meant to be a shorthand, it would make sense to allow `:f` as a synonym of `:fractional` if that is the name decided.

`:fractional` could take an argument.

But is it similar to `.round`?

```raku
my $t = DateTime.new: :year(2021), :second(1.2);
say $t.hh-mm-ss(:fractional(0.001));
# 00:00:01.200
```

Or is it similar to `.fmt`, `sprintf`?

```raku
my $t = DateTime.new: :year(2021), :second(1.2);
say $t.hh-mm-ss(:fractional('%.3f')); # '%02.3f'
# 00:00:01.200
```

Or does it do something strange and one off like just specifying the number of digits after the decimal?

```raku
my $t = DateTime.new: :year(2021), :second(1.2);
say $t.hh-mm-ss(:fractional(3));
# 00:00:01.200
```

Of those three, only the `.round` version seems to not be absolutely terrible.  
It also doesn't seem like the obviously correct approach.

Since I can't come up with what the argument in `:fractional(…)` should be; it makes me question if this is the right approach at all.

As such, I am tentatively going to say that 2. is the best approach.

**Comment by tbrowder** [comment]
I like the new module and approach by @alabamenhu. I'm closing this issue.
