### ISSUE TITLE
subst method  can put \r\n into a string

### ISSUE THREAD

**Issue by dwarring** [rakudo/rakudo#4349]
## The Problem

Related to [an issue in cro-http](https://github.com/croservices/cro-http/issues/136)

Golfs to the following, which does URL decoding:
```
my $name = "aa%0D%0Abb";
$name .= subst(:g, /'%' (<[A..Fa..f0..9]>**2)/, {
                            my $ord = :16(.[0].Str);
                            chr($ord)
                        });
dd $name
```
Produces: `Str $name = "aa\r\nbb"

## Expected Behavior

Output: Str $name = "aa\nbb"

## Actual Behavior

Output: `Str $name = "aa\r\nbb"

## Environment
* Operating system:Linux toshiba 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`):Welcome to Rakudo(tm) v2021.04.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.04.

**Comment by demanuel** [comment]
If i understood correctly you are replacing %0D and %0A by the corresponding chars.
`0x0D` is decimal value 13 and  `0x0A` value is 10 which corresponds to `\r `and `\n`. I would say that the behaviour is correct.

Am i missing something?

**Comment by jnthn** [comment]
It looks correct to me also.

It's true that `IO::Handle` will normalize `\r\n` into `\n` by default (and the reverse on output if on Windows). However, that's a behavior of IO handles, not of strings in general. There's no prohibition on `\r\n` being in a `Str`. One might argue that Cro's HTTP body parser should normalize these into `\n` to give a consistent experience with Raku's `IO::Handle`, but that'd happen there, not be enforced by the language.

What *would* be a bug is if `\r\n` came out as two separate graphemes rather than a single composed one. However, if we `say $name.chars`, we get 5, as expected. So that looks alright to me also.
