### ISSUE TITLE
regex /<!space>*/ should produce an error message rather that getting into an infinite loop

### ISSUE THREAD

**Issue by florian-pe** [rakudo/rakudo#4390]
## The Problem

When doing this

```
raku -e 'say "abc" ~~ /<!space>*/'
```
or this
```
raku -e 'say "abc" ~~ /<!space>* d/'
```
the regex never mathes because it goes into an infinite loop.
This is because what is quantified by the star (greedily) is a zero-width assertion that prevent the current match attempt to advance in the string or in the regex.

## Expected Behavior

This should either
- be optimizied by the regex engine
- produced an errror message when parsing or compiling the regex

so as to avoid going into that infinite loop

### Little context from my possibly misunderstanding of this issue

to be fair, I don't understand fully the new regex syntax, and I didn't find a clear explanation in the documentation
(https://docs.raku.org/language/regexes)
as to what does a excalamation point means when placed just after an angle bracket
`<space> --> <!space>`
it is vaguely explain that in the case `<!after>`  or `<![abc]>` it produce a negative lookaround
but it is not explained clearly what it means generally when what follows isn't "before", "after" or a character class
there should be a special section for it `<.> <?> <!>` rather that explain bits throughout the page

## Environment
* Operating system:
Linux archlinux 5.12.8-arch1-1 #1 SMP PREEMPT Fri, 28 May 2021 15:10:20 +0000 x86_64 GNU/Linux

* Compiler version (`perl6 -v` or `raku -v`):

Welcome to Rakudo(tm) v2021.05.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.05.

**Comment by pmichaud** [comment]
I think we're extremely unlikely to address this as a "bug".  At best it's a warning.

It's important to remember that Raku's pattern matching language isn't the same as Perl 5's regular expression language.  In the general case for Raku, when someone writes  ```<!somerule>```, while we know it's a zero-width assertion we don't know in the general case that ```somerule``` will always fail to match.  It could be any sort of rule that returns success/failure based on other criteria, such as a timer  (```<!expired>```), a random event (```<!fission>```), an external event (```<!message-received>```), etc.

So then the alternative becomes to keep a list of rules where the warning/optimization gets listed (or tag subrules that are volatile), and thus far that hasn't been considered important enough to be worth the effort to implement.  It's also something we can't necessarily decide/detect at compile time, because the <space> subrule could be overridden in a grammar.

As @jnthn mentioned in ticket #4388 (which spawned this one), we don't warn about things like ```while $pos < 3 { }``` as a potential infinite loop (I offer ```while $pos < 3 { somesub() }``` as a more equivalent example).

We'd also need a way to watch for things like  ```[ <!space> a* ]*```   which also have the potential to infinite loop.  And we don't want to penalize successful matches with a lot of code checking for infinite loops.

As @jnthn said (and I agree),  at best this merits a warning, and I'd want to have a way for a programmer to disable the warning.  And I'd only want a warning if it could be reliably detected at compile time.

Pm

**Comment by florian-pe** [comment]
All right I understand, your explanation makes sense.

Thanks you for taking the time to explain to me what I misunderstood. I'll close this non-issue.
