### ISSUE TITLE
Weird interaction between array interpolation, given and hyper

### ISSUE THREAD

**Issue by thundergnat** [rakudo/rakudo#4413]
## The Problem

There is some kind of weird interaction / interference between array interpolation, given and hyper.

Kind of bogus example: Pay no attention to the grep operation, or the actual printed result. It is immaterial. Just here for illustration purposes.

The hyper is obviously counterproductive for a such a small range, but I tripped over this when I was trying to use a ^1_000_000 range where hyper helps a lot.

(**EDIT:** golfed down the examples a little, cut out some extraneous clutter. )

Works fine: ( no hyper grep )
```
say "{+$_} found:\n{.batch(10).join: "\n"}" given (^100).grep: { .is-prime };
```
Also fine: ( explicitly expose the topic as an array when interpolating: @$_ )
```
say "{+$_} found:\n{@$_.batch(10).join: "\n"}" given (^100).hyper.grep: { .is-prime };
```
Hangs forever: ( well, 10 minutes at least before I killed it. )
```
say "{+$_} found:\n{.batch(10).join: "\n"}" given (^100).hyper.grep: { .is-prime };
```

Interestingly enough, it seems like the {+$_} is important. Works as expected if you remove it.
```
say " found:\n{.batch(10).join: "\n"}" given (^100).hyper.grep: { .is-prime };
```
Even moving the +$_ outside of the string interpolation doesn't help.
```
say .elems ~ " found:\n{.batch(10).join: "\n"}" given (^100).hyper.grep: { .is-prime };
```
Hangs

It may not be related to the interpolation. This also hangs:
```
say .elems ~ " found:\n" ~ .batch(10).join: "\n" given (^100).hyper.grep: { .is-prime };
```

## Environment
* Operating system: Linux Mint 20.1 Ulyssa
* Compiler version (`perl6 -v` or `raku -v`): $ raku -v
Welcome to Rakudo(tm) v2021.05.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.05.

**Comment by vrurg** [comment]
The smallest golf the problem is the following:

```raku
say .list ~ " found:\n" ~ .list given (^100).hyper;
```

The cause of freeze is best explained if we coerce hyper into a `Seq`:

```raku
say .list ~ " found:\n" ~ .list given (^10).hyper.Seq;
# The iterator of this Seq is already in use/consumed by another Seq
# (you might solve this by adding .cache on usages of the Seq, or
# by assigning the Seq into an array)
#   in block <unit> at hyper.raku line 9
```

The easiest fix is to add `.cache` to `grep`.

Apparently, an error must have been thrown instead of freezing. I tried the most simple approach and slightly modified `HyperSeq` `iterator` method:

```raku
    has $!joiner;
    method iterator(HyperSeq:D: --> Iterator) {
        X::Seq::Consumed.new.throw if nqp::isconcrete($!joiner);
        $!joiner := Rakudo::Internals::HyperToIterator.new:
            source => $!work-stage-head;
        Rakudo::Internals::HyperPipeline.start($!joiner, $!configuration);
        $!joiner
    }

```

This works for hypers and even passes spectest. But then if I try:

```raku
say .race.list ~ " found:\n" ~ .race.list given (^10).hyper;
```

The freeze is back. Considering that each `.race` will result in two different `RaceSeq`, the only thing they share is an instance of `$!work-stage-head`. So, I tried to create a new one for each new racer:

```raku
    method race(HyperSeq:D:) {
        RaceSeq.new(
          configuration =>
            HyperConfiguration.new(
                degree => $!configuration.degree,
                batch => $!configuration.batch,
                :method<race>),
          work-stage-head =>
            Rakudo::Internals::HyperIteratorBatcher.new(:$.iterator))
    }
```

This seems to fix `.race` case while still keeps spectest happy. But this is a frontal attack approach and, perhaps, there is more lightweight solution.

BTW, `RaceSeq` suffers from the same kind of problem and will need similar kind of fix.

Also, `X::Seq::Consumed` produces a message referring to `Seq` whereas it'd be better to report correct class.

That's all I got for today. It rather unlikely that I'm gonna have enough spare time to make a proper fix soon. So, if somebody can pick this up and produce a working PR I'd be very grateful!
