### ISSUE TITLE
Inline::Perl5 roundtrip tests fails on various releases

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#4418]
On various Rakudo versions running https://github.com/Raku/roast/blob/master/S01-perl-5-integration/roundtrip.t either passes or results in:

```
not ok 4 - 
# Failed test at roundtrip.t line 37
# expected: $("foo", "hate")
#      got: $("ARRAY(0x5621674d0310)",) # the address differs
```

So far the stats are:

* 2021.06 - fails
* 2021.05 - fails
* 2021.04 - pass
* 2021.02 - fails
* 2020.07 - fails

It is quite odd how this test passed in 2021.04 after being broken and then went broken again. As nobody seem to report it so far, it is not a release blocker for 2021.06, but is one for 2021.07.

**Comment by vrurg** [comment]
2021.04 is as broken as other releases in my test too. I think the problem is in `Inline::Perl5`. 

@niner could you have a look?

**Comment by niner** [comment]
The failure is caused by https://github.com/niner/Inline-Perl5/commit/bb81304b938473a30c4b575d4225c13f3e969634
So it was a bit of an intentional change in semantics (to no longer flatten arguments). You can see by the changes the commit makes to examples and far down to the tests for why I made it. The failing spec tests expects those hash keys to be passed as arguments instead of an array containing those keys in: `$tohash_p5.(keys %hash);` Like I mentioned in the commit message, the new way to write this would be `$tohash_p5.(|keys %hash);` but...it's a spec test. So is it a good idea to just change it?

**Comment by vrurg** [comment]
> but...it's a spec test. So is it a good idea to just change it?

I don't think it is. Though I have another question: do we have to spec `Inline::Perl5` whatsoever? It was making sense back then when Perl5 -> Perl6 transition was expected. But nowadays I doubt about it.

On the other hand, it feels pretty weird to me that something being part of the spec is basically a 3rd party project.

Feels like another problem-solving matter and I'm going to open one.

**Comment by Altai-man** [comment]
While putting the general discussion on Perl coverage in roast aside, to unblock the release I'd say we can at least remove the "bogus" test we have at hands to proceed IMO.

**Comment by Altai-man** [comment]
Closed with https://github.com/Raku/roast/commit/6b7c4f20d1
