### ISSUE TITLE
Class Predeclaration Fails Intermittently in a Large Project When Prerequisites are Recompiled

### ISSUE THREAD

**Issue by Xliff** [rakudo/rakudo#4440]
## The Problem

In [this file, at this location](https://github.com/Xliff/p6-ICal-GLib/blob/main/lib/ICal/GLib/Timezone.pm6#L449Z) the identified class fails with the following error:

```
===SORRY!=== Error while compiling /home/cbwood/Projects/p6-ICal-GLib/lib/ICal/GLib/Time.pm6 (ICal::GLib::Time)
Stage start      :   0.000
The following packages were stubbed but not defined:
    ICal::GLib::Timezone::Array

at /home/cbwood/Projects/p6-ICal-GLib/lib/ICal/GLib/Time.pm6 (ICal::GLib::Time):9

at /home/cbwood/Projects/p6-ICal-GLib/lib/ICal/GLib/Period.pm6 (ICal::GLib::Period):10

at -e:1
```

However it was [predeclared, here](https://github.com/Xliff/p6-ICal-GLib/blob/main/lib/ICal/GLib/Timezone.pm6#L15)

To fix this issue, I have remove the "does Positional" from the class definition, recompile, re-add the "does Positional" and then compile again.

Unfortunately, I have not been able to golf this issue. 

This error is part of a project with dependencies that have not yet been released. The replication steps will take this into account.

## Steps to Reproduce

1) First, make a directory to hold the various repositiories
2) Set the environment variable P6_GTK_HOME to this path
3) cd $P6_GTK_HOME
4) git clone https://github.com/Xliff/Method-Also # (contains required features, not available in the published version)
5) git clone https://github.com/Xliff/p6-GLib
6) git clone https://github.com/Xliff/p6-GtkPlus # (for it's scripts, not to be compiled)
7) git clone https://github.com/Xliff/p6-ICal-GLib
8) (cd $P6_GTK_HOME./p6-GLib; zef install --deps-only .)
8) Install the native packages for libical. For Debian, these are: libical and libical-glib
8) cd $P6_GTK_HOME/p6-ICal-GLib
9) ./build.sh

The project will then build. The error should occur on the 57th compunit

## Environment
* Operating system:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsu
```

* Compiler version (`perl6 -v` or `raku -v`):

```
Linux Infinity4 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vrurg** [comment]
I gave it a try. First of all, it doesn't work out of the box when I follow the instructions:

1. _scripts_ symlink is using an absolute path and has to be fixed. Basically, it must be a git submodule, but anyway...
2. Teach _build.sh_ to install dependencies. I had to `zef install` a whole bunch of modules.
3. Pre-create _stats/_. 

Dependencies are especially important because in my case it kind of succeed compiling and only ended up complaining about inability to create a file in _stats_. Now, with the dir created I found more missing dependencies in the report.

**Comment by vrurg** [comment]
Now, things are even more confusing as when I try to install the modules the build complains about as being missing (`Method::Also`, for instance) – I do actually have them already. Perhaps it has something to do with me using rakubrew. 

Also, the report contains this line:

```
    file#/home/cbwood/Other_Projects/Method-Also/lib
```

So far I give up.

**Comment by Xliff** [comment]
@vrurg: Crap! I greatly apologize. Replication steps have been edited to work. Please try again, when you have the time. Please refresh your p6-GtkPlus repository.

**Comment by vrurg** [comment]
Ok, tried it once again against Rakudo `master`. First of all, your instructions miss one more crucial ster: `p6-ICal` repository clone. Otherwise it fails with `ICal::Raw` modules missing.

Another thing, you still have a problem with path to `Method::Also`:

```
    file#/home/vrurg/src/Raku/gtk/p6-ICal-GLib/{/home/vrurg/src/Raku/gtk}/Method-Also/lib'
```

Anyway, with `p6-ICal` in place the thing compiled successfully. See the report attached.

[LastBuildResults.zip](https://github.com/rakudo/rakudo/files/6772797/LastBuildResults.zip)

**Comment by Xliff** [comment]
This appears to be fixed in v2022.06-21-gd253dc79e. Will be updating soon and will let you know if the fix persists throughout the next version.

**Comment by lizmat** [comment]
That'd be .... weird...  if d253dc79e would really have fixed that

**Comment by Xliff** [comment]
I don't suspect that particular commit did. It's just the first one I tried it on that worked. I suspect it was something much earlier. Possibly vrurg's work on the Stash.

**Comment by Xliff** [comment]
Passes OK for `v2022.06-23-gd7d8e9d0f`, so I am considering this fixed and closing. 

Thanks for the hard work!
