### ISSUE TITLE
^mro_unhidden shows things that are hidden

### ISSUE THREAD

**Issue by doomvox** [rakudo/rakudo#4500]
## The Problem

According to the documentation, ^mro_unhidden does this:

    "Returns a list of types in method resolution order, excluding
     those that are marked with is hidden."

I see it including Any and Mu at the root of the inheritance,
though I would think those are intended to be hidden.

## Expected Behavior

The output of 

     $obj.^mro_unhidden 

should not include the root classes "Any" and "Mu"

## Actual Behavior

I see output identical to  $obj.^mro

## Steps to Reproduce

    class A {}
    class B is A {}
    class D is B {}
    say D.^mro_unhidden; 

I see:

    ((D) (B) (A) (Any) (Mu))

I think you should see:

    ((D) (B) (A) 

For reference, when I do this:

    say D.^parents();
    say D.^parents( :all );

I see:

      ((B) (A))
      ((B) (A) (Any) (Mu))

So, as far as ^parents is concerned, Any and Mu are hidden.

## Environment

    raku --version
    Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.10.
    Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
    Built on MoarVM version 2020.10.

    uname -a
    Linux fandango 4.9.0-8-686 #1 SMP Debian 4.9.144-3 (2019-02-02) i686 GNU/Linux

**Comment by vrurg** [comment]
> I see it including Any and Mu at the root of the inheritance,
> though I would think those are intended to be hidden.

You're mistaken here. There are two different concepts aimed at different targets and you're mixing them up.

Method `parents` is about providing a list of parents in general. Depending on context, the list could be either used for reporting or for further processing. Correspondingly, with different parameters one could get different list of parents based on specified criteria.

`mro` and `mro_unhidden` has more narrow purpose as they provide a sorted list of typeobjects which is aimed at method resolution primarily. Thus the abbreviation MRO: Method Resolution Order. BTW, method `parents` is used to build MRO.

Due to different purpose of the methods they use different ways of hiding unwanted typeobjects. With `parents` it only makes sense in report-oriented introspection. Because everybody knows that all classes are inheriting from `Any` by default, it makes sense to hide `Any` and its parent `Mu` from outputs in order to somewhat unclutter them. For this reason the CORE requests the Metamodel to exclude them when possible. And `Cool` too, BTW.

It is totally different story about MRO where the purpose of hiding a parent is to exclude its methods from method dispatching:

```raku
class Foo {
    method m { say "Foo" }
}

class Bar is hidden is Foo {
    method m { say "Bar"; nextsame }
}

class Baz is Bar {
    method m { say "Baz"; nextsame }
}

say "-- BAR:";
Bar.new.m;
say "-- BAZ:";
Baz.new.m;

say Baz.^parents;
```

Note that method from `Bar` is skipped from `Baz.new.m` output, but `Bar` is still reported as a `Baz` parent.

Correspondingly, it doesn't make sense of excluding `Any`, `Mu`, or `Cool` from `mro_unhidden` output as in this case they won't be included into method dispatching and it is clearly not something we'd expect to happen.

**Comment by vrurg** [comment]
And, BTW, if you want a class of yours be skipped from the default `parents` output you can do so with `Metamodel::ClassHOW.exclude_parent(YourClass)`.

Otherwise I think it's ok to close this issue. Feel free to re-open if disagree.

**Comment by doomvox** [comment]
I'm fine with closing it, I just might make the point that these issues aren't described in the documentation very well.  The term "hidden" appears with methods that appear to have very similar purposes, but means different things in each context.

**Comment by vrurg** [comment]
Unfortunately, metamodel is not only badly documented, it's not even well enough standardized in specs. This task is still awaiting a volunteer. And one way or another is not likely to be done before 6.e is released.
