### ISSUE TITLE
Keeping or dropping the coercive aspect of a coercion / coercion type after it's been applied

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#4517]
## The Issue

Sometimes one wants a coercion type to remain part of a coerced value's target type. Other times one just wants the underlying type retained, and the coercion aspect dropped after the coercion has been applied.

*(The rest of this comment is completely rewritten. Apart from the above summary the original version was terribly written and led @vrurg far, far away from my intended point. If you want to see the original, click the `edited` drop down to the right of my name above left.)*

----

Raku's gradual typing supports a range of strengths of typing:

* Close to pure dynamic typing (aka "unityping" in the static typing world). (Raku imposes a little static typing at minimum; so it's never strictly just "unityping". For example an `@` sigil statically specifies an interface type for a variable.)

* A spectrum from there up to fairly strong typing. For example `my Array $foo;` constrains `$foo` to be an `Array` but lets the `Array` contain elements of any type. `my Array[Int] $bar;` constrains `$bar` to be an `Array` that only contains `Int`s.

This issue focuses on assigning values whose typing is weaker than a type constraint of a variable to comply with that constraint via use of coercion types.

----

This comment will focus on simple concrete examples of doing the following:

1. Assigning a value to a variable.

2. Using built in literal syntax to express the value.

3. Specifying a "strong" type constraint for the variable.

I'm talking about the general case for values, but will use two example values to illustrate what I'm trying to discuss in this issue:
```
[[1,2],]
[[1,'2'],]
```
I'm also talking about the general case for "type constraint for the variable" but will use two example "conceptual" type constraints to illustrate what I'm trying to discuss in this issue:
```
Array[Array[Int]] $
Array[Int] @
```
Obviously we can't just use just those exact example type constraints with the exact example values because, for example, `[1,2]` isn't an `Array[Int]`.

But, by using coercion types, we *can* assign those exact example values to the `$` variable with a type constraint that ensures that the coerced values that end up assigned to it are of type `Array[Array[Int]]`.

(I'm not sure about the `@` variant. By the time I got the `$` variant of this challenge to work I'd exhausted my patience. I will leave the `@` version as a stretch consideration for readers whose brain isn't fried by what it takes to get the `$` version to work.)

----

Here's what it takes to make things work, as just described, for the `$` variable with the example two values.

I'll start with type aliases declared using `constant` to minimize the verbosity. The most complex coercion variants are needed to deal with `[[1,'2'],]`, but even the simpler `[[1,2],]` still requires most of them:
```
constant a = Mu;
constant b = Array;
constant c = Array[Array];
constant d = Array[Array[Int]];
constant e = Array[Array[Int]]();
constant f = Array[Array[Int()]]();
constant g = Array[Array[Int()]()]();
constant h = Array[Array[Int]];
constant i = Array[Array[Int]](Array[Array[Int](Array[Int]())]());
constant j = Array[Array[Int]];
constant k = Array[Array[Int()]()]();
constant l = Array[Array[Int]](Array[Array[Int](Array[Int()]())]());
constant m = Array[Array[Int]];

say WHAT my a $a = [[1,2],];   # (Array)
say WHAT my b $b = [[1,2],];   # (Array)
#say WHAT my c $c = [[1,2],];   # expected Array[Array] got Array ([[1, 2],])
#say WHAT my d $d = [[1,2],];   # expected Array[Array[Int]] got got Array ([[1, 2],])
#say WHAT my e $e = [[1,2],];   # expected Array[Int] got Array ([1, 2])
#say WHAT my f $f = [[1,2],];   # expected Array[Int(Any)] got Array ([1, 2])
say WHAT my g $g = [[1,2],];   # (Array[Array[Int(Any)](Any)])
#say WHAT my h $h = $g;         # expected Array[Array[Int]]
                                # got Array[Array[Int(Any)](Any)] (Array[Array[Int(Any)...)
say WHAT my i $i = [[1,2],];   # (Array[Array[Int]])
say WHAT my j $j = $i;         # (Array[Array[Int]])

say WHAT my k $k = [[1,'2'],]; # (Array[Array[Int(Any)](Any)])
say WHAT my l $l = [[1,'2'],]; # (Array[Array[Int]])
say WHAT my m $m = $l;         # (Array[Array[Int]])
```
And here's what it looks like without the aliases:
```
say WHAT my                           $a = [[1,2],]; # (Array)
say WHAT my Array                     $b = [[1,2],]; # (Array)
#say WHAT my Array[Array]              $c = [[1,2],]; # Type check failed
#say WHAT my Array[Array[Int]]         $d = [[1,2],]; # Type check failed
#say WHAT my Array[Array[Int]]()       $e = [[1,2],]; # Type check failed
#say WHAT my Array[Array[Int()]]()     $f = [[1,2],]; # Type check failed
say WHAT my Array[Array[Int()]()]()   $g = [[1,2],]; # (Array[Array[Int(Any)](Any)])
#say WHAT my Array[Array[Int]]         $h = $g; # Type check failed
say WHAT my Array[Array[Int]](Array[Array[Int](Array[Int]())]()) $i = [[1,2],]; # (Array[Array[Int]])
say WHAT my Array[Array[Int]]         $j = $i; # (Array[Array[Int]])
say WHAT my Array[Array[Int()]()]()   $k = [[1,'2'],]; # (Array[Array[Int(Any)](Any)])
say WHAT my Array[Array[Int]](Array[Array[Int](Array[Int()]())]()) $l = [[1,'2'],]; # (Array[Array[Int]])
say WHAT my Array[Array[Int]]         $m = $l; # Array[Array[Int]]
```
Hopefully the foregoing is sufficient to illustrate the surprising complexity that arises when trying to combine "strong" type constraints on variables with coercion types to coerce values to comply with those "strong" type constraints.

## Discussion

In my first version of this issue/comment I began with a *vastly* simplified version of the above, and then discussed things I thought might be relevant to mitigating the complexity. That badly back-fired. So this time I'll leave the above as hopefully sufficient to make my point.

**Comment by vrurg** [comment]
I must admit, that I haven't given the issue a deep thinking. But that's because I'm not sure I have sufficient understanding of what target is to be achieved. So, let me guess a bit. What you want is to `(1, 2, "3")` "magically" turn into `[1, 2, 3]` of `Array[Int]`. So, that `@a[$i] = "42"` would throw instead of coercing "42" into 42.

A minor thing to mention from the start is that this may complicate code reading as most implicit magic would do. The functionality is certainly good for one-liners, but could bring some complications in a big code base.

As a part of the brainstorming process, wouldn't a method `infer` on `Array` do the same with better readability?

```raku
my @a := Array.infer(13, 666, "42"); # [13, 666, 42] of Array[Int]
```

The method could be something like this quickly thrown together routine:

```raku
sub infer(*@a) {
    my sub _infer(::T, @a) { 
        Array[T.WHAT](@a.map( { T($_) } ))
    }
    say _infer(@a.head, @a).raku
}

infer(1, 2, "2");             # Array[Int].new(1, 2, 2)
infer(pi, 1, "12.13");        # Array[Num].new(3.141592653589793e0, 1e0, 12.13e0)
infer("foo", pi, 1, "12.13"); # Array[Str].new("foo", "3.141592653589793", "1", "12.13")
```

With regard to the syntax part. `*( )` is a bad solution. First, it overloads `*` with new functionality. Second, `()` is a `List`, not `Array`. But `*[ ]` is already occupied. Moreover, I think `*()` being an error is actually an error of another kind:

```raku
({1}, {2}).map: { $_() }; # (1 2)
({1}, {2}).map: *(); # must be the same; as well as *.() too
```

With regard to `Array[*]`, it looks OK until you try to convert it into an array declaration syntax. Because `Array[Int]` is actually `my Int @a`. But what `Array[*]` is? `my * @a`? Here we recur to `*` overloading again. Pretty much questionable.

I'd rather consider a special type `Infer`. So `my Infer @a`, `sub foo(Infer @a)` would do the job. It could even be used with other containers:

```raku
sub foo(Infer $a is copy, $b) { $a = $b }
foo(1, "2"); # error
```

But this needs a lot of planning to cover hell of amount of edge cases like using it as constraint type in a coercion, etc.

Alternate solution is to introduce something like "fragile coercions". Such coercion would be possible to collapse into its target type when necessary. The big question here is what is the right time to collapse? It's about the same question for `Infer` type, BTW:

```raku
my Infer @a = (1, 2, "3");
@a = ("42", "13"); # Error

my Infer @b;
@b = ("42", "13"); # Should this error? Probably not, but aren't there unexpected actions at distance possible?
```

The last note on the syntax. One way or another, but `Array[Int]($(...))` is always an error. `$(...)` is an itemized list and it's going to be a single array element. Inferring over such thing must result in `Array[Any]` with the same outcome of singe-element list representation in the array.

To conclude with, the situation is particularly painful when it comes to hashes. Are they second-grade citizens with regard to type inferring? If not, how do we infer the type of a hash where there is no such thing as the first element?

**Comment by vrurg** [comment]
BTW, the `infer` routine can be made even more concise:

```raku
sub infer(*@a) {
    my Mu \T = @a.head.WHAT; # this can be replaced with `given @a.head.WHAT -> Mu \T {...}`
    Array[T](@a.map({ T.($_) }))
}

say infer(1, 2, "2").raku;
say infer(pi, 1, "12.13").raku;
say infer("foo", pi, 1, "12.13").raku;
```

**Comment by raiph** [comment]
Hi again @vrurg,

Are you on vacation? If so, please enjoy it and completely ignore this thread for now! I'll ping you again in a few weeks when you're well rested. :)

> I must admit, that I haven't given the issue a deep thinking. But that's because I'm not sure I have sufficient understanding of what target is to be achieved. 

I apologize for things going so badly off track from the get go due to me being so unclear.

Please consider revisiting this issue when you feel like it. I've *completely* rewritten the initial comment to try eliminate room for confusion about the target.

> What you want is to `(1, 2, "3")` "magically" turn into `[1, 2, 3]` of `Array[Int]`.

No. First, definitely no magic. Second, ignore strings in the first instance. 

Just focus on the enormous complexity of turning a `[[1,2],]` into an `Array[Array[Int]]`.

> A minor thing to mention from the start is that this may complicate code reading as most implicit magic would do. The functionality is certainly good for one-liners, but could bring some complications in a big code base.

To be absolutely clear, I am absolutely against complicating code reading, *especially* in large codebases.

Instead my claim is that many mainstream PLs with strong typing, or even just gradual typing, deal with assigning a value like `[[1,2],]` with utter simplicity. With *no* type annotation at all. (They retain strong typing information statically via inference.)

Compare that with what's currently needed to get the same result in Raku:
```
my Array[Array[Int]](Array[Array[Int](Array[Int]())]()) $i = [[1,2],];
my Array[Array[Int]]                                    $j = $i;
```
Imo the first of the two lines above is an ergonomic monster that would seriously complicate code reading even though it is explicit. And that's for what should be a simple case!

> As a part of the brainstorming process, wouldn't a method infer on Array do the same with better readability?

I'm going to resist engaging with discussion about type inference unless/until you've first seriously engaged with the simpler (but still incredibly complex!) `[[1,2],]` case.

> Alternate solution is to introduce something like "fragile coercions". Such coercion would be possible to collapse into its target type when necessary. The big question here is what is the right time to collapse?

I proposed an answer to that question in my first version of my first comment. But as I have hopefully now made clear, the first thing to do is to acknowledge the main issue as illustrated with the `[[1,2],]` case.

> It's about the same question for Infer type

I saw all the things you've discussed, and several things I think you've missed, including the overlap with inference, but also much more, before writing my first version of my first comment. I've no doubt missed many other aspects, but right now my problem is more that I ran too far ahead in my thinking because I'd been pondering it for a month or so, and then left most of the preliminaries unspoken.

But that back-fired because I rushed past the base case -- the should-be-simple-but-is-instead-incredibly-complex `[[1,2],]` case -- and that was a bad mistake.

Hopefully I've now fixed that such that this issue might get back on track. Alternatively perhaps I should close this one and start a fresh one that starts with just the first comment as it is now and avoids mentioning inference and any other aspects?

**Comment by vrurg** [comment]
I've just thrown the raw ore of your examples into the forge of my brain....... Phew, that's too pathetic, but being too serious in this case could be harmful to one's mind. :) Especially after 5hr driving.

Anyway, serious mode back on, this really needs good thinking over. A couple of things I've spotted so far. It seems you lost yourself in just a couple of trees while trying to figure out how to coerce the array on RHS. The case of `my Array[Array[Int]](Array[Array[Int](Array[Int]())]()) $i = [[1,2],];` is overwhelming, but is clearly written for when there is a string element in the nested array. Since we're talking about homogeneous values in it, here is what I came up with:

```raku
my Array[Array[Int]()]() $a = [[1,2,3],];
say $a.raku; # Array[Array[Int](Any)].new(Array[Int].new(1, 2, 3))
say $a.WHAT; # (Array[Array[Int](Any)])
```

Still not the best chain of types from the point of view of readability, but you clearly missed it in your research. Yet, re-written with a subset it looks slightly better:

```raku
subset AInt of Array[Int]();
my Array[AInt]() $a = [[1,2,3],];
say $a.raku; # Array[AInt].new(Array[Int].new(1, 2, 3))
say $a.WHAT; # (Array[AInt])
```

Of course, this would require one to know what `AInt` is.

Anyway, the point is that you seemingly didn't really cleared your mind from `[[1,2,'3'],]` case while trying to figure out something for pure all-Ints array.

_(the following is just a hasty note which may have any number of flaws in it)_ As to inferring types, I agree that the problem with passing `[1,2]` to something of `Array[Int]` is something annoying. I myself irritated with it for quite some time. It could be efficiently solvable with compile-time support in cases when the compiler knows the type of expression LHS (or routine's parameter) and types of all RHS element values. There are possible complications for nested structures, but technically it doesn't take away the feasibility.

Less efficient, of course, is the run-time analysis when we don't know the types of RHS array elements. Yet, it'd be possible to relax the type checking for arrays and let the assignment to see if all elements do match the array type on LHS. This might be a breaking change, but language revision boundary might make it possible **if** considered reasonable. 

Wether it is sensible to do run-time analysis of array content in order to infer its type – I'm still not sure. Lazy sequences may make this idea pretty much fragile. _(end of the note)_

**Comment by raiph** [comment]
> being too serious in this case could be harmful to one's mind. :)

Given the nature of the universe, being *too* serious in *any* case can be harmful to one's mind. :)

> It seems you lost yourself in just a couple of trees while trying to figure out how to coerce the array on RHS.

No, but it looks like I lost you right at the start, namely the tiny bit of the original issue I left as is. Hopefully adding appropriate emphasis fixes that, as follows.

The title:

> Keeping **or dropping** the coercive aspect of a coercion / coercion type after it's been applied

And in the opening paragraph:
 
> Sometimes one wants a coercion type to remain part of a coerced value's target type. **Other times one just wants the underlying type retained, and the coercion aspect dropped after the coercion has been applied.**

Please focus on the emphasized parts. These are the core of my point.

> The case of my `Array[Array[Int]](Array[Array[Int](Array[Int]())]()) $i = [[1,2],];` is overwhelming, but is clearly written for when there is a string element in the nested array.

Yes.

> Since we're talking about homogeneous values in it, here is what I came up with:
```
my Array[Array[Int]()]() $a = [[1,2,3],];
say $a.raku; # Array[Array[Int](Any)].new(Array[Int].new(1, 2, 3))
say $a.WHAT; # (Array[Array[Int](Any)])
```
This doesn't address the point I've been trying to make.

Both of the following `foo` calls, including using your `$a`, fail:
```
sub foo (Array[Array[Int]] $bar) {}
#foo [[1,2],]; # Type check failed ... expected Array[Array[Int]] but got Array ([[1, 2],])
foo $a; # Type check failed ... expected Array[Array[Int]] but got Array[Array[Int](Any)] (Array[Array[Int](Any...)
```
This scenario repeatedly comes up if one is writing code that creates values that are then passed as arguments to strongly typed functions.

Coercion types as they currently are neatly solve the following problem:
```
sub foo (Array[Int] $foo) { $foo }
sub bar (Array[Int] $bar) { $bar }
say WHAT foo bar [1,2]; # Type check failed ... expected Array[Int] but got Array ([1, 2])
```
Just add a judicious `()` and all is good:
```
sub foo (Array[Int] $foo) { $foo }
sub bar (Array[Int]() $bar) { $bar }
say WHAT foo bar [1,2]; # Array[Int]
```
This works because the value produced an `Array[Int]()` coercion type, where the `()` is *outside* of the nominal type yields a value coerced to that nominal type.

But if a coercion type is *kept* as part of the nominal type of a coerced value, which is what happens if it's *inside* a `[...]` part, then one can't use that value with the corresponding *strong* type. **This** is the core issue I've been trying to bring your attention to.

> Still not the best chain of types from the point of view of readability, but you clearly missed it in your research.

No. It's essentially where I *started*. If you refer back to the original version of my first comment opening this issue I wrote:

> Consider these variations:
```
say WHAT Array[Int](1,2,3);     # Array[Int]
say WHAT Array[Int](1,2,'3');   # expected Int but got Str ("3")
say WHAT Array[Int()](1,2,'3'); # (Array[Int(Any)])
```
> Either of the last two cases may be a desirable end result. But they may also not be.

You've focused like a laser on the first of those two cases. But you've ignored the second one. I think that's because I used `'3'` instead of `3`. I did that because I was trying to avoid you just saying "Hey, you could just do what was done in the first line of code".

(Unfortunately all my attempts to keep the opening really brief, erroneously thinking you'd see the consequences of what I was showing, backfired.)

> Anyway, the point is that you seemingly didn't really cleared your mind from `[[1,2,'3'],]` case while trying to figure out something for pure all-Ints array.

Heh. The irony is that it seems like I actually failed to clear *your* mind from that case. But anyway, all's well if you've *now* got my point. But has the penny yet dropped?

> As to inferring types...

Arrgh. Please let's not go backwards. Please wait until you've seen my point. Or, if you still don't, please just crack some jokes instead! :)

**Comment by vrurg** [comment]
I'm stuck in daily/work errands, not sure when gonna get some time for this  again. But there is an idea I'd better express now.

I barely expect the coercion syntax to be able to get any better. Neither I'm considering implicit inferring the course to follow. But what could be helpful is explicit typing of an array. Something like:

```
[Int(): 1, 2, '3'] # -> Array[Int()]
[Int:D: 1,2,3] # Array[Int]
[Int: 1,2,'3'] # Error
```

In the first case the coercion will be lost on assignment but preserved on binding. So, `my Int @a = [Int(): "1", "2"];` would work as expected. But `my @a := [Int(): "1", "2"]` will result int `@a.WHAT; # (Array[Int()])`.

Type inferring could also fit into this syntax:

```
[: 1,2,'3'] # Array[Int]
[: "1", 2, 3] # Array[Str]
```

BTW, we've already drifted into problem-solving waters.

**Comment by lizmat** [comment]
Closing as this should really be a problem solving issue
