### ISSUE TITLE
A LEAVE in nested scope in a sub can cause loss of the return value

### ISSUE THREAD

**Issue by jnthn** [rakudo/rakudo#4521]
## The Problem

This code produces the wrong output:

```
sub with-db(&operation) {
    with Nil {
    }
    else {
        return operation();
        LEAVE say "in leave";
    }
}
sub op() {
    with-db -> {
        42
    }
}
say op();
```

## Expected Behavior

```
in leave
42
```

## Actual Behavior

On a release:

```
in leave
The 'ForeignCode' class is a Rakudo-specific implementation detail and has no serviceable parts inside
```

In `new-disp`:

```
in leave
sink
```

## Environment
* Operating system: Verified on Linux and MacOS
* Compiler version (`perl6 -v` or `raku -v`): `v2021.08` (also exists on `v2021.05` and `v2021.06`), also in `new-disp` at `v2021.08-167-gba0e77cae`

**Comment by lizmat** [comment]
So is this something that needs to be fixed on master?  Or on new-disp?

**Comment by jnthn** [comment]
@lizmat It's broken on `master`, I mention `new-disp` just to note it's still there, but with different output.

**Comment by lizmat** [comment]
ok, so no action needed on master I assume  :-)

**Comment by jnthn** [comment]
@lizmat Action needed, `new-disp` may change the output, but it's still broken.

**Comment by patrickbkr** [comment]
Golf:

```
sub a() {
    with Nil {
    }
    else {
        return 7;
        LEAVE say "in leave";
    }
}

say a();
```

**Comment by patrickbkr** [comment]
```
sub one() {
    with Nil {
    }
    else {
        LEAVE say "in leave";
        7;
    }
}
say one();
```

Returns
```
in leave
7
```

So it's `return` in combination with `LEAVE` that's causing the problem.

**Comment by patrickbkr** [comment]
I think I see what's going wrong. `throwpayloadlexcaller` (the op backing `&return`) relies on a thread global variable (`tc->last_payload`) to persist the payload it tries to get to the frame of the routine. Without any handlers in between that works out. But if there is a handler in the middle and that handler does anything that also makes use of `tc->last_payload` things go wrong.

The first idea that comes to mind is to adapt `MVM_frame_unwind_to` to save the payload in the `MVMCallStackSpecialReturn` frame (in `MVMUnwindData`) and restore the `tc->last_payload` in `continue_unwind`. That feels a bit unclean though.

Can I have feedback on that idea? @jnthn @niner

**Comment by niner** [comment]
I'm a bit skeptical about the proposed MoarVM solution. It basically bakes in assumptions of the HLL code. That may be an ok thing to do. I just don't have the time right now to think it through completely.

A more targeted alternative would be for the generated LAST handler code to save last_payload via a lastexpayload op at the start of its frame and re-sets this payload at the end (probably needs a new syscall).

**Comment by patrickbkr** [comment]
> It basically bakes in assumptions of the HLL code. That may be an ok thing to do.

Which assumption do you have on your mind? - The only thing I could think of is the assumption that HLL code can no longer deliberately overwrite the payload in LEAVE handlers. But as you've already said, that's probably not even possible at the moment because the syscall is missing.

I think this boils down to the question of the intended semantics of `throwpayloadlexcaller`. If it's meant to save some variable that can later be retrieved, then yes, saving and restoring the value is magic that should probably not be there. If on the other hand it's meant to represent an exception with payload that moves up the call stack until a handler to catch it is found, then I believe the payload should arrive at the catching handler unmodified. This parallels to unwind of the stack, which also continues automatically after an intermediate handler has finished.
