### ISSUE TITLE
Bogus conversion warnings

### ISSUE THREAD

**Issue by moon-chilled** [rakudo/rakudo#4530]
```
$ raku -e 'my Str:D() $x = Nil'
Use of uninitialized value of type Str in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
  in block <unit> at -e line 1
```

Since I explicitly requested conversion to a defined type, the warning is unlikely to be of use.

**Comment by jonathanstowe** [comment]
I'm not so sure, what about:

```
[jonathan@menenius aws-s3-perl6]$ raku -e 'my $a; my Str:D() $x = $a'
Use of uninitialized value of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
  in block <unit> at -e line 1
```

It's effectively the same but surely the warning *is* of use in that case.

**Comment by moon-chilled** [comment]
> warning _is_ of use in that case

Why so?  Again, I've requested conversion to a defined type, why should it not simply happen without complaint?

**Comment by moon-chilled** [comment]
In particular, the _only_ difference—as far as I know—between `Str()` and `Str:D()` is that the latter will perform conversions from undefined values, where the former will not; so if you write the latter, you are specifically opting in to that behaviour, and only that behaviour.

**Comment by jonathanstowe** [comment]
On reflection I'm not even sure that the type smiley is playing any part in this,  that is to say `my Str() $f = Nil` results equally in an empty string (I personally would expect that to result in a warning and $f remaining undefined, but this may be the expected behaviour,) so if *that* is the expected behaviour then I don't see a problem with not warning with the type smiley.

Or y'know just prefix the thing with `quietly` and carry on :-D

**Comment by moon-chilled** [comment]
> `my Str() $f = Nil` results equally in an empty string

It doesn't seem to.

```
$ raku -e 'my Str() $f = Nil; say $f; quietly my Str:D() $g = Nil; say $g'
(Str)

```

**Comment by vrurg** [comment]
The behavior is totally valid here. The coercion with smiley is not about opting in for a defined value but it is about typechecking the variable. Nothing else. This is the key mistake here.

So, `Str:D()` as a variable type means: _coerce into `Str` and make sure it is a defined value_. The case of `my Str:D() $x = Nil` is no different from `my Str:D() $x; $x = Nil`. One could similarly do `my $n := Nil; my Str:D() $x = $n` and get the warning.

The warning is a side effect of the coercion. Because `.Str` method exists, this is what the coercion protocol tries to get a stringy value. So, the full chain of events, which is the same for both assignment with `my` and assignment after `my`, is following:

1. find out that `Nil` is assigned
2. get variable's `default` value which will be type object `Str` in our case
3. do `Str.Str` to get a string and a warning
