### ISSUE TITLE
 Cannot use a signature constraint on a named callable argument

### ISSUE THREAD

**Issue by codesections** [rakudo/rakudo#4537]
## The Problem

Named `&` parameters work, and `&` parameters with signature constraints work, but using those two features together does not. 

## Expected Behavior
```raku
sub named(:&fn)                       { 'ok ' }
sub constrained(&fn:(Int))            { 'ok ' }
sub named-and-constrained(:&fn:(Int)) { 'ok ' }
sub fn(Int) {}
say named(:&fn), constrained(&fn), named-and-constrained(:&fn);
# OUTPUT: «ok ok ok»
```

## Actual Behavior
That code throws `No such method 'signature' for invocant of type 'Callable' in sub named-and-constrained`.

## Environment
* tested on `v2021.06` and master `v2021.09-4`

**Comment by vrurg** [comment]
This was a tricky one. But the cause was extremely simple. When forming the named parameter name the compiler forgets to strip off the `:(...)` signature part. Apparently, lookups for `fn:(Int)` fail to match it against plain `fn` resulting in the named parameter to default to `Callable` role.

I'm awaiting for spectests to pass to submit a PR. It fixes the argument passing but leaves another problem unresolved. Apparently, omitting the named would result in the same error because this time it is explicitly defaults to `Callable`. A fix would apply implicit `!` to the named parameter making the above declaration of `named-and-constrained` be equivalent to:

```raku
sub named-and-constrained(:&fn:(Int)!) { 'ok ' }
```

I'd also expect it to produce a corresponding warning.

Will see tomorrow if implementing this fix is not too complicated or otherwise it doesn't worth time spent since RakuAST will obsolete it.
