### ISSUE TITLE
Raku for Windows does not glob command line arguments

### ISSUE THREAD

**Issue by pureabsolute** [rakudo/rakudo#4550]
## The Problem

A file glob on the windows raku command line is not expanded, and even causes an "Invalid Argument" error.

```
raku -ne ".say" *.file
Failed to open file C:\Users\goneill\rakuprojects\oneliners\*.file: Invalid argument
  in block <unit> at -e line 1
```

Related: using $*ARGFILES causes that same error.

```
raku -e ".say for $*ARGFILES.lines" *.file
Failed to open file C:\Users\goneill\rakuprojects\oneliners\*.file: Invalid argument
  in block <unit> at -e line 1

```
Related: going deeper into the documentation

```
raku -e "my $argfiles = IO::CatHandle.new(@*ARGS); .say for $argfiles.lines" *.file
Failed to open file C:\Users\goneill\rakuprojects\oneliners\*.file: Invalid argument
  in block <unit> at -e line 1

```

## Expected Behavior

The glob is expanded to the files that match the glob pattern, and even if not, then "no such file or directory" should be the response.  This behavior should occur regardless of whether or not there are files that match the glob.

Then each line in each file is iterated over. 

I'm no "windows" programmer, but it seems that each program has to handle its own globbing.  In this case, even if raku said nope - not part of the deal, I'd still expect it to attempt to open the unexpanded filehandle, and report file not found.

```
raku -ne ".say" nonexistant.file
Failed to open file C:\Users\goneill\rakuprojects\oneliners\nonexistant.file: No such file or directory
  in block <unit> at -e line 1

```

But I suspect that raku does want windows globbing to occur - at least if there are no other switches involved.

## Actual Behavior

The glob is not expanded - if it were, we wouldn't be getting this error.  Then the "Invalid Argument" error is thrown.

## Steps to Reproduce

These examples "fail" regardless of preparation, but to generate the expected behavior:

- Create at least one file with the extension ".file" in the current directory.

## Environment
* Operating system: Windows 10 cmd.exe
* Compiler version (`perl6 -v` or `raku -v`): 
C:\Users\goneill\rakuprojects\oneliners>raku -v
Welcome to ≡¥Éæ≡¥ÉÜ≡¥Éñ≡¥É«≡¥É¥≡¥É¿Γäó v2021.08.
Implementing the ≡¥Éæ≡¥ÉÜ≡¥Éñ≡¥É«Γäó programming language v6.d.
Built on MoarVM version 2021.08.

## Comments

There is a workaround:  one has to process @*ARGS yourself, and then everything else just works:

raku -MIO::Glob -e "@*ARGS = (map { glob($_) }, @*ARGS).flat; .say for $*ARGFILES.lines" *.file *.file2 nonexistant.file

However I don't know if it handles non-existent files the same.

I also don't know if the windows globbing grammar is different than the others, but if it is, then having that parameter in IO::Glob would make sense, and have it be the default on Windows machines.  One could even "Not Glob", except if a command-line switch were sent to Raku to glob.  This would allow the use of other globbing grammars on bashy/cshy systems (with the proper escapes so that the shell doesn't expand it first if they share some symbols).

**Comment by vendethiel** [comment]
Raku doesn’t do that on linux either. Your shell expands globs.

**Comment by jonathanstowe** [comment]
Just to illustrate:

```
[jonathan@menenius xt]$ raku -e '.say for $*ARGFILES.lines' '*.file'
Failed to open file /home/jonathan/working/NAP/xt/*.file: No such file or directory
  in block <unit> at -e line 1
```

(the single quotes prevent the shell expansion.)

The difference in the error message on Windows is because the latter part is OS specific and '*' is not a legal character in a filename for windows.

**Comment by patrickbkr** [comment]
I think the OP realized, that the Windows shell doesn't do globbing (but on Linux does). That's why they wrote:

> I'm no "windows" programmer, but it seems that each program has to handle its own globbing.

So I'd like to know what the convention on Windows actually is.
Is globbing a thing on Windows? Where does the expectancy to have globbing on Windows come from? Is there any globbing in CMD or PowerShell or any other shell on Windows? Are there any other command line programs on Windows that implement globbing themself?

**Comment by jonathanstowe** [comment]
I believe that PowerShell does support globbing, but `CMD.exe` doesn't.

**Comment by pureabsolute** [comment]
It seems that all native programs that accept files as input implement globbing.  Ex:

type *
dir *
more *

More * is illustrative - the more program, in addition to pausing once it get to the page size, also pauses between each file.  It also errored out when it got to a directory, whereas type * did not consider the directory.

**Comment by pureabsolute** [comment]
> I believe that PowerShell does support globbing, but `CMD.exe` doesn't.

PS C:\Users\goneill\rakuprojects\oneliners> raku -ne ".say" *.file
Failed to open file C:\Users\goneill\rakuprojects\oneliners\*.file: Invalid argument
  in block <unit> at -e line 1

PS C:\Users\goneill\rakuprojects\oneliners>

**Comment by jonathanstowe** [comment]
That's odd.

**Comment by pureabsolute** [comment]
I hadn't realized that Perl5, which I used a long long time ago, had versions that expanded the command line, and versions that didn't.  Cygwin also created a version of Perl5 that expanded the command line.

I still say add a switch so that whatever wildcards get through are globbed by the grammar specified.  It would be a better grammar than the normal grammars!  Whether or not it deals with the other aspects of the command line such as escaping I'd probably leave for a different exercise.  Just the optional globbing!

**Comment by jubilatious1** [comment]
Raku Design Decision: 

https://docs.raku.org/language/5to6-perlfunc#index-entry-glob_-_perlfunc

**glob**

-     glob EXPR

Not available in core, although some of the functionality is offered by dir routine and its test argument.

See `IO::Glob` module in ecosystem

https://modules.raku.org/dist/IO::Glob

**Comment by jubilatious1** [comment]
> I think the OP realized, that the Windows shell doesn't do globbing (but on Linux does). That's why they wrote:
> 
> > I'm no "windows" programmer, but it seems that each program has to handle its own globbing.
> 
> So I'd like to know what the convention on Windows actually is. Is globbing a thing on Windows? Where does the expectancy to have globbing on Windows come from? Is there any globbing in CMD or PowerShell or any other shell on Windows? Are there any other command line programs on Windows that implement globbing themself?

This conversation/issue is migrating over from StackOverflow, see:
https://stackoverflow.com/q/69384754/7270649

When I hear "Windows Shell", my mind naturally leaps to "Windows Subsystem for Linux" (WSL1 and WSL2):
https://docs.microsoft.com/en-us/windows/wsl/about

If @pureabsolute is using PowerShell, I'm not familiar with those shell conventions, specifically if it does `bash`-style split+glob (and associated, ENORMOUS, security implications):

https://unix.stackexchange.com/questions/108963/expansion-of-a-shell-variable-and-effect-of-glob-and-split-on-it    
https://unix.stackexchange.com/questions/171346/security-implications-of-forgetting-to-quote-a-variable-in-bash-posix-shells

In fact, you can turn off globbing in bash/zsh, see Q&A:

https://unix.stackexchange.com/q/388695/227738    
https://unix.stackexchange.com/a/388704/227738

Maybe we can get @zostay to give us a little info on how his `IO::Glob` module works, whether it's using/abusing Raku's core `dir()` function. 

've played with `dir()` and it's pretty powerful. My guess is the Raku Designers decided to forego a direct replacement for P5's `glob` by opting for the more powerful `dir()`. Having both in core may be confusing, and--given the number of security issues related to shell file globbing--it seems like a good move to create a "bright-line" between `Raku -- dir(/.../)` and `bash/zsh -- *.glob` issues.

**Comment by jubilatious1** [comment]
> I wouldn't try to do everything that all windows programs do.

There IS a difference in Windows shells, because that MS document says: 

_...but the Command shell can only run Windows Commands and not PowerShell cmdlets._

So far I haven't seen an example of a non-Windows program globbing at the Windows command line. Does Ruby do that? You indeed may begin to see 'priviliged' programs given access (i.e. native Windows utilities), while others are denied. The PowerShell issues/pull-request references I posted suggest that PowerShell "...is going to ... support file globbing for native commands..." and that the 2017 merged pull-request "(partially) fixes" the earlier issue.

But not for  Command shell (CMD.exe).

AFAIK the only one with a working Windows install is @pureabsolute (the OP). So we're sort of at the OP's mercy. That being said, have we resolved a few things so far: 

1. Is this, therefore, not a 'Rakudo bug particular to Windows' ? 
2. Is this issue essentially a feature request?

Finally, has the OP had any luck with either PowerShell or WSL1/WSL2? 

Thx.

@timo 
@Tyil
@hankache
@AntonOks

**Comment by jubilatious1** [comment]
So does moving to PowerShell solve your problem? (I believe your initial report concerned CMD.exe).

I really have to apologize that I don't know enough about the Windows ecosystem. When I see MS posting examples that say:

`C:\Test\*.txt`

My question is whether that means you have to specify the entire path? So there has to be a way to type in:

`C:\path\to\raku -ne ".say" C:\Test\*.txt`

Which doesn't look right to my eyes.


I did a brief excursion into the Ruby-sphere and found a few references, (ahem, problems), pertaining to Windows shells. The first SO post I encountered was seven years old and un-answered (I've listed it second below). I tried to track down others, listing maybe the most important one first, below:

1. "Is there any way to get the windows cmd shell to expand wildcard paths?"
https://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths

2. "Ruby Windows command-line globbing"
 https://stackoverflow.com/questions/23908299/ruby-windows-command-line-globbing

3. "Parsing command-line arguments as wildcards"
https://stackoverflow.com/questions/3954750/parsing-command-line-arguments-as-wildcards

4. "Ruby wildcard command line argument auto expansion"
https://www.ruby-forum.com/t/ruby-wildcard-command-line-argument-auto-expansion/106378/3

There isn' a lot of clarity as to what's going on here, except to say that the Windows system is quite different from Unix/Mac. In the Perl evolution, such a difference caused the founding of  company (ActiveState) to deal with it.

But it's a different era, and Maybe WSL will work for you? Or MinGW? Links below.

https://docs.microsoft.com/en-us/windows/wsl/install
https://sourceforge.net/projects/mingw/
https://www.mingw-w64.org/


@ToddAndMargo

**Comment by pureabsolute** [comment]
I looked at your links (finally -- for the first few, and even your most recent set).

1) Those people are all talking about PowerShell on Linux.
2) They have approached the problem from the other direction - since the shell normally globs for linux commands, they came up with a solution to have the powershell glob for "native" commands.  They ran into problems when running on windows since windows doesn't want or need the shell to do any globbing work.
3) They came up with a "No Glob" flag so that windows native commands (presumably the powershell commands in linux) would have access to the unglobbed command line arguments.

So actually the raku on windows job is easier than the powershell on linux job.  raku just has to add globbing for the command line in some way where the platform is windows - and it will work with all windows shells including powershell.    When not on windows, you do not want to glob the arguments..  Unless you use a flag.

So just  as powershell on linux came up with a way to no-glob windows commands, raku on windows and linix can have a way to always glob.  This would allow them to work with bash and powershell on linux (no glob), and windows (always glob), and have the flag to alter the behavior as needed.

**Comment by jonathanstowe** [comment]
Leaving aside the Windows shells for a moment I think the actual question to be answered here is "Should raku glob arguments for environments which don't do shell globbing?" (it is after all possible that it may be ported to other platforms where the shell doesn't do globbing, or even on one where the shell globbing is optional or whatever.)

Personally I'm not particularly in favour because, as I see it,  it only really applies to "one liners"; in a script it is easily dealt with by applying some module that implements `glob` to the arguments, and, whilst people like to test things with one-liners, I'm not sure that people actually do that otherwise,

If it were to be implemented I think I'd be more in favour of providing an interface like we do for `--doc`, that is give the name of some module that provides the glob function which will be used to generate the ArgFiles; there are multiple different globbing styles  and I don't think the developers want to be in the game of providing for all of them in core.

**Comment by pureabsolute** [comment]
> Personally I'm not particularly in favour because, as I see it, it only really applies to "one liners"; in a script it is easily dealt with by applying some module that implements glob to the arguments, and, whilst people like to test things with one-liners, I'm not sure that people actually do that otherwise,

It applies to all raku scripts - a one liner is just one where the extra cruft is more noticeable.  But have every windows raku script be forced to include globbing at the beginning which might look different program to program but do the same thing I assume is something raku with its myriad of syntax shortcuts would want to avoid.

With respect to one liners, however, I use them *all the time*.  I never learned AWK, SED, CUT, grep (although I know the basics), etc.  I do all of those commands with perl / raku one liners.  My original example:

    perl -ne "print if /begining line/../ending line/" text.file

Is amazing in its own right.  And as I mentioned, I used to do that on windows.  I thought I could pick up where I left off with raku, and I'm here to see if we can make this happen. 

As for you're last point - 

> If it were to be implemented I think I'd be more in favour of providing an interface like we do for --doc, that is give the name of some module that provides the glob function

That's all I'm arguing for.  Technically I've been throwing a couple of approaches around, but the base one is to be able to -g SQL or --glob=simple or even --glob=none.    I assume that raku knows the platform it is running under (or what it was compiled for), and have --glob=wincmd or --glob=winps (or just one by default if it can't tell what shell its running under).  Regardless of the default, by specifying the --glob argument it would behave the same on all platforms (assuming the correct modules loaded of course).

**Comment by jonathanstowe** [comment]
> That's all I'm arguing for

Well you're not really, you're arguing for all the different different varieties of glob to be built in.  If there was any builtin it should probably only be, say, that defined for the POSIX shell, any others to be pluggable by (ecosystem) modules with a defined interface.  Or even do something simpler (say just '*' expansion ) and if, say, `IO::Glob` is installed, use that instead to do something more comprehensive.

**Comment by pureabsolute** [comment]
> Well you're not really, you're arguing for all the different different varieties of glob to be built in

No - I'm arguing for IO::Glob to be built in.  

> Or even do something simpler (say just '*' expansion ) and if, say, IO::Glob is installed, use that instead

Why is that simpler than just having a class that represents the platforms you compile for be included and used from the start?  

Meh -- I'm not religious about these things.  If your solution is what plays, I'm not gonna argue.

**Comment by pureabsolute** [comment]
@ToddAndMargo  That quite was not mine, but rather @jonathanstowe's.  

But how does your function solve the problem?  I don't think I have enough knowledge.  Does it cause cmd.exe to expand the arguments for you?

And further, does it compress to one line?  :)

**Comment by jubilatious1** [comment]
@pureabsolute says:
> No - I'm arguing for IO::Glob to be built in.

Someone made the decision not to offer a Perl5-like globbing function in Raku. I don't think it's an oversight. Furthermore, one Larry Wall mentioned that many of the command-line switches available in P5 are now available *within* the Raku language, which means you only have to write the code once (and run it everywhere). 

`IO::Glob` hasn't been updated since 2016, and I can do a pretty good job on my Mac using `dir()` with a Regex Matcher. Again, the following lines of code both work for me on MacOS.  I have to think that the first line will work for you:

raku -e '.lines.say for dir(test => / \.txt $ /);'

OR:

raku -e '.lines.say for $*ARGFILES;' *.txt


Anyway, we're here to pick your brain as well. What would you tell a Windows User about Raku? What strategy (scripts vs one-liners) and/or ecosystem (CMD.exe vs PowerShell vs WSL1rWSL2) would you tell them to pursue? 

Where are nascent Raku coders going to find success on the Windows platform--today or tomorrow?

[[ Larry Wall quote (regarding command line switches): _"The key word above is 'occasionally', so most of these seldom-used switches [in P5] are gone [in Raku]. Also, most of their functions are really easy to do from inside the language."_  see: https://www.nntp.perl.org/group/perl.perl6.users/2020/07/msg9004.html ]]
