### ISSUE TITLE
Symbols declared in a nested block do not lookup for globals

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#4563]
## The Problem

```
# in file base.rakumod

class C::D {}
sub foo is export {}

# in file user.raku

use base;

say C::D.WHICH;
{
    sub foo {};
    class C::D {};
    say C::D.WHICH;
}
```

## Expected Behavior

An error about duplicated `C::D` and `foo`. The error happens properly if there is no nested block and symbols are declared in top level.

## Actual Behavior

No error.

```
➜  raku-test raku -I. user.raku
C::D|U72111088
C::D|U72111280
```

## Environment
* Operating system: gnu/linux
* Compiler version (`perl6 -v` or `raku -v`):`Rakudo™ v2021.09-252-g431c3d6b7`

**Comment by niner** [comment]
For subs this is expected and specified behaviour. Subs are `my` scoped by default. I.e. the `sub foo` in the block is only known inside that block and it shadows any similar named symbols in outer scopes. This is the same as with variables.
For classes it's a bit less clear, since those are `our` scoped by default. But even so, they would shadow the symbol defined in the outer scope.

So in short: it's a feature (or two).
