### ISSUE TITLE
junctions with given/when behave strangely

### ISSUE THREAD

**Issue by doomvox** [rakudo/rakudo#4615]
Passing an "all" junction to a given/when construct should let you
do a smartmatch against the junction.  This used to work with older 
rakudos, but with a recent build from HEAD it doesn't.

This should say "both int":

    raku -e 'say do given all(3,7) { when Int { "both int" }; default {"differ"} };' 

That used to work, but doesn't with recent builds.

    |                 version | result     | reported by                                  |
    |-------------------------+------------+----------------------------------------------|
    | v2021.10-43-ga8329f6fd. | "differ"   |                                              |
    | v2021.09-229-g38f6f8731 | "differ"   |                                              |
    |                 2021.06 | "differ"   | William Michels                              |
    |                 2021.04 | "differ"   | https://github.com/rakudo/rakudo/issues/4386 |
    |                 2020.11 | "both int" | Bruce Gray                                   |
    |                 2020.10 | "both int" |                                              |
    |             2020.[5..9] | "both int" | Bruce Gray                                  |
    |               2020.05.1 | "both int" | Andy Bach                                    |

I'm on:

    Linux fandango 4.9.0-8-686 #1 SMP Debian 4.9.144-3 (2019-02-02) i686 GNU/Linux

Some discussion of this:

    https://www.nntp.perl.org/group/perl.perl6.users/2021/11/msg10240.html

**Comment by MasterDuke17** [comment]
This bisects to https://github.com/rakudo/rakudo/commit/c080e59404ed1b27e8841249e1c71d7e013c09ca. If we decide the prior behavior is correct, I'm tempted to just revert that change. It was significantly more difficult to implement than expected, makes the code more complex, wasn't all that much faster, and might be made obsolete by RakuAST anyway.

**Comment by pmichaud** [comment]
FWIW, I find the old behavior to be more in line with what I would expect to happen here.  I would support reverting this change.

Pm

**Comment by doomvox** [comment]
I found the current behavior tremendously puzzling.  Consider the fact
that this works:

     given all(3,7) { say so $_ ~~ Numeric; }
     # True

Since the "given" does topicalize the junction, and an explicit
smartmatch against the junction works, it's difficult to see why an
implicit smartmatch with "when" wouldn't work.

**Comment by raiph** [comment]
cf https://github.com/Raku/problem-solving/issues/297

**Comment by doomvox** [comment]
And it turns out fecundf opened up an issue like this one already that I'd forgotten about:

https://github.com/rakudo/rakudo/issues/4386

**Comment by jnthn** [comment]
> This bisects to c080e59. If we decide the prior behavior is correct, I'm tempted to just revert that change. 

Per the discussion in problem-solving, I think the behavior that the commit introduced is the one we eventually want, but it needs to happen consistently, and it's going to have to happen at a language version boundary. I'd agree to revert the change here, since it creates inconsistency within a language version.

**Comment by doomvox** [comment]
Trying to understand what Larry Wall was getting at in his remark last May, it seems as though he's mainly concerned with a performance issue.  Is there also a correctness issue involved, some cases where it's not clear what the right thing should be to do where there's a left-hand junction in a smartmatch?  

Where I'm going here is I think the naive response to this kind of issue is "okay, maybe LH junctions can't perform as well as RH ones, but could we allow them anyway, and just document that there's a performance hit there?"

**Comment by raiph** [comment]
Hi @doomvox,

> Trying to understand what Larry Wall was getting at in his remark last May, it seems as though he's mainly concerned with a performance issue.

Mainly, but not only, I currently think.

> Is there also a correctness issue involved?

I think so. I'll provide an example in a moment.

First, let me quote from Larry's first email, which was a response to an email by yary, whose opening comment I've edited to make it easier to read:

>> Since `? (any(4,3) ~~ 3)` is `True` I expected
>> `given 4|3 { when 3 { True } }` to be `True` too.

Larry responded with:

> I think both of these should be returning `False`.

I agree his initial line of argument was auto-threading
and performance. But consider what he then wrote:

> In any case, the documentation says `~~` is defined
> underlyingly by `.ACCEPTS`, and for a `Numeric` pattern, that says:
```
    multi method ACCEPTS(Numeric:D: $other)
```
> Returns `True` if `$other` can be **coerced** to `Numeric` and
> is numerically equal to the invocant (or both evaluate to `NaN`).

Note how, even if we *don't* grant him an immediate win about performance, and try to keep things so the LHS *does* auto-thread, we see *more* problems such as:
```
say <42 3>.any ~~ 3; # False
say <42 3>.any ~~ '3'; # False
```
If it's supposed to coerce,, why doesn't that work?

----

I think what's happening here is that there was a clear design a decade+ ago, and Larry was simply reiterating that design (despite his characteristically mild/humble "In my opinion", which could be interpreted as if he had only just realized/seen these cases, whereas in fact he and the rest of the design team had already made their minds up 10-15 years ago, and he's just being Larry as he was ever been, never ever laying down the law).

And jnthn is clearly agreeing with Larry.

But there are many related bugs in Rakudo because that design hasn't been properly followed, with yary's examples being ones that prompted Larry to remind us of how it was always intended to be for the sensible reasons figured out way back when.

So, aiui, there's a bunch of existing bugs / contradictory behaviours related to the combination of smartmatching and junctions.

And, imo/aiui, the sensible thing to do is almost certainly to follow the guidance of Larry and jnthn on what is sensible, and fix the bugs by disabling autothreading on the LHS if the RHS is a **defined** value (while still allowing `(1,2,3).any ~~ Int` to work, unless jnthn et al decide that also ought to go for `6.e`).

> Where I'm going here is I think the naive response to this kind of issue is "okay, maybe LH junctions can't perform as well as RH ones, but could we allow them anyway, and just document that there's a performance hit there?"

My current understanding is that there's a wide swathe of bugs because of confusion. So that there's a bunch of bug fixing to do. And that it would be better to stick to the original well thought through and understood design, and fix bugs relative to that, and get the significant performance win that was always intended to deliver.

(As against throwing that design out, going against Larry and jnthn's wishes, fixing the existing contradictions/bugs to match this new design, crossing our fingers that sufficient thought is put into the new design without Larry and jnthn leading it, changing the doc to match this new design, and all the while knowingly killing optimizability.)

**Comment by vrurg** [comment]
#4698 fixes this issue and mostly preserves the optimizations introduced with c080e59.

**Comment by vrurg** [comment]
Closing with merge of #4698
