### ISSUE TITLE
Cannot find method 'unshift' on object of type VMNull in Inline::Perl5 tests

### ISSUE THREAD

**Issue by niner** [rakudo/rakudo#4638]
Several of Inline::Perl5's tests fail with error messages like:
```
===SORRY!=== Error while compiling /home/nine/Inline-Perl5/t/from.t
This representation (Null) does not support elems (for type VMNull)
at /home/nine/Inline-Perl5/t/from.t:16
```

## Steps to Reproduce
```
git clone git@github.com:niner/Inline-Perl5.git
cd Inline-Perl5
rakudo configure.pl6
make test
```

Breakage is caused by rakudo commit 856f1af0bb51e3a63781c5ff77bfd5af75526d8e.

**Comment by vrurg** [comment]
I thought I'm loosing my mind! `%!mro` is initialized only once in `compute_mro`, and yet I get it initialized whereas the method is never invoked for a class! Who'd guess you set it up manually... So, see https://github.com/niner/Inline-Perl5/pull/172.

For now I'm closing this issue. Yet, there is a question which bothers me. I consider reworking C3MRO toward more lazification and less memory consumption. Part of it is converting from hash attribute to an array. But doing so would make `Inline::Perl5` compiler-version dependent. This doesn't look good to me. And then, what if other changes to C3MRO internals will be necessary in the future?

Wouldn't it be better if `Inline::Perl5::ClassHOW` provide its own `mro` method? In this case you'd unbind yourself from C3MRO altogether. And the only point where compatibility would need to be maintained will be `mro`'s signature.

**Comment by niner** [comment]
I'd prefer to make C3MRO properly usable by custom meta classes. I only use nqp or reach into internals where there is no proper interface. Metamodel::Primitives currently only gets one so far. What's the point of having real meta classes when it's isn't possible to re-use or extend them in user code?

**Comment by vrurg** [comment]
@niner C3MRO is usable. The tiny detail you miss is [C3](https://en.wikipedia.org/wiki/C3_linearization) in its name. :) Sincerely, all what the role provides is a service of sorting classes/roles graph in C3 order and defaults means of accessing the results. From this point of view its existence is fully justified as it is consumed by a couple of core classes for exactly the purpose of implementing C3 linearization by them.

The only public interface we would guarantee and thus be, perhaps, somehow represented in `Metamodel::Primitives` is method `mro` itself and, possibly, its shortcut version `mro_unhidden`. But I doubt the latter is worth speccing at any level as it is only use is by `Perl6::Metamodel::Dispatchers` which is to be dismissed as soon as new-disp is supported by all backends.

Yet, I don't see how the method could be backed by `Metamodel::Primitives` as all one needs is just declare their own version of it. That's it. At NQP level the method would need to accept all the named parameters we'd expect it to accepts. At Raku level even this is not needed.

So, eventually, I'd say that the proper implementation of `Inline::Perl5` must provide it's own `mro` method. And since a [PR](https://github.com/niner/Inline-Perl5/pull/173) is better than words, here it goes.

*Off* BTW, I like the implementation of `NQPArray` with respect to `BUILDPLAN` relying on `mro` returning a `VMArray`, and normally we can't provide it considering that Raku hllizes method return value. `IterationBuffer` also solves the problem, but it's an implementation detail and lacks `list` method. Perhaps what is worth considering adding to `Metamodel::Primitives` is a method wrapping an HLL positional/iterable into a `VMArray` representation.
