### ISSUE TITLE
Dynvar accessed from whenever and Promise not found

### ISSUE THREAD

**Issue by FCO** [rakudo/rakudo#4654]
It feels a bug to me:

```
<SmokeMachine> Fernando Corrêa de Oliveira 
m: use Test; my $*a = 42; react whenever Promise.in: 1 { await start { is $*a, 42 } } # should this work?
02:21 C<camelia> combined, experimental evalbot 
rakudo-moar d6817f088: OUTPUT: «not ok 1 - ␤# Failed test at <tmp> line 1␤# expected: '42'␤#      got: (Failure)␤»
02:22 S<SmokeMachine> Fernando Corrêa de Oliveira 
m: use Test; my $*a = 42; react whenever Promise.in: 1 { is $*a, 42 }
02:22 C<camelia> combined, experimental evalbot 
rakudo-moar d6817f088: OUTPUT: «ok 1 - ␤»
02:23 S<SmokeMachine> Fernando Corrêa de Oliveira 
m: use Test; my $*a = 42; await start { is $*a, 42 }
02:23 C<camelia> combined, experimental evalbot 
rakudo-moar d6817f088: OUTPUT: «ok 1 - ␤»
02:23 S<SmokeMachine> Fernando Corrêa de Oliveira 
why it's ok with whenever, it's on on a Promise but when doing both that breaks?
```

https://logs.liz.nl/raku/2021-11-28.html#02:21

**Comment by jnthn** [comment]
While `start` does capture the dynamic context in order to make the same dynamically scoped variables available that were at the point the `start` was encountered, the same does not apply to `supply/`react`/`whenever`. I think it should stay this way, because:

* The performance price we pay for the feature with `start` blocks is non-trivial, and the dynamic nature of dynamic variables mean there's little that can be done to reduce it. I wouldn't like to see `supply` and `react` pay that price too.
* The feature with `start` blocks is there primarily to ease refactoring - so that one can add a `start` to parallelize without worrying about dynamic variable availability. This applies rather less strongly to `supply`/`react`
* While `start` one knows that the only things in dynamic scope are those introduced by the thread pool scheduler. Thus fallback to the dynamic scope of the location where `start` was used makes sense. With `whenever`, the thing in dynamic scope is whatever did the `emit` of the message being processed now, which in turn may have been something else result from an `emit`, etc. Thus using dynamic variables in a `whenever` is already a quite questionable idea.

**Comment by FCO** [comment]
But why is it working on whenever without start?

<img width="778" alt="image" src="https://user-images.githubusercontent.com/99834/143881346-32b748cc-75ac-47f0-aeca-dc48e43193b4.png">

what would you suggest to make a module that uses dynvars to work on that case?

How does that work for %*ENV? isn't %*ENV real dynvar? Shouldn't that be consistent?

<img width="847" alt="image" src="https://user-images.githubusercontent.com/99834/143881960-240ba45b-1dac-43b2-84a8-df9696492dc0.png">

**Comment by jnthn** [comment]
It works for `%*ENV` because no, that's not a real dynamic variable, it's using the `GLOBAL`/`PROCESS` fallback.

**Comment by vrurg** [comment]
There is another possibly confusing behavior of `start`: their dynamic lookups don't chain. I.e. if an "original context" starts a thread which, in turn, starts another thread, then the latter doesn't see dynamics from the "original context". As to help Jonathan not to duplicate his explanations, here is a link to why this is a feature: https://github.com/Raku/problem-solving/issues/151#issuecomment-575955491

**Comment by patrickbkr** [comment]
@FCO, do I suspect correctly, that Red currently deeply relies on a dynamic variable, having the effect that Red can't be reliably used in combination with `whenever` blocks? I.e. is this the cause for https://github.com/FCO/Red/issues/537 ?

Does that mean that dynvars break composability, as one can never be sure a user of a piece of code might utilize `whenever`s?

**Comment by jnthn** [comment]
Even if `whenever` did pick this up, it's not clear how much help it would be; there are many ways that code can end up running on another thread, and threads imply fresh dynamic scopes. This is exactly the use case for dynamic variable fallback to `GLOBAL` and `PROCESS`; I'd expect a `$RED-DB` to be installed in one of those, and then resolved that way ordinarily.

**Comment by FCO** [comment]
I'll make $*RED-DB fallback to GLOBAL/PROCESS, but I'm still not sure how to fix the other internal dynvar that changes depending on scope.

**Comment by patrickbkr** [comment]
Does that other var ever make it into use space?

**Comment by patrickbkr** [comment]
Given that FCO/Red#537 is fixed, can this issue be closed?
