### ISSUE TITLE
is cached sometimes fails to cache invocations with hash-like arguments.

### ISSUE THREAD

**Issue by nikola-benes** [rakudo/rakudo#4666]
## The Problem

```Raku
use experimental :cached;
sub foo($s) is cached { say "not cached: $s" }
foo(<1 2 3>.Set) for ^100;
```

## Expected Behavior

One line of output with `not cached:` and an arbitrary ordering of 1, 2, 3.

## Actual Behavior

Usually, six lines of output with all the permutations of 1, 2, 3. If you are really lucky, some of the permutations may be missing.

## Environment
* Operating system: Linux
* Compiler version: Rakudo™ v2021.10

## Comments

I get why this happens (`is cached` stringifies the capture and hashes are randomized); however, it would be nice to have a caching mechanism that works well with hashes (or at least sets).

**Comment by ab5tract** [comment]
We have a few issues going on here:

* `is cached` based on `.gist` doesn't make sense at this point
* `is cached` is not implemented in a thread-safe way (not an issue for this ticket in particular, but since we are poking at the trait, it's worth pointing out)
* even switching to `.raku`, we still have to adjust some of the undordered collections to sort in that method

**Comment by lizmat** [comment]
> however, it would be nice to have a caching mechanism that works well with hashes (or at least sets).

There are no plans on trying to fix "is cached".  Most likely, it will be deprecated from the core.

The ecosystem provides several solutions: https://raku.land/?q=cache
