### ISSUE TITLE
Unstable behavior with insertion/deletion of hash key inside a for loop

### ISSUE THREAD

**Issue by Skarsnik** [rakudo/rakudo#4684]
## The Problem

Inserting and removing key on a hash interaction with a for loop (using for example for %h.keys) result of random
numbers of iteration of the for loop.

## Expected Behavior

A stable number of iteration, either ignoring all insertion or trying to accord to them.
Like 
````
my $cpt = 0; 
for ^20 {
    my %h = (a => 1, b => 2, c => 3, d => 4); 
    for %h.keys -> $k {
       $cpt++; 
       if %h{$k} % 2 == 0 {
         %h<e> = 5; 
         %h{$k}:delete
       }
    }
}
say $cpt;
````
Etheir output 80 or 100.

## Actual Behavior

The above example output a random number between 80 and 100.

## Steps to Reproduce

```
skarsnik@DESKTOP-UIA12T1:/mnt/f/Project/gptrixie$ raku -e 'my $cpt = 0; for ^20 {my %h = (a => 1, b => 2, c => 3, d => 4
); for %h.keys -> $k {$cpt++; if %h{$k} % 2 == 0 {%h<e> = 5; %h{$k}:delete}}}; say $cpt'
88
skarsnik@DESKTOP-UIA12T1:/mnt/f/Project/gptrixie$ raku -e 'my $cpt = 0; for ^20 {my %h = (a => 1, b => 2, c => 3, d => 4); for %h.keys -> $k {$cpt++; if %h{$k} % 2 == 0 {%h<e> = 5; %h{$k}:delete}}}; say $cpt'
86
skarsnik@DESKTOP-UIA12T1:/mnt/f/Project/gptrixie$ raku -e 'my $cpt = 0; for ^20 {my %h = (a => 1, b => 2, c => 3, d => 4); for %h.keys -> $k {$cpt++; if %h{$k} % 2 == 0 {%h<e> = 5; %h{$k}:delete}}}; say $cpt'
89
```

## Environment
* Operating system: WSL2 (Ubuntu)
* Compiler version: 
Welcome to Rakudo™ v2021.10.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.10.

**Comment by lizmat** [comment]
That's because `Hash.keys` is lazy.  And that's a good thing, generally.

You can prevent the issue by making the iteration over the keys `eager`:
````raku
for %h.keys.eager -> $k {
````
This will make a list of all the keys when the first iteration is started.  This will thus never see the key you insert.

**Comment by Skarsnik** [comment]
The issue, if it was lazy and created 'on demand', it should still be consistent and the added key should always be seen. (that is the reason the counter vary)

**Comment by niner** [comment]
The output cannot be consistent due to hash randomization, which is an important security feature. The only way to make the output consistent over multiple runs would be to create the full list of keys to iterate over in advance, i.e. exactly what making the key list eager does. This of course costs a lot of memory and performance. And that's why it's up to the user to decide whether performance or handling insertions during iteration in a repeatable way is more important.

The same tradeoff exists really in any language that has hash tables as it's a property of the data structure itself. Perl for example warns you if you try to do this: "Use of each() on hash after insertion without resetting hash iterator results in undefined behavior". Python even throws an exception: "RuntimeError: dictionary changed size during iteration". Javascript behaves like Raku according to MDN: "Properties added to the object over which iteration is occurring may either be visited or omitted from iteration."
