### ISSUE TITLE
Using symbols (or just `Num`?) as an Enum key is allowed but breaks subsequent code

### ISSUE THREAD

**Issue by codesections** [rakudo/rakudo#4711]
Declaring an `Enum` that creates a name clash with existing types does not throw an error.  For example, this works (at least for now…):

```raku
enum <Num>;
say Num.raku; # OUTPUT: «::Num»
```

However, the presence of that enum key causes confusing and LTA compile errors in later code (LTA both in that the message doesn't mention the `enum` and because it doesn't contain any line numbers).  Here's a golfed example:

```raku
enum <Num>;
multi f {};
# OUTPUT:
# ===SORRY!===
# This type cannot box a native number: P6opaque,
```

I haven't done enough testing to be sure if this issue occurs with other symbols besides `Num` – the `multi` above runs fine with _some_ types (`Int`, `Sub`, and `num`, for example).  And I'm not sure what the intended behavior is – that is, I don't know if `enum <Num>` is supposed to be allowed (and the bug is that the `multi` (and maybe other code?) doesn't resolve the name correctly) or if `enum <Num>` is _not_ intended to be legal (and the bug is that Rakudo doesn't throw a helpful error at declaration time).

I get this bug on released versions of Rakudo and on the current build (`v2021.12-101-g38063d487`).

**Comment by lizmat** [comment]
Perhaps the Enum creation code needs to do a `CORE::.EXISTS-KEY($string)` on all of the given names.

**Comment by vrurg** [comment]
You can basically declare any lexical, it's not prohibited. `class Num { }`, for example.

**Comment by codesections** [comment]
@vrurg good point.  So, in your view, is it correct that `class Num {}` causes `multi` to throw?

```raku
class Num {}
multi f {};
# OUTPUT:
# ===SORRY!===
# This type cannot box a native number: P6opaque,
```

If so, this issue is just a LTA error message.  If not, there's a bug in how `multi` is compiling.

**Comment by vrurg** [comment]
Since we don't really make syntax difference between the core symbols and others, re-declaring something isn't a bug. Though we may consider making it a warning at some point.

`multi` is a different case, apparently. The bug traces down to creating a signature for default onlystar proto and, as I expected, it happens in boxing code. Method `add_constant` has `find_symbol` invocation to locate the type to box into. In that particular context `find_symbol_in_setting` would make more sense to me.

**Comment by vrurg** [comment]
Yep, `find_symbol` with `:setting-only` named parameter fixes the bug. Not sure if spectests are not broken because I tried it on my experimentally modified Rakudo.

**Comment by jnthn** [comment]
General policy has been that anything core language types are resolved in the setting; this should already include all `Code` objects and any exception types, and extending it to literals makes sense. I suspect in RakuAST it already does happen that way; in fact, since RakuAST nodes appear in the bootstrap, they can directly reference the types without any lookup.
