### ISSUE TITLE
Inconsistencies when defining postcircumfix operators 

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#4722]
## The Problem

Defining postcircumfix operator can be tricky.

For instance, 

```raku
sub postcircumfix:<^ ^>( @a, Int $n ) {
    @a[^$n];
}
```

Does not work, and fail with a message about not finding "^". Fair enough, that's the "upto" operator. But then:

```raku
sub postcircumfix:<⬆ ⬆>( @a, Int $n ) {
    @a[^$n];
}

my @ary = 3..20;
say @ary⬆5⬆;
```

fails with: 

```
Unable to parse expression in postcircumfix:sym<⬆ ⬆>; couldn't find final '⬆' (corresponding starter was at line 9)
```

You need to explicitly put the whitespace around the numbers to work: `say @ary⬆ 5 ⬆`;

```

## Expected Behavior

Whitespace should probably not be needed

## Environment
* Operating system: ubuntu 20.04
* Compiler version (`perl6 -v` or `raku -v`): 2021.12

**Comment by TimToady** [comment]
The whitespace is needed there because it will treat what you think of as
the closer as an additional nested opener.  This is why it's usually better
to use opposing bracketing characters for postcircumfixes.  You can get
away with things like circumfix:<| |> for absolute value because the first
| is parsed when a term is expected, while the second is parsed when a
postfix or infix is expected, so the two characters are never chosen in the
same context.  But a postcircumfix:<| |> will be formally ambiguous at
every location a postfix is possible, and the whole philosophy of matching
bigger things over smaller things says we can't just DWIM the second one to
be a terminator, when you *might* have been wanting it to be a nested
initiator.

The grammar always looks for postfix/postcircumfix tokens before anything
else that lives in the infixish set of tokens, which is also why you must
put whitespace around certain ambiguous infixes.  This whitespace
disambiguation is a fundamental design rule in Raku, which has to deal
coherently with any user-defined tokens you can throw at it.  We thought
about combining postfixish stuff with infixish under a longest-token rule,
but that turned out to be a terrible idea.  The typical user only knows
whether they expect a postfix or an infix, and pays no attention to what
they don't expect, so this approach is psychologically fragile when
user-defined operators are added.  Establishing a culture of whitespace
around most infix operators (and looking for them after postfix fails)
turns out to minimize user surprise.  As you discovered above, it doesn't
remove all surprise when you define highly ambiguous terminators.  But our
current approach at least *allows* you to disambiguate them.

Larry

**Comment by p6steve** [comment]
this issue can be closed, right?

**Comment by ab5tract** [comment]
Adding some of this to the docs would be helpful.
