### ISSUE TITLE
Unable to subclass IO::Path

### ISSUE THREAD

**Issue by sdondley** [rakudo/rakudo#4750]
## The Problem

Despite my best efforts, I don't seem to be able to subclass IO::Path. Please see [the gory details.](https://climatechangechat.com/vimkiki-files.html).

## Expected Behavior

I should be able to subclass `IO::Path` and create an object with additional attributes and has all the methods of `IO::Path` available to it.

## Actual Behavior

I am unable to create an object that is a subclass of `IO::Path` that has its methods plus attributes that can be set during object construction.

## Steps to Reproduce

This code represents my best attempt to try to subclass IO::Path:

```
    #! /usr/bin/env raku
    use v6;

    class Vimwiki::File is IO::Path {
        has $.blah;

        multi method new($path) {
            self.bless;
            nextwith($path);
        }

        submethod BUILD() {
            say 'hi';
            $!blah = 'test';
            say $!blah;
        }
    }

    my $vwf = Vimwiki::File.new('t/test_file.md');
    say $vwf.^mro;
    say $vwf.s;
    say $vwf.blah;
```
* the code outputs:
    
```
        hi
        test
        ((File) (Path) (Cool) (Any) (Mu))
        0
        (Any)
```

## Environment
* Operating system: macos

* Compiler version (`perl6 -v` or `raku -v`):

Welcome to Rakudo™ v2021.12.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.12.

**Comment by lizmat** [comment]
Subclassing CORE classes can be tricky.  This is a workaround:
````raku
class Vimwiki::File is IO::Path {
    has $.blah;

    method !SET-SELF($!blah) {
        self
    }

    method new($path, |c) {
        self.IO::Path::new($path)!SET-SELF(|c)
    }
}
my $vwf = Vimwiki::File.new($*PROGRAM.absolute,'foobar');
say $vwf.^mro;  # ((File) (Path) (Cool) (Any) (Mu))
say $vwf.s;     # 286
say $vwf.blah;  # foobar
````
This uses a few Raku features you may not be aware of.

1. You can call `.new` from a certain class explicitely: `self.IO::Path::new` will call the `new` method of the `IO::Path` class with `self` (aka, your subclass) as invocant.
2. You can set an attribute by using it as a parameter (`method !SET-SELF($!blah)`)
3. The name of the `!SET-SELF` private method, any name will do.  Just make sure it returns `self` for convenience, so that you can make it a single call in `new`.
4. `|c` in the signature of method `new` will collect all other parameters and pass them on, in this case to `SET-SELF`.  It's at that place that you're going to be handling any additional parameters that your subclass needs.

Hope this helps a bit.

**Comment by sdondley** [comment]
Awesome. Thanks. And what is the `!` doing? That makes the method private, I understand.

But in this line: `self.IO::Path::new($path)!SET-SELF(|c)`

It's not clear to me what it's doing. Is that instead of `.` I'm guessing?

**Comment by lizmat** [comment]
The `!` is indeed the way to call private methods (methods whose name start with a `!`).
