### ISSUE TITLE
Date.new('2015-02-27').later(:5foo) should be a syntax error.

### ISSUE THREAD

**Issue by ohmycloud** [rakudo/rakudo#4755]
## The Problem

```
> my $d = Date.new('2015-02-27');
> $d.later(:5h)
2020-02-27
> $d.later(:5ho)
2020-02-27
> $d.later(:5hou)
2020-02-27
> $d.later(:5hour)
2020-02-27
> $d.later(:5hours)
2020-02-27

> $d.later(:5foo)
2020-02-27

> $d.later(:5bar)
2020-02-27
```

It seems that the colon pair above appears to be recognized as the `year` unit.

## Expected Behavior

Report an error if the unit is not right.

## Environment

* Operating system: macOS Monterey 12.1
* Compiler version (`perl6 -v` or `raku -v`): v2021.12

**Comment by 0racle** [comment]
I had a brief look and I think the issue is that the `else` block in `Data.move-by-unit` just assumes that that any `$amount` is the year, regardless of `$unit`.

```raku
method move-by-unit(str $unit, int $amount) is implementation-detail {
    if nqp::atkey($valid-units,$unit) -> int $multiplier {
        ...
    }
    elsif nqp::eqat($unit,'month',0) {
        ...
    }
    else { # year
        my int $year = nqp::add_i($!year,$amount);
        ...
    }
}
```

Potentially, a guard clause that checks `$unit` is in `$valid-units` could be used, though the general rule with methods is to ignore arbitrary named args, so maybe instead of `else` we can check if `nqp::eqat($unit,'year',0)`.

**Comment by lizmat** [comment]
So done in https://github.com/rakudo/rakudo/commit/3445513858 .

It should not be a compile-time error as unexpected named arguments are ignored on methods in Raku.
