### ISSUE TITLE
Chomp Argument silently ignored on `lines` multi method

### ISSUE THREAD

**Issue by Mercerenies** [rakudo/rakudo#4794]
## The Problem

From the [Raku documentation](https://docs.raku.org/routine/lines).

```
say lines(:!chomp, "a\nb").raku;  # OUTPUT: «("a\n", "b").Seq␤» 
```

It seems like, currently, the optional `chomp` argument to the `lines` multi method is ignored.

## Expected Behavior

As indicated in the comment above, the expected output of the above snippet is a list containing two elements: `"a\n"` and `"b"`.

## Actual Behavior

The `chomp` argument seems to be silently ignored, and the resulting sequence is `("a", "b").Seq`. Note the lack of a newline.

## Environment
* Operating system: Fedora 31
* Compiler version (`perl6 -v` or `raku -v`): Rakudo version 2020.01 built on MoarVM version 2020.01.1 implementing Perl 6.d.

**Comment by MasterDuke17** [comment]
This was fixed in https://github.com/rakudo/rakudo/commit/1bcc5d73e3433badcdcb8b981a805cae9e84466d, so from release 2020.06 until now it's working correctly (https://gist.github.com/Whateverable/1ac9f05cf8cb07ad587a55e614a6bb22). If the stock fedora repos don't have a newer rakudo, you could try https://nxadm.github.io/rakudo-pkg/

**Comment by Mercerenies** [comment]
Thanks! My mistake. Should've tried a newer version before bothering you fine folks. Cheers! :)
