### ISSUE TITLE
possible regression in checking the topic within where blocks?

### ISSUE THREAD

**Issue by fluca1978** [rakudo/rakudo#4878]
I'm not sure if this is a regression, as suggested on the mailing list <https://www.nntp.perl.org/group/perl.perl6.users/2022/04/msg10483.html>, or something has changed in the language specification.

## The Problem

The topic variable `$_` seems to get not set within some `where` blocks inside a `MAIN` argument list. It was working fine with previous releases of Rakudo, even if I'm not sure since when the behaviour happened.

Here's a test program:

```
sub MAIN( Str :$dir where { .so && .IO.d // warn "Specify the directory [$dir]" } ) {
    say $dir;
}
```

## Expected Behavior

When invoked without arguments, the program should print `Specify the directory []`. When invoked with something that is not a directory it should print the message with the value of `$dir` set.
It worked in Rakudo 2020-01, but fails in recent Rakudo versions.

## Actual Behavior

Invoking with a non-dir value (i.e., `foo` is not a local directory) prints errors about the topic not being set, then a message with the value, and then again the topic not being set.
```
% raku ~/tmp/test.p6 --dir=foo
Use of uninitialized value of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to
something meaningful.
 in block  at /home/luca/tmp/test.p6 line 4
Specify the directory []
 in block  at /home/luca/tmp/test.p6 line 4
Specify the directory [foo]
 in block  at /home/luca/tmp/test.p6 line 4
Use of uninitialized value of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to
something meaningful.
 in block  at /home/luca/tmp/test.p6 line 4
Specify the directory []
 in block  at /home/luca/tmp/test.p6 line 4
Usage:
 /home/luca/tmp/test.p6 [--dir=<Str where { ... }>]
```

Note that explicitly identifying the variable in the `where` block, i.e., not using the topic, fixes the issue:

```
sub MAIN( Str :$dir where { $dir.so && $dir.IO.d // warn "Specify the directory [$dir]" } ) {
    say $dir;
}
```

This works fine with every Rakudo version, up to 2022-01. Apparently the topic is not set appropriately or the language has changed the way `where` and `$_` work together.

## Environment
- Linux Neon 22.04
- Rakudo 2022-01 on moar.

**Comment by vrurg** [comment]
The key mistake of this code is about not reading [the documentation](https://docs.raku.org/type/Signature#index-entry-where_clause_) carefully:

> The code in `where` clauses has some limitations: anything that produces side-effects (e.g., printing output, pulling from an iterator, or increasing a state variable) is not supported and may produce surprising results if used. Also, the code of the `where` clause may run more than once for a single typecheck in some implementations.

This is exactly what we observe. It is also wrong to think that the "correct" code is actually correct. Even though it issues just single warning, it gets executed multiple times. Check it out but inserting a dummy print.

BTW, use of `$dir` in the initial variant is what's causing the multiple 'use of uninitialized value' warnings.

**Comment by fluca1978** [comment]
> The key mistake of this code is about not reading [the documentation](https://docs.raku.org/type/Signature#index-entry-where_clause_) carefully:

It could be but I actually read, even if I did not mentioned it. What I don't understand is why the behavior is different between the usage of the topic and the use of an explicit named argument.

> 
> BTW, use of `$dir` in the initial variant is what's causing the multiple 'use of uninitialized value' warnings.

But `$dir` is initialized, that's why I used `.so` and the `//` operator. Am I missing something here?

**Comment by vrurg** [comment]
> It could be but I actually read, even if I did not mentioned it.

Then, perhaps, you haven't done it _carefully_? 😉

> What I don't understand is why the behavior is different between the usage of the topic and the use of an explicit named argument.

Because they're not the same. Consider your `where` block to be `-> $_ { ... }`. Then internally it gets invoked as `&where($something)` where `$something` could be the named parameter, or it could be some other value, depending on the context. Try to add something like `note $_;` into your `where` block and observe rather surprising values.

> But `$dir` is initialized, that's why I used `.so` and the `//` operator. Am I missing something here?

Yes, you are. Don't know what exactly you're missing, as I'm not familiar with the guts surrounding `MAIN` invocation, but since `$_` is not necessarily bound to `$dir`, at some point the block is invoked at a point when `$dir` is not set yet. Again, best is to print all the values and see what's going on.

Eventually, the primary purpose of `where` is to ensure that the value it receives is valid. Anything else one does with the value is totally up to their responsibility.

**Comment by vrurg** [comment]
> so it is invoked with something that reminds a string

Didn't you notice that `say` from the body of `MAIN` got executed? And that `$dir` is uninitialized because is not passed in?

> I agree with the documentation here: there can be unexpected results. But I would like to better understand this apparent change of behavior within versions.

My point about printing the value was to demonstrate how unpredictable the behavior could be and how it couldn't be relied upon. And this is exactly what _implementation detail_ means when applied to this case: things may change over the time without notification.

When it comes to `MAIN` there are too many "subsystems" of the language dealing with it, starting with signature binding and likely including argument parsing and validating.

For now I'm closing this issue because there is no bug in it.
