### ISSUE TITLE
comma-assign problem with HinH

### ISSUE THREAD

**Issue by 0rir** [rakudo/rakudo#4945]
The `,=` operator crashes when assigning a hash-within-a-hash to a hash.  As in:

`%sink ,= %src<key>;`

The last test crashes in
[comma-assign.txt](https://github.com/rakudo/rakudo/files/8841261/comma-assign.txt)

Thanks, again.

**Comment by 2colours** [comment]
I'm not sure this is a bug.

Let's expand the statement:
`%sink ,= %src<key>;` -> `%sink = %sink, %src<key>;` -> `%sink.STORE: (%sink, %src<key>);`

So first let's understand what `(%sink, %src<key>)` is.

Let's suppose `%sink = {:makes("us"), :work("it")}` and `%src<key> = {:faster("stronger"), :harder("better")}`.

`dd (%sink, %src<key>); # ({:makes("us"), :work("it")}, ${:faster("stronger"), :harder("better")}) `

The important thing to see here is that this is a list that consists of two elements: the first one is a Hash and the second one is... well, an _itemized_ Hash. The values stored in a Hash come with a Scalar container, hence `%src<key>` returns its content within the Scalar container, as an item.  
If you want to know why its a good thing that Hashes contain values as Scalar containers, I can name some of the pretty consequences.

Now, it seems that the STORE method of a Hash takes this containerisation into account. I'm not sure if the exact semantics is described somewhere but it seems to flatten the Hashes (perhaps all Associatives?) it gets. However, `${:faster("stronger"), :harder("better")}` defines itself as an _item_ so it doesn't have the audacity to disregard this info. What do we end up with: a Hash and one single item. The Hash gets flattened, the single item cannot be paired with anything. Boom, fail.

Now that we know that the containerisation of `%src<key>` gets in the way, we have an easy fix: [decontainerisation](https://docs.raku.org/routine/%3C%3E). At the moment, both `%src<key><>` and `%src<key>[]` would do the trick.

And now, jumping to the conclusion:

`%sink ,= %src<key><>` succeeds, and `dd %sink` dumps `{:faster("stronger"), :harder("better"), :makes("us"), :work("it")}`. :)

Sidenote: you might correctly conclude that %src<key> could cause problems on the left handside of a similar statement: indeed, because it's an item, `%src<key> ,= %sink;` could create a weird recursive structure inside it, rather than a failure. However, decontainerisation can fix that too: `%src<key><> ,= %sink;` will work flawlessly.

**Comment by 2colours** [comment]
@0rir if you find my explanation convincing and consistent with Raku docs, please consider closing the issue as a reward. :)

**Comment by 0rir** [comment]
@2colours, I found your explanation of my 'error' compelling.  Thanks.   I have paused to keep it in public while view considering if `%src<key> ,= %sink;` should warn because the resultant hash is so unlikely to be what was desired.  I think it should.
