### ISSUE TITLE
.raku method sorts maps and hashes but not sets and bags

### ISSUE THREAD

**Issue by m-dango** [rakudo/rakudo#4975]
I noticed that the raku method on hashes and maps will sort the keys for you:
https://github.com/rakudo/rakudo/blob/7cf26457288a245646e134fa3fbf6488a7d0d28f/src/core.c/Hash.pm6#L176
https://github.com/rakudo/rakudo/blob/90d876a3fdaa5b381f2e765060aac67fe7e923ab/src/core.c/Map.pm6#L186

However this doesn't seem to happen for sets and bags:
https://github.com/rakudo/rakudo/blob/90d876a3fdaa5b381f2e765060aac67fe7e923ab/src/core.c/Setty.pm6#L151
https://github.com/rakudo/rakudo/blob/7cf26457288a245646e134fa3fbf6488a7d0d28f/src/core.c/Baggy.pm6#L283

I had not expected the former to be sorted, but I think it would be nice if sorting with the .raku method on Associatives was a consistent behaviour.

**Comment by 0rir** [comment]
It would be nice only sometimes.

Since the purpose of `.raku` is to create a string from which an instance can be resurrected, it would be inefficient to impose order on an unordered collection.  Besides `Associative` is just a role.

**Comment by TimToady** [comment]
I dunno about that—I think the main purpose of .raku is not serialization,
and in fact given compiler performance it's a terrible way to
serialize....unless you want it to be human readable, in which case all
these things should be sorted because you're likely to install such code
into another program, and if you ever want to modify that program, ordering
is rather beneficial to the next programmer that will see the data.
Mainly, .raku is there to present a much less ambiguous representation to
the user than a .gist might, when the user is likely to not mind the extra
punctuation.

Larry

**Comment by m-dango** [comment]
My current use is for output into `.raku` files, so the sorting is nice to have so diffs don't change each time. When I first used the method on a `Bag` the output being different each time was unsurprising, and I changed my approach to account for it, but when I later noticed `Hash` was being sorted, it drove me to open this ticket.

Its less an issue and more a question of "why this one and not that one?"
