### ISSUE TITLE
Final list of .snip should be a lazy list with a $!todo set

### ISSUE THREAD

**Issue by FCO** [rakudo/rakudo#4986]
https://irclogs.raku.org/raku/2022-07-15.html#22:07-0002

**Comment by lizmat** [comment]
Actually, this should only be applicable if the underlying iterator is lazy

**Comment by lizmat** [comment]
For the record, the example code was:
```raku
use v6.*; dd (^20).snip( |^Inf .map: { (* * 5 > *) } );
```
But actually, this turns out to be a bug / behaviour in the binder.  Issue golfed to:
```raku
sub a(|) { }
a( | (^Inf).Seq );
```
The binder apparently doesn't know how to `Slip` a lazy `Seq` into arguments, and hangs while reifiying itself into oblivion.

FWIW, I don't think the `|` is needed there.  Taking away the `|` shows:
```raku
use v6.*; dd (^20).snip( ^Inf .map: { (* * 5 > *) } );
# Too few positionals passed; expected 2 arguments but got 1
```
which makes sense.

So I feel this particular example is a case of DIHWIDT.

However, more generally this may well be an issue in the binder, instead of a DIHWIDT.  So I created https://github.com/rakudo/rakudo/issues/5717 to follow up on that.

In the meantime closing this one.
