### ISSUE TITLE
build error when making rakudo RPM packages from github repo source code in Fedora

### ISSUE THREAD

**Issue by topazus** [rakudo/rakudo#4999]
## The Problem

I try to build RPM packages in my Fedora linux machine.
I can make rpm packges from the [latest release source code](https://github.com/rakudo/rakudo/releases/tag/2022.06), but failed in source code from github repo.

here is the error

```
RPM build errors:
    Invalid version (double separator '-'): 2022.06-2-gcc49dcf93: pkgconfig(moar) = 2022.06-2-gcc49dcf93
```

similar version name error https://github.com/KrispyCamel4u/SysMonTask/issues/34

maybe change `2022.06-2-gcc49dcf93` to `2022.06.2-gcc49dcf93` would work.

## Environment
* Operating system: Fedora
* Compiler version (`perl6 -v` or `raku -v`):

**Comment by patrickbkr** [comment]
Thanks for your report!

I've looked at this. Our version numbering system is not valid semver. But I think its valuable to have a look at it anyways as it's the most popular versioning system.

**semver** is fine with multiple dashes in a version number. The first dash separates the well known three part version number from a so called pre-release version number. That pre-release version number may contain dashes. ([link](https://semver.org/spec/v2.0.0.html#spec-item-9))

**RPM** on the other hand has its [own definition of how version numbers have to look](https://rpm-software-management.github.io/rpm/manual/spec.html#version). There the rules for the general version number itself are more relaxed, but pre-release numbers should to be separated by '~' (and post release numbers by '^'). The pre-release number may not contain '-'.

So I think its obvious that a conversion step needs to happen. I propose to replace the first '-' with '\~' and all following '-' with '_'. So '2022.06-2-gcc49dcf93' would become '2022.06\~2_gcc49dcf93'.
@niner In your OpenSuse packages you did something else: '2022.03+git126.g320bc4c72'. It looks like you replaced the first '-' with '+git' and the following '-' with '.'. Is there a specific reasoning for this?

I know little about the build process of RPM packages, but I guess that there are mechanisms in place to allow to easily adapt version numbers, given how common the use case probably is.

**Comment by niner** [comment]
Yes, my script does: `RAKUDOVERSION=$(echo -n $RAKUDOGITVERSION | sed 's/-/+git/' | sed 's/-/./g')`
This is just the convention that openSUSE seems to use for git versions. Both `.` and `-` have meaning to rpm so we can't use them. Since this convention is known to work, I'd just use it for those Fedora packages as well. That said, @topazus you may as well take my packages directly: https://build.opensuse.org/repositories/devel:languages:perl6 I just enabled building on Fedora rawhide (other distro versions are just one click away, let me know). Rakudo builds fine, modules apparently need some minor adjustments to the spec files.

**Comment by lizmat** [comment]
Closing assuming this is no longer an issue, please re-open if this assumption was wrong
