### ISSUE TITLE
Order of operands is different for exp and expmod

### ISSUE THREAD

**Issue by thundergnat** [rakudo/rakudo#5032]
Order of operands is different for exp and expmod.

```
say 2**7 % 10 # 8
```
Yep. great.

```
say exp(7, 2) % 10 # 8
```
Ok. <strike>Not sure why the exponent comes first but ok.</strike> Base comes second to allow for a default base of e. Ok, reasonable.

```
say expmod(2, 7, 10) # 8
```
Now wait a minute. How come the base and exponent are reversed from exp()? There are no default parameters for expmod() so why aren't the exponent and base in the same order as in exp()? If you are going to be inconsistent, don't be inconsistently inconsistent.

Don't really expect anything to change. Just grumbling about LTA behavior. :(

**Comment by vrurg** [comment]
The only one not kind of in line here is `exp` and it is for a reason. There is no way for different order in `2**7` and `expmod` ordering makes full sense with this respect.

But `exp` is primarily about `exp(7)` use, i.e. `e**7`. In this case `2` is just an optional substitution for `e`. I wouldn't be investigating this into the depths of `git log`, but my best guess would be that the other solution with multi-dispatch where a two-parameter candidate would provide the more common order of arguments wasn't implemented from optimization point view because multi-dispatching was way more expensive back then.

So, I'd say it's a kind of legacy we can live with. Especially with `2**7` in our disposal.

**Comment by thundergnat** [comment]
Not really an issue. No the place for grumbling.
