### ISSUE TITLE
Strange behavior of »--

### ISSUE THREAD

**Issue by frithnanth** [rakudo/rakudo#5057]
I was toying with the code shown in this blog post [Assuming optionality](https://gfldex.wordpress.com/2022/09/04/assuming-optionality/) and I realized that running the following one-liner repeatedly:

```bash
$ raku -e'my BagHash $a=‘Perl Weekly Challenge’.comb.BagHash»--;$a.keys.sort.say'
```

got me different results, such as:

```raku
(  e l)
(  W e l)
(  C e l)
```

OTOH, the following:

```bash
$ raku -e'my BagHash $a=‘Perl Weekly Challenge’.comb.BagHash;$a.keys.sort.say'
```

always returns the same result, so I guess that the problem lays with the '»--'.

I'm running Rakudo v2022.07 on Debian sid.

**Comment by lizmat** [comment]
Good catch!  This is indeed weird.

But the `>>--` appears to only be an issue when used when **creating** the BagHash.  This appears to always produce the same results (at least for me):

````
$ raku -e 'my $a="Perl Weekly Challenge".comb.BagHash; say $a; $a>>--; say $a'
BagHash( (2) C P W a e(5) g h k l(4) n r y)
BagHash(  e(4) l(3))

**Comment by frithnanth** [comment]
Yes, your version works fine here too!

**Comment by lizmat** [comment]
````
$ raku -e '(my $a=‘Perl Weekly Challenge’.comb.BagHash)»--; say $a'
BagHash(  e(4) l(3))
````
also does the right thing.

**Comment by lizmat** [comment]
Some progress: It turns out that in the case of the error, it is always the **first** key that is being decremented, that loses its decrement.  If that is one of the higher valued keys, then you won't notice it unless you actually look at the value.  If it is one the keys that has a value of `1`, it won't get removed.

**Comment by lizmat** [comment]
FWIW, this is the golf I'm working on ATM:
````
$ raku -e 'my $a:=‘Perl Weekly Challenge’.comb.BagHash.deepmap(&postfix:<-->); say $a'
````
as the `>>--` codegens to a calle to `deepmap`.

**Comment by lizmat** [comment]
Another datapoint: `.MixHash` has the same issue.

**Comment by lizmat** [comment]
````
$ raku -e 'my $a:=‘Perl Weekly Challenge’.comb.MixHash.deepmap(&postfix:<-->); say $a'

**Comment by lizmat** [comment]
Another Datapoint:
````
$ raku -e 'my $a:=‘Perl Weekly Challenge’.comb.BagHash.deepmap(&postfix:<++>); say $a'
BagHash( (2) C P W a e(5) g h k l(4) n r y)
````
Note that the increments somehow got lost  :-(

**Comment by lizmat** [comment]
Ok, finally got to the bottom of this: https://github.com/rakudo/rakudo/commit/63d03eb899

**Comment by lizmat** [comment]
See https://github.com/Raku/problem-solving/issues/345

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/d0ec99a861 changed the example:
````
$ raku -e 'my $a=‘Perl Weekly Challenge’.comb.BagHash»--;$a.keys.sort.say'
(  C P W a e g h k l n r y)
````
and this is correct, as the increments happen on the original `‘Perl Weekly Challenge’.comb.BagHash` and the *result* of `>>--` on that is stored in `$a`.  Since this has been specced as an object of the same type, but built on the **return value** of the operator, you effectively get the original `BagHash` and the decrements were done on the original `BagHash` object, which is not saved anywhere and therefore lost.

Adding parentheses to make sure that `$a` is bound **before** running `>>--`, makes the example run reliably now with the expected result:
````
$ raku -e '(my $a=‘Perl Weekly Challenge’.comb.BagHash)»--;$a.keys.sort.say'
(  e l)
````
So I'm now closing this issue, now that we hopefully have full clarity on the issue at hand, and its resolution.
