### ISSUE TITLE
Is it valid to use zef install --to=home for multiple rakudo installations?

### ISSUE THREAD

**Issue by melezhik** [rakudo/rakudo#5145]
Hi! I am note sure this is complete zef question, so writing here.

My scenario:

1. install rakudo version X:

```
version=X
curl -sL https://rakudo.org/dl/rakudo/rakudo-moar-$version-01-linux-x86_64-gcc.tar.gz \
-o rakudo-moar-$version-01-linux-x86_64-gcc.tar.gz
tar -xzf rakudo-moar-$version-01-linux-x86_64-gcc.tar.gz          
eval "$(rakudo-moar-$version-01-linux-x86_64-gcc/scripts/set-env.sh)"
```

and then install _some_ M module for this rakudo using zef install -to=home:

```
zef install M --/test --to=home
zef test .
```
So we end up installing module M and it's dependencies to `~/.raku`path

2. do the same for the same module M, but for rakudo version Y

So, this is how testing for multiple rakudo versions now works in SparrowCI, for example - https://ci.sparrowhub.io/report/2296

I've noticed that a module test time for the **Rakudo that comes first** (does not matter which version is used) is always SIGNIFICANTLY less then for the same tests carried out for the following Rakudo version. And I don't understand why it is.

So the question is it a valid  approach. I heard that "if a Rakudo version is changed ones need to recompile all existing modules ... ( which does not happen as I only switch rakudo by using `eval "$(rakudo-moar-$version-01-linux-x86_64-gcc/scripts/set-env.sh)")` , or may be I just missing the point ...

Thanks

**Comment by melezhik** [comment]
add @ugexe

**Comment by patrickbkr** [comment]
IIUC the behavior you describe correctly then I think the following happens:

- zef install M --to=home # This installs and precompiles the module M with the currently active Rakudo version.
- run some tests
- Switch the rakudo version
- zef install M --to=home # This is basically a no-op as that module is already installed. Module installations are cross-usable with different rakudo installations.
- run some tests # As the precomp files of module M don't fit to the compiler version they are precompiled again on the fly. That's why you observe higher running times.

What I'm unsure about: Do precomp files compiled with different Rakudo versions have the same hash and overwrite each other, or does the entire dependency chain factor into the hash which would mean that the precomp files are preserved and one could switch back and forth between versions without having to re-precompile every time?

@ugexe Do you approve of the above thesis?

**Comment by niner** [comment]
precomp files are stored in a directory structure with paths like
`<compiler-id>/<precomp-id-prefix>/<precomp-id>`, so precomp files for the 
same source but different compilers do not conflict.

**Comment by melezhik** [comment]
So I’m other words the approach I use is correct and I don’t have to change anything here ?

**Comment by melezhik** [comment]
> run some tests # As the precomp files of module M don't fit to the compiler version they are precompiled again on the fly. That's why you observe higher running times.

does this happen during zef test . stage ? I can have this precompilaton stage as a separate zef step , I want to measure pure tests time , that does not include precompilaton ….

**Comment by jonathanstowe** [comment]
> I want to measure pure tests time , that does not include precompilaton ….

I guess you could make a thing that reads the dependencies from the META6 and then "warms them up" by _require_  for instance.

**Comment by patrickbkr** [comment]
I think `raku -c` can be used to compile but don't run.
