### ISSUE TITLE
Inconsistency with \c[] and \C[] if multiple characters

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#5155]
````raku
% raku -e 'say ",🦋" ~~ / \c[COMMA, BUTTERFLY] /'
｢,🦋｣
% raku -e 'say "ab" ~~ / \C[COMMA, BUTTERFLY] /'
｢a｣
````
The documentation states:
> \c takes a parameter delimited by square-brackets which is the name of a Unicode character as it appears in the [Unicode Character Database (UCD)](https://unicode.org/ucd/) and matches that specific character.

and:

> \C matches a single character that is not the named Unicode character.

If it only matches a single character, what is the meaning of specifying multiple characters?  The first case it basically looks like `\c[COMMA, BUTTERFLY]` is long for `,🦋`, or `\C[COMMA] \C[BUTTERFLY]`, whereas `\C[COMMA, BUTTERFLY]` is just another way of saying `\C[COMMA] | \C[BUTTERFLY]`.

This feels inconsistent.

If the `\c[COMMA, BUTTERFLY]` case is deemed incorrect, and it is a bug in the NQP regex engine, we could workaround in RakuAST by adapting the `RakuAST::Regex::CharClass::Specified.new` method somehow.

**Comment by lizmat** [comment]
It appears that `\x` has the same issue:
````raku
% raku -e 'say "ab" ~~ / \x[61, 62] /'
｢ab｣
% raku -e 'say "AB" ~~ / \X[61, 62] /'
｢A｣
````

**Comment by vrurg** [comment]
While it is fresh in memory: https://irclogs.raku.org/raku/2023-01-13.html#15:41-0001

Yet, despite I'd prefer things to be the way I said on IRC, there is another view to the issue. According to the specs and, if the memory serves me right, to the docs as well, `\c[P1, P2]` stands to a sequence of codepoints. They may or may not form a single grapheme, it doesn't matter.

For this reason the correct behavior would be for `\c` and `\x` cases. Since there is no stringification specification possible for the negations, their definitions could differ, but should they? Unfortunately, I don't remember if we have a regex notation for "anything but a string", so would use a complicated notation of `"AB" ~~ / .. <?{ $/ ne "ab" }> /` for what `\X[P1, P2]` is expected to do.

**Comment by lizmat** [comment]
So, the problem is really if the given sequence did **NOT** result in a single grapheme.  It should not allow that.

**Comment by vrurg** [comment]
For `\c` it would then mean different behavior depending on context which is not very good. Would that control be regex-specific I'd be just happy about this limitation, but not when we use the same for strings and have it working there perfectly well.

Negation could be limited to a single-char, but this would make it distinct from the positive match and that'd be another source of confusion. 

So, for where we are now it is better to fix it as a bug.

**Comment by lizmat** [comment]
I have code to just limit this to regexes, but this for some reason makes RakuAST very unhappy  :-(   Enough for me to have to nuke my install dir.
