### ISSUE TITLE
where-clause in subset does not work with Block/Callable

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#5175]
```
subset IntCallabel of Block where *.signature ~~ :(Int);

sub foo(IntCallabel \c) { }

sub works(Int $i) { }

foo(&works);
```
OUTPUT:
```
Can only use dispatcher-track-attr on a P6opaque
  in sub foo at rakudobug/tmp.raku line 3
  in block <unit> at rakudobug/tmp.raku line 7
```

The same happens with a block instead of the Whatever. I didn't check against the RakuAST branch.

## Environment
* Operating system: Linux dexhome 5.18.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.14-1 (2022-07-23) x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo™ v2022.12-1-gd52342eb0. Implementing the Raku® Programming Language v6.d. Built on MoarVM version 2022.12.

**Comment by ab5tract** [comment]
Just checked and this is also an issue on the RakuAST branch with the new subset implementation. This suggests the problem/fix is somewhere in the metamodel code itself.

**Comment by ab5tract** [comment]
This appears to be `WhateverCode` specific, as the following version of the subset works fine:

```
subset IntCallable2 of Block where { .signature ~~ :(Int) };
sub foo(IntCallable2 \c) { }
sub works(Int $i) { }
foo(&works);
```

Even though the `WhateverCode` stack in RakuAST has been massively overhauled, the behavior there has not changed (ie, it still fails).

It's failing in MoarVM's `MVM_disp_program_record_track_attr` where it fails the check that ensures `MVM_REPR_ID_P6opaque` because the representation ID is `MVM_REPR_ID_Uninstantiable` (`10`) instead.

**Comment by ab5tract** [comment]
I've created a (non-exploding) golf that demonstrates the issue:

```
> with -> Int $ {} { { .signature ~~ :(Int) } ?? say "yeah" !! say "no" }
yeah
> with -> Int $ {} { *.signature ~~ :(Int) ?? say "yeah" !! say "no" }
no
```

It appears to be an issue with the thunking of blocks into `WhateverCode`.

For example, according to the general rules of `Whatever` thunking, the following should probably work:

```
> with -> Int $i { $i } { *.(5) == 5 ?? say "yeah" !! say "no" }
No such method 'CALL-ME' for invocant of type 'Whatever'
  in block <unit> at -e line 1
```

**Comment by ab5tract** [comment]
Here's an even clearer demonstration:

```
> ./rakudo-m -e 'dd (*.signature)(-> Int $ {})'
:(Int $)
> ./rakudo-m -e 'dd (*.signature ~~ :(Int))(-> Int $ {})'
No such method 'CALL-ME' for invocant of type 'Bool'
  in block <unit> at -e line 1
```

**Comment by ab5tract** [comment]
@gfldex It appears that this is intentional behavior, as `&infix:<~~>` is special-cased to only curry `Whatever` and not `WhateverCode`.

The error message is less than awesome in both your original bug report but also in the later examples I've added. I will look into addressing that.

For this use case, it appears that your two options are:

1. `subset S where *.signature.ACCEPTS(:(Int))`
2. `subset S where { .signature ~~ :(Int) }`

**Comment by ab5tract** [comment]
There is now a clear indication to the user that they may be holding the `WhateverCode` expression wrong.
