### ISSUE TITLE
`Date('2023-03-17') ~~ DateTime('2023-03-17') # False`

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#5232]
## Problem

The original problem that led me to open this issue was an infinite loop mentioned in a SO: https://stackoverflow.com/questions/75730695/is-date-new-datetime-new-a-valid-syntax

It boils down to:
```
say Date('2023-03-17') ~~ DateTime('2023-03-17'); # False
```
Before Liz's https://github.com/rakudo/rakudo/commit/31779f4701797bfb4e9ea980eb5ad300b6e74797 response to #5001, the `DateTime('2023-03-17')` would have been an error. I think Liz did the right thing, but I think the same reasoning (first, ISO allows just a date, and second, a naive user would expect the above to work) suggests to me it would be best if the above evaluated to `True`.

**Comment by 2colours** [comment]
Fun(?) fact: `DateTime('2023-03-17') ~~ Date('2023-03-17')` yields `True`. That direction has an [explicit overload to cover this exact case](https://github.com/rakudo/rakudo/blob/704a05b934ba10f3240e8764827bbfd7fe089cdf/src/core.c/Date.pm6#L392).

Now, I think the situation isn't all that trivial... there is no hierarchic relation between `Date` and `DateTime`, they are sibling types, with the common `Dateish` role. Smartmatching doesn't have semantics set to stone but it's generally not a coercive equality check, at least. Usually, the broader thing is on the right handside, like you write `5 ~~ Int` to mean "is 5 an Int" - `Int ~~ 5` would be `False`. It makes sense that a point in time *belongs to* a date, which is the covered direction.

An important question is: how do we feel about `Date('2023-03-17') ~~ DateTime('2023-03-17T12:13:14')`? Right now, I feel that's rightfully `False`. If it appeared in a given-when structure, I wouldn't want `when DateTime('2023-03-17T12:13:14') {}` to execute for `Date('2023-03-17')`. Based on this, I would say `Date('2023-03-17') ~~ DateTime('2023-03-17T00:00:00')` shouldn't be any different, and `DateTime('2023-03-17')` is a mere shorthand for that, not something distinguished, right?

I think, overall "the solution" would be to start to work out general rules for smartmatch semantics. The current patterns I can think of, rather tell me that the current return value is right.

**Comment by raiph** [comment]
@2colours

> `DateTime('2023-03-17') ~~ Date('2023-03-17')` yields `True`.

Right. While it's "scary" to throw away the timezone offset, if a user has written such code then it's presumably what they wanted to happen, and those who made it work presumably considered it a [sufficiently safe DWIM](https://stackoverflow.com/questions/44101411/is-that-a-raku-hash-or-block#:~:text=3%20WAT%20refers,to%20this%20question.) despite the inevitable WATs.

> Now, I think the situation isn't all that trivial

Oh it's most assuredly not trivial. There was a 2 day delay between my posting my SO answer and filing this issue and there's been 2 weeks of delay between your comment and this reply. There are technical issues, community issues, all kinds of stuff to triangulate.

> there is no hierarchic relation between Date and DateTime, they are sibling types, with the common Dateish role.

Right.

And with good reason; to a large degree they are completely different things and the default notion should be to keep them apart unless we're so confident that a given DWIM that glosses over their differences will be a sufficiently safe DWIM that we decide to go that route.

> Smartmatching doesn't have semantics set to stone but it's generally not a coercive equality check, at least.

Not necessarily equality, no. But appropriate coercion is a staple of smartmatching, no?

I was so surprised by what you wrote I had to do a quick sanity check. The first couple examples I considered were numbers (which was the first example off the top of my head) and `Baggy` (which was the first one listed by the doc). The instance versions of both were a type specific coercive check (with numbers being numeric equality and bags being coercion to a bag and then equal elements).

These first (only) two (counter) examples don't prove the general point that your assertion is off, but still, Raku embraces the strength of appropriate weak typing over the weakness of inappropriate strong typing, and weak typing (coercion) is surely a core element of the very concept of smartmatching, no?

> Usually, the broader thing is on the right handside, like you write `5 ~~ Int` to mean "is 5 an Int" - `Int ~~ 5` would be `False`.

Agreed.

> It makes sense that a point in time belongs to a date, which is the covered direction.

Nooo. A point in time does not belong to a date that doesn't include a timezone. Right now my day (locally) is Friday, 7th April, 2023, but after 11pm. If you read this at this exact same instant it will not be the same date where you are if you're just one hour away timezone-wise.

> An important question is: how do we feel about `Date('2023-03-17') ~~ DateTime('2023-03-17T12:13:14')`? Right now, I feel that's rightfully `False`. If it appeared in a given-when structure, I wouldn't want when `DateTime('2023-03-17T12:13:14') {}` to execute for `Date('2023-03-17')`. 

Agreed.

> Based on this, I would say `Date('2023-03-17') ~~ DateTime('2023-03-17T00:00:00')` shouldn't be any different, and `DateTime('2023-03-17')` is a mere shorthand for that, not something distinguished, right?

Well it shouldn't be any different in *logic*, if that's what you mean. But it *is* a different *time*. It's `00:00:00`, not `12:13:14`. And that's the time component given to a `Date` when it's coerced to a `DateTime`.

So **if** we decide Liz did the right thing by making `DateTime('2023-03-17')` work, and assume `00:00:00` as its time, and whatever timezone is assumed, then it seems to me that a naive user would expect `Date('2023-03-17') ~~ DateTime('2023-03-17')` to evaluate to `True`, and that the best thing we can do is to make it so.

If we decide Liz did the right thing but we *don't* want `Date('2023-03-17') ~~ DateTime('2023-03-17')` to smartmatch, then we have two problems that should probably be addressed:

* The smartmatch won't DWIM for average users and we need an appropriate way to explain that in doc and/or warn at runtime or whatever.

* The sequence will continue to infinitely loop, and again we need an appropriate way to explain that in doc and/or warn at runtime or whatever.

Finally, if we're wondering if Liz's PR was a mistake, then I propose we review the reddit thread that led to Liz's PR.

> I think, overall "the solution" would be to start to work out general rules for smartmatch semantics.

The #1 principle is that smartmatch is the ultimate DWIM construct. That's its raison d'etre.

The #1 thing to read to see Larry's thinking about this is [Smart matching](https://design.raku.org/S03.html#Smart_matching). In particular:

> smart matches are dispatched first on the basis of the pattern's form or type ... and then that pattern itself decides whether and how to pay attention to the type of the topic.

> The `Any` entries in the first column indicate a pattern that either doesn't care about the type of the topic, or that picks that entry as a default because the more specific types listed above it didn't match.

I note that that last sentence provides data about smartmatch coercion because the `Any` cases imply coercion if any specific types handled by a smartmatch don't match. In that table there is only *one* type that does *not* imply coercion (`Capture`).

----

Two final resources to pay attention to are:

* [Temporal](https://design.raku.org/S32/Temporal.html).

* [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339).

**Comment by 2colours** [comment]
> Nooo. A point in time does not belong to a date that doesn't include a timezone. Right now my day (locally) is Friday, 7th April, 2023, but after 11pm. If you read this at this exact same instant it will not be the same date where you are if you're just one hour away timezone-wise.

I find this statement weird. If _neither the time point, nor the date_ contains a reference to a timezone, they should be assumed to have the same reference.

**Comment by 2colours** [comment]
> I was so surprised by what you wrote I had to do a quick sanity check. The first couple examples I considered were numbers (which was the first example off the top of my head) and Baggy (which was the first one listed by the doc). The instance versions of both were a type specific coercive check (with numbers being numeric equality and bags being coercion to a bag and then equal elements).

> These first (only) two (counter) examples don't prove the general point that your assertion is off, but still, Raku embraces the strength of appropriate weak typing over the weakness of inappropriate strong typing, and weak typing (coercion) is surely a core element of the very concept of smartmatching, no?

Can you show what you mean?

I think, if there is a main "governing rule" to smartmatching, it's that it is used in `given-when`, and the weaker descriptive statement that it's _not commutative_. If you want an equivalence check, that was meant to be the `eqv` operator.

There are two "statements" here to take a stance on:
1. particular coercions from one type to another
2. the intended role of coercions to comparing relations, especially smartmatching in our case

I have the impression that I might "disagree with you" (if this framing even makes sense here) on both cases. I think there are many coercion rules that just weren't very well reasoned. `List`s turning into numbers as their length comes to mind first. And then still, even if I think an _explicit conversion_ from `Date` to `DateTime` as that date, with 00:00:00 set within the day, might be fine - I don't think it would follow that the smartmatch should succeed.  
If you got a `Date`, to _implicitly_ accept that as a certain very specific time... there are several better ways to write that. Either do the conversion explicitly, or match against the corresponding `Date` value rather than a very carefully chosen `DateTime` value - and then I intentionally left out the case of "just swap the arguments", because preferably one should know the asymmetry between the two arguments.

> it seems to me that a naive user would expect Date('2023-03-17') ~~ DateTime('2023-03-17') to evaluate to True, and that the best thing we can do is to make it so.

I think it was @b2gills who regularly made the oppositional statement: "it's okay to surprise a beginner but it's not okay to surprise an expert". Frankly, I think these are two extremes:
- we cannot keep telling people to [git gud](https://knowyourmeme.com/memes/git-gud) every time something has an obscure, complicated, unintuitive logic
- we also cannot take everything somebody doesn't get for first as a moment when we need to adapt to them

There needs to be a balance between accepting user feedback and willingness to educate people based on what we believe to be "the right thing". I don't think there is anybody who is confident about the principles of smartmatching, and I'm not convinced for one that `Date('2023-03-17') ~~ DateTime('2023-03-17')` is based on an expectation that is worth acting upon. `X('value') ~~ Y('value')` isn't always `True`, and then I'm not sure what makes the expectation justified.

**Comment by b2gills** [comment]
While I did often write "it's okay to surprise a beginner but it's not okay to surprise an expert"; I did not come up with that. It was from Larry in one of the apacalypses.  I think I would amend that to say "it's okay to [occasionally] surprise a beginner but it's not okay to surprise an expert"

Having DateTime/Date coerce in a smartmatch may fail on both accounts if not thought through carefully.

**Comment by raiph** [comment]
> If neither the time point, nor the date contains a reference to a timezone, they should be assumed to have the same reference.

A `DateTime` always has a reference to a timezone.

A `Date` never has a reference to a timezone.

**Comment by raiph** [comment]
> I think, if there is a main "governing rule" to smartmatching, it's that it is used in given-when

What do you mean? Do you just mean we can pick that and not worry about other use cases like smartmatch operator (`~~`), sequence endpoints (which is what led to the infinite loop that led me to file this issue), `where`, and routines that use smartmatching such as `grep`?

> Either do the conversion explicitly, or match against the corresponding `Date` value rather than a very carefully chosen `DateTime` value.

OK. But what are you proposing is done with `$Date ~~ $DateTime` (where the variables are instances of the types in their name)? Should it be a runtime error, `False`, or something else?

>> it seems to me that a naive user would expect Date('2023-03-17') ~~ DateTime('2023-03-17') to evaluate to True...

That misrepresents what I wrote. I allow that that might have been a mistake, but I'm not going to engage with discussion based on a mistake.

> There needs to be a balance between accepting user feedback and willingness to educate people based on what we believe to be "the right thing".

Good to hear you're getting with the program. :)

> I'm not convinced for one that `Date('2023-03-17') ~~ DateTime('2023-03-17')` is based on an expectation that is worth acting upon.

When I filed this issue I had become convinced it should not be `False`, and should instead be either a runtime error or `True`. After the discussion we've had so far that remains my view.

**Comment by 2colours** [comment]
> While I did often write "it's okay to surprise a beginner but it's not okay to surprise an expert"; I did not come up with that. It was from Larry in one of the apacalypses. I think I would amend that to say "it's okay to [occasionally] surprise a beginner but it's not okay to surprise an expert"
> 
> Having DateTime/Date coerce in a smartmatch may fail on both accounts if not thought through carefully.

To be frank, these quotes from Larry (I've never heard this one from anyone but you, for what it's worth) are like biblical quotes: you can prove or disprove anything by choosing the quotes that fit your narrative. There is also one about fixing the language rather than the user. From what I see, you have used this quote for [justifying something that had reasonable counter-arguments](https://github.com/Raku/doc/issues/1428#issuecomment-323535758) and [never has been actually implemented](https://github.com/Raku/problem-solving/issues/351#issuecomment-1312418494).

All in all, I think it's the polar opposite of "this should DWIM more" but both are rather vague stances; hopefully they can at least be used to balance each other.

**Comment by 2colours** [comment]
> > If neither the time point, nor the date contains a reference to a timezone, they should be assumed to have the same reference.
> 
> A `DateTime` always has a reference to a timezone.
> 
> A `Date` never has a reference to a timezone.

On one hand, I can see how this could cause problems in general, with any intermixing of the two types.
On the other hand - isn't this yet another reason why `some-date ~~ some-datetime` should never become `True`? If there is one more thing that restricts the validity of a `DateTime` that we would have to imply for a `Date`?

> What do you mean? Do you just mean we can pick that and not worry about other use cases like smartmatch operator (`~~`), sequence endpoints (which is what led to the infinite loop that led me to file this issue), `where`, and routines that use smartmatching such as `grep`?

Let's clarify what "worrying about other use cases" means.

I think when you worry about the infinite loop, that has nothing to do with smartmatching. `1, 2 ... 'almafa'` will also be an infinite loop. If the community decides that an infinite loop is not what should happen when the terminal condition never matches (by the way, it's quite funky that `1, 2 ... 0` is an empty sequence - perhaps these inconsistencies are more bothersome), that can be addressed. From all I can see, that SO sequence led to an infinite loop _because the code was faulty_. You could have said that just as much as "the smartmatch doesn't do what people expect it to". Next time they will know and won't make the same mistake, that can also be a resolution. Or we can propose a change that never-matching conditions also shouldn't lead to an infinite loop; not sure how that would work but in theory one could.

This is kind of besides the point and I don't know if I heard this from someone or just concluded it on my own but `~~` tends to be code smell. It's a jack of all trades and a master of none. Maybe its most fitting use is for type checks. Also, `m//` and `s///` kind of structures do more harm than good: they are hacked into the same smartmatching process, therefore [we cannot have meaningful smartmatching on match objects](https://github.com/rakudo/rakudo/blob/2022.12/src/core.c/Match.pm6#L242), they always return the right handside, not even a `Bool`! (Actually, for the same reason, Lists that contain Match objects also need to be hacked.) I'm still hoping that these "regex quotes" can be supported by a logic that doesn't break down to the usual `ACCEPTS` way at all. They _are_ special so they should be special-cased, rather than trump general smartmatching semantics.

For `where` clauses and matchers as callbacks to higher-order functions - what's the "worry"? Semantically, they are equivalent to `given-when`. If you know about a case where you want different behavior for certain data in a `where` clause, or a `grep`, and `given-when`, please do tell. I don't see any conflict between these.

> OK. But what are you proposing is done with `$Date ~~ $DateTime` (where the variables are instances of the types in their name)? Should it be a runtime error, `False`, or something else?

I think it can stay the way it is. Maybe one can add a warning for this particular case, "to please everyone" (smartmatching to `Bool` does give you a warning, although the reason is much more serious in that case). 
Throwing an error would go against the conventions. I think it can be taken as an "apples to pears" case, or at least an `Int ~~ 5` case.

> When I filed this issue I had become convinced it should not be `False`, and should instead be either a runtime error or `True`. After the discussion we've had so far that remains my view.

Well, I'm not convinced but also not surprised that _I_ couldn't change your mind. It rather seems to me that _you yourself_ brought up things that would have changed _my mind in your place_. :P I can recite my thought pattern ("a time belongs to a date but a date doesn't belong to a time") but I guess that won't convince you just by repetition. It would be good to know how you would interpret that `True` value, i.e what question would it answer?

Is it coercion to rhs and then equivalence check? That's not how `List`s or `Array`s work, for example. If we are going to respect the status quo, I think that's a serious enough counter-example. If we aren't, I would say `<a b> ~~ 2` (and the `Numeric` coercion of `List`s in general) does more harm than good and we should rather push _away from_ coercions, _for an operator that doesn't have well-defined semantics_. I think it was Jonathan Worthington who said: if you do both overloading _and_ coercion, chaos arises. `~~` is this kind of operator... somewhat. Perhaps we should lower this chaos, not add to it.

**Comment by ab5tract** [comment]
I for one find @2colours position quite convincing. It's true that the original change "broke" `Temporal` by having a `DateTime` that doesn't have a timezone, but I don't see that as a very strong argument against the solidity of "a time belongs to a date but a date doesn't belong to a time".

From a DWIM/user expectations perspective, perhaps what we should provide for new users is an `annotations` pragma that can provide runtime worries to the user when they get into curious corners of syntax.

**Comment by lizmat** [comment]
Closing as the discussion has wandered.  Please re-open as a problem solving issue if so deemed necessary.

**Comment by raiph** [comment]
Hi @ab5tract,

I'm pondering re-opening this as a PS issue. It would be helpful to me if you helped me understand if there's any common ground between our viewpoints.

> I for one find @2colours position quite convincing. 

There was a whole lot of ground covered in this thread. So I'm unsure which part you mean. But it sounds like it might be just "a time belongs to a date but a date doesn't belong to a time".

Given that that's a simple formulation that's now been repeated three times, and I still disagree with it, let's see if we can come to some common ground related to that. If we can't, then it seems unlikely anything else is going to work out.

I'll describe my view; hopefully you will understand my view; then hopefully you can comment in some way that progresses us toward a unification of our positions.

First, there's reality. At this moment in time, as I write this paragraph, my computer says it's 11:45pm on the 20th of October 2024, and my friend, who lives in Sydney Australia, is telling me that it's the 21st and they ate breakfast after they got up a couple hours ago, around 7:30am.

Because I don't see time as belonging to a date, singular, I don't find it confusing that "now" belongs to at least two different dates (and sometimes three, depending on the locations involved).

But you're saying it belongs to a date, singular. So which date should right now belong to? For example, you presumably think the time right now, as you read this sentence, is such-and-such. Which date does it belong to?

Second, there's Raku's built in data types. If time belongs to a date, why don't Raku's `Date` and `Dateish` types, which both model a _date_, optionally store a time field?

Third, there's the built in type `DateTime` that models a date/time combination. Note this comparison:
```
DateTime('2024-10-20T23:45:00+0000') ~~ DateTime('2024-10-21T09:45:00+1000')
```
The dates are different. If a time belongs to a date, then surely this comparison should return `False`. How come it returns `True`?

----

Thanks in advance for reading this far and working through this!
