### ISSUE TITLE
Using a backreference in a regex only works when there's no extra capture

### ISSUE THREAD

**Issue by moritz** [rakudo/rakudo#5248]
## The Problem

The regex

```
"aa" ~~ /$<start>=<alpha> $<start>/
```
doesn't match

## Expected Behavior

It should match

## Actual Behavior

It doesn't

## Steps to Reproduce

Run the code above

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo™ v2022.02.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.02.

(Yes, that is ancient, but evalbot in #raku on 1fd667cf7 exhibits the same behavior

## Context

The curious part is that it matches as expected if you write it as `$<start>=<.alpha> $<start>` (so you suppress the capture of the `alpha` rule).

The other curious thing is that if you you shove in a debug print between the capture and backreference, you get identical output both in the working and in the non-working case:

```
$ raku -e '"aa" ~~ /^$<start>=<alpha> { say $<start>.perl } $<start>/'
Match.new(:orig("aa"), :from(0), :pos(1))
$ raku -e '"aa" ~~ /^$<start>=<.alpha> { say $<start>.perl } $<start>/'
Match.new(:orig("aa"), :from(0), :pos(1))
```
```

**Comment by vrurg** [comment]
It's a long known non-critical problem. In a number of places in Rakudo's own grammar you can find use of empty blocks `{}`. This is due to `$/` being explicitly set before invoking a block, and you need `$/` for `$<token>` to work. The exact same reason is why adding debug printing makes it work for you.

For now you can use `{}` as a workaround. Otherwise I'm not sure anybody could soon get enough time to put their hands on regexes and grammars.

**Comment by lizmat** [comment]
Merged https://github.com/Raku/nqp/pull/802 and bumped with https://github.com/rakudo/rakudo/commit/8826b839c3

**Comment by jnthn** [comment]
Did it get a spectest?

**Comment by lizmat** [comment]
Will add one in a mo

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/7fad7bed8f
