### ISSUE TITLE
moar.dll: Windows build fails for the latest 2023.05 release

### ISSUE THREAD

**Issue by AntonOks** [rakudo/rakudo#5281]
## The Problem
- moar.DLL and therefore the Rakudo Windows build fails for the latest release 2023.05... maybe due to some "libuv" changes?
- See https://github.com/rakudo/star/actions/runs/5150349749/jobs/9274377740#step:5:1005 for detailed build error logs...

## Expected Behavior
- Windows release of 2023.05 builds successfully :)

## Steps to Reproduce

- I guess currently no windows releases are build nowhere on none of the different used build infra's....

**Comment by patrickbkr** [comment]
This has been fixed in https://github.com/MoarVM/MoarVM/commit/278af767496430b8e2d36a1ed241b3c00aae75ef but no intermediary release has been made yet. There is an unsolved build issue on Linux as well. Given the next release is only two weeks away, I tend to just get the Linux build issue solved by then and get a proper 2023.06 out.
Do you agree?

**Comment by patrickbkr** [comment]
2023.06 has been released with the respective fixes. Thus I'm closing this.
