### ISSUE TITLE
Constraint rejects value for @-sigiled parameter when it shouldn't

### ISSUE THREAD

**Issue by landyacht** [rakudo/rakudo#5313]
## Expected Behavior
An anonymous constraint on the type(s) of an `@`-sigiled parameter's elements should succeed when the elements are of the correct type

## Actual Behavior
Fails with message saying the constraint was not met 

## Steps to Reproduce
```
[0] > (Str.new,).all ~~ Str # Just as a baseline for expectations
True
[1] > sub foo(@args where *.all ~~ Str) { say 'success' }
&foo
[2] > foo((Str.new,))
Constraint type check failed in binding to parameter '@args'; expected anonymous constraint to be met but got List (("",))
  in sub foo at <unknown file> line 1
  in block <unit> at <unknown file> line 1
```

## Environment
* Operating system: Linux 5.10.76-gentoo-r1
* Compiler version (`perl6 -v` or `raku -v`): Rakudo™ v2023.04

**Comment by 2colours** [comment]
This is a `WhateverCode` problem.

`*.all ~~ Str` simply produces `False`, even though on their own `*.all` and `* ~~ Str` would both produce a `WhateverCode` instance.

Now, since it produces constant `False`, the function will never accept any arguments as valid.

To your particular problem: if you use a `Block` instead of the failing "whatever currying", it will work:

```raku
sub foo(@args where { .all ~~ Str }) { say 'success' }
foo((Str.new,)) # success
foo(('1', 2)) # Constraint type check failed (...)
```

**Comment by 2colours** [comment]
We already have an issue for this exact phenomenon: https://github.com/rakudo/rakudo/issues/2086

**Comment by librasteve** [comment]
no need for a block 

```
sub foo(@args where .all ~~ Str) { say 'success' }
foo((Str.new,)) #success
```

**Comment by landyacht** [comment]
@2colours yes, I think this can be closed
