### ISSUE TITLE
Rakudo incorrectly calls methods on Match subclasses (eg Grammars) instead of on Match itself

### ISSUE THREAD

**Issue by grondilu** [rakudo/rakudo#5443]
## The Problem

It seems the character class `print` (printable characters) is interpreted as a function inside a grammar and as a result it throws an exception.

## Expected Behavior

No exception thrown.

## Actual Behavior

Exception thrown:

    Cannot resolve caller print(Mu:U: <anon|1>:D); none of these signatures matches:
        (Mu: *%_)

## Steps to Reproduce

```raku
say grammar { token TOP { <print>+ } }.parse: "foo";
```

## Environment
* Operating system:  Fedora Linux 38 (Workstation Edition) x86_64
* Compiler version (`rakudo -v` or `raku -v`):

```console
$ raku -v
Welcome to Rakudo™ v2023.10-47-g5e3f8f333.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.10-2-g18604f691.
```

**Comment by 2colours** [comment]
Posting here as well: it's probably [this phenomenon](https://docs.raku.org/language/traps#Using_certain_names_for_rules/token/regexes) on steroids.

**Comment by 2colours** [comment]
Also, apparently this never worked. https://gist.github.com/Whateverable/623fe08f019f0f1595d665c4db8a54f0

In my opinion, the very principle that all methods available to a grammar implicitly sneak in and get to shadow grammar-related symbols is a serious issue that isn't properly remedied just by documenting it as a "trap"...

**Comment by codesections** [comment]
This issue was just productively discussed in the [#raku IRC channel](http://irclogs.raku.org/raku/2023-11-08.html#21:05-0001).  Based on that discussion (and, especially, helpful comments by @2colours and @ugexe) I'm pretty sure that the issue is that Rakudo should be calling `Match::print` specifically instead of calling any `print` method that might have overridden `Match`es `print`.  (And of course the same applies to pretty much every `Match` method that Rakudo calls – it pretty much _always_ wants to call the `Match` method specifically, not a user-defined one.  For another example of this causing problems, see [this Grammar::HTTP commit](https://github.com/ugexe/Raku-Grammar--HTTP/commit/210371b64dafcca7b4eecf450489d9a992388f27#diff-eaa4adc2ebf0875baae009d8c79d543d84a10cebc1e7580a9e259258718b68ad).)

I've edited the issue title to that effect, but please feel free to revert that change if my title doesn't capture the issue you're reporting.

**Comment by 2colours** [comment]
I still don't completely understand the suggestion. There is no `Match::print` for all I'm concerned. What actually gets called is probably the `print` method inherited from `Any`, and I don't know how the character class `<print>` that should be called instead is represented.

Actually, I do see some method names like `ws` for example in `Match.^methods` but I don't know how to even safely gather them.

In any case, even though I think it would be a clear improvement to at least get the method resolution order more useful inside grammars, I have the feeling that this would navigate us to a situation where more and more hacks are required. Even at the moment, it's plain obvious that _the vast majority_ of methods in `Match` are actual methods to be called by the end user, like `from`, `to`, `made`, `hash`, `Numeric` etc., or internal "magic methods" like `BUILD` and `WHICH` and all that jazz. I think this is the main problem and changing the method resolution rules doesn't really address it. Nobody has ever really wanted a declarative grammar-ish and an imperative method-ish interface to the very same token/regex/rule. These name collisions are completely unjustified, even if the effects are somewhat leveraged.

Therefore I still think, even if it isn't immediately possible and it is more of a design change in itself, that grammar-related declarative stuff should not just translate to a method with the very same name. I think we already have patterns that can be followed: I don't know what the accurate term is but I think of `trait_mod:<is>`, `infix:<eqv>`, `sym:<Z>`, `dispatch:<var>` kind of things. I don't know whether they should be translated into distinct `regex:<foo>`, `token:<bar>` things or have one common name overall (currently they would name-conflict anyway, right?) but that's more for the bike-shedding part.

That way, the implementations could still find the appropriate methods (in fact, it would have a more finegrained control over the resolution rules!), and so could the users, if they actually needed it once in a blue moon, without having to worry about name-collisions basically imposed them by Raku built-ins.

**Comment by codesections** [comment]
> There is no Match::print for all I'm concerned. 

Sure there is.  (Though admittedly it's slightly hard to find because `Match` is getting pretty close to nqp).  `Match.does(NQPMatchRole)`, which [defines a `print` method](https://github.com/Raku/nqp/blob/main/src/QRegex/Cursor.nqp#L1078-L1085).  And you can call it directly: `Match.new(:orig('foo').print` is just another way to write `'foo' ~~ /<print>/`.  (Or, to really see that `Match::print` exists, you can be more explicit: `Match.new(:orig('foo').Match::print`.)

And, indeed, we can do the same thing with grammars.  Let's start with `punct`, since it doesn't exhibit the bug that this issue is about.

```raku
grammar G { 
    token TOP { <.punct> }
}
G.parse('!')  # OUTPUT:  ｢!｣
```

is just a more expressive way to write

```raku
grammar G {
   method TOP { self.Match::punct }
}
G.parse('!')  # OUTPUT:  ｢!｣
```

And the same is true for `<print>` – except that with `<print>`, we don't get the same correct result; instead **due to a bug** we get the same error:

```raku
grammar G { 
    token TOP { <.print> }
}
G.parse('!')
```

is the same as

```raku
grammar G {
   method TOP { self.Match::print } # or just self.print
}
G.parse('!')
```

Both should match; instead, both throw the same error.  But that's just a bug (one that I'm pretty sure I've found in nqp; I'll have a PR shortly).

> it's plain obvious that _the vast majority_ of methods in `Match` are actual methods to be called by the end user, like `from`, `to`, `made`, `hash`, `Numeric` etc., or internal "magic methods" like `BUILD` and `WHICH` and all that jazz. 

Well, I don't want to quibble about what counts as "the vast majority", but `Match`es certainly have more than a few built-in tokens/rules in their method list (all of the built ins, in fact).  By my count, that's  `same`, `before`, `after`, `ws`, `ww`, `wb`, `ident`, `alpha`, `alnum`, `upper`, `lower`, `digit`, `xdigit`, `space`, `blank`, `print`, `cntrl`, `punct`, and `graph`.

> Nobody has ever really wanted a declarative grammar-ish and an imperative method-ish interface to the very same token/regex/rule.

Sure they have.  Maybe not in simple cases, but any time a token/rule/regex takes an argument, it was defined as a method in the grammar.  One idiom I've seen a fair bit (IIRC, in the book on Raku Regexes/Grammars, among other places) is to have an `error` method that takes accepts a `$msg` argument and then to call it with `<error("Specific error message")>` somewhere inside another token/rule.

In any event, I very much like the fact that tokens/rules/regexes are "just" syntactic sugar for method calls; imo, it makes them much easier to reason about.  But we can of course debate the merits of different design choices all day and night; hopefully, that won't distract from fixing what we can all agree to be bugs, such as the one @grondilu ran into.

**Comment by 2colours** [comment]
Frankly, I'm sick and tired that I bring all this evidence again and again and it just gets cut short by saying something akin to "I don't see the problem". The problem was apparent every single time somebody carelessly named a declarative grammar thingy the same way as any of the silently inherited methods in one of the most dense built-in type system across all programming languages. It should be this behavior that should justify itself to begin with.

**Comment by MasterDuke17** [comment]
> The problem was apparent every single time somebody carelessly named a declarative grammar thingy the same way as any of the silently inherited methods in one of the most dense built-in type system across all programming languages.

AIUI, nobody disagrees that this is a problem. I haven't looked at the new PRs closely enough to tell exactly what they do in this situation. @codesections if someone does `token from {}` after your PR, what will happen? Again, AIUI, we want to get to a place where "fixes" like https://github.com/ugexe/Raku-Grammar--HTTP/commit/210371b64dafcca7b4eecf450489d9a992388f27 aren't needed.

**Comment by raiph** [comment]
@codesections,

I haven't looked closely but a glance suggests this issue was ultimately a dupe of https://github.com/rakudo/rakudo/issues/1870,  and with liz's commit that older issue, and the one that came before it, https://github.com/Raku/old-issue-tracker/issues/5247, can be closed, right?

**Comment by codesections** [comment]
@raiph

Agreed

**Comment by raiph** [comment]
Heh. I don't have privs to close 1870. I do have privs to close the older one, and accidentally did, then reopened it because of the comment in it by zoffix that [this test](https://github.com/Raku/roast/commit/f4e2505dbc#diff-81a4bd9dd554cb996cbfeff6bdbfd12c5cfc50a1c9f2f2b1d3c88ce6bd46813bR63-R72) should be added to roast if it now works (which I'm thinking might be true due to liz's fix).
