### ISSUE TITLE
Rakudo should detect multi sub duplicates at compile time

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#5455]
This is the [oldest unsolved issue in the old-issue tracker.](https://github.com/Raku/old-issue-tracker/issues/1455). Won't try to summarize, because there's a lot of context there that could be lost.

**Comment by ab5tract** [comment]
I hope this is a decent enough exception text:

```
> ./rakudo-m -e 'multi foo(Int $a) { dd "a" ~ $a }; multi foo(Int $b) { dd "b" ~ $b }; foo(5)'
===SORRY!=== Error while compiling
Redeclaration of multi sub 'foo' with equivalent signatures would lead
to ambiguous dispatch:
	multi sub foo (Int $a) { #`(Sub|6285154414976) ... }
	multi sub foo (Int $b) { #`(Sub|6285154415104) ... }
at line
```

**Comment by ab5tract** [comment]
@JJ This is supposed to be a compile-time error, correct? Not simply a worry generated at compile-time?

**Comment by JJ** [comment]
According to the original post, yes, it should.

**Comment by ab5tract** [comment]
> According to the original post, yes, it should.
 
It seems that others have a contradicting opinion. @niner can you weigh in here?

From an implementation standpoint, this is the last bit of bike shedding necessary. Everything else is working as expected.

**Comment by niner** [comment]
Actually the original post only asks for us to "detect" or "catch" this situation. That we report it to the user is certainly implied. So it's asking at least for a Worry. It's then compared to e.g. calling an only sub with incompatible args. In this case we throw a Sorry, so that seems appropriate.

Alas, it was also brought up that for multi methods there are use cases where duplicates make sense and that they could still be called via `.*` or `.+`.  We also have syntax for calling subs as if they were methods, so these use cases could be extended even to subs. In that case `multi foo(Int $i) { say 1 }; multi foo(Int $i) { say 2 }; 1.*&foo` would simply call both candidates. However in the current implementation this also complains about ambiguous dispatch. Looking at the docs for `.*` and `.+` it strongly ties this feature to class hierarchies, basically doing one normal multi dispatch per parent class. If that's accurate, then yes, we're back to a Sorry being the right answer.

What it definitely, absolutely is not is a Panic. Panic means that there's no point in the compiler even trying to continue which is demonstrably false as the compiler right now continues quite successfully. It's only at runtime that we cannot escape the problem. What's the difference you may ask? The compiler may not just be used to create runnable code. It could be used for static analysis, code reformatting or cool things like [semantic patching](https://www.kernel.org/doc/html/latest/dev-tools/coccinelle.html).

**Comment by ab5tract** [comment]
If I I understand your point correctly: there _could be_ meaningful semantics for multi subs of the same signature (when called as methods) but since `.*` and `.+` are strongly tied to class hierarchies (at least in the current implementation), we should make this a Sorry. 


This is the current implementation in #5462.

An additional thought of my own: It can more easily become a Worry later than the other way around, should the implementation evolve to make same-sign multi sub dispatch sensible.

One advantage of using a Worry here, however, is that it require zero spec changes. That's partially irrelevant (having to make spec changes isn't a dealbreaker for using a Sorry) but it might be worth considering in terms of potential ecosystem impact.

**Comment by lizmat** [comment]
> One advantage of using a Worry here, however, is that it require zero spec changes.

I hadn't even thought about that aspect.  I like that as an extra reason for a worry rather than a sorry.

**Comment by niner** [comment]
On Tuesday, 7 November 2023 12:12:53 CET Elizabeth Mattijsen 
wrote:

> It can more easily become a Worry later than the other way 
around

Actually not, since currently the compiler does not even warn about 
duplicates. So there's bound to be code already that has them. 
Throwing a Worry about duplicates already is one step stricter than 
currently. At least people will have had some warning (literally) 
before we again tighten the screws when we promote the Worry to 
a Sorry.

**Comment by ab5tract** [comment]
Sounds like worry is the winner here.
