### ISSUE TITLE
Error when adding RakuAST QuantifiedAtom to regex

### ISSUE THREAD

**Issue by hythm7** [rakudo/rakudo#5479]
## The Problem
Getting `No such method 'made' for invocant of type 'Array'.` error when running the below code.
The error disappears if removed the quantifier from `<foo>` (tested quantifiers `?` and `*`)

```raku
#!/usr/bin/env raku 

my $grammar = q｢        
grammar G {
  token TOP {<foo>?} # error disappear when remove `?` 
  token foo { 'foo' }
}  
｣.AST.EVAL;         
     
my $actions = q｢
class A {
  method TOP ($/) { $<foo>.made }
}
｣.AST.EVAL;
   
$grammar.parse( 'foo', :$actions );

```
## Expected Behavior
No Error.
## Actual Behavior
Error.

## Environment
* Operating system: Linux
* Compiler version:
```
> raku -v
Welcome to Rakudo™ v2023.10.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.10.
```

**Comment by lizmat** [comment]
Simplified code to:
````raku
grammar G {
    token TOP { <foo>? } # error disappear when remove `?`
    token foo { 'foo'  }
}

class A {
    method TOP ($/) { { $<foo>.made }
}

say G.parse( 'foo', :actions(A) ).made;
````
Running this with `RAKUDO_RAKUAST=1` will cause the error.

Investigation into the value of `$/` inside method `A.TOP` reveals that in RakuAST this is `[Match.new...]`, rather than `Match.new...`.

So it looks like the `QuantifiedAtom` logic is assuming possible multiple matches, as opposed to a single match or no match.
