### ISSUE TITLE
Unable to run rakudo in chroot (without /proc)

### ISSUE THREAD

**Issue by andinus** [rakudo/rakudo#5598]
## The Problem

First posted on #raku,

> andinus ? i get "ERROR: Could not retrieve executable path." when trying to run rakudo, downloaded the binary from https://rakudo.org/downloads/rakudo - this is running inside a chroot, when i run `strace raku` - just before printing the error it tries to open /proc/self/exe - which is not available inside the chroot

Compiling Rakudo with `perl Configure.pl --backend=moar --gen-moar --prefix=/root/rakudo` a prefix works.

## Expected Behavior

I should be able to run the binary downloaded from https://rakudo.org/downloads/rakudo without mounting /proc in chroot.

## Actual Behavior

Unable to run the downloaded binary.

## Steps to Reproduce
- download rakudo binary from https://rakudo.org/downloads/rakudo
- create a chroot with jailkit
  - jk_init -j /jailtest interactiveshell
  - jk_jailuser -m -j /jailtest jailuser1
  - jk_cp -j /jailtest /path/to/downloaded/rakudo/binary (it copies the source to the same path inside chroot)

Now we have the binary inside chroot, connect to the chroot user. (ex. with SSH, note: directory and file permissions) and try to execute the binary, it fails with "ERROR: Could not retrieve executable path.".

## Environment
* Operating system: Ubuntu 24.04

**Comment by vrurg** [comment]
Any reason why you can't symlink /proc into the chroot dir? A lot of of applications require appropriate environment to be created for them in order to guarantee failure-free functionality.

In the particular case of Rakudo, barely much could be done because MoarVM backend is heavily dependent on libuv which is, in turn, dependent on /proc on far too many occasions. Once could `grep -w proc src/uniux/linux.c` inside libuv sources to see the whole picture.

I would consider this issue a bug. Would like to close it unless there are objections to this.

**Comment by andinus** [comment]
This was an external task, they really wanted to avoid linking `/proc`. No objections to closing the issue, I just wanted to highlight this. 

Related: https://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe

**Comment by andinus** [comment]
Why does a binary that I compile work and not the one downloaded from the website? IIRC if I move the self compiled binary, that too doesn't work. (I tried this a long time ago, not sure if it's still the case)

**Comment by vrurg** [comment]
There was a reason I suggested to do `grep` in libuv. `/proc` has wider usage than for locating binary path alone.

> IIRC if I move the self compiled binary, that too doesn't work.

See `--relocatable` switch of `Configure.pl`.
