### ISSUE TITLE
Regex :ignoremark does not apply to branches of an alternation

### ISSUE THREAD

**Issue by bluebear94** [rakudo/rakudo#5613]
## The Problem

The `:ignoremark` adverb on a regex is ignored for branches of an alternation.

## Expected Behavior

```
$ raku -e 'say "a_é" ~~ rx:i:m/<[aou]>_<[ei]>/'
｢a_é｣
$ raku -e 'say "a_e" ~~ rx:i:m/<[aou]>_<[ei]>|<[ei]>_<[aou]>/'
｢a_e｣
$ raku -e 'say "a_é" ~~ rx:i:m/<[aou]>_<[ei]>|<[ei]>_<[aou]>/'
｢a_é｣
```

## Actual Behavior

```
$ raku -e 'say "a_é" ~~ rx:i:m/<[aou]>_<[ei]>|<[ei]>_<[aou]>/'
Nil
```

## Environment
* Operating system: Linux x86_64 (EndeavourOS)
* Compiler version (`rakudo -v` or `raku -v`): v2024.06

**Comment by mustafaaydn** [comment]
hi, did you mean [`||`](https://docs.raku.org/language/regexes#Alternation:_||)?
```sh
$ raku -e 'say "a_é" ~~ rx:i:m/ <[aou]>_<[ei]> || <[ei]>_<[aou]> /'
｢a_é｣
```
`|` in other regex engines (sequential alternation) is `||` here. On the other hand, [`|`](https://docs.raku.org/language/regexes#Longest_alternation:_|) in Raku does something different ([longest token matching](https://perlgeek.de/en/article/longest-token-matching)), although i was unable to pinpoint why it chooses the right branch (or does something different?) in your example because they seem to be tied in terms of declarative prefix lengths and specificity.

**Comment by lizmat** [comment]
Closing as this appears to be a misunderstanding of `|` vs `||`.  Please re-open if this assumption is incorrect.
