### ISSUE TITLE
Map.keys Returns Surprising Result

### ISSUE THREAD

**Issue by kmazza2** [rakudo/rakudo#5668]
## The Problem
Creating a Map containing a Map as a value (corresponding to some key) then calling the "keys" method of the top-level Map produces a surprising result.
## Expected Behavior
REPL:
[0] > my $data := Map.new('key_1', Map.new('subkey_1','subval_1','subkey_2','subval_2'));
[1] > $data.keys 		
	(key_1)
## Actual Behavior
REPL:
[0] > my $data := Map.new('key_1', Map.new('subkey_1','subval_1','subkey_2','subval_2'));
[1] > $data.keys 		
	(subkey_1 key_1)

## Environment
* Operating system: Tested with both Mac OS Sonoma and Ubuntu 23.10
* Compiler version (`rakudo -v` or `raku -v`): Rakudo 2022.12

**Comment by lizmat** [comment]
This was a bit of a hunt  :-)

The problem is that `Map.new` has a signature of `*@args`, which has flattening semantics.  So the inner `Map` is being flattened into a list of `Pair`s, and that then becomes the value for "key_1".

The easiest way to prevent this from happening, is providing `Pair`s:
```raku
my $data := Map.new('key_1' => Map.new('subkey_1' => 'subval_1','subkey_2' => 'subval_2'));
```
Because `Pair`s are single entities, they won't get flattened.

Also, the `.Map` coercer does **not** have flattening semantics, so you can do:
```raku
my $data := ('key_1', ('subkey_1','subval_1','subkey_2','subval_2').Map).Map;
```

I also looked at changing the signature of `Map.new`, but that causes too much spectest fallout.

**Comment by melezhik** [comment]
@lizmat  the issue is closed as it's not an issue right?

**Comment by lizmat** [comment]
Somewhere in the mist of time, it was decided that `Map.new` would have flattening semantics.  If you flatten a `Map`, you get a list of `Pair`s in random order.  When you have a `Map` as a value of a `Pair`, then the first `Pair` of the `Map` will become the value of that key.  Any subsequent `Pair`s will arrive in the Map storing logic, and since they are `Pair`s, will be stored as key/value.

So: `Map.new( "a" => Map.new( "b" => 2, "c" => 3 ))` will be handled as:
```raku
my %m;
%m<a> = "b" => 2;
%m<c> = 3;
```
or if the order of `Pair`s in the inner `Map` is reversed:
 ```raku
my %m;
%m<a> = "c" => 3;
%m<b> = 2;
```
Hope this made sense.

The only way to fix this, is to change the signature of `Map.new`, but that causes sigificant spectest fallout.
