### ISSUE TITLE
Extremely nested hash causes bytecode validation error

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#5733]
## The Problem

When doing `%x<x><x><x><x>... = 1`  with enough depth a bytecode validation error can occur:

```
raku -e 'my $runme = "runme.raku"; my $h = $runme.IO.open(:w); $h.write(q|my %x; %x|.encode); my $d = q|<x>|.encode; for 1..1000000 { $h.write($d); }; $h.write(q| = 1; say %x.keys;|.encode); say "running generated code now..."; say so run $*EXECUTABLE.absolute, $runme; say "finished";'
```
```
running generated code now...
Bytecode validation error at offset 1310906, instruction 196633:
operand type 64 does not match register type 56 for op getlexstatic_o in frame <unit>

False
finished
```

**Comment by timo** [comment]
The code we generate for this uses one local variable for each of the calls to `&postcircumfix:<{ }>`, and we can only address locals up to index 65534, and we don't have an earlier error in the compiler to complain about out-of-range locals. We then write the local register index as a 16bit unsigned integer and erroneously end up with instructions that try to use registers where the type doesn't match.

The bytecode validation error is correct, since we are emitting broken bytecode.

I am writing up a patch in nqp that checks if a frame we're trying to compile contains too many locals (or lexicals) and complains earlier, with minimal performance impact.
