### ISSUE TITLE
"none of these signatures matches" output is confusing when using revision-gated trait

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#5749]
## The Problem

Multis with identical signatures but with differing `revision-gated` values can lead to confusing output:

```
Cannot resolve caller chmod(Int:D, Str:D); none of these signatures matches:
    ($mode, IO(Any) $path)
    (IO(Any) $path, Int(Any) :$mode!)
    ($mode, *@filenames)
    ($mode, *@filenames)
  in block <unit> at t/spec/S16-filehandles/chmod.t line 38
```

## Expected Behavior

I'm not sure if the message should only list the candidates for the matching `revision-gated` candidate, or if we should add some sort of identifier to the output that differentiates the e.g. two `($mode, *@filenames)` lines

**Comment by ugexe** [comment]
Actually this has nothing to do with `revision-gated`

**Comment by ab5tract** [comment]
FWIW I think we could improve the output here in the cases where there is revision gating.

@ugexe Would it be possible to share any example code that you wrote in the process of becoming convinced that `revision-gated` is not involved?

It seems that there is at least _something_ missing when it comes to coercive type constraints and un-typed slurpies in dispatch, whether it is specific to revision gating or not. I haven't managed to recreate the scenario myself, but I haven't tried super hard due to hopes that you already have a snippet that I can use as a diving board.

Also, happy new years!

**Comment by ugexe** [comment]
Regardless of the revision gated trait we can have multis with identical signatures which can lead to similarly confusing messages
```
$ raku -e 'use MONKEY-SEE-NO-EVAL; proto sub foo(|) {*}; multi sub foo(Int:D $a) { }; multi sub foo(Int:D $a) { }; foo(EVAL q|"x"|)'
Cannot resolve caller foo(Str:D); none of these signatures matches:
    (Int:D $a)
    (Int:D $a)
  in block <unit> at -e line
```
